### ISSUE TITLE
SSL/TLS connection between Kong 0.11.2 and Postgres 9.6

### ISSUE THREAD

**Issue by aakarshit-batchu** [Kong/kong#3214] opened 2018-02-12 11:02 UTC
Hi,
I am trying to connect Kong 0.11.2 to PostgreSQL 9.6 database over ssl connection with verification.
I failed getting this to work.

**SSL certificate generation steps:**
```
openssl genrsa -passout pass:mypass -des3 -out server.key 1024
openssl rsa -passin pass:mypass -in server.key -out server.key
chmod 400 server.key
openssl req -new -key server.key -days 3650 -out server.crt -x509 -subj '/C=IN/ST=Maharastra/L=Mumbai/O=Development/CN=10.0.1.191'
cp server.crt root.crt
openssl genrsa -passout pass:iotadmin -des3 -out postgresql.key 1024
openssl rsa -in postgresql.key -out postgresql.key -passin pass:mypass
openssl req -new -key postgresql.key -days 3650 -out postgresql.csr -subj '/C=IN/ST=Maharastra/L=Mumbai/O=Development/CN=kong'
openssl x509 -req -in postgresql.csr -CA root.crt -CAkey server.key -out postgresql.crt -CAcreateserial

```

**Kong Config:**
```
# DATASTORE
database = postgres                
pg_host = 10.0.1.191
pg_port = 5432
pg_user = kong
pg_password = kong
pg_database = kong    
pg_ssl = on    
pg_ssl_verify = on

# DEVELOPMENT & MISCELLANEOUS
lua_ssl_trusted_certificate = /opt/postgres_ssl/postgresql.crt  # Absolute path to the certificate
```

**Postgresql Config:**
_pg_hba.conf:_
`hostssl all         all    10.0.1.191/32             md5 clientcert=1`

_postgresql.conf:_
```
listen_addresses = '10.0.1.191'
ssl_cert_file = 'server.crt'
ssl_key_file = 'server.key'
ssl_ca_file = 'root.crt'
```

**Kong Logs:**
```
2018/02/12 11:01:12 [verbose] Kong: 0.11.2
2018/02/12 11:01:12 [debug] ngx_lua: 10008
2018/02/12 11:01:12 [debug] nginx: 1011002
2018/02/12 11:01:12 [debug] Lua: LuaJIT 2.1.0-beta2
2018/02/12 11:01:12 [verbose] reading config file at /etc/kong/kong.conf
2018/02/12 11:01:12 [debug] admin_access_log = "logs/admin_access.log"
2018/02/12 11:01:12 [debug] admin_error_log = "logs/error.log"
2018/02/12 11:01:12 [debug] admin_http2 = false
2018/02/12 11:01:12 [debug] admin_listen = "0.0.0.0:8001"
2018/02/12 11:01:12 [debug] admin_listen_ssl = "0.0.0.0:8444"
2018/02/12 11:01:12 [debug] admin_ssl = true
2018/02/12 11:01:12 [debug] admin_ssl_cert = "/etc/kong/ssl/server.crt"
2018/02/12 11:01:12 [debug] admin_ssl_cert_key = "/etc/kong/ssl/server.key"
2018/02/12 11:01:12 [debug] anonymous_reports = true
2018/02/12 11:01:12 [debug] cassandra_consistency = "ONE"
2018/02/12 11:01:12 [debug] cassandra_contact_points = {"127.0.0.1"}
2018/02/12 11:01:12 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2018/02/12 11:01:12 [debug] cassandra_keyspace = "kong"
2018/02/12 11:01:12 [debug] cassandra_lb_policy = "RoundRobin"
2018/02/12 11:01:12 [debug] cassandra_port = 9042
2018/02/12 11:01:12 [debug] cassandra_repl_factor = 1
2018/02/12 11:01:12 [debug] cassandra_repl_strategy = "SimpleStrategy"
2018/02/12 11:01:12 [debug] cassandra_schema_consensus_timeout = 10000
2018/02/12 11:01:12 [debug] cassandra_ssl = false
2018/02/12 11:01:12 [debug] cassandra_ssl_verify = false
2018/02/12 11:01:12 [debug] cassandra_timeout = 5000
2018/02/12 11:01:12 [debug] cassandra_username = "kong"
2018/02/12 11:01:12 [debug] client_body_buffer_size = "8k"
2018/02/12 11:01:12 [debug] client_max_body_size = "0"
2018/02/12 11:01:12 [debug] client_ssl = false
2018/02/12 11:01:12 [debug] custom_plugins = {}
2018/02/12 11:01:12 [debug] database = "postgres"
2018/02/12 11:01:12 [debug] db_cache_ttl = 3600
2018/02/12 11:01:12 [debug] db_update_frequency = 5
2018/02/12 11:01:12 [debug] db_update_propagation = 0
2018/02/12 11:01:12 [debug] dns_error_ttl = 1
2018/02/12 11:01:12 [debug] dns_hostsfile = "/etc/hosts"
2018/02/12 11:01:12 [debug] dns_no_sync = false
2018/02/12 11:01:12 [debug] dns_not_found_ttl = 30
2018/02/12 11:01:12 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2018/02/12 11:01:12 [debug] dns_resolver = {}
2018/02/12 11:01:12 [debug] dns_stale_ttl = 4
2018/02/12 11:01:12 [debug] error_default_type = "text/plain"
2018/02/12 11:01:12 [debug] http2 = false
2018/02/12 11:01:12 [debug] latency_tokens = true
2018/02/12 11:01:12 [debug] log_level = "debug"
2018/02/12 11:01:12 [debug] lua_package_cpath = ""
2018/02/12 11:01:12 [debug] lua_package_path = "./?.lua;./?/init.lua;"
2018/02/12 11:01:12 [debug] lua_socket_pool_size = 30
2018/02/12 11:01:12 [debug] lua_ssl_trusted_certificate = "/opt/postgres_ssl/postgresql.crt"
2018/02/12 11:01:12 [debug] lua_ssl_verify_depth = 1
2018/02/12 11:01:12 [debug] mem_cache_size = "128m"
2018/02/12 11:01:12 [debug] nginx_daemon = "on"
2018/02/12 11:01:12 [debug] nginx_optimizations = true
2018/02/12 11:01:12 [debug] nginx_user = "nobody nobody"
2018/02/12 11:01:12 [debug] nginx_worker_processes = "auto"
2018/02/12 11:01:12 [debug] pg_database = "kong"
2018/02/12 11:01:12 [debug] pg_host = "10.0.1.191"
2018/02/12 11:01:12 [debug] pg_password = "******"
2018/02/12 11:01:12 [debug] pg_port = 5432
2018/02/12 11:01:12 [debug] pg_ssl = true
2018/02/12 11:01:12 [debug] pg_ssl_verify = true
2018/02/12 11:01:12 [debug] pg_user = "kong"
2018/02/12 11:01:12 [debug] prefix = "/usr/local/kong/"
2018/02/12 11:01:12 [debug] proxy_access_log = "logs/access.log"
2018/02/12 11:01:12 [debug] proxy_error_log = "logs/error.log"
2018/02/12 11:01:12 [debug] proxy_listen = "0.0.0.0:8000"
2018/02/12 11:01:12 [debug] proxy_listen_ssl = "0.0.0.0:8443"
2018/02/12 11:01:12 [debug] real_ip_header = "X-Real-IP"
2018/02/12 11:01:12 [debug] real_ip_recursive = "off"
2018/02/12 11:01:12 [debug] server_tokens = true
2018/02/12 11:01:12 [debug] ssl = true
2018/02/12 11:01:12 [debug] ssl_cert = "/etc/kong/ssl/server.crt"
2018/02/12 11:01:12 [debug] ssl_cert_key = "/etc/kong/ssl/server.key"
2018/02/12 11:01:12 [debug] ssl_cipher_suite = "modern"
2018/02/12 11:01:12 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2018/02/12 11:01:12 [debug] trusted_ips = {}
2018/02/12 11:01:12 [debug] upstream_keepalive = 60
2018/02/12 11:01:12 [verbose] prefix in use: /usr/local/kong
2018/02/12 11:01:12 [verbose] running datastore migrations
Error:
/usr/local/share/lua/5.1/kong/cmd/migrations.lua:34: [postgres error] could not retrieve current migrations: [postgres error] certificate verify failed
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/cmd/migrations.lua:34: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
        /usr/local/bin/kong:7: in function 'file_gen'
        init_worker_by_lua:41: in function <init_worker_by_lua:39>
        [C]: in function 'xpcall'
        init_worker_by_lua:48: in function <init_worker_by_lua:46>

```

**postgresql Logs:**
`LOG:  could not accept SSL connection: tlsv1 alert unknown ca`

**Comment by bungle** [comment] 2018-02-14 18:21
Certificate needs to be in `PEM` format.

**Comment by aakarshit-batchu** [comment] 2018-02-14 18:28
Hi @bungle,
When you say the certificate needs to be in PEM format, can you please elaborate that?
I mean what should be the content of that file.
Also would appreciate if you can list out the steps to generate the required certificate.

**Comment by kikito** [comment] 2018-02-15 16:58
Hi @aakarshit-batchu , this question in StackOverflow seems to fit your situation.

Since your issue is not a bug, I am going to close it down. If you need to continue discussing this please use our forum: discuss.konghq.com . Thanks!

**Closed by kikito** 2018-02-15 16:58 UTC
