### ISSUE TITLE
Kong is crashing when the L1 cache miss happens

### ISSUE THREAD

**Issue by rajagopalvreghunath** [Kong/kong#3018] opened 2017-11-07 08:54 UTC
NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

Kong is crashing when the L1 cache miss happens and start sending 500 for all the requests

### Steps To Reproduce

1. edit the api config when the kong is under load
2. make cassandra latency go high
3. kong will hit a cache miss and crash and start sending 500 to all the requests

### Additional Details & Logs

- Kong version 0.11.1-0
- Kong debug-level startup logs

==================
false
==================
2017/11/07 01:11:32 [verbose] Kong: 0.11.1
2017/11/07 01:11:32 [debug] ngx_lua: 10008
2017/11/07 01:11:32 [debug] nginx: 1011002
2017/11/07 01:11:32 [debug] Lua: LuaJIT 2.1.0-beta2
2017/11/07 01:11:32 [verbose] no config file found at /etc/kong/kong.conf
2017/11/07 01:11:32 [verbose] reading config file at /etc/kong.conf
2017/11/07 01:11:32 [debug] KONG_NGINX_DAEMON ENV found with "off"
2017/11/07 01:11:32 [debug] admin_access_log = "logs/admin_access.log"
2017/11/07 01:11:32 [debug] admin_error_log = "logs/error.log"
2017/11/07 01:11:32 [debug] admin_http2 = false
2017/11/07 01:11:32 [debug] admin_listen = "0.0.0.0:8001"
2017/11/07 01:11:32 [debug] admin_listen_ssl = "0.0.0.0:8444"
2017/11/07 01:11:32 [debug] admin_ssl = false
2017/11/07 01:11:32 [debug] anonymous_reports = true
2017/11/07 01:11:32 [debug] cassandra_consistency = "ONE"
2017/11/07 01:11:32 [debug] cassandra_contact_points = {""}
2017/11/07 01:11:32 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2017/11/07 01:11:32 [debug] cassandra_keyspace = ""
2017/11/07 01:11:32 [debug] cassandra_lb_policy = "RoundRobin"
2017/11/07 01:11:32 [debug] cassandra_local_datacenter = "# When using the `DCAwareRoundRobin` load"
2017/11/07 01:11:32 [debug] cassandra_password = "******"
2017/11/07 01:11:32 [debug] cassandra_port = 9042
2017/11/07 01:11:32 [debug] cassandra_repl_factor = 1
2017/11/07 01:11:32 [debug] cassandra_repl_strategy = "SimpleStrategy"
2017/11/07 01:11:32 [debug] cassandra_schema_consensus_timeout = 10000
2017/11/07 01:11:32 [debug] cassandra_ssl = false
2017/11/07 01:11:32 [debug] cassandra_ssl_verify = false
2017/11/07 01:11:32 [debug] cassandra_timeout = 5000
2017/11/07 01:11:32 [debug] cassandra_username = ""
2017/11/07 01:11:32 [debug] client_body_buffer_size = "8k"
2017/11/07 01:11:32 [debug] client_max_body_size = "0"
2017/11/07 01:11:32 [debug] client_ssl = false
2017/11/07 01:11:32 [debug] custom_plugins = 
2017/11/07 01:11:32 [debug] database = ""
2017/11/07 01:11:32 [debug] db_cache_ttl = 3600
2017/11/07 01:11:32 [debug] db_update_frequency = 5
2017/11/07 01:11:32 [debug] db_update_propagation = 0
2017/11/07 01:11:32 [debug] dns_error_ttl = 1
2017/11/07 01:11:32 [debug] dns_hostsfile = "/etc/hosts"
2017/11/07 01:11:32 [debug] dns_no_sync = false
2017/11/07 01:11:32 [debug] dns_not_found_ttl = 30
2017/11/07 01:11:32 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2017/11/07 01:11:32 [debug] dns_resolver = {}
2017/11/07 01:11:32 [debug] dns_stale_ttl = 4
2017/11/07 01:11:32 [debug] error_default_type = "text/plain"
2017/11/07 01:11:32 [debug] http2 = false
2017/11/07 01:11:32 [debug] latency_tokens = true
2017/11/07 01:11:32 [debug] log_level = "debug"
2017/11/07 01:11:32 [debug] lua_package_cpath = ""
2017/11/07 01:11:32 [debug] lua_package_path = "./?.lua;./?/init.lua;"
2017/11/07 01:11:32 [debug] lua_socket_pool_size = 30
2017/11/07 01:11:32 [debug] lua_ssl_verify_depth = 1
2017/11/07 01:11:32 [debug] mem_cache_size = "128m"
2017/11/07 01:11:32 [debug] nginx_daemon = "off"
2017/11/07 01:11:32 [debug] nginx_optimizations = true
2017/11/07 01:11:32 [debug] nginx_user = "nobody nobody"
2017/11/07 01:11:32 [debug] nginx_worker_processes = "auto"
2017/11/07 01:11:32 [debug] pg_database = "kong"
2017/11/07 01:11:32 [debug] pg_host = "127.0.0.1"
2017/11/07 01:11:32 [debug] pg_port = 5432
2017/11/07 01:11:32 [debug] pg_ssl = false
2017/11/07 01:11:32 [debug] pg_ssl_verify = false
2017/11/07 01:11:32 [debug] pg_user = "kong"
2017/11/07 01:11:32 [debug] prefix = "/usr/local/kong/"
2017/11/07 01:11:32 [debug] proxy_access_log = "logs/access.log"
2017/11/07 01:11:32 [debug] proxy_error_log = "logs/error.log"
2017/11/07 01:11:32 [debug] proxy_listen = "0.0.0.0:8000"
2017/11/07 01:11:32 [debug] proxy_listen_ssl = "0.0.0.0:8443"

- Kong error logs 2017/11/07 01:12:28 [error] 64#0: *8276 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/core/balancer.lua:166: attempt to index local 'upstream' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/kong/core/balancer.lua: in function 'get_balancer'
	/usr/local/share/lua/5.1/kong/core/balancer.lua:274: in function 'execute'
	/usr/local/share/lua/5.1/kong/core/handler.lua:391: in function 'after'

- Operating System : centos

**Comment by thibaultcha** [comment] 2017-11-08 03:58
Hi,

Thank you for reporting. I have a few questions about things I would like to clarify first, before investigating this, if you don't mind.

> when the L1 cache miss happens

What do you call the L1 cache?

Also, could you clarify a little bit your "steps to reproduce" section?

> edit the api config when the kong is under load

What did you edit exactly? What type of load is Kong being put under at this point? Do you have numbers and/or can reproduce this load with tools such as `ab` or `wrk` for us to reproduce similar traffic?

> make cassandra latency go high

How exactly did you proceed to do this? We are interested not only to know how to reproduce the issue, but also to ensure this reproducible step is acceptable and allows for this to be qualified as a bug or not.

> Kong error logs

I suppose you are seeing many of these errors due to traffic on the proxy port, and not just one?

**Comment by thibaultcha** [comment] 2017-11-08 03:59
I do have a strong hunch as to what is happening here, but to confirm it, I would very much like to clarify the last point about the error logs that you are seeing. How frequent are those errors? Do they stop after a few seconds have passed? That'd be helpful to know.

**Comment by rajagopalvreghunath** [comment] 2017-11-10 06:41
we have observed this when we put the load to the kong instances the load is 200K RPM 
By L1 Cache i meant the in memory cache of kong.
Increasing cassandra latency i dont think we will be able to simulate but this we observed in our prod instances.
The Issue happened and errored out all the traffic went to the instances at that time and it was completely every request went 500 
The issue got rectified with a restart

**Comment by rajagopalvreghunath** [comment] 2017-11-15 17:57
What we have observed is that the local cache is not having the upstream and the checks are on the table  in balancer.lua
 return singletons.cache:get(upstream_cache_key, nil,
                              load_upstream_into_memory, upstream_id)

**Comment by kikito** [comment] 2018-01-22 12:26
Hi @rajagopalvreghunath,

If you are still experiencing this issue, please try updating to Kong 0.12. It contains some changes on the load balancer which could fix or at least alleviate the problem.

**Comment by kikito** [comment] 2018-02-21 16:53
Hello @rajagopalvreghunath, are you still experiencing this problem? Did you try 0.12?

**Comment by thibaultcha** [comment] 2018-04-28 20:36
I believe this was fixed in more recent work on the balancer in 0.12 and 0.13. Closing this then, thank you for the report.

**Closed by thibaultcha** 2018-04-28 20:36 UTC
Labels: pending author feedback
