### ISSUE TITLE
Not able to find Kong API and Plugin entries after restarting the server.

### ISSUE THREAD

**Issue by Nijisha** [Kong/kong#2200] opened 2017-03-14 05:38 UTC
@shashiranjan84,

 Not finding the Kong API and Plugin entries after restarting the the Server, where the Kong Server, Kong Database and Kong Dashboard Docker images are running.

I am running Kong docker images on AWS EC2 instance and added API and plugin entries. but Whenever I restarting the EC2 server, the Docker containers will go to stopped state and all the Kong entries will not be there. Again I need to re-enter all the entries. I couldn't find any solution for this.

1.  I am running the docker images for Kong database, Kong server and Kong dashboard.
2.  All the Containers are running on AWS rancher EC2 server.
3.  Added some API entries and pluggins
4.  Restarted the EC2 server.
5. SSH to the server and do docker ps, no containers are running.
6. do docker ps -a, lists all stopped containers and restarted the stopped containers using docker start container_name
7. then Access the Kong dash-board on browser, but no Kong API and Plugin entries.

- Kong version : 0.9.5

**Comment by Tieske** [comment] 2017-03-14 14:34
I'm not that involved with the docker images, but it seems the data in the datastore is not persisted. 

Let me ping @shashiranjan84 as he is more into the cloud stuff

**Comment by Nijisha** [comment] 2017-03-16 08:49
Hi,
Can anyone help on this issue?

**Comment by Tieske** [comment] 2017-03-16 21:06
maybe this: https://gitter.im/Mashape/kong?at=58cae91605a31d5a4a65d171

**Comment by shashiranjan84** [comment] 2017-03-16 21:16
@Nijisha I have no knowledge of Kong Dashboad but in you seems like Kong not able to reach backend Kong database and this Kong container fail to start.

**Comment by Nijisha** [comment] 2017-03-17 05:17
@shashiranjan84 ,
first I run this command for kong database.
docker run -d --name kong-database -p 9042:9042 -v /data/api:/var/lib/cassandra cassandra:2.2
then I linked the database with kong server using
docker run --privileged -d --name kong  --link kong-database:kong-database -e "KONG_DATABASE=cassandra" -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" -e 
"KONG_PG_HOST=kong-database"  -p 80:80  -p 443:443 -p 7001:7001  -p 7946:7946  -p 7946:7946/udp   kong

Then I ran the Dash board docker image to access it from the browser.
docker run --name "kong-dashboard" -d -p 8080:8080 pgbi/kong-dashboard 

And added api and curresponding plugins.
then I restarted  the server which all these docker containers are running. after the restart all the containers went into stopped state. Then I  started all docker containers one by one. then I access the URL I am not able to find added api and plugin.
I am able to get it if I run the cassandra back up. but I am feeling this is not a good approach. Its taking long time to take the db back up and copy it and rerun all. 
could you please suggest any other solution than this.? if we can solve this some other easy way that would be appreciated. 
Note: if I use postgres SQL instead of cassandra, I couldn't find a proper way to take the db back up also.  I found its very hectic for me.

Appreciate your suggestions .
Thanks in Advance,

**Comment by Nijisha** [comment] 2017-04-18 12:21
Hi,
Can you please help me to take the kong database back up? I am using docker installation of kong. so whenever I am restarting the server my api entries and plugin entries are invisbible. and I am using cassandra as the db

**Comment by Nijisha** [comment] 2017-05-23 09:24
Hi,
After I add many entries to my kong api, plugins, and consumers server got hang and I restarted my server.
but after, when I access kong url, I didn't see any api, plugin, and consumers.
again I have to add all these entries. it looks very hectic for me and I am not aware of all these consumers also. now my applications are getting failed only because of this.
could anyone please tell me a solution for this?
I am totally fed up with  adding all the entries again and again...

**Comment by kikito** [comment] 2017-11-17 15:58
@Nijisha docker containers are not stateful by default - unless you configure them to store state somewhere, turning them off will make you lose the state. The solution depends on the platform you use. In the case of AWS, there seems to be a way to use EFS as a persistence layer. More info here: https://aws.amazon.com/blogs/compute/using-amazon-efs-to-persist-data-from-amazon-ecs-containers/ 

Since this is more an AWS/Docker issue than a Kong issue *per se*, and it is not a bug, I will close this issue. If you have more questions, please use our [gitter](https://gitter.im/Mashape/kong) channel.

**Closed by kikito** 2017-11-17 15:58 UTC
Labels: support
