### ISSUE TITLE
Kong IP restriction plugin does not allow DNS name, only IP is allowed for it.

### ISSUE THREAD

**Issue by trafalgarf** [Kong/kong#7794] opened 2021-09-01 04:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.0

### Current Behavior

It allows like 10.10.10.0/24 can be used.
but it does not allow "abc.com" as an entry list.

### Expected Behavior

"abc.com" or its underlying IP should be allowed in the plugin.

### Steps To Reproduce

```markdown
Add Ip restriction from Kong UI 
Try adding a restriction entry as "abc.com" (also try replacing domain with IP, would result in same)
try accessing the service from anywhere else 
it allows access.
```

**Comment by Tieske** [comment] 2021-09-01 05:34
This would be unreliable I think. Getting a conclusive list of IPs from a nameserver is very tricky. Typically answers are limited to only a few entries, and there can be several levels of indirection (CNAME -> SRV -> A -> IP).

How to deal with those?

**Comment by trafalgarf** [comment] 2021-09-01 05:43
Mentioning underlying ip in the restriction list also doesn't work. It allows calls from dns name.

**Comment by Tieske** [comment] 2021-09-02 06:38
@trafalgarf can you describe your real-world use case where you'd need this?

we cannot update the config dynamically (eg. resolve the name and store the IP's in the plugin config). So the only way would be to do this on a dataplane. But then if there is a nameserver that returns a random set of 3 IPs from the available ones (eg. a name has A records, with 4 IPs and the name server only returns 3 random), Then in a Kong cluster 2 different Kong nodes will get 2 different sets of IPs to block/allow. Really hairy stuff this request.

**Comment by trafalgarf** [comment] 2021-09-03 04:33
@Tieske 
We have a service which should be restricted to a specific IP access.
Now that IP is mapped to dns too.
In the plugin i can either mention the ip or dns.
So ip addition doesn't work and dns addition is not allowed.

**Comment by Tieske** [comment] 2021-09-03 05:37
Why doesn't it work when you add the ip?

**Comment by trafalgarf** [comment] 2021-09-03 05:44
can this be a case that the source of that service call on the IP which is in allowed IP restriction is also on the same kong ?

**Comment by carnei-ro** [comment] 2021-09-06 15:24
A long time ago I have written something like that to try to allow my home dynamic ip (using duckdns). I did not used it in production environment, I went to a authn/authz solution. Here is my old code https://github.com/carnei-ro/openresty-controller-by-dns-name/blob/master/dns.lua

**Comment by StarlightIbuki** [comment] 2023-10-11 06:24
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:24 UTC
Labels: task/feature, plugins/ip-restriction
