### ISSUE TITLE
Response content-length header stripped when content-type is “text/html”   

### ISSUE THREAD

**Issue by kikito** [Kong/kong#4306] opened 2019-02-13 17:18 UTC
### Summary

Source: https://discuss.konghq.com/t/response-content-length-header-stripped-when-content-type-is-text-html/2810

> When examining ngx.header.content_length of a RESPONSE, we notice this field is nil ONLY when the response content-type is text/html.
>
> In all cases, the Content-Length header is being explicitly set on the response. And ngx.header.content_length is accurate when the Content-Type is any of the following: text/plain, application/json, application/xml. Only for text/html is it nil.
>
> So I’m thinking maybe something in Kong, ngx, openresty is stripping it? But only for this specific content-type value?
>
> Any thoughts?
>
> Edit: This is in Kong 1.0

### Steps To Reproduce

Assumed steps:

1. Set up a server which returns a non-empty response with `Content-Type = `text/html` and a non-empty `Content-Length`
2. Proxy that server with Kong
3. Make a request to the proxied server
4. The response should have the `Content-Length` header set.

### Additional Details & Logs

- Kong version 1.0

**Comment by bungle** [comment] 2019-02-13 17:34
I tried to create service and route and pointed service to http://www.google.com/, and it returned content-length just fine. Is there plugins involved? Does your upstream set that, or does it perhaps return data with `chunked` encoding?

**Comment by jeremyjpj0916** [comment] 2019-02-13 17:46
@bungle yes, this plugin is involved: https://github.com/Optum/kong-response-size-limiting , if the size is set lower that the configured size limiter it should see the content-length header and return error to proxy consuming client. debug traces of this plugin revealed when text/html is set to the content-type on response accessing the length header is nil in ngx context in header_filter phase.

**Comment by bungle** [comment] 2019-02-16 21:31
@jeremyjpj0916 can you try with this branch:
https://github.com/Kong/kong/pull/4316

**Comment by bungle** [comment] 2019-02-16 21:36
@jeremyjpj0916,

Also `ngx.header["Content-Length"]`is not the same as `ngx.var.upstream_http_content_length`. You should be using the latter. Or use `pdk`'s `kong.service.response.get_header("Content-Length")`

**Comment by jeremyjpj0916** [comment] 2019-02-17 05:12
@bungle, back when I was debugging a mem leak found in pdk I reverted code from using pdk to barbones ngx.* fields, and I think in a rush I must have chosen the wrong value when I did the revert although the field I chose seems to generally work(when I hard code a large content length header value that field does pick it up it seems). I will change it to the latter, but were you able to reproduce any weird behavior when setting different response content-types? I will give that branch a go sometime this week, but I am confused because one post makes me think you made a PR that handles a potential issue and a second post stating I am referencing a field incorrectly as a goof up 😄  .

**Comment by bungle** [comment] 2019-02-17 11:28
@jeremyjpj0916 I think changing to `ngx.var.upstream_http_content_length` is what you want to do. The PR might solve issues with some upstream hop-by-hop headers sent to downstream. But I think the `ngx.var.upstream_http_content_length` is what you want. `ngx.header` contains response headers, and `ngx.var.upstream_http_*` contains upstream response headers.

**Comment by bungle** [comment] 2019-02-18 14:46
@jeremyjpj0916 to elaborate a bit. What do you have in `ngx.var.upstream_http_transfer_encoding` when this happens?

**Comment by bungle** [comment] 2019-02-20 17:24
Btw. is there `gzip` involved?

**Comment by jeremyjpj0916** [comment] 2019-02-20 22:04
@bungle we just validated a chg on the plugin. 
```
ngx.header["Content-Length"] ->ngx.var.upstream_http_content_length
```

This was the fix and fixed what we were seeing. no gzip or fancyness involved on our mock response, the issue was just using ngx.header["Content-Length"] and some reason it was null when text/html was the content-type on response it seemed.

@kikito you can can close this, bit of a false alarm here, sorry!

**Comment by thibaultcha** [comment] 2019-02-20 23:27
Closing this then, good job everyone.

**Closed by thibaultcha** 2019-02-20 23:27 UTC
