### ISSUE TITLE
Who is throwing "{"message":"failure to get a peer from the ring-balancer"}" ?

### ISSUE THREAD

**Issue by Sereneee** [Kong/kong#7156] opened 2021-05-15 10:51 UTC
I'm in kubernetes environment, and there's the frontend, kong and backend (envoy + microservice) in the environment. 
Whenever a request is being forwarded to backend service that is down, I get this response, {"message":"failure to get a peer from the ring-balancer"}.
Does anyone know where this error is being thrown from and how I can intercept it?

**Comment by locao** [comment] 2021-05-17 15:42
Hi @Sereneee! This is error is thrown by Kong and usually (but not always) is an issue with upstream names. Can you share more details about the config used?

**Comment by Sereneee** [comment] 2021-05-17 15:51
Hi there @locao , thanks for replying!
May I know what configs are you asking about specifically?

Actually, I am perfectly aware of why the error is being thrown, it is because my upstream service is down/unavailable.

What I am trying to get at is where is this error being thrown from? And how can I intercept it in my custom kong plugin?

Instead of forwarding this default response to client whenever a service is down, I would like to customize the response.

**Comment by fffonion** [comment] 2021-05-19 17:47
@Sereneee you will expect `get_source()` returns `exit` in this case. Try to print the `kong.response.get_source()`
in a log if you are not certain.

**Comment by Sereneee** [comment] 2021-05-20 15:02
Hi @fffonion , yes I have tried that and I've gotten "service" as a result.

**Comment by fffonion** [comment] 2021-05-20 16:00
@Sereneee That seems weird and could be a bug. In which phase did you call the `kong.response.get_source()`?
Could you maybe share the POC of the plugin?

**Comment by Sereneee** [comment] 2021-05-21 10:13
Hey @fffonion 
So, I was calling it in :body_filter() phase, but actually, I'm working towards using :response() phase in place of body_filter() phase, I have found out that `kong.response.get_source()` does not work in :response() phase at all, would you know if there are other function similar to this that I can use in :response() phase?

Here's the POC of my plugin:
**_handler.lua_**
```
local BasePlugin = require "kong.plugins.base_plugin"
local response_transformer = require "kong.plugins.custom-exception-handling.response_transformer"
local cjson = require("cjson.safe").new()

local concat = table.concat
local string_find = string.find
local kong = kong
local ngx = ngx


local ExceptionHandlingHandler = BasePlugin:extend()

function ExceptionHandlingHandler:new()
  ExceptionHandlingHandler.super.new(self, "custom-exception-handling")
end

function ExceptionHandlingHandler:access()
  ExceptionHandlingHandler.super.access(self)
  kong.service.request.enable_buffering()
  kong.ctx.shared.language_from_header = kong.request.get_header("Accept-Language")
  kong.ctx.shared.request_path = kong.request.get_path()
  kong.ctx.shared.request_headers = kong.request.get_headers()
end

function ExceptionHandlingHandler:body_filter(conf)
  ExceptionHandlingHandler.super.body_filter(self)
  if kong.response.get_source() == "service" then
    kong.log("The response comes from the Service")
  elseif kong.response.get_source() == "error" then
    kong.log("There was an error while processing the request")
  elseif kong.response.get_source() == "exit" then
    kong.log("There was an early exit while processing the request")
  end
  kong.log("kong.response.get_source(): " .. kong.response.get_source())
end

function ExceptionHandlingHandler:log()
  ExceptionHandlingHandler.super.log(self)
end

ExceptionHandlingHandler.PRIORITY = 600
ExceptionHandlingHandler.VERSION = "1.0.1"


return ExceptionHandlingHandler
```

**_schema.lua_**
```
local typedefs = require "kong.db.schema.typedefs"
return {
  name = "custom-exception-handling",
  fields = {
    { protocols = typedefs.protocols_http },
    { config = {
        type = "record",
        fields = {
          { placeholder = { type = "string", default = "placeholder" }, },
        },
      },
    },
  },
}

```

this is the logs im getting:
```
2021/05/21 17:58:32 [error] 8513#0: *2510 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: kong, request: "POST /v1/grant?grant_type=client_credentials HTTP/1.1", subrequest: "/kong_buffered_http", upstream: "http://127.0.0.1:8080/v1/auth/mfa/verification?grant_type=client_credentials", host: "localhost:8090"
2021/05/21 17:58:32 [error] 8513#0: *2510 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: kong, request: "POST /v1/grant?grant_type=client_credentials HTTP/1.1", subrequest: "/kong_buffered_http", upstream: "http://127.0.0.1:8080/v1/auth/mfa/verification?grant_type=client_credentials", host: "localhost:8090"
2021/05/21 17:58:32 [error] 8513#0: *2510 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: kong, request: "POST /v1/grant?grant_type=client_credentials HTTP/1.1", subrequest: "/kong_buffered_http", upstream: "http://127.0.0.1:8080/v1/auth/mfa/verification?grant_type=client_credentials", host: "localhost:8090"
2021/05/21 17:58:32 [error] 8513#0: *2510 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: kong, request: "POST /v1/grant?grant_type=client_credentials HTTP/1.1", subrequest: "/kong_buffered_http", upstream: "http://127.0.0.1:8080/v1/auth/mfa/verification?grant_type=client_credentials", host: "localhost:8090"
2021/05/21 17:58:32 [error] 8513#0: *2510 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: kong, request: "POST /v1/grant?grant_type=client_credentials HTTP/1.1", subrequest: "/kong_buffered_http", upstream: "http://127.0.0.1:8080/v1/auth/mfa/verification?grant_type=client_credentials", host: "localhost:8090"
2021/05/21 17:58:32 [error] 8513#0: *2510 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: kong, request: "POST /v1/grant?grant_type=client_credentials HTTP/1.1", subrequest: "/kong_buffered_http", upstream: "http://127.0.0.1:8080/v1/auth/mfa/verification?grant_type=client_credentials", host: "localhost:8090"
2021/05/21 17:58:32 [notice] 8513#0: *2510 [kong] handler.lua:45 [custom-exception-handling] There was an early exit while processing the request while sending to client, client: 127.0.0.1, server: kong, request: "POST /v1/grant?grant_type=client_credentials HTTP/1.1", host: "localhost:8090"
2021/05/21 17:58:32 [notice] 8513#0: *2510 [kong] handler.lua:47 [custom-exception-handling] kong.response.get_source(): exit while sending to client, client: 127.0.0.1, server: kong, request: "POST /v1/grant?grant_type=client_credentials HTTP/1.1", host: "localhost:8090"
2021/05/21 17:58:32 [notice] 8513#0: *2510 [kong] handler.lua:45 [custom-exception-handling] There was an early exit while processing the request while sending to client, client: 127.0.0.1, server: kong, request: "POST /v1/grant?grant_type=client_credentials HTTP/1.1", host: "localhost:8090"
2021/05/21 17:58:32 [notice] 8513#0: *2510 [kong] handler.lua:47 [custom-exception-handling] kong.response.get_source(): exit while sending to client, client: 127.0.0.1, server: kong, request: "POST /v1/grant?grant_type=client_credentials HTTP/1.1", host: "localhost:8090"
```
I'm aware that this is showing that `kong.response.get_source()` returned `"exit"` instead of `"service"`, I'm not sure why today I couldn't replicate that, but anyway, I'm pretty sure `"exit"` isn't the correct response either, as that is the only plugin enabled on that particular route and service.

**Comment by fffonion** [comment] 2021-05-24 12:49
@Sereneee `response` phase is actually the "Service Response" or say reponse from upstream, it's before Kong started to generate
response. You will normally use `kong.service.response.*` in this case. While `kong.response.*` deals with the response
Kong sends back to client. So it's too early to use `kong.service.get_source` in response phase. There's unfortunately
no alternative in get_source at presentl; maybe you get *some* context with `kong.service.response.get_raw_body`
or `get_headers` to check if certain pattern in body or headers exists from upstream.

Regarding the error inconsistency, there's a same issue #7093. Please stay tuned for updated on that issue.

**Comment by esatterwhite** [comment] 2022-01-19 21:48
@fffonion So is it possible to over ride this resposne from kong with a plugin?
I have kong infront of a web application, and returning this json when the service is down is not ideal. I'd like to be able to send back a customer HTML page. Is that at all possible?

**Comment by akira28** [comment] 2022-01-20 14:25
I'd need to do the same thing for all errors sent by Kong (not upstream services).
For 404 I solved it with the 'fallback' route and request termination workaround, but for 503 like these I can't find a good solution that would impact performance (as far as I understand adding a plugin with a `response` phase could impact performance.
Is there a workaround?

**Comment by esatterwhite** [comment] 2022-01-20 20:07
@akira28  What is the request termination workaround?

**Comment by akira28** [comment] 2022-01-21 12:06
@esatterwhite it only works for 404.
You create a 'fallback' route '/', and add the request-termination plugin to it, returning 404 and the body you want. Kong matches the longest route you have so it doesn't impact with other routes you have configured. When it reaches '/' it'll execute the request-termination plugin

**Comment by StarlightIbuki** [comment] 2023-10-11 06:34
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:34 UTC
Labels: core/balancer

**Comment by odorT** [comment] 2024-10-28 14:40
did you find how default ring balancer error response can be changed?

**Comment by esatterwhite** [comment] 2024-10-28 15:02
I think with the current versions you can define error templates.

**Comment by odorT** [comment] 2024-10-29 05:39
Can you please share sample configuration or documentation about it?
