### ISSUE TITLE
Custom shared_dict defined via env KONG_NGINX_HTTP_LUA_SHARED_DICT is not "found" by check_shdict func

### ISSUE THREAD

**Issue by cristichiru** [Kong/kong#7739] opened 2021-07-02 07:58 UTC
## Details
- Kong: from 2.2.x to 2.4.1
- Start kong with env `KONG_NGINX_HTTP_LUA_SHARED_DICT=proxy_cache_storage  128m`
- In `nginx-kong.conf`, an entry is created: `lua_shared_dict proxy_cache_storage  128m;`

## Plugin definition
```json
{
  "request_method": [
    "GET",
    "HEAD"
  ],
  "cache_control": false,
  "vary_query_params": null,
  "cache_ttl": 2,
  "strategy": "memory",
  "response_code": [
    200,
    301,
    404
  ],
  "memory": {
    "dictionary_name": "proxy_cache_storage"
  },
  "vary_headers": null,
  "content_type": [
    "text/plain",
    "application/json",
    "application/json;charset=utf-8",
    "application/json; charset=utf-8",
    "text/xml",
    "text/xml; charset=utf-8",
    "text/xml;charset=utf-8"
  ],
  "storage_ttl": null
}
```
## Expected
- Kong start normally, plugin use proxy_cache_storage dict

## What actually happens
- Kong fails to start:

```yaml
2021/01/05 23:06:42 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:474: error parsing declarative config file /kong_dbless/kong.yml:
in 'services':
  - in entry 37 of 'services':
    in 'plugins':
      - in entry 1 of 'plugins':
        in '@entity':
          - in entry 1 of '@entity': missing shared dict 'proxy_cache_storage'
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/init.lua:474: in function 'init'
	init_by_lua:11: in main chunk
```

## Weird behavior
If I set in the plugin config another dictionary, pre-configured in `nginx-kong.conf` a few lines above, it works, as it seems that dict is present in the [object `ngx.shared`](https://github.com/Kong/kong-plugin-proxy-cache/blob/559675e2453615eaf14b8ee6fa74b9f10447391f/kong/plugins/proxy-cache/schema.lua#L8).

## Excerpt of kong-nginx.conf
```nginx
## If I set in the cache plugin "kong_core_db_cache_2",  will work, as it seems to be present in 'ngx.shared' object, checked by the plugin code
lua_shared_dict kong_core_db_cache_2        128m;

lua_shared_dict kong_core_db_cache_miss_2   12m;
lua_shared_dict kong_db_cache_2             128m;
lua_shared_dict kong_db_cache_miss_2        12m;

underscores_in_headers on;
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GC
M-SHA384;

# injected nginx_http_* directives
client_body_buffer_size 8k;
client_max_body_size 0;

## But the one defined by me, "proxy_cache_storage", a few lines below is not loaded as "it missing"!??
lua_shared_dict proxy_cache_storage  128m;

lua_shared_dict prometheus_metrics 5m;
```

## Related issues
https://github.com/Kong/kong/issues/6703

**Comment by cristichiru** [comment] 2021-09-03 06:03
As you can see in the excerpt from `kong-nginx.conf`, the line is there. I do not add it explicitly to the conf, instead the bootstrap step of kong adds it baded on my configuration (via env variable).

Regardless, the declaration is there, but somehow ignored by the plugin in init phase.

**Comment by StarlightIbuki** [comment] 2023-10-11 06:24
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:24 UTC
Labels: plugins/proxy-cache
