### ISSUE TITLE
chore(scripts) Release Scripts Usability: missing instructions on how to check/fix issues

### ISSUE THREAD

**Issue by kikito** [Kong/kong#7867] opened 2021-09-21 17:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.5

### Current Behavior

The release scripts (`scripts/make-*-release`) are lack detail on some steps carried out by internal servers

### Expected Behavior

When the script does not perform a task directly, it should include:

* Instructions about how to check that a step has finished successfully (e.g "go to this link, all status should be green, there should be a new Docker image")
* Instructions about how to fix (e.g. logs should be available on this link, in order to retry a build you should do this)

**Comment by kikito** [comment] 2021-09-23 16:00
Did some tests today:

`./scripts/make-final-release 2.6.0 check_perf` says:

```
Ensure Kong performance tests were performed and no showstopper regressions were found. If everything looks all right, press Enter to continue or Ctrl+C to quit
```

It should include some kind of link or instructions about how to run them (extra point: trigger an automated run in some server and open page with dashboard of it running).

`./scripts/make-final-release 2.6.0 check_upgrade_tests` says:

```
Ensure Kong upgrade tests were performed and no showstopper regressions were found. If everything looks all right, press Enter to continue or Ctrl+C to quit
```

It should at the very least point where the upgrade tests are (currently in https://github.com/Kong/kong-upgrade-tests)

`./scripts/make-final-release 2.6.0 check_changelog` opens the changelog and asks to check that it was "written on the prerelease". We didn't do a prerelease. However we do have a draft changelog on a custom branch.

The script should mention what to do. Does the changelog need to be updated in the `master` branch?

**Comment by kikito** [comment] 2021-09-27 15:09
`./scripts/make-final-release 2.6.0 merge` Shows a message saying
```
Make sure the packages are built and available on download.konghq.com
before continuing to the following steps.
Once they are built, you may run the following steps in parallel:
* 'homebrew'
* 'luarocks'
* 'vagrant'
* 'update_docker', then 'merge_docker', then 'submit_docker'
```
It does not say how much they take to build, where to see status, or what to do if something fails.

**Comment by StarlightIbuki** [comment] 2023-10-11 06:24
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:24 UTC
Labels: distribution
