### ISSUE TITLE
Error: failed the initial dns/balancer resolve for domain, with: port on Kong 0.12.1

### ISSUE THREAD

**Issue by likwid** [Kong/kong#3223] opened 2018-02-13 22:14 UTC
### Summary

We are seeing some weird behavior in Kong around DNS interaction.  The basic gist is that some kong servers in our cluster fail to resolve DNS correctly. 

We are getting the following error:

```
2018/02/13 15:44:16 [error] 8659#0: *2523 [lua] responses.lua:121: after(): failed the initial dns/balancer resolve for 'servicename.service.consul' with: 23963, client: 172.22.14.2
39, server: kong, request: "GET / HTTP/1.1", host: "servicename.domain.com"
```

For context, we are using consul for our DNS resolution, and the Kong instance has dnsmasq configured like this:
```
% cat /etc/dnsmasq.d/10-consul
server=/consul/127.0.0.1#8600
```

Using dig and nslookup both provide the expected results for `servicename.service.consul` while this problem is happening. 

Here is a sample dig:
```
; <<>> DiG 9.9.5-3ubuntu0.17-Ubuntu <<>> servicename.service.consul ANY
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55910
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;servicename.service.consul. IN      ANY

;; ANSWER SECTION:
servicename.service.consul. 0 IN     A       [redacted but correct]
servicename.service.consul. 0 IN     TXT     "consul-network-segment="

;; Query time: 2 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Feb 13 16:09:28 CST 2018
;; MSG SIZE  rcvd: 110
```
### Steps to Reproduce

The problem is intermittent, and very difficult to reproduce. 

We are essentially launching the same AMI with a very small amount of configuration in userdata multiple times and sometimes the server comes up and resolves DNS correctly, and sometimes it doesn't.  There is no discernible difference (that we can detect at least) between servers that work, and servers that don't.

We are attempting to figure out why it sometimes presents and why it doesn't other times.

### Additional Details & Logs

- Kong version (`$ kong version`)
We are running 0.12.1

- Kong debug-level startup logs (`$ kong start --vv`)
```
2018/02/13 15:51:17 [verbose] Kong: 0.12.1
2018/02/13 15:51:17 [debug] ngx_lua: 10010
2018/02/13 15:51:17 [debug] nginx: 1011002
2018/02/13 15:51:17 [debug] Lua: LuaJIT 2.1.0-beta3
2018/02/13 15:51:17 [verbose] reading config file at /etc/kong/kong.conf
2018/02/13 15:51:17 [debug] admin_access_log = "logs/admin_access.log"
2018/02/13 15:51:17 [debug] admin_error_log = "logs/error.log"
2018/02/13 15:51:17 [debug] admin_http2 = false
2018/02/13 15:51:17 [debug] admin_listen = "0.0.0.0:8001"
2018/02/13 15:51:17 [debug] admin_listen_ssl = "127.0.0.1:8444"
2018/02/13 15:51:17 [debug] admin_ssl = true
2018/02/13 15:51:17 [debug] anonymous_reports = true
2018/02/13 15:51:17 [debug] cassandra_consistency = "ONE"
2018/02/13 15:51:17 [debug] cassandra_contact_points = {"127.0.0.1"}
2018/02/13 15:51:17 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2018/02/13 15:51:17 [debug] cassandra_keyspace = "kong"
2018/02/13 15:51:17 [debug] cassandra_lb_policy = "RoundRobin"
2018/02/13 15:51:17 [debug] cassandra_port = 9042
2018/02/13 15:51:17 [debug] cassandra_repl_factor = 1
2018/02/13 15:51:17 [debug] cassandra_repl_strategy = "SimpleStrategy"
2018/02/13 15:51:17 [debug] cassandra_schema_consensus_timeout = 10000
2018/02/13 15:51:17 [debug] cassandra_ssl = false
2018/02/13 15:51:17 [debug] cassandra_ssl_verify = false
2018/02/13 15:51:17 [debug] cassandra_timeout = 5000
2018/02/13 15:51:17 [debug] cassandra_username = "kong"
2018/02/13 15:51:17 [debug] client_body_buffer_size = "8k"
2018/02/13 15:51:17 [debug] client_max_body_size = "0"
2018/02/13 15:51:17 [debug] client_ssl = false
2018/02/13 15:51:17 [debug] custom_plugins = {}
2018/02/13 15:51:17 [debug] database = "postgres"
2018/02/13 15:51:17 [debug] db_cache_ttl = 3600
2018/02/13 15:51:17 [debug] db_update_frequency = 5
2018/02/13 15:51:17 [debug] db_update_propagation = 0
2018/02/13 15:51:17 [debug] dns_error_ttl = 1
2018/02/13 15:51:17 [debug] error_default_type = "text/plain"
2018/02/13 15:51:17 [debug] http2 = false
2018/02/13 15:51:17 [debug] latency_tokens = true
2018/02/13 15:51:17 [debug] log_level = "debug"
2018/02/13 15:51:17 [debug] lua_package_cpath = ""
2018/02/13 15:51:17 [debug] lua_package_path = "./?.lua;./?/init.lua;"
2018/02/13 15:51:17 [debug] lua_socket_pool_size = 30
2018/02/13 15:51:17 [debug] lua_ssl_verify_depth = 1
2018/02/13 15:51:17 [debug] mem_cache_size = "128m"
2018/02/13 15:51:17 [debug] nginx_daemon = "on"
2018/02/13 15:51:17 [debug] nginx_optimizations = true
2018/02/13 15:51:17 [debug] nginx_user = "nobody nobody"
2018/02/13 15:51:17 [debug] nginx_worker_processes = "auto"
2018/02/13 15:51:17 [debug] pg_database = "kong11"
2018/02/13 15:51:17 [debug] pg_host = "[redacted].nonprod.internal"
2018/02/13 15:51:17 [debug] pg_password = "******"
2018/02/13 15:51:17 [debug] pg_port = 5432
2018/02/13 15:51:17 [debug] pg_ssl = false
2018/02/13 15:51:17 [debug] pg_ssl_verify = false
2018/02/13 15:51:17 [debug] pg_user = "[redacted]"
2018/02/13 15:51:17 [debug] prefix = "/usr/local/kong/"
2018/02/13 15:51:17 [debug] proxy_access_log = "logs/access.log"
2018/02/13 15:51:17 [debug] proxy_error_log = "logs/error.log"
2018/02/13 15:51:17 [debug] proxy_listen = "0.0.0.0:8000"
2018/02/13 15:51:17 [debug] proxy_listen_ssl = "0.0.0.0:8443"
2018/02/13 15:51:17 [debug] real_ip_header = "X-Real-IP"
2018/02/13 15:51:17 [debug] real_ip_recursive = "off"
2018/02/13 15:51:17 [debug] server_tokens = true
2018/02/13 15:51:17 [debug] ssl = true
2018/02/13 15:51:17 [debug] ssl_cipher_suite = "modern"
2018/02/13 15:51:17 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2018/02/13 15:51:17 [debug] trusted_ips = {}
2018/02/13 15:51:17 [debug] upstream_keepalive = 60
2018/02/13 15:51:17 [verbose] prefix in use: /usr/local/kong
2018/02/13 15:51:17 [verbose] preparing nginx prefix directory at /usr/local/kong
2018/02/13 15:51:17 [verbose] SSL enabled, no custom certificate set: using default certificate
2018/02/13 15:51:17 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
2018/02/13 15:51:17 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2018/02/13 15:51:17 [verbose] admin SSL certificate found at /usr/local/kong/ssl/admin-kong-default.crt
2018/02/13 15:51:17 [warn] ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
2018/02/13 15:51:17 [debug] searching for OpenResty 'nginx' executable
2018/02/13 15:51:17 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.11.2.5'
2018/02/13 15:51:17 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2018/02/13 15:51:17 [debug] starting nginx: /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong -c nginx.conf
2018/02/13 15:51:17 [debug] nginx started
2018/02/13 15:51:17 [info] Kong started
```

- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
```
2018/02/13 15:54:46 [debug] 13184#0: *659 [lua] statsd_logger.lua:73: send_statsd(): Sending data to statsd server: kong.deploy-it-dashboard.user..request.status.total:1|c|#app:kong
2018/02/13 15:54:46 [info] 13184#0: *656 client 127.0.0.1 closed keepalive connection
2018/02/13 15:54:47 [debug] 13184#0: *665 [lua] cluster_events.lua:231: [cluster_events] polling events from: 1518558677.736 to: 1518558887.86
2018/02/13 15:54:49 [info] 13184#0: *672 client [redacted] closed keepalive connection
2018/02/13 15:54:52 [debug] 13183#0: *679 [lua] cluster_events.lua:231: [cluster_events] polling events from: 1518558677.736 to: 1518558892.86
2018/02/13 15:54:57 [debug] 13183#0: *696 [lua] cluster_events.lua:231: [cluster_events] polling events from: 1518558677.736 to: 1518558897.869
2018/02/13 15:55:02 [debug] 13184#0: *709 [lua] cluster_events.lua:231: [cluster_events] polling events from: 1518558677.736 to: 1518558902.87
2018/02/13 15:55:04 [info] 13184#0: *719 client [redacted] closed keepalive connection
2018/02/13 15:55:07 [debug] 13183#0: *726 [lua] cluster_events.lua:231: [cluster_events] polling events from: 1518558677.736 to: 1518558907.872
2018/02/13 15:55:12 [debug] 13183#0: *740 [lua] cluster_events.lua:231: [cluster_events] polling events from: 1518558677.736 to: 1518558912.878
2018/02/13 15:55:17 [info] 13184#0: *559 client closed connection while waiting for request, client: [redacted], server: 0.0.0.0:8001
2018/02/13 15:55:17 [debug] 13183#0: *759 [lua] cluster_events.lua:231: [cluster_events] polling events from: 1518558677.736 to: 1518558917.879
2018/02/13 15:55:18 [info] 13183#0: *576 client closed connection while waiting for request, client: [redacted], server: 0.0.0.0:8001
2018/02/13 15:55:18 [info] 13183#0: *577 client closed connection while waiting for request, client: [redacted], server: 0.0.0.0:8001
2018/02/13 15:55:19 [info] 13184#0: *767 client [redacted] closed keepalive connection
2018/02/13 15:55:22 [debug] 13183#0: *774 [lua] cluster_events.lua:231: [cluster_events] polling events from: 1518558677.736 to: 1518558922.88
2018/02/13 15:55:27 [debug] 13183#0: *788 [lua] cluster_events.lua:231: [cluster_events] polling events from: 1518558677.736 to: 1518558927.886
2018/02/13 15:55:27 [debug] 13184#0: *794 [lua] base_plugin.lua:20: rewrite(): executing plugin "key-auth": rewrite
2018/02/13 15:55:27 [debug] 13184#0: *794 [lua] base_plugin.lua:20: rewrite(): executing plugin "datadog": rewrite
2018/02/13 15:55:27 [debug] 13184#0: *794 [lua] base_plugin.lua:20: rewrite(): executing plugin "syslog": rewrite
2018/02/13 15:55:27 [debug] 13184#0: *794 [lua] base_plugin.lua:24: access(): executing plugin "key-auth": access
2018/02/13 15:55:27 [debug] 13184#0: *794 [lua] base_plugin.lua:24: access(): executing plugin "acl": access
2018/02/13 15:55:28 [debug] 13184#0: *794 [lua] base_plugin.lua:24: executing plugin "datadog": access
2018/02/13 15:55:28 [debug] 13184#0: *794 [lua] base_plugin.lua:24: executing plugin "syslog": access
2018/02/13 15:55:28 [error] 13184#0: *794 [lua] responses.lua:121: after(): failed the initial dns/balancer resolve for 'servicename.service.consul' with: 23963, client: [redacted]
39, server: kong, request: "GET / HTTP/1.1", host: "servicename.domain.com"
2018/02/13 15:55:28 [debug] 13184#0: *794 [lua] base_plugin.lua:28: header_filter(): executing plugin "key-auth": header_filter
2018/02/13 15:55:28 [debug] 13184#0: *794 [lua] base_plugin.lua:28: header_filter(): executing plugin "acl": header_filter
2018/02/13 15:55:28 [debug] 13184#0: *794 [lua] base_plugin.lua:28: header_filter(): executing plugin "datadog": header_filter
2018/02/13 15:55:28 [debug] 13184#0: *794 [lua] base_plugin.lua:28: header_filter(): executing plugin "syslog": header_filter
2018/02/13 15:55:28 [debug] 13184#0: *794 [lua] base_plugin.lua:32: body_filter(): executing plugin "key-auth": body_filter
2018/02/13 15:55:28 [debug] 13184#0: *794 [lua] base_plugin.lua:32: body_filter(): executing plugin "acl": body_filter
2018/02/13 15:55:28 [debug] 13184#0: *794 [lua] base_plugin.lua:32: body_filter(): executing plugin "datadog": body_filter
2018/02/13 15:55:28 [debug] 13184#0: *794 [lua] base_plugin.lua:32: body_filter(): executing plugin "syslog": body_filter
2018/02/13 15:55:28 [debug] 13184#0: *794 [lua] base_plugin.lua:32: body_filter(): executing plugin "key-auth": body_filter
2018/02/13 15:55:28 [debug] 13184#0: *794 [lua] base_plugin.lua:32: body_filter(): executing plugin "acl": body_filter
2018/02/13 15:55:28 [debug] 13184#0: *794 [lua] base_plugin.lua:32: body_filter(): executing plugin "datadog": body_filter
2018/02/13 15:55:28 [debug] 13184#0: *794 [lua] base_plugin.lua:32: body_filter(): executing plugin "syslog": body_filter
2018/02/13 15:55:28 [debug] 13184#0: *794 [lua] base_plugin.lua:36: log(): executing plugin "key-auth": log
2018/02/13 15:55:28 [debug] 13184#0: *794 [lua] base_plugin.lua:36: log(): executing plugin "acl": log
2018/02/13 15:55:28 [debug] 13184#0: *794 [lua] base_plugin.lua:36: log(): executing plugin "datadog": log
2018/02/13 15:55:28 [debug] 13184#0: *794 [lua] base_plugin.lua:36: log(): executing plugin "syslog": log
```
- Kong configuration (registered APIs/Plugins & configuration file)
```
database = postgres
pg_host = [redacted].nonprod.internal
pg_port = 5432
pg_user = [redacted]
pg_password = [redacted]
pg_database = kong11
admin_listen = 0.0.0.0:8001
log_level = debug
```

- Operating System
```
Ubuntu 14.04.5 LTS
Linux [redacted] 3.13.0-141-generic #190-Ubuntu SMP Fri Jan 19 12:52:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Tieske** [comment] 2018-02-14 06:16
duplicate of #3210. See that issue for a workaround.

Since these pop up all of a sudden, it seems Consul has changed something recently?

**Closed by Tieske** 2018-02-14 06:16 UTC
