### ISSUE TITLE
HMAC signature cannot be verified when using more than one enforced header

### ISSUE THREAD

**Issue by nopslip** [Kong/kong#4321] opened 2019-02-18 21:39 UTC
### Summary
After setting up Kong hmac-auth plugin i'm getting error 403: `HMAC signature cannot be verified` when using more than one enforced header. 

### Steps To Reproduce

1. Setup the plugin, consumer and creds:
```
curl -i -X POST http://localhost:8001/services/my-service/plugins \
      -d "name=hmac-auth" \
      -d "config.enforce_headers=date, host, request-line" \
      -d "config.algorithms=hmac-sha256"
```
```
curl -i -X POST http://localhost:8001/consumers/ \
      -d "username=alice"
```
```
curl -i -X POST http://localhost:8001/consumers/alice/hmac-auth \
      -d "username=alice123" \
      -d "secret=XXX"
```
2. Testing POST from nodejs using Axios (relevant lines):
```
var d = new Date().toUTCString();
var signing_string = `date: ${d.trim()}\nhost: myhostname.com\nPOST /request HTTP/1.1`;
var new_hash = crypto.createHmac('sha256', secret).update(signing_string);
var base64_digest = new_hash.digest('base64');

let header = {
  headers: {
    date: d,
    Authorization: `hmac username="alice123", algorithm="hmac-sha256", headers="date, host, request-line", signature="${base64_digest}"`,
  },
};
```
produces `HMAC signature cannot be verified` 

I tracked down the error message here:
https://github.com/Kong/kong/blob/master/kong/plugins/hmac-auth/access.lua

enabled debug logging in Kong which lead me to this error: 

`[kong] access.lua:324 [hmac-auth] enforced header not used for signature creation`

From there I decided test with a single enforced header:
```
curl -i -X PATCH http://localhost:8001/plugins/<my_plugin_id_here>       -d "name=hmac-auth"       -d "config.enforce_headers=date"       -d "config.algorithms=hmac-sha256"
```
And sure enough, after removing the other header fields from the signature it worked with out issue. I tried each header individually and they all work by themselves but if I attempt to use more than one enforced header it fails. 

It seems likely this is related to how i'm crafting my signing_string but I can't seem to figure what I might be doing wrong? I also tested using this module https://www.npmjs.com/package/kong-hmac and I get the same 403 error.  

Any ideas why I can't get more than one enforced header working? 

### Additional Details & Logs
- Kong version 1.0.2
- my Kong Gateway is sitting behind Cloudflare 
- route/service in question is using SSL
 
All error.log related to the problem:
```
2019/02/18 20:41:49 [debug] 13352#0: *6728 [kong] access.lua:324 [hmac-auth] enforced header not used for signature creation
2019/02/18 20:41:49 [debug] 13352#0: *6728 [lua] base_plugin.lua:30: header_filter(): executing plugin "hmac-auth": header_filter
2019/02/18 20:41:49 [debug] 13352#0: *6728 [lua] base_plugin.lua:34: body_filter(): executing plugin "hmac-auth": body_filter
2019/02/18 20:41:49 [debug] 13352#0: *6728 [lua] base_plugin.lua:34: body_filter(): executing plugin "hmac-auth": body_filter
2019/02/18 20:41:49 [debug] 13352#0: *6728 [lua] base_plugin.lua:43: log(): executing plugin "hmac-auth": log
```

**Comment by HsinHeng** [comment] 2019-03-19 17:08
```
headers: {
    date: d,
    Authorization: `hmac username="alice123", algorithm="hmac-sha256", headers="date, host, request-line", signature="${base64_digest}"`,
  },
```

I think you missed your "Host" header in your header

**Comment by HsinHeng** [comment] 2019-03-23 14:31
I found the bug is located at

https://github.com/Kong/kong/blob/a33a592a4a578058195d159232279fda5f51ffb5/kong/plugins/hmac-auth/access.lua#L130

kong.request.get_header(header) get  incorrect value.

in my case,  header="X-APP-ID", should return my customized app-id, but return striing:
"Thu, 23 Mar 2019 14:25:00 GMT, client: 172.17.0.1, server: kong, request: "GET /api/v1/ping HTTP/1.1", host: "192.168.99.122:31346"

hope develop team will fix the bug.
Thx.

**Comment by HsinHeng** [comment] 2019-03-23 15:01
I found the problem is that

https://github.com/Kong/kong/blob/a33a592a4a578058195d159232279fda5f51ffb5/kong/plugins/hmac-auth/access.lua#L148

Use the "\n" as split will cause unexpected signature.
I try to modify the source code from "\n" to "|".
It will pass when I use multiple headers.

Maybe Develop team can quick fix the bug.
Thanks.

**Comment by RuChiang** [comment] 2019-08-21 05:38
Hi @nopslip 
I think that's a bug from the docs.
`curl -i -X POST http://localhost:8001/services/my-service/plugins \
      -d "name=hmac-auth" \
      -d "config.enforce_headers=date, host, request-line" \
      -d "config.algorithms=hmac-sha256"
`
Will give you the string "date, host, request-line" in the config.enforce_headers field.
You should use
`curl -i -X POST http://localhost:8001/services/my-service/plugins \
      -d "name=hmac-auth" \
      -d "config.enforce_headers[]=date&config.enforce_headers[]=request-line" \
      -d "config.algorithms=hmac-sha256"
`

**Comment by robincher** [comment] 2019-10-04 07:38
Just a question, do i need to send in Request line as a header when making a call? 

I was following the documents and keep getting HMAC signature cannot be verified error


```
hmac username="helios",algorithm="hmac-sha256",headers="date request-line",signature="asdsadasdasdasdsa"
```

Request HTTP Header
```
 Host: '*.something.io',
 Date: 'Fri, 04 Oct 2019 07:36:24 GMT',
 Authorization:'hmac username="helios",algorithm="hmac-sha256",headers="date request-line",signature="aasdasdasdadada="'
```

**Comment by RuChiang** [comment] 2019-10-06 04:16
Hi @robincher 
there is no need to include the `Request line` as a header.
I guess the issue might have come from the `signature`, as it is generated with the date object, so putting something like `asdsadasdasdasdsa` won't work

**Comment by robincher** [comment] 2019-10-07 03:16
Hi,

Copied that.  Not sure what i exactly changed, but seems like it's working now.

```asdsadasdasdasdsa``` obviously was sanitised from the actual signature value ;P

**Comment by kikito** [comment] 2019-10-11 11:02
Hi @nopslip, can you confirm whether the solutions posted here solved your issue?

**Comment by nopslip** [comment] 2019-10-11 17:57
It's been awhile since I looked into this but I can pull it back up and test soon.

**Comment by bungle** [comment] 2020-03-31 11:11
I am closing this now, as it is getting a bit old with further info. @nopslip, please reopen if you can still reproduce this.

**Closed by bungle** 2020-03-31 11:11 UTC
Labels: pending author feedback
