### ISSUE TITLE
Error when Starting Kong API

### ISSUE THREAD

**Issue by Danni-Ke** [Kong/kong#4648] opened 2019-05-24 04:26 UTC
Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary
When I start the kong, it gives me error message below:
SUMMARY_GOES_HERE
ERROR: /usr/local/share/lua/5.1/kong/cmd/utils/nginx_signals.lua:16: attempt to call field 'set' (a nil value)
stack traceback:
	[C]: in function 'require'
	/usr/local/share/lua/5.1/kong/cmd/utils/prefix_handler.lua:22: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:2: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:55: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:7: in function 'file_gen'
	init_worker_by_lua:49: in function <init_worker_by_lua:47>
	[C]: in function 'xpcall'
	init_worker_by_lua:56: in function <init_worker_by_lua:54>

ANY HELP will be appricated! THANK U GUYS.
### Steps To Reproduce

1. I tried to drop the database and create a new one, but it doesn't work.
2.
3.
4.

### Additional Details & Logs

- Kong version (`1.1.2`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system
 ubuntu 18.4

**Comment by gszr** [comment] 2019-05-24 04:53
Hi @Danni-Ke,

Could you provide us with more information - the configuration you are using and a step-by-step on how to reproduce the issue? Also, how did you install Kong - was it using our [official Ubuntu repository](https://bintray.com/kong/kong-deb)?

**Comment by Danni-Ke** [comment] 2019-05-24 06:03
> Hi @Danni-Ke,
> Could you provide us with more information - the configuration you are using and a step-by-step on how to reproduce the issue? Also, how did you install Kong - was it using our official Ubuntu repository?

hi！What I did just start a new database on my vitual machine(Ubuntu), then I download the file on the official page of kong according to my ubuntu version. Then I use the kong.conf.default as the my argument of the database migrations command and start command.

**Comment by gszr** [comment] 2019-05-25 00:01
@Danni-Ke,

I'm not able to reproduce the issue.

Check if the user you are running Kong with has write permissions over the Kong prefix (which by default is `/usr/local/kong`). From the error message it's unlikely that this is the root cause, but worth checking.

Closing the issue, but do feel free to reopen if you have more information.

**Closed by gszr** 2019-05-25 00:01 UTC
