### ISSUE TITLE
set port 0 into a upstream which switch on health check,upstream will be damaged

### ISSUE THREAD

**Issue by luguohong** [Kong/kong#7888] opened 2021-09-25 08:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.2.0

### Current Behavior

when i set target(with port 0)into a upsteam(switch on passsive active healthcheck), target show DNS_ERROR.
then i delete it and set a right target into upstream, upstream still not work.
i guess the upstream be damaged.

### Expected Behavior

when i delete a error target, and set right target, upstream will be work

### Steps To Reproduce

```markdown
1. create service-a
2. create route-a(/) in service-a
3. set upstream-a in service-a
4. create upstream-a and set passtive healthcheck and active healthcheck
5. add target 192.168.0.10:0 into upstream-a
6. access kong:8000/ and show error msg
7. delete target 192.168.0.10:0
8. add target 192.168.0.10:8080(a right target)
9. access kong:8000/ and show error msg
10. kong reload
11. access kong:8000/ and show normal
```

**Comment by Tieske** [comment] 2021-09-25 11:09
Haven't looked into the issue itself, just leaving this here as context; DNS SRV records can return a port 0. Normally the load balancer will pick up the port provided by the SRV record and override the user provided port (Kong trusts the nameserver). But in case of port 0 in the SRV record it will fall back to the user provided port. So this is a special case.

**Comment by StarlightIbuki** [comment] 2023-10-11 06:24
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:24 UTC
Labels: task/needs-investigation, core/balancer
