### ISSUE TITLE
Errors after change a nginx_kong.lua file

### ISSUE THREAD

**Issue by RobertMlo** [Kong/kong#3245] opened 2018-02-22 08:04 UTC
### Summary

I have changed a `nginx_kong.lua` file to add a custom var:

```lua
lru_cache_size ${{LRU_CACHE_SIZE}};
```

I have also deliverd a default value for the `lru_cache_size` in a `kong_defaults.lua` file:

```lua
lru_cache_size = 500000
```

After that if I want to restart a kong, I receive the following error:

> ./kong/cmd/start.lua:9: lru_cache_size is not a string: '500000'

If I set a `KONG_LRU_CACHE_SIZE` env in OS:

> export KONG_LRU_CACHE_SIZE=500000

then I receive a different error:

> Error: ./kong/cmd/start.lua:51: nginx: [emerg] unknown directive "lru_cache_size" in /usr/local/kong/nginx-kong.conf:12

How to fix this issue for both cases?

### Steps To Reproduce for case 1

1. Add `lru_cache_size ${{LRU_CACHE_SIZE}};` to the `nginx_kong.lua` file.
2. Add `lru_cache_size = 500000` to the `kong_defaults.lua` file.
3. Restart the kong (or start it if it is turned off).

### Steps To Reproduce for case 2

1. Add `lru_cache_size ${{LRU_CACHE_SIZE}};` to the `nginx_kong.lua` file.
2. Add `lru_cache_size = 500000` to the `kong_defaults.lua` file.
3. Add  env to OS: `export KONG_LRU_CACHE_SIZE=500000`.
4. Restart the kong (or start it if it is turned off).

### Additional Details & Logs

- Kong version: 0.11.1
- Kong debug-level startup logs for case 1: [LOGS](https://gist.github.com/RobertMlo/751b01d1821f0528d079aeb9c8da9306)
- Kong debug-level startup logs for case 2: [LOGS](https://gist.github.com/RobertMlo/27899e3e8041afe2e5997255a41c3527)
- Kong error logs for case 1: nothing to show.
- Kong error logs for case 2:

> 2018/02/22 07:32:36 [emerg] 11023#0: unknown directive "lru_cache_size" in /usr/local/kong/nginx-kong.conf:12

- Operating System: CentOS 7

**Comment by hishamhm** [comment] 2018-02-22 14:27
@RobertMlo If you want to add custom variables, instead of editing the defaults generated by Kong, you should generate your own nginx configuration and use that when launching Kong. For Kong 0.11.1 this is done using the (now deprecated) [kong compile](https://getkong.org/docs/0.11.x/cli/#kong-compile) command. With Kong 0.12+ this is done using [kong prepare](https://getkong.org/docs/0.12.x/cli/#kong-prepare). The `kong prepare` command will generate the Kong-enabled Nginx configuration which you can then tweak and use.

Note however that the following error message:

> Error: ./kong/cmd/start.lua:51: nginx: [emerg] unknown directive "lru_cache_size" in /usr/local/kong/nginx-kong.conf:12

means that the nginx binary does not understand the `lru_cache_size` directive. Are you bundling a custom nginx module?

**Comment by hishamhm** [comment] 2018-02-22 14:30
(I'm closing this issue since it is not a bug in Kong, but feel free to reply here or to post in [Kong Nation](https://discuss.konghq.com) for further discussion.)

**Closed by hishamhm** 2018-02-22 14:30 UTC
