### ISSUE TITLE
Errors logged for health check setAddressStatus failure

### ISSUE THREAD

**Issue by chris-branch** [Kong/kong#5589] opened 2020-02-20 18:24 UTC
I see a large number of error messages in the error_log that look like this:

`2020/02/20 18:02:44 [error] 315#0: *107648547 [lua] balancer.lua:294: [healthchecks] failed setting peer status: no peer found by name '<redacted>' and address 10.2.220.4:443, context: ngx.timer`

Kong is able to serve traffic to these hosts perfectly fine, so there doesn't seem to be any negative impact from this other than cluttering up of the error_log.  The DNS for the host name in question is configured with a TTL of 30 seconds, and it rotates the IP address every 30 seconds (returns a single A name record).  So I think what is happening is that Kong is doing a DNS requery every minute and getting a new IP address.  During the health check callback, it calls `setAddressStatus`:

https://github.com/Kong/kong/blob/master/kong/runloop/balancer.lua#L286

`setAddressStatus` attempts to find an existing entry that matches the host, port, and IP address.  The host and port match, but the IP address has changed, so it logs an error because the lookup failed due to the new IP address.

My question is: Is this really an error, or is it safe to ignore the setAddressStatus failure in this particular scenario?  If the latter, could the code be changed to avoid logging an error message for this scenario?

By the way, I don't have health checks explicitly configured for this upstream.  This health check is the built-in one that Kong adds automatically.

Kong version: 1.4.2

**Comment by wanyuetian** [comment] 2020-04-09 10:14
I face the same problem with Kong v1.4.2

**Comment by agaffney** [comment] 2020-04-28 17:29
I'm seeing this problem with both 1.5.1 and 2.0.2, when using a S3 endpoint for the upstream. The DNS record for the S3 bucket returns a different single IP on each query.

**Comment by agaffney** [comment] 2020-04-30 15:41
I cannot seem to reproduce this in an isolated environment :(

**Comment by agaffney** [comment] 2020-04-30 21:41
This only seems to occur when using multiple workers. I deployed Kong with the helm chart and set `env.nginx_worker_processes=4` and then deployed the following manifest, and the errors popped up almost immediately.

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: kong-peer-status-test
spec:
  externalName: foo.s3-website-us-east-1.amazonaws.com
  type: ExternalName
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  name: kong-peer-status-test
spec:
  rules:
  - host: foo.example.com
    http:
      paths:
      - backend:
          serviceName: kong-peer-status-test
          servicePort: 80
        path: /
```

**Comment by Tieske** [comment] 2020-05-01 11:58
thx for the update. Just came back here because I thought of a possible underlying reason for this to happen.

The environments you are using are highly dynamic from a DNS perspective. The backends have most likely a DNS based LB in front of them, which returns a new IP on every query.

Now the DNS caches are per worker. But the healthchecks are on the Kong node level. Now if you have a 2 worker node, and each gets a different IP from the DNS server, then setting the status of each IP will only work in one worker, and will fail in the other.

**Comment by chris-branch** [comment] 2020-05-01 12:36
Is there a reason why the DNS cache is maintained per nginx worker (rather than per Kong instance)?  It seems like you could significantly reduce the number of DNS queries needed (and maybe solve this problem too?) if all workers shared a cache.

**Comment by Tieske** [comment] 2020-05-01 12:40
yes and no

if you share the cache, then all workers would hit the same IP, whereas with individual caches you spread the load because workers will get different IP's and hence hit different backends.

Essentially by sharing the cache you will undo the efforts of the backend LB of distributing the load.

**Comment by chris-branch** [comment] 2020-05-01 12:46
I think I would argue that DNS is misconfigured in that case.  If you are trying to use DNS load balancing, then the DNS server should either: 1) return a single IP address each time with TTL = 0 to force a requery on every request, or 2) return a collection of IPs with whatever TTL is reasonable.  If the DNS server returns a collection of IPs, Kong would load balance across all of those (using upstreams + targets), correct?  If the DNS server is configured to return a single IP with a non-zero TTL, then I would argue that it's reasonable to send all traffic to that single IP until the TTL has expired.

**Comment by Tieske** [comment] 2020-05-01 12:55
I guess so.

But this is a hairy issue. The OP is about errors from healthcheckers. If we share the cache, with for example an AWS S3, with 5 second TTL. Then every 5 seconds the address would be removed from the balancer and be replaced by another one. Destroying the healthcheckers and all state with them. Would render the HC completely useless.

**Comment by chris-branch** [comment] 2020-05-01 13:04
I kind of question the value of the default healthchecker in the first place.  If I understand correctly, the default healthcheck is simply doing a DNS requery, which doesn't really tell you whether the upstream is available -- only that the name is still resolvable.  Is there a way to disable the default health check?  If I configure my own healthcheck, does my health check run _instead of_ or _in addition_ to the default health check?

**Comment by Tieske** [comment] 2020-05-12 08:59
@chris-branch what do you mean by "default healthchecker"? Kong only has the healthchecks with the upstream entity. These are disabled by default?

**Comment by chris-branch** [comment] 2020-05-12 12:38
Maybe I'm using the wrong terminology, but this is what I'm considering the "default healthchecker":
https://github.com/Kong/kong/blob/master/kong/runloop/balancer.lua#L273

In contrast to the healthchecks that are user-configurable for an upstream (but do not exist by default unless/until configured):
```
{
    "id": "58c8ccbb-eafb-4566-991f-2ed4f678fa70",
    "name": "my-upstream",
    "healthchecks": {
        "active": {
            ....
        },
        "passive": {
            ....
        },
        "threshold": 0
    },
}
```

**Comment by Tieske** [comment] 2020-05-12 15:25
it gets a healthchecker attached, but if not configured, it is only there to report the status if requested. It will not do anything.

But maybe you mean the dns-requery timer (1sec) that checks for expired ttl of targets in the loadbalancer. Because updating dns records might trigger the error in the OP.

see https://github.com/Kong/lua-resty-dns-client/blob/master/src/resty/dns/balancer/base.lua#L1409-L1421

**Comment by chris-branch** [comment] 2020-05-12 16:22
Yes, the health check callback (hc_callback) that's installed in balancer.lua seems to be called during dns requeries, and logs an error message if the IP address has changed since the previous callback.  There is nothing inherently wrong just because the IP has changed, so it really shouldn't log an error in that situation.  That is the crux of the OP.

The followup questions I asked were my attempt at finding a workaround.  Specifically, if there was a way to disable this "built-in" callback that is happening for dns requiries, or otherwise override it (perhaps by explicitly configuring my own healthcheck for the upstream).

**Comment by Tieske** [comment] 2020-05-12 17:18
nope, no workaround through config, only fix is through code

**Comment by kikito** [comment] 2020-06-17 17:28
I'm going to close this down for now since #5932 makes the error a warning. Please reopen if needed.

**Closed by kikito** 2020-06-17 17:28 UTC
Labels: task/needs-investigation
