### ISSUE TITLE
Kong intermittently maps to the shortest uri when multiple uris are defined

### ISSUE THREAD

**Issue by supraja93** [Kong/kong#3262] opened 2018-02-26 21:32 UTC
### Summary

If two (or more) APIs have uris that match the incoming uri, Kong intermittently routes to the wrong upstream url, in this case the shortest uri.
### Steps To Reproduce

1. Create 3 apis associated to an entity and each api has the same hosts but different uris and upstream urls. 
Api Config =>
/ --> upstream1.com 
/api/public --> upstream2.com 
/api/secure --> upstream3.com

2. curl /api/public/123 (after API's are created ), it rightly routes to upstream2.com

3. Delete and create the /api/public and /api/secure apis (with changes to the upstream url's)
New Api config =>
/ --> upstream1.com 
/api/public --> upstream22.com 
/api/secure --> upstream33.com

4. Now curl /api/public/123,  it routes to upstream1.com instead of upstream22.com

Note:
This happens intermittently. 
curl /api/public/123 always works initially, when created, but on consecutive deletion and creation of the /api/public and /api/secure routes, it routes to the wrong upstream url.

### Additional Details & Logs

- Kong version (0.11.0)

**Comment by hishamhm** [comment] 2018-02-26 22:05
Hi! 0.11.0 is out-of-date. Can you confirm if the bug still happens in the latest version (0.12.1)?

**Comment by supraja93** [comment] 2018-02-26 22:36
@hishamhm haven't got a chance to check it in the latest version, will do so and post my findings.

**Comment by supraja93** [comment] 2018-03-06 22:59
@hishamhm This happens in 0.12.1 version as well

**Comment by bungle** [comment] 2018-04-02 09:44
I tried this with `0.13.0` and couldn't reproduce:

```
http :8001/apis name=a uris=/ upstream_url=http://upstream1.com/
http :8001/apis name=b uris=/api/public upstream_url=http://upstream2.com/
http :8001/apis name=c uris=/api/secure upstream_url=http://upstream3.com/
# http :8000/api/public/123 # optional check
http delete :8001/apis/b
http delete :8001/apis/c
# http :8000/api/public/123 # optional check
http :8001/apis name=b uris=/api/public upstream_url=http://upstream2.com/
http :8001/apis name=c uris=/api/secure upstream_url=http://upstream3.com/
http :8000/api/public/123
```

**Comment by supraja93** [comment] 2018-04-17 20:32
@bungle  below is the workaround we did to fix the issue. Instead of just having the uri and upstreams  like 
/ --> upstream1.com
/api/public --> upstream2.com
/api/secure --> upstream3.com
 
we also included the **Methods on /api/public and /api/secure** routes as below

/ --> upstream1.com
/api/public --> upstream2.com --> POST,GET,PUT,DELETE
/api/secure --> upstream3.com --> POST,GET,PUT,DELETE

this caused /api/public/123, to be correctly routed to upstream2.com instead of upstream1.com.
From what I understood, if given **uri and method** this takes higher preference in evaluating the upstream than just having the **uri**.

This is in kong 0.12

**Comment by supraja93** [comment] 2018-04-17 21:32
@bungle  these were my observations and workaround, to prevent /api/public/123 to be mapped to base uri(/) upstream. When adding the method the calls are getting routed correctly. I think this ascertains that the /api/public/123 call was mapped to the shortest path (/) earlier, not sure if there could be any other reasons.

**Comment by thegreatanon** [comment] 2018-06-25 08:10
I'm running kong 0.13.1 and I think I have a similar issue:

Route 1: /api
Route 2: /api POST,UPDATE,DELETE (has rate-limiting)
Route 3: /api-internal

(all connected to same service)

The expectation would be that when making requests to /api/... the POST, UPDATE and DELETE requests would be rate-limited (caught by route 2). Other request types are ok and are allowed (caught by route 1).

For internal purposes I don't want to have any rate-limiting and I've set up route 3 without any request type definitions.

I've noticed that requests to /api-internal would be directed to /api/-internal (so route 1 or 2)
I would expect route 3 to be followed.

**Comment by subnetmarco** [comment] 2019-02-28 01:05
Any updates with this issue on latest Kong `1.x` ?

**Comment by supraja93** [comment] 2019-03-01 06:25
Hey Marco,

I moved out of the company and I no longer have access to that specific use
case. Sorry about that, let me know if you need anything from my side,
I'd be happy to help.

Thanks,
Supraja

**Comment by bungle** [comment] 2019-08-15 15:16
Closing this, as it does not seem to be a concern anymore and nobody has reported about it

**Closed by bungle** 2019-08-15 15:16 UTC
Labels: task/needs-investigation
