### ISSUE TITLE
Adding config string with literal plus sign (+) is sanitized as whitespace

### ISSUE THREAD

**Issue by thomasgriffin** [Kong/kong#2970] opened 2017-10-19 02:26 UTC
### Summary

Using the AWS Lambda plugin, one of my AWS key/secret pairs contains a literal plus sign (+) in the string. I couldn't for the life of me figure out why I kept getting key errors until I realized that once the information was saved, the plus sign was removed and replaced with whitespace.

To fix the problem, I had to use `%2B` in place of the plus sign to get it to save as the literal plus sign. Once I did this, everything worked.

### Steps To Reproduce

1. Configure the AWS Lambda plugin with any API route and pass in a config string that contains a `+` in it.
2. After running the RESTful request, notice in the response that the `+` is stripped out and replaced with whitespace.

### Additional Details & Logs

- Kong version (`0.11.0`)
- Operating System: Ubuntu 16.04 (Xenial)

**Comment by hishamhm** [comment] 2017-10-19 16:41
How did you send the request to the Admin API endpoint?

If you are using `curl`, for example, when sending any [reserved characters in an HTTP request](https://en.wikipedia.org/wiki/Percent-encoding), you need to use `--data-urlencode` instead of `--data` to supply your data.

**Comment by p0pr0ck5** [comment] 2017-10-19 18:19
@hishamhm is correct. This is a duplicate of https://github.com/Kong/kong/issues/2651, which in turn was not a bug :) Please use `--data-urlencode` when defining request body params with `+` characters.

**Closed by p0pr0ck5** 2017-10-19 18:19 UTC
