### ISSUE TITLE
Postgres password from kong.conf is truncated when it contains a '#' char

### ISSUE THREAD

**Issue by jonhy-bigodes** [Kong/kong#5761] opened 2020-04-07 18:59 UTC
### Summary

While using a Kong instance with a Postgres DB configured via kong.conf file, if the password contains a '#' char, even when escaped with a single '\', Kong fails to start.

The `kong migrations up` step runs successfully, but `kong start` command fails with an authentication failure.
Example of a password in the configuration file: `pg_password = !abCDefGHijKL4\#1MN2OP3`

### Steps To Reproduce

**1.** Setup **kong.conf** file with all the pg_XXX properties, set a password with a '#' in the middle, eg: `pg_password = !abCDefGHijKL4\#1MN2OP3`
**2.** Do not use / unset any KONG_PG_xxx environment properties
**3.** Run `kong migrations up` and `kong migrations finish`: it connects to the DB and runs migrations successfully
**4.** Run kong `start --vv`: it fails DC connection with a bad password authentication error

### Additional Details & Logs

- Kong version 2.0.2 (same error occurs at least from version 1.1.2 up to 2.0.2)
- Kong debug-level startup logs:

```
# kong start --vv
2020/04/07 17:55:29 [verbose] Kong: 2.0.2
2020/04/07 17:55:29 [debug] ngx_lua: 10015
2020/04/07 17:55:29 [debug] nginx: 1015008
2020/04/07 17:55:29 [debug] Lua: LuaJIT 2.1.0-beta3
2020/04/07 17:55:29 [verbose] reading config file at /etc/kong/kong.conf
2020/04/07 17:55:29 [debug] reading environment variables
2020/04/07 17:55:29 [debug] admin_access_log = "logs/admin_access.log"
2020/04/07 17:55:29 [debug] admin_error_log = "logs/error.log"
2020/04/07 17:55:29 [debug] admin_listen = {"0.0.0.0:8001"}
2020/04/07 17:55:29 [debug] anonymous_reports = true
2020/04/07 17:55:29 [debug] cassandra_consistency = "ONE"
2020/04/07 17:55:29 [debug] cassandra_contact_points = {"127.0.0.1"}
2020/04/07 17:55:29 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2020/04/07 17:55:29 [debug] cassandra_keyspace = "kong"
2020/04/07 17:55:29 [debug] cassandra_lb_policy = "RequestRoundRobin"
2020/04/07 17:55:29 [debug] cassandra_port = 9042
2020/04/07 17:55:29 [debug] cassandra_refresh_frequency = 60
2020/04/07 17:55:29 [debug] cassandra_repl_factor = 1
2020/04/07 17:55:29 [debug] cassandra_repl_strategy = "SimpleStrategy"
2020/04/07 17:55:29 [debug] cassandra_schema_consensus_timeout = 10000
2020/04/07 17:55:29 [debug] cassandra_ssl = false
2020/04/07 17:55:29 [debug] cassandra_ssl_verify = false
2020/04/07 17:55:29 [debug] cassandra_timeout = 5000
2020/04/07 17:55:29 [debug] cassandra_username = "kong"
2020/04/07 17:55:29 [debug] client_body_buffer_size = "8k"
2020/04/07 17:55:29 [debug] client_max_body_size = "0"
2020/04/07 17:55:29 [debug] client_ssl = false
2020/04/07 17:55:29 [debug] cluster_control_plane = "127.0.0.1:8005"
2020/04/07 17:55:29 [debug] cluster_listen = {"0.0.0.0:8005"}
2020/04/07 17:55:29 [debug] database = "postgres"
2020/04/07 17:55:29 [debug] db_cache_ttl = 0
2020/04/07 17:55:29 [debug] db_cache_warmup_entities = {"services","plugins"}
2020/04/07 17:55:29 [debug] db_resurrect_ttl = 30
2020/04/07 17:55:29 [debug] db_update_frequency = 5
2020/04/07 17:55:29 [debug] db_update_propagation = 0
2020/04/07 17:55:29 [debug] dns_error_ttl = 1
2020/04/07 17:55:29 [debug] dns_hostsfile = "/etc/hosts"
2020/04/07 17:55:29 [debug] dns_no_sync = false
2020/04/07 17:55:29 [debug] dns_not_found_ttl = 30
2020/04/07 17:55:29 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2020/04/07 17:55:29 [debug] dns_resolver = {}
2020/04/07 17:55:29 [debug] dns_stale_ttl = 4
2020/04/07 17:55:29 [debug] error_default_type = "text/plain"
2020/04/07 17:55:29 [debug] go_plugins_dir = "off"
2020/04/07 17:55:29 [debug] go_pluginserver_exe = "/usr/local/bin/go-pluginserver"
2020/04/07 17:55:29 [debug] headers = {"server_tokens","latency_tokens"}
2020/04/07 17:55:29 [debug] log_level = "notice"
2020/04/07 17:55:29 [debug] lua_package_cpath = ""
2020/04/07 17:55:29 [debug] lua_package_path = "./?.lua;./?/init.lua;"
2020/04/07 17:55:29 [debug] lua_socket_pool_size = 30
2020/04/07 17:55:29 [debug] lua_ssl_trusted_certificate = ""
2020/04/07 17:55:29 [debug] lua_ssl_verify_depth = 1
2020/04/07 17:55:29 [debug] mem_cache_size = "128m"
2020/04/07 17:55:29 [debug] nginx_admin_directives = {}
2020/04/07 17:55:29 [debug] nginx_daemon = "on"
2020/04/07 17:55:29 [debug] nginx_events_directives = {{name="worker_connections",value="auto"},{name="multi_accept",value="on"}}
2020/04/07 17:55:29 [debug] nginx_events_multi_accept = "on"
2020/04/07 17:55:29 [debug] nginx_events_worker_connections = "auto"
2020/04/07 17:55:29 [debug] nginx_http_client_body_buffer_size = "8k"
2020/04/07 17:55:29 [debug] nginx_http_client_max_body_size = "0"
2020/04/07 17:55:29 [debug] nginx_http_directives = {{name="client_max_body_size",value="0"},{name="ssl_prefer_server_ciphers",value="off"},{name="client_body_buffer_size",value="8k"},{name="ssl_protocols",value="TLSv1.2 TLSv1.3"},{name="ssl_session_tickets",value="on"},{name="ssl_session_timeout",value="1d"}}
2020/04/07 17:55:29 [debug] nginx_http_ssl_prefer_server_ciphers = "off"
2020/04/07 17:55:29 [debug] nginx_http_ssl_protocols = "TLSv1.2 TLSv1.3"
2020/04/07 17:55:29 [debug] nginx_http_ssl_session_tickets = "on"
2020/04/07 17:55:29 [debug] nginx_http_ssl_session_timeout = "1d"
2020/04/07 17:55:29 [debug] nginx_http_status_directives = {}
2020/04/07 17:55:29 [debug] nginx_http_upstream_directives = {{name="keepalive_requests",value="100"},{name="keepalive_timeout",value="60s"},{name="keepalive",value="60"}}
2020/04/07 17:55:29 [debug] nginx_http_upstream_keepalive = "60"
2020/04/07 17:55:29 [debug] nginx_http_upstream_keepalive_requests = "100"
2020/04/07 17:55:29 [debug] nginx_http_upstream_keepalive_timeout = "60s"
2020/04/07 17:55:29 [debug] nginx_main_daemon = "on"
2020/04/07 17:55:29 [debug] nginx_main_directives = {{name="daemon",value="on"},{name="worker_rlimit_nofile",value="auto"},{name="worker_processes",value="auto"}}
2020/04/07 17:55:29 [debug] nginx_main_worker_processes = "auto"
2020/04/07 17:55:29 [debug] nginx_main_worker_rlimit_nofile = "auto"
2020/04/07 17:55:29 [debug] nginx_optimizations = true
2020/04/07 17:55:29 [debug] nginx_proxy_directives = {{name="real_ip_header",value="X-Real-IP"},{name="real_ip_recursive",value="off"}}
2020/04/07 17:55:29 [debug] nginx_proxy_real_ip_header = "X-Real-IP"
2020/04/07 17:55:29 [debug] nginx_proxy_real_ip_recursive = "off"
2020/04/07 17:55:29 [debug] nginx_sproxy_directives = {}
2020/04/07 17:55:29 [debug] nginx_status_directives = {}
2020/04/07 17:55:29 [debug] nginx_stream_directives = {}
2020/04/07 17:55:29 [debug] nginx_supstream_directives = {}
2020/04/07 17:55:29 [debug] nginx_upstream_directives = {{name="keepalive_requests",value="100"},{name="keepalive_timeout",value="60s"},{name="keepalive",value="60"}}
2020/04/07 17:55:29 [debug] nginx_upstream_keepalive = "60"
2020/04/07 17:55:29 [debug] nginx_upstream_keepalive_requests = "100"
2020/04/07 17:55:29 [debug] nginx_upstream_keepalive_timeout = "60s"
2020/04/07 17:55:29 [debug] nginx_worker_processes = "auto"
2020/04/07 17:55:29 [debug] pg_database = "kong"
2020/04/07 17:55:29 [debug] pg_host = "localhost"
2020/04/07 17:55:29 [debug] pg_max_concurrent_queries = 0
2020/04/07 17:55:29 [debug] pg_password = "******"
2020/04/07 17:55:29 [debug] pg_port = 5432
2020/04/07 17:55:29 [debug] pg_schema = "kong"
2020/04/07 17:55:29 [debug] pg_semaphore_timeout = 60000
2020/04/07 17:55:29 [debug] pg_ssl = false
2020/04/07 17:55:29 [debug] pg_ssl_verify = false
2020/04/07 17:55:29 [debug] pg_timeout = 5000
2020/04/07 17:55:29 [debug] pg_user = "kong"
2020/04/07 17:55:29 [debug] plugins = {"bundled"}
2020/04/07 17:55:29 [debug] prefix = "/usr/local/kong/"
2020/04/07 17:55:29 [debug] proxy_access_log = "logs/access.log"
2020/04/07 17:55:29 [debug] proxy_error_log = "logs/error.log"
2020/04/07 17:55:29 [debug] proxy_listen = {"0.0.0.0:8000"}
2020/04/07 17:55:29 [debug] real_ip_header = "X-Real-IP"
2020/04/07 17:55:29 [debug] real_ip_recursive = "off"
2020/04/07 17:55:29 [debug] role = "traditional"
2020/04/07 17:55:29 [debug] router_consistency = "strict"
2020/04/07 17:55:29 [debug] router_update_frequency = 1
2020/04/07 17:55:29 [debug] ssl_cipher_suite = "intermediate"
2020/04/07 17:55:29 [debug] ssl_ciphers = "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"
2020/04/07 17:55:29 [debug] status_access_log = "off"
2020/04/07 17:55:29 [debug] status_error_log = "logs/status_error.log"
2020/04/07 17:55:29 [debug] status_listen = {"off"}
2020/04/07 17:55:29 [debug] stream_listen = {"off"}
2020/04/07 17:55:29 [debug] trusted_ips = {}
2020/04/07 17:55:29 [debug] upstream_keepalive = 60
2020/04/07 17:55:29 [verbose] prefix in use: /usr/local/kong
2020/04/07 17:55:31 [debug] loading subsystems migrations...
2020/04/07 17:55:31 [verbose] retrieving database schema state...
2020/04/07 17:55:32 [verbose] schema state retrieved
2020/04/07 17:55:32 [verbose] preparing nginx prefix directory at /usr/local/kong
2020/04/07 17:55:33 [debug] searching for OpenResty 'nginx' executable
2020/04/07 17:55:33 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.15.8.2'
2020/04/07 17:55:33 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2020/04/07 17:55:33 [debug] testing nginx configuration: KONG_NGINX_CONF_CHECK=true /usr/local/openresty/nginx/sbin/nginx -t -p /usr/local/kong -c nginx.conf
2020/04/07 17:55:33 [debug] searching for OpenResty 'nginx' executable
2020/04/07 17:55:33 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.15.8.2'
2020/04/07 17:55:33 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2020/04/07 17:55:33 [debug] sending signal to pid at: /usr/local/kong/pids/nginx.pid
2020/04/07 17:55:33 [debug] kill -0 `cat /usr/local/kong/pids/nginx.pid` >/dev/null 2>&1
2020/04/07 17:55:33 [debug] starting nginx: /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong -c nginx.conf
2020/04/07 17:55:34 [verbose] could not start Kong, stopping services
2020/04/07 17:55:34 [debug] sending signal to pid at: /usr/local/kong/pids/nginx.pid
2020/04/07 17:55:34 [debug] kill -0 `cat /usr/local/kong/pids/nginx.pid` >/dev/null 2>&1
2020/04/07 17:55:34 [verbose] stopped services
Error: 
/usr/local/share/lua/5.1/kong/cmd/start.lua:75: /usr/local/share/lua/5.1/kong/cmd/start.lua:64: nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:389: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: FATAL: password authentication failed for user "kong"
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/init.lua:389: in function 'init'
        init_by_lua:3: in main chunk

stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/kong/cmd/start.lua:75: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
        /usr/local/bin/kong:9: in function 'file_gen'
        init_worker_by_lua:47: in function <init_worker_by_lua:45>
        [C]: in function 'xpcall'
        init_worker_by_lua:54: in function <init_worker_by_lua:52>

```

- Operating System: Ubuntu 18.04, tests done using kong:2.0 docker image

**Comment by hutchic** [comment] 2020-04-07 19:27
Duplicate of https://github.com/Kong/kong/issues/5289#issuecomment-561667406

> Use the \ character to escape #. This is documented in the config file reference.

**Comment by jonhy-bigodes** [comment] 2020-04-08 08:32
Your docker-compose template uses environment variables  KONG_PG_PASSWORD: kong\#123.
The bug does not happen when the password is injected through environment variables, it only happens when kong.conf file-based configuration is used instead of using environment vars.

**Closed** 2020-04-28 16:22 UTC
Labels: task/bug

**Comment by wtfyucheng** [comment] 2020-07-29 05:43
Hi there,
We're using AWS RDS access token to connect to our Kong AWS RDS db.
It's successful to connect to db when using injected environment variables, but failed to start Kong with kong.conf file-based configuration.

Here is the example of the access token:
kong-service.xxxxxxxxxxx.aws_region.rds.amazonaws.com:5432/?Action=connect&DBUser=kong&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=aws_key%2F20200728%2Fus-west-2%2Frds-db%2Faws4_request&X-Amz-Date=20200728T083013Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Signature=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Could you tell us which special character that we should escape ?
Thanks.
