### ISSUE TITLE
client prematurely closed connection while processing HTTP/2 connection return 500

### ISSUE THREAD

**Issue by highwayliu** [Kong/kong#8192] opened 2021-12-15 03:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 2.4.1

### Current Behavior

I found some 500 error in access log, and I trace the error log, and found some logs here.

2021/12/15 01:32:29 [info] 2312400#0: *1475399307 client prematurely closed connection while processing HTTP/2 connection, client: 119.160.59.59, server: 0.0.0.0:9081

### Expected Behavior

HOW does it happen ? i seems that user client close the connection.
But it should return 499 instead?

### kong start -vv
2021/12/15 03:23:39 [verbose] Kong: 2.4.1
2021/12/15 03:23:39 [debug] ngx_lua: 10019
2021/12/15 03:23:39 [debug] nginx: 1019003
2021/12/15 03:23:39 [debug] Lua: LuaJIT 2.1.0-beta3
2021/12/15 03:23:39 [verbose] no config file found at /etc/kong/kong.conf
2021/12/15 03:23:39 [verbose] no config file found at /etc/kong.conf
2021/12/15 03:23:39 [verbose] no config file, skip loading
2021/12/15 03:23:39 [debug] reading environment variables
2021/12/15 03:23:39 [debug] KONG_PG_HOST ENV found with "172.26.0.45"
2021/12/15 03:23:39 [debug] KONG_NGINX_HTTP_CLIENT_MAX_BODY_SIZE ENV found with "50m"
2021/12/15 03:23:39 [debug] KONG_DATABASE ENV found with "postgres"
2021/12/15 03:23:39 [debug] KONG_PG_USER ENV found with "kong"
2021/12/15 03:23:39 [debug] KONG_PG_PORT ENV found with "5432"
2021/12/15 03:23:39 [debug] KONG_PG_PASSWORD ENV found with "******"
2021/12/15 03:23:39 [debug] KONG_PROXY_ERROR_LOG ENV found with "/usr/local/kong/logs/proxy-error.log"
2021/12/15 03:23:39 [debug] KONG_ADMIN_ACCESS_LOG ENV found with "/usr/local/kong/logs/admin-access.log main"
2021/12/15 03:23:39 [debug] KONG_ADMIN_ERROR_LOG ENV found with "/usr/local/kong/logs/admin-error.log"
2021/12/15 03:23:39 [debug] KONG_LOG_LEVEL ENV found with "info"
2021/12/15 03:23:39 [debug] KONG_PLUGINS ENV found with "bundled,grpc-itop-verify,grpc-api-log,grpc-error-handler,p-prometheus,correlationid,itop-verify,g-gateway,short-link,gdos-sig-check,error-transformer"
2021/12/15 03:23:39 [debug] KONG_NGINX_HTTP_LOG_FORMAT ENV found with "main '$remote_addr - $remote_user [$time_local] "$request"  $status "$upstream_status" $body_bytes_sent "$http_referer" "$http_user_agent" "$request_time" "$upstream_response_time"'"
2021/12/15 03:23:39 [debug] KONG_NGINX_HTTP_TCP_NODELAY ENV found with "on"
2021/12/15 03:23:39 [debug] KONG_NGINX_PROXY_CLIENT_BODY_BUFFER_SIZE ENV found with "8m"
2021/12/15 03:23:39 [debug] KONG_NGINX_PROXY_CLIENT_MAX_BODY_SIZE ENV found with "8m"
2021/12/15 03:23:39 [debug] KONG_NGINX_PROXY_KEEPALIVE_TIMEOUT ENV found with "60s"
2021/12/15 03:23:39 [debug] KONG_NGINX_PROXY_PROXY_BUFFERS ENV found with "4 256k"
2021/12/15 03:23:39 [debug] KONG_NGINX_PROXY_PROXY_BUFFER_SIZE ENV found with "128k"
2021/12/15 03:23:39 [debug] KONG_NGINX_PROXY_PROXY_BUSY_BUFFERS_SIZE ENV found with "256k"
2021/12/15 03:23:39 [debug] KONG_SSL_CERT_KEY ENV found with "/usr/local/custom/kong/ssl/server.key"
2021/12/15 03:23:39 [debug] KONG_SSL_CERT ENV found with "/usr/local/custom/kong/ssl/server.pem"
2021/12/15 03:23:39 [debug] KONG_PG_DATABASE ENV found with "kong_prod_outer"
2021/12/15 03:23:39 [debug] KONG_LUA_PACKAGE_PATH ENV found with "./?.lua;./?/init.lua;/usr/local/custom/?.lua;;"
2021/12/15 03:23:39 [debug] KONG_PROXY_ACCESS_LOG ENV found with "/usr/local/kong/logs/proxy-access.log main"
2021/12/15 03:23:39 [debug] KONG_PROXY_LISTEN ENV found with "0.0.0.0:8000, 0.0.0.0:8443 ssl, 0.0.0.0:9080 http2, 0.0.0.0:9081 http2 ssl"
2021/12/15 03:23:39 [debug] KONG_ADMIN_LISTEN ENV found with "0.0.0.0:8001"
2021/12/15 03:23:39 [debug] admin_access_log = "/usr/local/kong/logs/admin-access.log main"
2021/12/15 03:23:39 [debug] admin_error_log = "/usr/local/kong/logs/admin-error.log"
2021/12/15 03:23:39 [debug] admin_listen = {"0.0.0.0:8001"}
2021/12/15 03:23:39 [debug] admin_ssl_cert = {}
2021/12/15 03:23:39 [debug] admin_ssl_cert_key = {}
2021/12/15 03:23:39 [debug] anonymous_reports = true
2021/12/15 03:23:39 [debug] cassandra_contact_points = {"127.0.0.1"}
2021/12/15 03:23:39 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2021/12/15 03:23:39 [debug] cassandra_keyspace = "kong"
2021/12/15 03:23:39 [debug] cassandra_lb_policy = "RequestRoundRobin"
2021/12/15 03:23:39 [debug] cassandra_port = 9042
2021/12/15 03:23:39 [debug] cassandra_read_consistency = "ONE"
2021/12/15 03:23:39 [debug] cassandra_refresh_frequency = 60
2021/12/15 03:23:39 [debug] cassandra_repl_factor = 1
2021/12/15 03:23:39 [debug] cassandra_repl_strategy = "SimpleStrategy"
2021/12/15 03:23:39 [debug] cassandra_schema_consensus_timeout = 10000
2021/12/15 03:23:39 [debug] cassandra_ssl = false
2021/12/15 03:23:39 [debug] cassandra_ssl_verify = false
2021/12/15 03:23:39 [debug] cassandra_timeout = 5000
2021/12/15 03:23:39 [debug] cassandra_username = "kong"
2021/12/15 03:23:39 [debug] cassandra_write_consistency = "ONE"
2021/12/15 03:23:39 [debug] client_body_buffer_size = "8k"
2021/12/15 03:23:39 [debug] client_max_body_size = "0"
2021/12/15 03:23:39 [debug] client_ssl = false
2021/12/15 03:23:39 [debug] cluster_control_plane = "127.0.0.1:8005"
2021/12/15 03:23:39 [debug] cluster_data_plane_purge_delay = 1209600
2021/12/15 03:23:39 [debug] cluster_listen = {"0.0.0.0:8005"}
2021/12/15 03:23:39 [debug] cluster_mtls = "shared"
2021/12/15 03:23:39 [debug] cluster_ocsp = "off"
2021/12/15 03:23:39 [debug] database = "postgres"
2021/12/15 03:23:39 [debug] db_cache_ttl = 0
2021/12/15 03:23:39 [debug] db_cache_warmup_entities = {"services"}
2021/12/15 03:23:39 [debug] db_resurrect_ttl = 30
2021/12/15 03:23:39 [debug] db_update_frequency = 5
2021/12/15 03:23:39 [debug] db_update_propagation = 0
2021/12/15 03:23:39 [debug] dns_error_ttl = 1
2021/12/15 03:23:39 [debug] dns_hostsfile = "/etc/hosts"
2021/12/15 03:23:39 [debug] dns_no_sync = false
2021/12/15 03:23:39 [debug] dns_not_found_ttl = 30
2021/12/15 03:23:39 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2021/12/15 03:23:39 [debug] dns_resolver = {}
2021/12/15 03:23:39 [debug] dns_stale_ttl = 4
2021/12/15 03:23:39 [debug] error_default_type = "text/plain"
2021/12/15 03:23:39 [debug] go_plugins_dir = "off"
2021/12/15 03:23:39 [debug] go_pluginserver_exe = "/usr/local/bin/go-pluginserver"
2021/12/15 03:23:39 [debug] headers = {"server_tokens","latency_tokens"}
2021/12/15 03:23:39 [debug] host_ports = {}
2021/12/15 03:23:39 [debug] kic = false
2021/12/15 03:23:39 [debug] log_level = "info"
2021/12/15 03:23:39 [debug] lua_package_cpath = ""
2021/12/15 03:23:39 [debug] lua_package_path = "./?.lua;./?/init.lua;/usr/local/custom/?.lua;;"
2021/12/15 03:23:39 [debug] lua_socket_pool_size = 30
2021/12/15 03:23:39 [debug] lua_ssl_protocols = "TLSv1.1 TLSv1.2 TLSv1.3"
2021/12/15 03:23:39 [debug] lua_ssl_trusted_certificate = {}
2021/12/15 03:23:39 [debug] lua_ssl_verify_depth = 1
2021/12/15 03:23:39 [debug] mem_cache_size = "128m"
2021/12/15 03:23:39 [debug] nginx_admin_client_body_buffer_size = "10m"
2021/12/15 03:23:39 [debug] nginx_admin_client_max_body_size = "10m"
2021/12/15 03:23:39 [debug] nginx_admin_directives = {{name="client_body_buffer_size",value="10m"},{name="client_max_body_size",value="10m"}}
2021/12/15 03:23:39 [debug] nginx_daemon = "on"
2021/12/15 03:23:39 [debug] nginx_events_directives = {{name="worker_connections",value="auto"},{name="multi_accept",value="on"}}
2021/12/15 03:23:39 [debug] nginx_events_multi_accept = "on"
2021/12/15 03:23:39 [debug] nginx_events_worker_connections = "auto"
2021/12/15 03:23:39 [debug] nginx_http_client_body_buffer_size = "8k"
2021/12/15 03:23:39 [debug] nginx_http_client_max_body_size = "50m"
2021/12/15 03:23:39 [debug] nginx_http_directives = {{name="client_max_body_size",value="50m"},{name="client_body_buffer_size",value="8k"},{name="ssl_protocols",value="TLSv1.2 TLSv1.3"},{name="ssl_prefer_server_ciphers",value="off"},{name="ssl_session_tickets",value="on"},{name="ssl_session_timeout",value="1d"},{name="lua_ssl_protocols",value="TLSv1.1 TLSv1.2 TLSv1.3"},{name="log_format",value="main '$remote_addr - $remote_user [$time_local] \"$request\"  $status \"$upstream_status\" $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$request_time\" \"$upstream_response_time\"'"},{name="tcp_nodelay",value="on"},{name="ssl_dhparam",value="ffdhe2048"}}
2021/12/15 03:23:39 [debug] nginx_http_log_format = "main '$remote_addr - $remote_user [$time_local] \"$request\"  $status \"$upstream_status\" $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$request_time\" \"$upstream_response_time\"'"
2021/12/15 03:23:39 [debug] nginx_http_lua_ssl_protocols = "TLSv1.1 TLSv1.2 TLSv1.3"
2021/12/15 03:23:39 [debug] nginx_http_ssl_dhparam = "ffdhe2048"
2021/12/15 03:23:39 [debug] nginx_http_ssl_prefer_server_ciphers = "off"
2021/12/15 03:23:39 [debug] nginx_http_ssl_protocols = "TLSv1.2 TLSv1.3"
2021/12/15 03:23:39 [debug] nginx_http_ssl_session_tickets = "on"
2021/12/15 03:23:39 [debug] nginx_http_ssl_session_timeout = "1d"
2021/12/15 03:23:39 [debug] nginx_http_status_directives = {}
2021/12/15 03:23:39 [debug] nginx_http_tcp_nodelay = "on"
2021/12/15 03:23:39 [debug] nginx_http_upstream_directives = {}
2021/12/15 03:23:39 [debug] nginx_main_daemon = "on"
2021/12/15 03:23:39 [debug] nginx_main_directives = {{name="user",value="kong kong"},{name="worker_processes",value="auto"},{name="daemon",value="on"},{name="worker_rlimit_nofile",value="auto"}}
2021/12/15 03:23:39 [debug] nginx_main_user = "kong kong"
2021/12/15 03:23:39 [debug] nginx_main_worker_processes = "auto"
2021/12/15 03:23:39 [debug] nginx_main_worker_rlimit_nofile = "auto"
2021/12/15 03:23:39 [debug] nginx_optimizations = true
2021/12/15 03:23:39 [debug] nginx_proxy_client_body_buffer_size = "8m"
2021/12/15 03:23:39 [debug] nginx_proxy_client_max_body_size = "8m"
2021/12/15 03:23:39 [debug] nginx_proxy_directives = {{name="real_ip_header",value="X-Real-IP"},{name="real_ip_recursive",value="off"},{name="client_body_buffer_size",value="8m"},{name="client_max_body_size",value="8m"},{name="keepalive_timeout",value="60s"},{name="proxy_buffers",value="4 256k"},{name="proxy_buffer_size",value="128k"},{name="proxy_busy_buffers_size",value="256k"}}
2021/12/15 03:23:39 [debug] nginx_proxy_keepalive_timeout = "60s"
2021/12/15 03:23:39 [debug] nginx_proxy_proxy_buffer_size = "128k"
2021/12/15 03:23:39 [debug] nginx_proxy_proxy_buffers = "4 256k"
2021/12/15 03:23:39 [debug] nginx_proxy_proxy_busy_buffers_size = "256k"
2021/12/15 03:23:39 [debug] nginx_proxy_real_ip_header = "X-Real-IP"
2021/12/15 03:23:39 [debug] nginx_proxy_real_ip_recursive = "off"
2021/12/15 03:23:39 [debug] nginx_sproxy_directives = {}
2021/12/15 03:23:39 [debug] nginx_status_directives = {}
2021/12/15 03:23:39 [debug] nginx_stream_directives = {{name="ssl_protocols",value="TLSv1.2 TLSv1.3"},{name="ssl_prefer_server_ciphers",value="off"},{name="ssl_session_tickets",value="on"},{name="ssl_session_timeout",value="1d"},{name="lua_ssl_protocols",value="TLSv1.1 TLSv1.2 TLSv1.3"},{name="ssl_dhparam",value="ffdhe2048"}}
2021/12/15 03:23:39 [debug] nginx_stream_lua_ssl_protocols = "TLSv1.1 TLSv1.2 TLSv1.3"
2021/12/15 03:23:39 [debug] nginx_stream_ssl_dhparam = "ffdhe2048"
2021/12/15 03:23:39 [debug] nginx_stream_ssl_prefer_server_ciphers = "off"
2021/12/15 03:23:39 [debug] nginx_stream_ssl_protocols = "TLSv1.2 TLSv1.3"
2021/12/15 03:23:39 [debug] nginx_stream_ssl_session_tickets = "on"
2021/12/15 03:23:39 [debug] nginx_stream_ssl_session_timeout = "1d"
2021/12/15 03:23:39 [debug] nginx_supstream_directives = {}
2021/12/15 03:23:39 [debug] nginx_upstream_directives = {}
2021/12/15 03:23:39 [debug] nginx_user = "kong kong"
2021/12/15 03:23:39 [debug] nginx_worker_processes = "auto"
2021/12/15 03:23:39 [debug] pg_database = "kong_prod_outer"
2021/12/15 03:23:39 [debug] pg_host = "172.26.0.45"
2021/12/15 03:23:39 [debug] pg_max_concurrent_queries = 0
2021/12/15 03:23:39 [debug] pg_password = "******"
2021/12/15 03:23:39 [debug] pg_port = 5432
2021/12/15 03:23:39 [debug] pg_ro_ssl = false
2021/12/15 03:23:39 [debug] pg_ro_ssl_verify = false
2021/12/15 03:23:39 [debug] pg_semaphore_timeout = 60000
2021/12/15 03:23:39 [debug] pg_ssl = false
2021/12/15 03:23:39 [debug] pg_ssl_verify = false
2021/12/15 03:23:39 [debug] pg_timeout = 5000
2021/12/15 03:23:39 [debug] pg_user = "kong"
2021/12/15 03:23:39 [debug] plugins = {"bundled","grpc-itop-verify","grpc-api-log","grpc-error-handler","p-prometheus","correlationid","itop-verify","g-gateway","short-link","gdos-sig-check","error-transformer"}
2021/12/15 03:23:39 [debug] pluginserver_names = {}
2021/12/15 03:23:39 [debug] port_maps = {}
2021/12/15 03:23:39 [debug] prefix = "/usr/local/kong/"
2021/12/15 03:23:39 [debug] proxy_access_log = "/usr/local/kong/logs/proxy-access.log main"
2021/12/15 03:23:39 [debug] proxy_error_log = "/usr/local/kong/logs/proxy-error.log"
2021/12/15 03:23:39 [debug] proxy_listen = {"0.0.0.0:8000","0.0.0.0:8443 ssl","0.0.0.0:9080 http2","0.0.0.0:9081 http2 ssl"}
2021/12/15 03:23:39 [debug] proxy_stream_access_log = "logs/access.log basic"
2021/12/15 03:23:39 [debug] proxy_stream_error_log = "logs/error.log"
2021/12/15 03:23:39 [debug] real_ip_header = "X-Real-IP"
2021/12/15 03:23:39 [debug] real_ip_recursive = "off"
2021/12/15 03:23:39 [debug] role = "traditional"
2021/12/15 03:23:39 [debug] ssl_cert = {"/usr/local/custom/kong/ssl/server.pem"}
2021/12/15 03:23:39 [debug] ssl_cert_key = {"/usr/local/custom/kong/ssl/server.key"}
2021/12/15 03:23:39 [debug] ssl_cipher_suite = "intermediate"
2021/12/15 03:23:39 [debug] ssl_ciphers = "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"
2021/12/15 03:23:39 [debug] ssl_dhparam = "ffdhe2048"
2021/12/15 03:23:39 [debug] ssl_prefer_server_ciphers = "on"
2021/12/15 03:23:39 [debug] ssl_protocols = "TLSv1.1 TLSv1.2 TLSv1.3"
2021/12/15 03:23:39 [debug] ssl_session_tickets = "on"
2021/12/15 03:23:39 [debug] ssl_session_timeout = "1d"
2021/12/15 03:23:39 [debug] status_access_log = "off"
2021/12/15 03:23:39 [debug] status_error_log = "logs/status_error.log"
2021/12/15 03:23:39 [debug] status_listen = {"off"}
2021/12/15 03:23:39 [debug] status_ssl_cert = {}
2021/12/15 03:23:39 [debug] status_ssl_cert_key = {}
2021/12/15 03:23:39 [debug] stream_listen = {"off"}
2021/12/15 03:23:39 [debug] trusted_ips = {}
2021/12/15 03:23:39 [debug] untrusted_lua = "sandbox"
2021/12/15 03:23:39 [debug] untrusted_lua_sandbox_environment = {}
2021/12/15 03:23:39 [debug] untrusted_lua_sandbox_requires = {}
2021/12/15 03:23:39 [debug] upstream_keepalive_idle_timeout = 60
2021/12/15 03:23:39 [debug] upstream_keepalive_max_requests = 100
2021/12/15 03:23:39 [debug] upstream_keepalive_pool_size = 60
2021/12/15 03:23:39 [debug] worker_consistency = "strict"
2021/12/15 03:23:39 [debug] worker_state_update_frequency = 5
2021/12/15 03:23:39 [verbose] prefix in use: /usr/local/kong
2021/12/15 03:23:39 [verbose] preparing nginx prefix directory at /usr/local/kong
2021/12/15 03:23:39 [debug] searching for OpenResty 'nginx' executable
2021/12/15 03:23:39 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.19.3.1'
2021/12/15 03:23:39 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2021/12/15 03:23:39 [debug] testing nginx configuration: KONG_NGINX_CONF_CHECK=true /usr/local/openresty/nginx/sbin/nginx -t -p /usr/local/kong -c nginx.conf
2021/12/15 03:23:39 [debug] sending signal to pid at: /usr/local/kong/pids/nginx.pid
2021/12/15 03:23:39 [debug] kill -0 `cat /usr/local/kong/pids/nginx.pid` >/dev/null 2>&1
Error: 
/usr/local/share/lua/5.1/kong/cmd/start.lua:26: Kong is already running in /usr/local/kong
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/cmd/start.lua:26: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
        /usr/local/bin/kong:9: in function 'file_gen'
        init_worker_by_lua:47: in function <init_worker_by_lua:45>
        [C]: in function 'xpcall'
        init_worker_by_lua:54: in function <init_worker_by_lua:52>

### Kong configuration
 - name: KONG_NGINX_PROXY_CLIENT_BODY_BUFFER_SIZE
          value: 8m
        - name: KONG_NGINX_PROXY_CLIENT_MAX_BODY_SIZE
          value: 8m
        - name: KONG_NGINX_PROXY_PROXY_BUFFERS
          value: 4 256k
        - name: KONG_NGINX_PROXY_PROXY_BUFFER_SIZE
          value: 128k
        - name: KONG_NGINX_PROXY_PROXY_BUSY_BUFFERS_SIZE
          value: 256k
        - name: KONG_NGINX_HTTP_LOG_FORMAT
          value: main '$remote_addr - $remote_user [$time_local] "$request"  $status
            "$upstream_status" $body_bytes_sent "$http_referer" "$http_user_agent"
            "$request_time" "$upstream_response_time"'
        - name: KONG_NGINX_PROXY_KEEPALIVE_TIMEOUT
          value: 60s
        - name: KONG_NGINX_HTTP_CLIENT_MAX_BODY_SIZE
          value: 50m
        - name: KONG_NGINX_GRPC_SEND_TIME_OUT
          value: 3s
        - name: KONG_NGINX_GRPC_READ_TIME_OUT
          value: 5s
        - name: KONG_NGINX_HTTP_TCP_NODELAY
          value: "on"

###  Running operating system
centos 7

**Comment by locao** [comment] 2021-12-16 18:59
Hello @highwayliu!

`client prematurely closed connection while processing HTTP/2 connection` is a log entry that comes from Nginx and it is related to the client's behavior. It means Nginx could not answer the request because the client connection is not available anymore. That sometimes can show up as `499` in the `access.log`, but also as `400`. That log is unrelated to any `500` that your client may have received. 

There are no erros in the logs you shared that could result in clients receiving `500`. In most of the cases, errors that return `500` are entries labeled `[error]` in Kong's `error.log`.

As this is not a bug, I'm closing the issue. Please feel free to get in touch again if needed.

**Closed by locao** 2021-12-16 18:59 UTC
Labels: question, core/proxy

**Comment by highwayliu** [comment] 2021-12-21 03:14
> Hello @highwayliu!
> 
> `client prematurely closed connection while processing HTTP/2 connection` is a log entry that comes from Nginx and it is related to the client's behavior. It means Nginx could not answer the request because the client connection is not available anymore. That sometimes can show up as `499` in the `access.log`, but also as `400`. That log is unrelated to any `500` that your client may have received.
> 
> There are no erros in the logs you shared that could result in clients receiving `500`. In most of the cases, errors that return `500` are entries labeled `[error]` in Kong's `error.log`.
> 
> As this is not a bug, I'm closing the issue. Please feel free to get in touch again if needed.

@locao  as the image below, i found the 500 code int access log, and i search the ip in the error log in that time, the only log was "client prematurely closed connection while processing HTTP/2 connection"
![image](https://user-images.githubusercontent.com/39515014/146864728-b3132cfd-0fad-4f3d-b20c-7a0236938f3f.png)

**Comment by locao** [comment] 2021-12-21 16:27
@highwayliu that code may have been returned by the proxied server. What do you get when issuing this same request directly to the proxied server, i.e. without Kong? Also, is your client using the correct mime-type header?
