### ISSUE TITLE
upstream healthcheck not working

### ISSUE THREAD

**Issue by lclin412** [Kong/kong#7473] opened 2021-06-19 09:41 UTC
kong version 2.4.1

When a target is unhealthy (for example, the port is unavailable), but the kong healthcheck is still healthy, the problem still exists after the reload, and it will not recover until the restart operation，it will appear again within a few hours after restart。

upstream info
{
    "created_at": 1599554301,
    "healthchecks": {
        "active": {
            "https_sni": null,
            "https_verify_certificate": true,
            "timeout": 1,
            "concurrency": 1,
            "type": "http",
            "healthy": {
                "interval": 5,
                "successes": 3,
                "http_statuses": [
                    200,
                    302
                ]
            },
            "unhealthy": {
                "timeouts": 3,
                "http_failures": 3,
                "interval": 5,
                "tcp_failures": 3,
                "http_statuses": [
                    429,
                    404,
                    500,
                    501,
                    503,
                    504,
                    505
                ]
            },
            "http_path": "/kong/monitor/AUpstream"
        },
        "passive": {
            "healthy": {
                "successes": 0,
                "http_statuses": [
                    200,
                    201,
                    202,
                    203,
                    204,
                    205,
                    206,
                    207,
                    208,
                    226,
                    300,
                    301,
                    302,
                    303,
                    304,
                    305,
                    306,
                    307,
                    308
                ]
            },
            "unhealthy": {
                "timeouts": 0,
                "http_failures": 0,
                "tcp_failures": 0,
                "http_statuses": [
                    429,
                    500,
                    503
                ]
            },
            "type": "http"
        },
        "threshold": 0
    },
    "client_certificate": null,
    "slots": 1000,
    "tags": null,
    "hash_on_header": null,
    "name": "AUpstream",
    "id": "ba87f0b9-dba8-4904-bb14-693696709847",
    "host_header": null,
    "hash_on": "ip",
    "hash_on_cookie": null,
    "hash_on_cookie_path": "/",
    "hash_fallback": "none",
    "hash_fallback_header": null,
    "algorithm": "consistent-hashing"
}

The following information exists in the error.log
2021/06/19 02:37:36 [warn] 64282#0: *208097 [lua] balancer.lua:316: [healthchecks] failed setting peer status (upstream: 33f6e3a9-92d4-48ca-b4cc-20b8fd14afb1:AUpstream): no peer found by name '127.0.0.1' and address 127.0.0.1:8790, context: ngx.timer

thanks for help.

**Comment by mrpk1906** [comment] 2021-06-29 08:20
I also have this problem, reported in the issue https://github.com/Kong/kong/issues/7163

**Comment by beck917** [comment] 2021-07-29 09:07
Use lua-resty-healthcheck version 2.0.0 can solve this problem

**Comment by isaac88** [comment] 2021-09-15 20:22
Hello @beck917,
I tested this version https://luarocks.org/modules/kong/lua-resty-healthcheck/2.0.0-1 and the problem persist.

`2021/09/15 22:17:20 [warn] 10976#0: *9906 [lua] balancer.lua:316: [healthchecks] failed setting peer status (upstream: f2d81265-4588-40b0-8853-f8f378d9602c:<bucket-name>): no peer found by name <bucket-name>.eu-west-1.amazonaws.com' and address 52.218.24.208:80, possibly the IP originated from these nested dns names: <bucket-name>.s3.eu-west-1.amazonaws.com:80, context: ngx.timer`

any clue on that ?

**Comment by StarlightIbuki** [comment] 2023-10-11 06:24
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:24 UTC
Labels: task/needs-investigation, core/balancer
