### ISSUE TITLE
How to read env in plugin

### ISSUE THREAD

**Issue by Asilent** [Kong/kong#7083] opened 2021-04-23 17:11 UTC
I use `docker run -e "env_name=xxx"   kong:2.4.0-ubuntu ` to export env into container. Then I hope to get it by using os.getenv("env_name") in lua plugin. But it doesn't work and responds with nil.

**Comment by gszr** [comment] 2021-04-23 17:24
Hi @Asilent,

This is expected behavior; in order to be able to read an environment variable from Lua code, you need to specify it in the Nginx `env` directive. In Kong, that can be done with [directive injection](https://docs.konghq.com/enterprise/2.3.x/property-reference/#injecting-nginx-directives).

In your case, you can achieve that by setting the following Kong configuration as an environment variable: `KONG_NGINX_MAIN_ENV=env_name`.

Closing this, but feel free to reopen if needed.

Happy Konging! 🦍

**Closed by gszr** 2021-04-23 17:24 UTC

**Comment by Tieske** [comment] 2021-04-23 17:44
Alternatively you can read the variable when the plugin code loads, since that is executed in the master process where variables are still available

**Comment by Asilent** [comment] 2021-04-25 15:49
I use directive injection like `-e KONG_NGINX_HTTP_CUSTOM_ENV=env_value` to add custom env when start the docker.
<img width="413" alt="d5b0c0f-36f2-4904-a487-2d5e12028b45" src="https://user-images.githubusercontent.com/44249329/115999937-a3ab2a00-a620-11eb-9509-73668c1230ef.png">

Afrer this action, kong container can't restart with error.
The Error is as follows:
![1619364668029](https://user-images.githubusercontent.com/44249329/115999550-cd635180-a61e-11eb-946f-8a8404f6cd91.jpg)

What should I do?

**Comment by Asilent** [comment] 2021-04-25 15:56
> Hi @Asilent,
> 
> This is expected behavior; in order to be able to read an environment variable from Lua code, you need to specify it in the Nginx `env` directive. In Kong, that can be done with [directive injection](https://docs.konghq.com/enterprise/2.3.x/property-reference/#injecting-nginx-directives).
> 
> In your case, you can achieve that by setting the following Kong configuration as an environment variable: `KONG_NGINX_MAIN_ENV=env_name`.
> 
> Closing this, but feel free to reopen if needed.
> 
> Happy Konging! 🦍

Can I reopen this issue?

**Comment by Tieske** [comment] 2021-04-26 08:48
@Asilent you did not specify them as inidcated by @gszr .

This is the format:
```shell
export KONG_NGINX_MAIN_ENV=env_name
```

The name consists of 2 parts; `KONG_NGINX_MAIN` and `ENV`, and the value is `env_name`. The first part tells Kong where to inject the directive; in the Nginx main config file. The second one is the name of the directive `ENV` which causes Kong to inject it as name (lower-case) + value;
```
env env_name;
```
So you need to specify 2 environment variables for each variable you need
1. to tell Kong it should keep that variable around
2. the actual variable with its value

So you need to specify:
```shell
export KONG_NGINX_MAIN_ENV=HTTP_SSO_ENDPOINT
export HTTP_SSO_ENDPOINT=http://sso.my
export KONG_NGINX_MAIN_ENV=PROXY_SSO_ENDPOINT
export PROXY_SSO_ENDPOINT=http://sso.my
```

Now there is a problem, because the second `KONG_NGINX_MAIN_ENV` will overwrite the first... To get around that use a little hack, specify it like so (must be quoted because of the `;`):
```shell
export "KONG_NGINX_MAIN_ENV=HTTP_SSO_ENDPOINT;env PROXY_SSO_ENDPOINT"
export HTTP_SSO_ENDPOINT=http://sso.my
export PROXY_SSO_ENDPOINT=http://sso.my
```
If you check the generated config file, you'll see that Kong injects this line:
```
env HTTP_SSO_ENDPOINT;env PROXY_SSO_ENDPOINT;
```
which is a valid nginx config, but now contains both variables. You should now be able to access those variables from your plugin code.

**Comment by demonkit** [comment] 2024-06-21 10:26
> @Asilent you did not specify them as inidcated by @gszr .
> 
> This is the format:
> 
> ```shell
> export KONG_NGINX_MAIN_ENV=env_name
> ```
> 
> The name consists of 2 parts; `KONG_NGINX_MAIN` and `ENV`, and the value is `env_name`. The first part tells Kong where to inject the directive; in the Nginx main config file. The second one is the name of the directive `ENV` which causes Kong to inject it as name (lower-case) + value;
> 
> ```
> env env_name;
> ```
> 
> So you need to specify 2 environment variables for each variable you need
> 
> 1. to tell Kong it should keep that variable around
> 2. the actual variable with its value
> 
> So you need to specify:
> 
> ```shell
> export KONG_NGINX_MAIN_ENV=HTTP_SSO_ENDPOINT
> export HTTP_SSO_ENDPOINT=http://sso.my
> export KONG_NGINX_MAIN_ENV=PROXY_SSO_ENDPOINT
> export PROXY_SSO_ENDPOINT=http://sso.my
> ```
> 
> Now there is a problem, because the second `KONG_NGINX_MAIN_ENV` will overwrite the first... To get around that use a little hack, specify it like so (must be quoted because of the `;`):
> 
> ```shell
> export "KONG_NGINX_MAIN_ENV=HTTP_SSO_ENDPOINT;env PROXY_SSO_ENDPOINT"
> export HTTP_SSO_ENDPOINT=http://sso.my
> export PROXY_SSO_ENDPOINT=http://sso.my
> ```
> 
> If you check the generated config file, you'll see that Kong injects this line:
> 
> ```
> env HTTP_SSO_ENDPOINT;env PROXY_SSO_ENDPOINT;
> ```
> 
> which is a valid nginx config, but now contains both variables. You should now be able to access those variables from your plugin code.

if I run on k8s, how to write this env KONG_NGINX_MAIN_ENV?
