### ISSUE TITLE
why kong can't go on runing when database shutdown

### ISSUE THREAD

**Issue by xxwade** [Kong/kong#3188] opened 2018-01-30 01:59 UTC
We recently upgraded postgresql to 9.5+. We think kong should be able to continue working when the database is closed because of the cache. But in fact, it does not. I want to know why this design? Thanks

**Comment by jeremyjpj0916** [comment] 2018-01-30 06:29
Could this be a duplicate related to : https://github.com/Kong/kong/issues/3068 , have you tried setting that override to see if you spot different behavior?

**Comment by hishamhm** [comment] 2018-02-26 18:11
Closing this as a duplicate of #3068.

**Closed by hishamhm** 2018-02-26 18:11 UTC
Labels: task/needs-investigation
