### ISSUE TITLE
Imports in .proto don't work as expected in kong-grpc-gateway

### ISSUE THREAD

**Issue by dmitrysleptsov** [Kong/kong#8725] opened 2022-04-26 09:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.1

### Current Behavior

I use separate .proto files for messages and service. When use them in local grpc server - everything is working fine. When I use them with grpc-gateway - I got an error 

```
google/api/annotations.proto: No such file or directory
        ./google/api/annotations.proto: No such file or directory
        /usr/include/google/api/annotations.proto: No such file or directory
        /usr/local/opt/protobuf/include//google/api/annotations.proto: No such file or directory
        /usr/local/kong/lib//google/api/annotations.proto: No such file or directory
        kong/google/api/annotations.proto: No such file or directory
        kong/include/google/api/annotations.proto: No such file or directory
        spec/fixtures/grpc/google/api/annotations.proto: No such file or directory
        /google/api/google/api/annotations.proto: No such file or directory, client: 10.254.6.1, server: kong, request: "GET /grpc-service/v1/users HTTP/1.1", host: "localhost:8000"
```

Directory structure:
```
grpc-service/
    google/
        api/
            annotations.proto
            http.proto
    user_messages.proto
    user_service.proto
kong.yaml
```

Content of `user_service.proto`:

```
syntax = "proto3";

import "google/api/annotations.proto";
import "user_messages.proto";

package user_service;

service UserService {
  rpc GetUser(GetUserRequest) returns (GetUserResponse) {
    option (google.api.http) = {
      get: "/grpc-service/v1/users/{id}"
    };
  }
}
```

Content of `kong.yaml`:

```
_format_version: "2.1"
_transform: true

services:
  - url: grpc://grpc-service-prototype:50051
    name: grpc-service-v1
    routes:
      - protocols:
          - http
        name: grpc-service-route-v1
        paths:
          - /
        plugins:
          - name: grpc-gateway
            config:
              proto: /kong/declarative/grpc-service/user_service.proto
```

Content of `user_messages.proto`:

```
syntax = "proto3";

message GetUserRequest {
  string id = 1;
}

message GetUserResponse {
  User data = 1;
}

message User {
  string id = 1;
  string username = 2;
  string created_at = 3;
  string updated_at = 4;
}
```

Everything running in docker. I use command from kong tutorial. The only thing that matter from it (as I think) is 
`-v "$(pwd):/kong/declarative/"`

### Expected Behavior

According to [this issue, ](https://github.com/Kong/kong/issues/6572) directory with the main .proto file (`user_service.proto` in my case) should be treated as import root. But looks like it's not.

### Steps To Reproduce

Create project with the same structure, run kong, make a request to `http://localhost:8000/grpc-service/v1/users/{anything}`

### Anything else?

If you need any extra info - please ask, would be glad to provide. I tried to use different paths in `kong.yaml`. When I use relative path - I get an error that `user_service.proto` can't be found. If I remove `annotations.proto` import - I get the same error for `user_messages.proto`.

**Comment by javierguerragiraldez** [comment] 2022-04-26 14:22
in your directory structure there's a `google/` subdir, but not a `google/api/`

**Comment by dmitrysleptsov** [comment] 2022-04-29 12:55
@git-torrent Same as it in discription. I specified a full path inside the container. If I use only `user_service.proto` I get an error that `user_service.proto` can't be found

**Comment by git-torrent** [comment] 2022-04-29 13:06
Path is parsed from what you put into config {proto} by https://github.com/Kong/kong/blob/master/kong/tools/grpc.lua#L57 to directory and file. Directory is added at https://github.com/Kong/kong/blob/master/kong/tools/grpc.lua#L67

If we remove all automatically included paths (lines https://github.com/Kong/kong/blob/master/kong/tools/grpc.lua#L59-L64) we end up with:

google/api/annotations.proto: No such file or directory
./google/api/annotations.proto: No such file or directory
/google/api/google/api/annotations.proto:

this looks like no directory has been parsed out of your path. Is it in the right form?

**Comment by dmitrysleptsov** [comment] 2022-05-12 16:17
@javierguerragiraldez , @git-torrent . Tagging you because you were the only ones that tried to help. I investigated a little bit and found the reason of my problem. I think this is a bug, but maybe developers did it intentionally for some reason. 

So, here https://github.com/Kong/kong/blob/1439f9c4b928a47cad7e29660ceeea32d3bb99d8/kong/tools/grpc.lua#L80 we recursively process all the imports in `.proto` file but each time we create new `protoc`. So when we parse the main file `fname` is the path to main file (`config.proto`) and we add it's parent directory to `p.paths`. But when we process imports the `fname` is the path of the import (in my case `google/api/annotations.proto`) and new `protoc` has no idea about main file path. And we add to path the result of `pl_path.splitpath(pl_path.abspath("google/api/annotations.proto"))` which appears to be empty string. And that's why I get this error.

In my opinion, recursive calls should take in account the path of the main file. The most obvious solution will be to path main file path to each `each_method` call. But I'm not an expert in lua so maybe there's a better solution.

**Comment by git-torrent** [comment] 2022-05-12 21:02
This is fixed by PR https://github.com/Kong/kong/pull/8297
grpctools are only loaded once at https://github.com/Kong/kong/blob/beaa482df8c86994fee9aa19d4d0ed7e10e9944a/kong/plugins/grpc-gateway/deco.lua#L156

**Comment by StarlightIbuki** [comment] 2023-10-11 06:35
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:35 UTC
Labels: plugins/grpc-gateway
