### ISSUE TITLE
rate-limiting plugin get_timestamps bug

### ISSUE THREAD

**Issue by fairyqb** [Kong/kong#8894] opened 2022-06-03 06:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

all version

### Current Behavior

https://github.com/Kong/kong/blob/master/kong/tools/timestamp.lua

**method get timestamp:**
-------------
-- now = timestamp.get_utc()

local function get_timestamps(now)
  local timetable = get_timetable(now)
  local stamps = {}

  timetable.sec = math_floor(timetable.sec)   -- reduce to second precision
  stamps.second = timetable:timestamp() * 1000

  timetable.sec = 0
  stamps.minute = timetable:timestamp() * 1000

  timetable.min = 0
  stamps.hour = timetable:timestamp() * 1000

  timetable.hour = 0
  stamps.day = timetable:timestamp() * 1000

  timetable.day = 1
  stamps.month = timetable:timestamp() * 1000

  timetable.month = 1
  stamps.year = timetable:timestamp() * 1000

  return stamps
end

--------------

**test code:**
  --local current_timestamp = timestamp.get_utc()
  local current_timestamp = time() * 1000
  local periods = timestamp.get_timestamps(current_timestamp)
  for period, period_date in pairs(periods) do
       print(period   .. "---" .. period_date)
  end

**result:**
  "second---1654221091000" --2022-06-03 09:51:31
  "minute---1654221060000"---2022-06-03 09:51:00
  "hour---1654218000000"  -- 2022-06-03 09:00:00
  "day---1654214400000" -- 2022-06-03 08:00:00
  "month---1654041600000"--2022-06-01 08:00:00
  "year---1640995200000"   --2022-01-01 08:00:00

### Expected Behavior

The correct result should be:

  "day---1654214400000" -- 2022-06-03 00:00:00
  "month---1654041600000"--2022-06-01 00:00:00
  "year---1640995200000"   --2022-01-01 00:00:00

A new day starts at 0 o'clock, why is it at 8 o'clock？？

@bungle 

### Steps To Reproduce

eproduce the problem :
1.add a rate-limit plugin to a route ([www.test.com](http://www.test.com/))
2.setting plug-in configuration: policy=local , day=10
3.setting the system Time: date -s "2022-06-03 23:59:00"
4.request site [www.test.com](http://www.test.com/) 5 times
5.waiting system time to 2022-06-04 00:00:00
6.request again, only 5 times remaining

expected result:
sart counting again, 10 remaining times

**Comment by fairyqb** [comment] 2022-06-05 00:01
@ADD-SP  @Tieske @kikito @hbagdi @guanlan

**Comment by fairyqb** [comment] 2022-06-06 03:47
Causes a count of requests between 00:00-07:59:59, not counted in days

**Comment by ADD-SP** [comment] 2022-06-06 07:39
```
$ date --utc -d "@1654214400"
Fri Jun  3 00:00:00 UTC 2022
$ date --utc -d "@1654041600"
Wed Jun  1 00:00:00 UTC 2022
$ date --utc -d "@1640995200"
Sat Jan  1 00:00:00 UTC 2022
```

I think it's just the time zone that causes the illusion. It is not a bug.

**Comment by fairyqb** [comment] 2022-06-06 09:23
date +"%Z %z"
CST +0800

https://github.com/Kong/kong/blob/master/kong/plugins/rate-limiting/policies/init.lua

added below line 119
kong.log.err(period .. "---" .. period_date)

result:
"second---1654221091000" --2022-06-03 09:51:31
"minute---1654221060000"---2022-06-03 09:51:00
"hour---1654218000000" -- 2022-06-03 09:00:00
"day---1654214400000" -- 2022-06-03 08:00:00
"month---1654041600000"--2022-06-01 08:00:00
"year---1640995200000" --2022-01-01 08:00:00

**Comment by fairyqb** [comment] 2022-06-06 11:42
Different time zones, different conversion results, year, month, and day do not start from 00:00:00。imprecise when rate limiting

**Comment by fairyqb** [comment] 2022-06-06 23:53
**reproduce the problem :**
1.add a rate-limit plugin to a route (www.test.com)
2.setting plug-in configuration: policy=local , day=10
3.setting the system Time: date -s  "2022-06-03 23:59:00"
4.request site www.test.com 5 times
5.waiting system time to 2022-06-04 00:00:00
6.request again, only 5 times remaining

**expected result:**
sart counting again, 10 remaining times

**Comment by bungle** [comment] 2022-06-08 08:45
@fairyqb is your system running on non-utc timezone, and you expect us to rate-limit based on non-utc timezone? I think everything inside Kong happens in utc. But if that is not the case, then we need to check it out.

**Comment by fairyqb** [comment] 2022-06-08 12:27
Yes, we are in East Eight District (UTC/GMT+08:00)，We hope rate-limit based on non-utc timezone，
thank you very much。

**Comment by StarlightIbuki** [comment] 2023-10-11 06:35
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:35 UTC
Labels: plugins/rate-limiting
