### ISSUE TITLE
Error during WebSocket handshake: 'Upgrade' header is missing

### ISSUE THREAD

**Issue by ourfor** [Kong/kong#5714] opened 2020-03-23 08:07 UTC
- Kong `2.0.2`
- Server Config
```json
{
    "host": "api.dev.ourfor.top",
    "created_at": 1584945910,
    "connect_timeout": 60000,
    "id": "46f07b22-d0e8-4f5e-a05f-eb3f57e4da54",
    "protocol": "http",
    "name": "api",
    "read_timeout": 60000,
    "port": 80,
    "path": null,
    "updated_at": 1584945910,
    "retries": 5,
    "write_timeout": 60000,
    "tags": null,
    "client_certificate": null
}
```
- Route Config
```json
{
    "id": "de596b50-c3b9-48aa-98e2-5d3d7e245230",
    "path_handling": "v0",
    "paths": null,
    "destinations": null,
    "headers": null,
    "protocols": [
        "http",
        "https"
    ],
    "methods": null,
    "snis": null,
    "service": {
        "id": "46f07b22-d0e8-4f5e-a05f-eb3f57e4da54"
    },
    "name": null,
    "strip_path": true,
    "preserve_host": false,
    "regex_priority": 0,
    "updated_at": 1584945983,
    "sources": null,
    "hosts": [
        "demo.ourfor.top"
    ],
    "https_redirect_status_code": 426,
    "tags": null,
    "created_at": 1584945983
}
```
![Xnip2020-03-23_15-55-15](https://user-images.githubusercontent.com/33711476/77294888-f4ff3080-6d1f-11ea-8164-dd2f10b3220d.png)

![Xnip2020-03-23_15-56-23](https://user-images.githubusercontent.com/33711476/77294905-fb8da800-6d1f-11ea-8f03-4ed63c5e2f5c.png)

http works ok, but can't connect websocket, what should I do?

**Comment by bungle** [comment] 2020-03-23 08:30
I think it is your upstream that does not handle the request correctly. Kong will send:
`Connection: keep-alive, Upgrade`, and your upstream websocket implementation just cannot parse that, aka it thinks there is no `Upgrade` in connection while there is? Am I correct?

**Comment by ourfor** [comment] 2020-03-23 10:02
I use tomcat and the log show, the `onError` execute

```log
2020-03-23 08:00:15.046 ERROR 1 --- [nio-8080-exec-3] k.r.j.i.KClassImpl                       : LoginSocket: 出现异常
2020-03-23 08:00:15.046 ERROR 1 --- [nio-8080-exec-3] k.r.j.i.KClassImpl                       : java.io.EOFException
```

![image](https://user-images.githubusercontent.com/33711476/77305088-65ae4900-6d30-11ea-8dc2-feecbdc785c8.png)

![image](https://user-images.githubusercontent.com/33711476/77305103-6c3cc080-6d30-11ea-8641-99b022fc9828.png)

any good idea?

**Comment by bungle** [comment] 2020-03-23 10:09
@ourfor,

If you change this line:
https://github.com/Kong/kong/blob/2.0.2/kong/runloop/handler.lua#L1120
```
var.upstream_connection = "keep-alive, Upgrade"
```
TO
```
var.upstream_connection = "Upgrade"
```

Does it work then?

**Comment by ourfor** [comment] 2020-03-23 10:15
I use docker image 😅
![image](https://user-images.githubusercontent.com/33711476/77306141-2ed93280-6d32-11ea-82e1-34ef0680bebe.png)

**Comment by ourfor** [comment] 2020-03-23 10:32
build next branch source code and change 👍 

![image](https://user-images.githubusercontent.com/33711476/77307492-50d3b480-6d34-11ea-8af1-466b7d07d60a.png)

![image](https://user-images.githubusercontent.com/33711476/77307418-297ce780-6d34-11ea-9a3f-08af80f1de01.png)

> tomcat log
![image](https://user-images.githubusercontent.com/33711476/77307660-a0b27b80-6d34-11ea-8049-0c4b72f60699.png)

it seems like connection closed early

**Comment by bungle** [comment] 2020-03-23 10:39
In docker image the files should be at:
```
/usr/local/share/lua/5.1/kong
```

But the issue is rather strange.  Is there anything between:
1. client and kong?
2. kong and upstream?

**Comment by ourfor** [comment] 2020-03-23 11:37
I change the file in docker image, got this error:
```log
WebSocket connection to 'ws://demo.ourfor.top:8000/auth/wechat' failed: Error during WebSocket handshake: Unexpected response code: 404
```

before using kong, I had used apache and iis. work well with apache, same error with iis

**Comment by ourfor** [comment] 2020-03-23 12:32
I use nodejs to test websocket.

- server code
```js
const Server = require('ws').Server
ws = new Server({port: 80})
ws.on('connection', ws => {
	console.log('client connected')

	ws.on('message', msg => {
		console.log(`client -> server: ${msg}`)
		ws.send('hello, I am server')
	})
})
```
deploy: `api.dev.ourfor.top`[Test](http://api.dev.ourfor.top)

- client code
```js
const socket = new WebSocket('ws://demo.ourfor.top')

socket.onopen = () => {
	console.log('connected!')
	socket.send('hello, I am client.')
}

socket.onmessage = ({data: msg}) => {
	console.log(`server -> client: ${msg}`)
	console.log(msg)
}
```

before using kong, 
![image](https://user-images.githubusercontent.com/33711476/77316712-df503200-6d44-11ea-8f45-3ff5149d3559.png)

after using those config:
- `api service`:
```json
{
    "host": "api.dev.ourfor.top",
    "created_at": 1584966116,
    "connect_timeout": 60000,
    "id": "ffe00cc0-40ab-4109-843c-c9818efc0038",
    "protocol": "http",
    "name": "api",
    "read_timeout": 60000,
    "port": 80,
    "path": null,
    "updated_at": 1584966116,
    "retries": 5,
    "write_timeout": 60000,
    "tags": null,
    "client_certificate": null
}
```

- `route`
```json
{
    "next": null,
    "data": [
        {
            "id": "ad8eb330-6f5e-46fe-b8b6-38d7364b537e",
            "path_handling": "v0",
            "paths": null,
            "destinations": null,
            "headers": null,
            "protocols": [
                "http",
                "https"
            ],
            "methods": null,
            "snis": null,
            "service": {
                "id": "ffe00cc0-40ab-4109-843c-c9818efc0038"
            },
            "name": null,
            "strip_path": true,
            "preserve_host": false,
            "regex_priority": 0,
            "updated_at": 1584966133,
            "sources": null,
            "hosts": [
                "demo.ourfor.top"
            ],
            "https_redirect_status_code": 426,
            "tags": null,
            "created_at": 1584966133
        }
    ]
}
```

and client code change to:
```js
const socket = new WebSocket('ws://demo.ourfor.top:8000')

socket.onopen = () => {
	console.log('connected!')
	socket.send('hello, I am client.')
}

socket.onmessage = ({data: msg}) => {
	console.log(`server -> client: ${msg}`)
	console.log(msg)
}
```
![image](https://user-images.githubusercontent.com/33711476/77316917-35bd7080-6d45-11ea-9c3b-b3a8de7b6d6d.png)

and test http
![image](https://user-images.githubusercontent.com/33711476/77316976-508fe500-6d45-11ea-9c06-0ee9c9ed1cd0.png)

**Comment by bungle** [comment] 2020-03-23 14:42
@ourfor I used my machine to proxy to:
http://api.dev.ourfor.top/

![proxying through kong](https://user-images.githubusercontent.com/983257/77328513-4c53cf80-6d25-11ea-8d56-d76b44a310a8.png)

**Comment by bungle** [comment] 2020-03-23 14:43
Here is the service I used:
```json
{
    "client_certificate": null,
    "connect_timeout": 60000,
    "created_at": 1584974390,
    "host": "api.dev.ourfor.top",
    "id": "b6838ab6-a71e-48e2-aee2-b367a8be1eac",
    "name": null,
    "path": "/",
    "port": 80,
    "protocol": "http",
    "read_timeout": 60000,
    "retries": 5,
    "tags": null,
    "updated_at": 1584974390,
    "write_timeout": 60000
}
```
and here is the route:
```json
{
    "created_at": 1584974415,
    "destinations": null,
    "headers": null,
    "hosts": null,
    "https_redirect_status_code": 426,
    "id": "c669e947-a9bc-45a3-8ab1-ea83703f0f34",
    "methods": null,
    "name": null,
    "path_handling": "v0",
    "paths": [
        "/"
    ],
    "preserve_host": false,
    "protocols": [
        "http",
        "https"
    ],
    "regex_priority": 0,
    "service": {
        "id": "b6838ab6-a71e-48e2-aee2-b367a8be1eac"
    },
    "snis": null,
    "sources": null,
    "strip_path": true,
    "tags": null,
    "updated_at": 1584974415
}
```

**Comment by ourfor** [comment] 2020-03-23 15:02
the problem is that I have a static website and api service in one server. I use `blog.ourfor.top` to visit my
static website and use `api.ourfor.top` to provide data. How should I configure?

**Comment by bungle** [comment] 2020-03-23 19:46
Do you know why it works on my machine? I think it should work on yours as well. I don’t see why it won’t work with static website.

**Comment by ourfor** [comment] 2020-03-24 02:35
set service `path` to `/`, it worked. thank you!

**Comment by bungle** [comment] 2020-03-24 09:56
@ourfor, great! thanks for getting back. I am closing this as it turned out to be a small configuration issue.

**Comment by ourfor** [comment] 2020-04-01 03:20
[UPDATE]
It seems like can't work well with tomcat

- `service`
```json
{
    "host": "api.dev.ourfor.top",
    "created_at": 1585711143,
    "connect_timeout": 60000,
    "id": "ed72b4f9-8e89-4211-b86f-cec1a56841b5",
    "protocol": "http",
    "name": "api",
    "read_timeout": 60000,
    "port": 80,
    "path": null,
    "updated_at": 1585711143,
    "retries": 5,
    "write_timeout": 60000,
    "tags": null,
    "client_certificate": null
}
```

- `route`
```json
{
    "next": null,
    "data": [
        {
            "id": "d1287f25-4e1e-4d77-926d-1f5b0928febd",
            "path_handling": "v0",
            "paths": [
                "/"
            ],
            "destinations": null,
            "headers": null,
            "protocols": [
                "http",
                "https"
            ],
            "methods": null,
            "snis": null,
            "service": {
                "id": "ed72b4f9-8e89-4211-b86f-cec1a56841b5"
            },
            "name": null,
            "strip_path": true,
            "preserve_host": false,
            "regex_priority": 0,
            "updated_at": 1585711151,
            "sources": null,
            "hosts": [
                "demo.ourfor.top"
            ],
            "https_redirect_status_code": 426,
            "tags": null,
            "created_at": 1585711151
        }
    ]
}
```

- `websocket`
```js
const socket1 = new WebSocket('ws://api.dev.ourfor.top/auth/wechat')
socket1.onopen = () => {
	console.log('socket1 connected')
}

const socket2 = new WebSocket('ws://demo.ourfor.top:8000/auth/wechat')
socket2.onopen = () => {
	console.log('socket2 connected')
}
```

result is `WebSocket connection to 'ws://demo.ourfor.top:8000/auth/wechat' failed: Error during WebSocket handshake: Unexpected response code: 404`

**Comment by ourfor** [comment] 2020-04-01 03:24
[UPDATE]
It seems like can't work well with tomcat

- `service`
```json
{
    "host": "api.dev.ourfor.top",
    "created_at": 1585711143,
    "connect_timeout": 60000,
    "id": "ed72b4f9-8e89-4211-b86f-cec1a56841b5",
    "protocol": "http",
    "name": "api",
    "read_timeout": 60000,
    "port": 80,
    "path": "/",
    "updated_at": 1585711351,
    "retries": 5,
    "write_timeout": 60000,
    "tags": null,
    "client_certificate": null
}
```

- `route`
```json
{
    "next": null,
    "data": [
        {
            "id": "d1287f25-4e1e-4d77-926d-1f5b0928febd",
            "path_handling": "v0",
            "paths": [
                "/"
            ],
            "destinations": null,
            "headers": null,
            "protocols": [
                "http",
                "https"
            ],
            "methods": null,
            "snis": null,
            "service": {
                "id": "ed72b4f9-8e89-4211-b86f-cec1a56841b5"
            },
            "name": null,
            "strip_path": true,
            "preserve_host": false,
            "regex_priority": 0,
            "updated_at": 1585711151,
            "sources": null,
            "hosts": [
                "demo.ourfor.top"
            ],
            "https_redirect_status_code": 426,
            "tags": null,
            "created_at": 1585711151
        }
    ]
}
```

- `websocket`
```js
const socket1 = new WebSocket('ws://api.dev.ourfor.top/auth/wechat')
socket1.onopen = () => {
	console.log('socket1 connected')
}

const socket2 = new WebSocket('ws://demo.ourfor.top:8000/auth/wechat')
socket2.onopen = () => {
	console.log('socket2 connected')
}
```

result is `WebSocket connection to 'ws://demo.ourfor.top:8000/auth/wechat' failed: Error during WebSocket handshake: Unexpected response code: 404`

**Comment by ourfor** [comment] 2020-04-01 09:48
![image](https://user-images.githubusercontent.com/33711476/78123610-0099d800-7441-11ea-8247-4f6d7ae3d1c9.png)

**Comment by elvis824** [comment] 2020-04-13 18:55
@bungle I also encountered the same issue with Tomcat.
With Kong v2.0.3, websocket connections from both Chrome or Firefbox would be dropped by Tomcat 9.0.29 if it is behind Kong.

Following the changes you mentioned in https://github.com/Kong/kong/issues/5714#issuecomment-602500322, or downgrading Kong to v2.0.0, everything works again.

**Comment by dwin** [comment] 2020-05-01 16:16
Also having this issue with Java Spring, looking into resolving with https://github.com/Kong/kong/issues/5714#issuecomment-602500322

**Comment by zcpwillam** [comment] 2020-08-03 13:00
![image](https://user-images.githubusercontent.com/8898954/89184869-f729a380-d5cb-11ea-9136-c305dba0e044.png)
I got the same problem, the client parsed upgrade response, and when I checked the headers of the upgrade response, there was no key named "upgrade", which caused the following validation exception;
![image](https://user-images.githubusercontent.com/8898954/89185126-4ec80f00-d5cc-11ea-9f9a-57079e557fb9.png)

**Comment by dwin** [comment] 2020-08-03 14:43
The Upgrade header is still there, but it is not in the order that these servers inspect and I think this is an issue on the upstream side that it doesn't inspect more than one value for each header key. 

This is the Dockerfile we use to fix it, we're _not actually building Kong_, just updating a line in the handler for this header.

```dockerfile
FROM alpine:3.12 AS helper

WORKDIR /scratch

RUN apk add --no-cache sed
# copy handler file from Kong image to modify
COPY --from=kong:2.1.0-alpine /usr/local/share/lua/5.1/kong/runloop/handler.lua .
# Apply modification to Websocket handling https://github.com/Kong/kong/issues/5714#issuecomment-602514521
RUN sed -i 's/var.upstream_connection = "keep-alive, Upgrade"/var.upstream_connection = "Upgrade"/' handler.lua

FROM kong:2.1.0
# Copy modified file in
COPY --from=helper /scratch/handler.lua /usr/local/share/lua/5.1/kong/runloop/handler.lua
# no other changes
```

**Comment by jasine** [comment] 2020-11-20 08:14
same issue

**Comment by zonybob** [comment] 2020-12-01 15:02
same issue

**Comment by YouYue123** [comment] 2021-01-18 03:05
This handler.lua fix works for me. If the connection in header is "Keep-alive, Upgrade", socket.io won't handle it.

My env: 

Backend: socket.io 3.0.5 on nodeJS 14
Frontend: socket.io-client 3.0.5

**Comment by dwin** [comment] 2021-01-23 04:15
@bungle Can this be reopened?

**Comment by lovejj1994** [comment] 2021-01-26 08:08
@dwin 3q ，Solve my problem with tomcat9 and kong 2.2.1

**Comment by missops** [comment] 2021-01-28 12:25
k8s内代理websocket一样的问题，版本：2.1.0

按@重新打下镜像解决。

> The Upgrade header is still there, but it is not in the order that these servers expect and I think this is an issue on the upstream side that it doesn't inspect more than one value for each header key.
> 
> This is the Dockerfile we use to fix it, we're _not actually building Kong_, just updating a line in the handler for this header.
> 
> ```dockerfile
> FROM alpine:3.12 AS helper
> 
> WORKDIR /scratch
> 
> RUN apk add --no-cache sed
> # copy handler file from Kong image to modify
> COPY --from=kong:2.1.0-alpine /usr/local/share/lua/5.1/kong/runloop/handler.lua .
> # Apply modification to Websocket handling https://github.com/Kong/kong/issues/5714#issuecomment-602514521
> RUN sed -i 's/var.upstream_connection = "keep-alive, Upgrade"/var.upstream_connection = "Upgrade"/' handler.lua
> 
> FROM kong:2.1.0
> # Copy modified file in
> COPY --from=helper /scratch/handler.lua /usr/local/share/lua/5.1/kong/runloop/handler.lua
> # no other changes
> ```

k8s kong ingress 一样的问题，按这个重新打镜像后解决。 版本：2.1.0

**Closed** 2021-03-17 17:37 UTC
Labels: pending author feedback
