### ISSUE TITLE
After postgre upgrade to 14.3 kong migrations do not pass

### ISSUE THREAD

**Issue by nick-kostov** [Kong/kong#9374] opened 2022-09-02 15:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong:2.3.1-alpine

### Current Behavior

After upgrade of Postgres to 14.3 kong fails migrations.
We run this into EKS 1.21.
```
k logs -n kong api-gw-kong-init-migrations-6khtx
Error: don't know how to auth: 10

  Run with --v (verbose) or --vv (debug) for more details
```

### Expected Behavior

Kong migrations to pass.
We have upgraded the Postgres databases in all of our environments.

### Steps To Reproduce

```markdown
1. Upgrade postgres to 14.3
2. Tried to deploy kong into the EKS.
3. Deployment failed.
```

### Anything else?

We use helm for the installation

**Comment by samugi** [comment] 2022-09-03 11:00
Closing this as duplicate of: https://github.com/Kong/kong/issues/8259

**Closed by samugi** 2022-09-03 11:00 UTC
Labels: core/db/migrations, core/db
