### ISSUE TITLE
URIs with same prefix are not routed correctly

### ISSUE THREAD

**Issue by kushmansingh** [Kong/kong#3021] opened 2017-11-10 17:56 UTC
### Summary

Overlapping uris for an API definition are not routed correctly

### Steps To Reproduce

1. `curl -X POST -d '{"name":"foo", "uris":"/a,/a-alternate", "upstream_url":"https://google.com"}' localhost:8001/apis`
2. `curl localhost:8000/a` will always route correctly too `https://google.com`
3. `curl localhost:8000/a-alternate` will route to `https://google.com` correctly or `https://google.com/-alternate` which is incorrect.

### Additional Details & Logs
- Kong version (0.10.4)

However, if I have two separate API definitions, this will work fine as this was addressed in https://github.com/Kong/kong/issues/2662

**Comment by bungle** [comment] 2017-11-15 16:05
If have a feeling that `/a-alternate` may be considered as `regex`.

**Comment by bungle** [comment] 2017-11-15 19:21
^- the above feeling is probably be wrong (according to: https://github.com/Kong/kong/blob/master/kong/core/router.lua#L168), but this is indeed interesting case. I look more into it.

**Comment by bungle** [comment] 2017-12-08 17:58
Hmm... this seems to be the case, I couldn't reproduce this with `httpie`, but with `curl` I can:

**First Request:**
```
$ curl http://localhost:8000/a-alternate// -vv
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8000 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /a-alternate// HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Fri, 08 Dec 2017 17:55:07 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 173
< Connection: keep-alive
< Server: Werkzeug/0.13 Python/3.6.3
< X-Kong-Upstream-Latency: 2
< X-Kong-Proxy-Latency: 0
< Via: kong/0.10.4
< 
Location: /
X-Real-Ip: 127.0.0.1
X-Forwarded-For: 127.0.0.1
X-Forwarded-Proto: http
Host: localhost:8020
Connection: keep-alive
User-Agent: curl/7.54.0
Accept: */*

* Connection #0 to host localhost left intact
```

**Second Request:**
```
$ curl http://localhost:8000/a-alternate// -vv
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8000 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /a-alternate// HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Fri, 08 Dec 2017 17:55:08 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 185
< Connection: keep-alive
< Server: Werkzeug/0.13 Python/3.6.3
< X-Kong-Upstream-Latency: 1
< X-Kong-Proxy-Latency: 0
< Via: kong/0.10.4
< 
Location: /-alternate//
X-Real-Ip: 127.0.0.1
X-Forwarded-For: 127.0.0.1
X-Forwarded-Proto: http
Host: localhost:8020
Connection: keep-alive
User-Agent: curl/7.54.0
Accept: */*

* Connection #0 to host localhost left intact
```

**Comment by bungle** [comment] 2017-12-08 18:04
I cannot reproduce this with `0.11.2`, @kushmansingh can you reproduce this with `0.11.2`? I guess this might have to do with `serf` removal. Maybe something with cache got fixed with that as well(?).

**Comment by kikito** [comment] 2018-02-15 15:53
Hi, I am closing this issue because of lack of activity. @kushmansingh, If you think it is still unresolved, please reopen with the requested information. Thanks!

**Closed by kikito** 2018-02-15 15:53 UTC
Labels: pending user feedback, task/needs-investigation
