### ISSUE TITLE
Kong does not support TLS 1.2 in a correct manner

### ISSUE THREAD

**Issue by rawgrr** [Kong/kong#6734] opened 2021-01-14 17:17 UTC
### Summary

When running with SSL_CIPHER_SUITE "Intermediate", only a few ciphers works.

### Steps To Reproduce

1. Start Kong with `ssl_cipher_suite` "Intermediate"
2. The value `ssl_ciphers` is "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"
3. Try ex. `curl https://mypage.whatever.com --cipher ECDHE-ECDSA-AES128-GCM-SHA256`  
4. The response is: `curl: (35) error:14004410:SSL routines:CONNECT_CR_SRVR_HELLO:sslv3 alert handshake failure`

### Additional Details & Logs

Tested on Kong 2.1.4 and 2.3.0

When testing, the following ciphers work:

ECDHE-RSA-AES128-GCM-SHA256
ECDHE-RSA-AES256-GCM-SHA384
ECDHE-RSA-CHACHA20-POLY1305

The following do not work:

ECDHE-ECDSA-AES256-GCM-SHA384
ECDHE-ECDSA-CHACHA20-POLY1305
ECDHE-ECDSA-AES128-GCM-SHA256
DHE-RSA-AES128-GCM-SHA256
DHE-RSA-AES256-GCM-SHA384

**Comment by bungle** [comment] 2021-01-14 17:38
@rawgrr, I tried it with `Kong 2.3.0` but I could not reproduce. Works fine for me. Can you provide more information on how to reproduce it with `2.3.0`. Please do it in clean environment or in new prefix at least.

**Comment by bungle** [comment] 2021-01-14 17:44
@rawgrr, if you are using Kong auto-generated and self-signed certs, you need to add `-k` argument for `curl`.

**Comment by bungle** [comment] 2021-01-14 17:45
@rawgrr, also if you are using your own certs with `:8001/certificates` you need to add both types of certs RSA and DSA).

**Comment by rawgrr** [comment] 2021-01-15 08:13
@bungle, thanks a lot for the feedback! I will look into the `_alt`-fields. I cannot find any information or documentation about it though?

**Comment by rawgrr** [comment] 2021-01-15 08:53
@bungle, I noticed an error in my first post. Only 3 ciphers work, not 5 as I mentioned first.

**Comment by bungle** [comment] 2021-01-15 12:08
@rawgrr, yes, you need to use `_alt` to to get both RSA and DSA to work. You need hybrid cert configuration. And you need to have both types of certs to get all algs to work.

**Comment by bungle** [comment] 2021-01-15 12:17
@rawgrr also how do you configure your certs? In Kong configuration or in `:8001/certificates`?

**Comment by rawgrr** [comment] 2021-01-15 12:36
@bungle I added the GoDaddy cert in Konga, so I guess it's in `:8001/certificates`. I'm a beginner when it comes to certs - how can I get both types? I think the current one is an RSA type.

![image](https://user-images.githubusercontent.com/71869309/104728045-9be10d00-5736-11eb-8bcf-e3e272c06024.png)

**Comment by bungle** [comment] 2021-01-15 15:47
@rawgrr, I am afraid that you will need to consult Go Daddy on it. When you start Kong `2.3` with default configuration you will see these in `/usr/local/kong/nginx-kong.conf`:

```
ssl_dhparam /usr/local/kong/ssl/ffdhe2048.pem;
ssl_prefer_server_ciphers off;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_session_tickets on;
ssl_session_timeout 1d;
ssl_certificate     /usr/local/kong/ssl/kong-default.crt;
ssl_certificate_key /usr/local/kong/ssl/kong-default.key;
ssl_certificate     /usr/local/kong/ssl/kong-default-ecdsa.crt;
ssl_certificate_key /usr/local/kong/ssl/kong-default-ecdsa.key;
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
```

This is the so called default config and this is `intermediate` config as specified in:
https://wiki.mozilla.org/Security/Server_Side_TLS

And same as here:
https://ssl-config.mozilla.org/#server=nginx&version=1.17.7&config=intermediate&openssl=1.1.1i&hsts=false&ocsp=false&guideline=5.6

Except that we do generate both types of vert. See the `ssl_certificate` and `ssl_certificate_key` is specified twice. This is same as with `:8001/certificates` where we have `key` and `cert` and `key_alt` and `cert_alt`.

**Comment by bungle** [comment] 2021-01-20 18:40
I think we have given the information needed, and checked that Kong works correctly as long as you configure and give proper certificates. Thus, I am closing this. @rawgrr, there are 2 types of certs basically RSA and DSA, and they require different keys. You need them both if you want all `intermediate ciphers` to work.

**Closed by bungle** 2021-01-20 18:40 UTC
Labels: pending author feedback
