### ISSUE TITLE
Response cache hit/miss metrics

### ISSUE THREAD

**Issue by anup-krai** [Kong/kong#7671] opened 2021-06-17 09:39 UTC
Is there a way to get the cache metrics for the responses cached through [Proxy Cache ](https://docs.konghq.com/hub/kong-inc/proxy-cache/?_ga=2.212628244.161458172.1623566973-286951487.1616498335) plugin like below -

1. Number of times response returned from cache (cache hit) per route/service.
2. Number of times request was proxied to upstream (cache miss) per route/service.

Is there a way to get this metrics from Prometheus plugin?

**Comment by StarlightIbuki** [comment] 2023-10-11 06:23
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:23 UTC
Labels: plugins/prometheus
