### ISSUE TITLE
Why proxy latency includes receive_time ?

### ISSUE THREAD

**Issue by shettyh** [Kong/kong#9833] opened 2022-11-26 06:59 UTC
### Discussed in https://github.com/Kong/kong/discussions/9481

<div type='discussions-op-text'>

<sup>Originally posted by **shettyh** September 28, 2022</sup>
Hi,

Currently proxy latency includes `receive_time`, that is the time spent receiving headers and body from upstream. Currently it is calculated as `body_filter_ended_time` - `header_filter_start` ( or similar ), Why it is not just `header_filter_time` + `body_filter_time` ? Can upstream effect the `receive_time` ?

Thanks</div>

**Comment by shettyh** [comment] 2022-11-26 07:00
Moving to issue as i don't see any response in the discussion.

**Comment by mayocream** [comment] 2022-11-30 03:28
https://github.com/Kong/kong-ee/blob/bb5b4717bb00db7d571e0a12472e595064ef28e2/kong/init.lua#L1532-L1539
IMO, it's more accurate by calculating as `ctx.KONG_BODY_FILTER_ENDED_AT` - `(ctx.KONG_RESPONSE_START or ctx.KONG_HEADER_FILTER_START`, this includes the response time from upstream, which is neither included in `header_filter_time` nor `body_filter_time`.

**Comment by shettyh** [comment] 2022-11-30 04:15
@mayocream thanks for the response. What is the time spent between `header_filter` and `body_filter` ?. Wanted to understand this as we are seeing higher proxy latency due to a change in upstream service and this latency is not accounted in any of the kong phases

**Comment by bungle** [comment] 2023-01-03 10:51
@shettyh I think `KONG_RECEIVE_TIME` is a time spent in `header_filter` + possible multiple calls to `body_filter` as the data is streaming from the upstream service. The buffered proxying complicates this (the ctx.KONG_RESPONSE_START), but by default Kong does not buffer the responses. So think it this ways:

1. clock starts ticking when header_filter is called
2. clock stops ticking when the last chunk of body is received
3. receive time is last chunk received time - header filter start time

So the number basically tells how long it took for kong to stream data from upstream to downstream, starting from the time Kong received the headers from the upstream service. If upstream does something like `send_headers()`, `flush()`, `sleep(10)`, `send_body()`, the `sleep(10)` is included in `KONG_RECEIVE_TIME` too.

**Comment by shettyh** [comment] 2023-01-11 11:51
Sure @bungle , will try that out. Thanks

**Comment by locao** [comment] 2023-02-14 17:44
Hi @shettyh! Do you have any updates about your test results?

**Comment by shettyh** [comment] 2023-02-16 13:16
@locao That didnt help 😢

**Comment by StarlightIbuki** [comment] 2023-10-18 08:41
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md?rgh-link-date=2023-10-18T08%3A39%3A47Z) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-18 08:41 UTC
Labels: core/proxy, help wanted
