### ISSUE TITLE
bug: Patch request for basic-auth credential returns 404 incorrectly

### ISSUE THREAD

**Issue by hbagdi** [Kong/kong#4893] opened 2019-08-12 15:46 UTC
### Summary

When password specified in a patch request is same as the one currently stored in DB(hashed), patch request return a 404.
This could be due to the hashing logic on the password field.

### Steps To Reproduce

```bash
$ http :8001/consumers username=foo
HTTP/1.1 201 Created
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 115
Content-Type: application/json; charset=utf-8
Date: Mon, 12 Aug 2019 15:39:19 GMT
Server: kong/1.3.0rc1

{
    "created_at": 1565624359,
    "custom_id": null,
    "id": "6a3c317e-daa9-4934-89be-10fc4a04e703",
    "tags": null,
    "username": "foo"
}

$ http post :8001/consumers/foo/basic-auth username=bar
HTTP/1.1 201 Created
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 197
Content-Type: application/json; charset=utf-8
Date: Mon, 12 Aug 2019 15:39:32 GMT
Server: kong/1.3.0rc1

{
    "consumer": {
        "id": "6a3c317e-daa9-4934-89be-10fc4a04e703"
    },
    "created_at": 1565624372,
    "id": "8b80904a-68c9-432c-a7e9-f308d5ab860a",
    "password": "ea809177afb40b62a34582080b8a876b9056cbf5",
    "username": "bar"
}

# Please note that specifying the hashed password as the password should again hash it

$ http patch :8001/consumers/foo/basic-auth/8b80904a-68c9-432c-a7e9-f308d5ab860a password=ea809177afb40b62a345820
80b8a876b9056cbf5 username=new-bar
HTTP/1.1 404 Not Found
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 23
Content-Type: application/json; charset=utf-8
Date: Mon, 12 Aug 2019 15:40:43 GMT
Server: kong/1.3.0rc1

{
    "message": "Not found"
}

$ http patch :8001/consumers/foo/basic-auth/8b80904a-68c9-432c-a7e9-f308d5ab860a password=any-other-password username=new-bar
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 201
Content-Type: application/json; charset=utf-8
Date: Mon, 12 Aug 2019 15:45:31 GMT
Server: kong/1.3.0rc1

{
    "consumer": {
        "id": "6a3c317e-daa9-4934-89be-10fc4a04e703"
    },
    "created_at": 1565624372,
    "id": "8b80904a-68c9-432c-a7e9-f308d5ab860a",
    "password": "bda1183766a0e94b1ea14f7733f9c21ffade8805",
    "username": "new-bar"
}
```

### Additional Details & Logs

- Kong version (`$ kong version`) 1.3.0rc1

**Comment by bungle** [comment] 2019-08-13 07:25
Exactly:
https://github.com/Kong/kong/blob/master/kong/plugins/basic-auth/basicauth_credentials.lua#L6-L7

**Comment by bungle** [comment] 2019-08-13 08:00
Btw. I tried this with `next` and could not reproduce.

**Comment by bungle** [comment] 2019-08-14 14:06
@hbagdi can you check it with `next` if it is not an issue anymore, can you then close this?

**Comment by hbagdi** [comment] 2019-08-15 20:45
Verified that this is till an issue in `next` at a169bcf354f3ac67aa5.

**Comment by bungle** [comment] 2019-10-01 12:02
The dao transformations got merged, so I will close this. Please reopen if it didn't fix the issue.

**Closed by bungle** 2019-10-01 12:02 UTC
Labels: task/bug
