### ISSUE TITLE
Add delay in API response

### ISSUE THREAD

**Issue by anup-krai** [Kong/kong#9115] opened 2022-07-18 06:19 UTC
### Discussed in https://github.com/Kong/kong/discussions/8980

<div type='discussions-op-text'>

<sup>Originally posted by **anup-krai** June 20, 2022</sup>
We are using Kong with KIC deployed in K8s cluster with Postgres DB.
Kong - 2.7.1
KIC - 2.2.1
We have Kong deployed in multiple datacenter and Postgres running with master and replica setup.
Postgres master is running in one datacenter and replicas are running in other datacenter. Write calls are routed to Postgres master node and read calls are routed to Postgres replicas. We are using oauth2 plugin for the API routes.

We see when token is generated a write call is made to master Postgres node and the same is getting synced to other replicas. So when actual API call comes then token will be read from read replicas and then API call is allowed.

In some cases we see before the tokens are synced to the replicas the API call is made and it’s getting rejected with HTTP 401.

Is there a way we can avoid this issue?

We tried to add some (ms) delay to the oauth calls using a custom plugin with below code -
```
function ResponseDelayHandler:header_filter(conf)
    local http_status = kong.response.get_status()
    local sleep_time = conf.sleep_time
    if http_status == 200 then
        socket.sleep(sleep_time)
    end
end
```
This plugin is added only to oauth token route but this is decreasing the throughput for other routes also.

**Before adding a delay** -
Both oauth and API calls are handling more than 1K TPS.

**After adding a delay** -
TPS is reduced to 1/3. OAuth call throughput reduction is expected because of delay but why other API calls throughput is also reduced? This API has only local rate limiting plugin added.

</div>

**Comment by kikito** [comment] 2022-07-19 15:32
> Is there a way we can avoid this issue?

Not completely, by design. Two geographically disperse are eventually consistent by nature. The tokens being on the replica immediately after creating them in the master explicitly goes against that expectation.

In your case I would create your own custom plugin based on the oauth one to make a retry or two after getting a failure when retrieving the token. The function that governs token retrieval is [retrieve_token in access.lua](https://github.com/Kong/kong/blob/master/kong/plugins/oauth2/access.lua#L818-L833). You probably want to sleep some ms between retries.

Also, beware that kong.cache does negative caching as well. See https://docs.konghq.com/gateway/latest/plugin-development/entities-cache/

**Comment by kikito** [comment] 2022-07-22 09:31
I just noticed I had not answered this part of your ticket:

> TPS is reduced to 1/3. OAuth call throughput reduction is expected because of delay but why other API calls throughput is also reduced? This API has only local rate limiting plugin added.

Your delay-based solution means that each worker has to "keep" connections for a longer time than needed. Each connection that is "on hold" takes "a spot". Workers have a limited number of connections they can simultaneously handle. If your system has enough of these "blocked" responses you could be "running out of spots", in which case new requests get put on a queue. That might be why, even if you added your plugin to one specific route, it impacts the rest of the system.

Open connections also consume memory and more open connections means more CPU time spent context-switching.  If your CPU usage is close to the limit (~90%) you might be able to sidestep the problem by adding more cores to your system, and more workers. Same goes for memory usage.

**Comment by hanshuebner** [comment] 2023-06-27 08:35
Closing as this was discussed in #8980

**Closed by hanshuebner** 2023-06-27 08:35 UTC
Labels: area/ingress-controller, core/db
