### ISSUE TITLE
Include tags in metrics labeles

### ISSUE THREAD

**Issue by rmrf** [Kong/kong#7678] opened 2021-04-16 10:52 UTC
We can setup tags on kong for each route, these tags have lots of useful  information aside of name,  can prometheus bring these tags on when export metrics?

**Comment by carnei-ro** [comment] 2023-01-08 20:21
hey, I refactored and opened this new PR https://github.com/Kong/kong/pull/10082;

this is still relevant to our scenario.

I can label a specific set of consumers and/or routes, and if the threshold of 5xx for those calls is reached, I can wake up the SREs to take a look!

**Comment by StarlightIbuki** [comment] 2023-10-18 08:39
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md?rgh-link-date=2023-10-11T06%3A14%3A30Z) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-18 08:39 UTC
Labels: plugins/prometheus
