### ISSUE TITLE
Schema validation in db-less mode Kong 1.4

### ISSUE THREAD

**Issue by altexy** [Kong/kong#5401] opened 2020-01-07 09:44 UTC
### Summary

Schema validation silently ignored when starting Kong in db-less mode.

### Steps To Reproduce

1. Write db-less config with any plugin with missed required field.
2. Start Kong in DB-less mode

Kong 1.3.x failed to start, the error log contains an appropriate message.

Kong 1.4.x silently start, no schema validation logs present.

### Additional Details & Logs

- Kong version official Docker images kong:1.4.x-alpine and kong:1.3.x-alpine

**Comment by bungle** [comment] 2020-01-07 12:17
@altexy, thanks for reporting. Possibly a bug.

**Comment by bungle** [comment] 2020-01-11 15:33
@hishamhm, do you have an idea about this?

**Comment by hbagdi** [comment] 2020-05-28 00:11
Re-opening because https://discuss.konghq.com/t/kong-2-0-1-db-less-schema-validation-issue/6375

**Comment by bungle** [comment] 2020-06-01 08:08
I can confirm that this only happens with `reload`. So investigating it further.

E.g. start with:

```yaml
_format_version: "1.1"

services:
  - name: sample_api
    host: kong.test
    port: 4000
```

```bash
KONG_DATABASE=off KONG_DECLARATIVE_CONFIG=b.yaml ./bin/kong start --vv
```

And you have:
```json
{
    "data": [
        {
            "client_certificate": null,
            "connect_timeout": 60000,
            "created_at": 1590998526,
            "host": "kong.test",
            "id": "f43346f0-16f5-55b3-b815-f4dfa7cdb1e8",
            "name": "sample_api",
            "path": null,
            "port": 4000,
            "protocol": "http",
            "read_timeout": 60000,
            "retries": 5,
            "tags": null,
            "updated_at": 1590998526,
            "write_timeout": 60000
        }
    ],
    "next": null
}
```

Then
```yaml
_format_version: "1.1"

services:
  - name: sample_api
    port: 4000

services:
  - name: sample_api2
    host: another.test
    port: 4000
```

```bash
KONG_DATABASE=off KONG_DECLARATIVE_CONFIG=b.yaml ./bin/kong reload --vv
```

And you have:

```
{
    "data": [
        {
            "client_certificate": null,
            "connect_timeout": 60000,
            "created_at": 1590998526,
            "host": "kong.test",
            "id": "f43346f0-16f5-55b3-b815-f4dfa7cdb1e8",
            "name": "sample_api",
            "path": null,
            "port": 4000,
            "protocol": "http",
            "read_timeout": 60000,
            "retries": 5,
            "tags": null,
            "updated_at": 1590998526,
            "write_timeout": 60000
        }
    ],
    "next": null
}
```

So I think that  perhaps the `reload` does not load declarative and you actually need restart to do so? So is this expected or not? @hishamhm?

**Comment by bungle** [comment] 2020-09-16 23:34
I think it is expected. `reload` does not honor `environment vars` it uses the env vars that were used when Kong was started.

**Comment by bungle** [comment] 2020-09-16 23:35
I am closing this now. Please reopen if you have any further info, or need more guidance.

**Closed by bungle** 2020-09-16 23:35 UTC
Labels: task/needs-investigation
