### ISSUE TITLE
JWT plugin allows invalid configuration for cookie_names

### ISSUE THREAD

**Issue by rainest** [Kong/kong#4479] opened 2019-04-04 22:52 UTC
### Summary

The JWT plugin allows invalid configuration for `cookie_names`

### Steps To Reproduce

1. Create a JWT plugin instance without specifying any configuration, e.g. with `http localhost:8001/plugins name=jwt`. The resulting instance will correctly have `config.cookie_names: []`. Send a request through Kong to confirm that JWT works normally (i.e. returns unauthorized, since no consumer configuration was added).
2. PATCH the instance to remove any `cookie_names` configuration, e.g. with `http patch localhost:8001/plugins/68831609-45d7-4c64-a106-3fd4ec5bf128 config.cookie_names='' protocols:='["http","https"]'`. The plugin will now have `config.cookie_names: null`. Send another test request, which should result in a 500 error.
3. Restore the original configuration, e.g. with `http patch localhost:8001/plugins/68831609-45d7-4c64-a106-3fd4ec5bf128 config.cookie_names='[]' protocols:='["http","https"]'` and test again to confirm the error is cleared.

### Additional Details & Logs

Tested on Kong version 1.1.0, Ubuntu Xenial.

Was not an issue prior to 1.x. Tested also on 0.13, it set `cookie_names` to `{}` if PATCHed to the empty string.

This looks like a more general issue with how the new DAO handles setting array/table configuration--it's possible to break `uri_param_names` in a similar way, and likely table configuration in other plugins also. I'm not sure if clearing configuration by PATCHing tables to the empty string is intentionally no longer supported as of 1.0, but if so, it'd probably make sense for the admin API to reject it outright. This looks like [a side effect of the "Array values ... must now be "proper" JSON values on JSON requests"  change](https://github.com/Kong/kong/blob/master/CHANGELOG.md#admin-api-4), but while comma-separated values are still safe (they result in an array like `['foo,bar']`, which, while likely never the intended configuration, will not break ipairs), the empty string converting to null is unsafe, and results in the error below.

Error logs will show a failure in [retrieve_token](https://github.com/Kong/kong/blob/1.1.0/kong/plugins/jwt/handler.lua#L36-L42):

```
2019/04/04 22:26:07 [error] 2214#0: *1952 lua coroutine: runtime error: /usr/local/share/lua/5.1/kong/plugins/jwt/handler.lua:37: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'ipairs'
        /usr/local/share/lua/5.1/kong/plugins/jwt/handler.lua:37: in function 'retrieve_token'
        /usr/local/share/lua/5.1/kong/plugins/jwt/handler.lua:133: in function 'do_authentication'
        /usr/local/share/lua/5.1/kong/plugins/jwt/handler.lua:252: in function </usr/local/share/lua/5.1/kong/plugins/jwt/handler.lua:238>
coroutine 1:
        [C]: in function 'resume'
        coroutine.wrap:21: in function <coroutine.wrap:21>
        /usr/local/share/lua/5.1/kong/init.lua:741: in function 'access'
        access_by_lua(nginx-kong.conf:99):2: in function <access_by_lua(nginx-kong.conf:99):1>, client: 127.0.0.1, server: kong, request: "GET / HTTP/1.1", host: "mismatch.example"
2019/04/04 22:26:07 [error] 2214#0: *1952 [kong] init.lua:747 /usr/local/share/lua/5.1/kong/plugins/jwt/handler.lua:37: bad argument #1 to 'ipairs' (table expected, got nil), client: 127.0.0.1, server: kong, request: "GET / HTTP/1.1", host: "mismatch.example"
```

**Comment by hishamhm** [comment] 2019-04-05 15:36
Ah, the Billion Dollar Mistake bites us again. Those set fields in the JWT plugin were not marked as `required` and therefore accept `null`. Fixing the plugin schema to add `default = {}, required = true` fixes it<sup>*</sup>, and the offending `patch` returns a schema validation error.

This probably may be lurking in more places other than JWT. Interestingly, _one_ of the sets of the JWT [does handle `null` via code](https://github.com/Kong/kong/blob/master/kong/plugins/jwt/jwt_parser.lua#L312-L314). I guess that's another option, but fixing the schema sounds more sensible.

One weird thing is how `config.cookie_names=''` was converted into `null`, since this was not a form-encoded request. I checked via a unit test and the schema library does not accept empty strings for sets. @bungle, maybe the auto-conversions created for form-encoded are overreaching? It is also converting any non-empty string into a singleton array (producing the `["foo,bar"]` footgun that @rainest described).

---
<sup>*</sup> it would be so much better if values did _not_ accept null by default and had to use `optional = true` instead when they want `null` to be valid, but this ship has sailed, at least for Kong 1.x...

**Comment by bungle** [comment] 2020-01-24 14:25
@hishamhm, that inferring on json is fixed already.

**Comment by StarlightIbuki** [comment] 2023-10-11 06:14
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:14 UTC
Labels: plugins/jwt
