### ISSUE TITLE
Kong Marking unhealthy target healthy again on deletion of target or addition of new target

### ISSUE THREAD

**Issue by puneet739** [Kong/kong#7835] opened 2021-09-12 20:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.5.0

### Current Behavior

When we create a service/route/upstream and then attach some targets to it. 
on addition of any new target, all old earlier marked unhealthy targets automatically turns back healthy, when those are already deleted. 
This cause a delayed in response and kong again marking them unhealthy. 
we are using combination of active/passive health-check. 

### Expected Behavior

The targets which are already marked as unhealthy should not be updated to healthy again unless they comes back or pass the health status. 

### Steps To Reproduce

```markdown
Create a service with 3 fake targets and 1 active target(Service which can serve request). with below status check. 
{
    "healthchecks": {
        "active": {
            "https_verify_certificate": false,
            "healthy": {
                "successes": 2,
                "http_statuses": [
                    200,
                    301,
                    302,
                    404,
                    201,
                    204,
                    401,
                    403
                ],
                "interval": 0
            },
            "unhealthy": {
                "interval": 5,
                "http_statuses": [
                    429,
                    500,
                    501,
                    502,
                    503,
                    504,
                    505
                ],
                "tcp_failures": 5,
                "timeouts": 5,
                "http_failures": 5
            },
            "https_sni": null,
            "timeout": 15,
            "type": "http",
            "http_path": "/status",
            "concurrency": 10
        },
        "passive": {
            "healthy": {
                "http_statuses": [
                    200,
                    201,
                    202,
                    203,
                    204,
                    205,
                    206,
                    207,
                    208,
                    226,
                    300,
                    301,
                    302,
                    303,
                    304,
                    305,
                    306,
                    307,
                    308,
                    401,
                    403
                ],
                "successes": 2
            },
            "unhealthy": {
                "http_statuses": [
                    404,
                    429,
                    500,
                    501,
                    502,
                    503,
                    504
                ],
                "tcp_failures": 1,
                "timeouts": 1,
                "http_failures": 1
            },
            "type": "http"
        },
        "threshold": 0
    }
}

After you sends a lot of request you see the 3 fake targets will be market unhealthy. 
Now just add a new target and you will see all 5 targets will become healthy again. 

Expected behaviour is: Only the last active target and new target should be in healthy state. Not the ones which were earlier marked unhealthy.
```

**Comment by puneet739** [comment] 2021-09-12 20:49
For Making it easy to understand you can use below health-check configuration which is taken from 
https://docs.konghq.com/gateway-oss/2.5.x/health-checks-circuit-breakers/
`{
    "healthchecks": {
        "active": {
            "https_verify_certificate": true,
            "unhealthy": {
                "http_statuses": [
                    429,
                    404,
                    500,
                    501,
                    502,
                    503,
                    504,
                    505
                ],
                "tcp_failures": 2,
                "timeouts": 2,
                "http_failures": 2,
                "interval": 5
            },
            "http_path": "/",
            "timeout": 1,
            "healthy": {
                "http_statuses": [
                    200,
                    302
                ],
                "interval": 10,
                "successes": 0
            },
            "https_sni": "example.com",
            "concurrency": 10,
            "type": "http"
        },
        "passive": {
            "unhealthy": {
                "http_failures": 1,
                "http_statuses": [
                    429,
                    500,
                    503
                ],
                "tcp_failures": 1,
                "timeouts": 0
            },
            "type": "http",
            "healthy": {
                "successes": 0,
                "http_statuses": [
                    200,
                    201,
                    202,
                    203,
                    204,
                    205,
                    206,
                    207,
                    208,
                    226,
                    300,
                    301,
                    302,
                    303,
                    304,
                    305,
                    306,
                    307,
                    308
                ]
            }
        }
    }
}`

**Comment by puneet739** [comment] 2021-09-12 20:55
@Tieske can you suggest something here.

**Comment by puneet739** [comment] 2021-09-13 10:08
@fffonion can you please check this once.

**Comment by puneethps** [comment] 2021-09-16 07:16
@fffonion, @hbagdi  Any update on this? We are facing a similar issue.

**Comment by jeremyjpj0916** [comment] 2021-09-17 15:32
Guessing as part of the rebuild it resets those known health statuses for targets.

**Comment by puneet739** [comment] 2021-09-18 09:03
@jeremyjpj0916  but is this expected, specially when kong says, it never deletes the target, just mark them unhealhty. This way we will be struggling now and then on high end applications.

**Comment by jeremyjpj0916** [comment] 2021-09-18 15:36
Certainly seems undesirable behavior to me. I don't utilize Kong as a LB yet but I am glad there are folks out there like you vetting it so hopefully by the time I integrate it Kong can have all the glaring issues fixed with the feature set.

**Comment by puneet739** [comment] 2021-09-23 06:16
Any update on this? I thought kong is production grade system. but this is causing issue for us.

**Comment by puneethps** [comment] 2021-09-23 10:43
@javierguerragiraldez looks like this issue is happening due to https://github.com/Kong/kong/blob/master/kong/runloop/balancer/targets.lua#L132 this line, was invalidating health check statues on modifications to any target in that upstream done deliberately, and if so what was the reason for this? and can we expect this to be fixed in future releases or not?

**Comment by javierguerragiraldez** [comment] 2021-09-23 12:41
> looks like this issue is happening because of [this line](https://github.com/Kong/kong/blob/master/kong/runloop/balancer/targets.lua#L132), was invalidating health check statues on modifications to any target in that upstream done deliberately, and if so what was the reason for this?

this is a cache invalidation, not "make this resource invalid".  it means that the next time those target records are needed, they would be read again from the database and not from cache.

Also note that the line you link to doesn't exist in Kong 2.5.x

**Comment by puneethps** [comment] 2021-09-23 12:48
@javierguerragiraldez  Ok, my bad, I assumed that invalidation of cached targets would automatically make the unhealthy targets healthy, as there is no reference to current health status of the target in the database, maybe my understanding of how healthcheck values are stored is wrong.

**Comment by StarlightIbuki** [comment] 2023-10-11 06:24
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:24 UTC
Labels: core/balancer
