### ISSUE TITLE
handler.lua:133: attempt to concatenate field 'hostname' (a nil value)

### ISSUE THREAD

**Issue by DennoVonDiesel** [Kong/kong#3128] opened 2017-12-29 22:08 UTC
We have batch job that uses a service behind Kong that receives a 500 Error and message "An unexpected error occurred" about 10 times (out of ~ 75k) per day, and the following logged by Kong:

2017/12/10 23:00:53 [error] 1352#0: *23304774 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/core/handler.lua:133: attempt to concatenate field 'hostname' (a nil value)
stack traceback:
coroutine 0:
        /usr/local/share/lua/5.1/kong/core/handler.lua: in function 'before'
        /usr/local/share/lua/5.1/kong.lua:292: in function 'access'
        access_by_lua(nginx-kong.conf:108):2: in function <access_by_lua(nginx-kong.conf:108):1>, client: 1.1.1.1, server: kong, request: "POST /path/to/endpoint HTTP/1.1", host: "kong.domain.com"
2017/12/10 23:00:53 [error] 1352#0: *23304447 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/core/handler.lua:133: attempt to concatenate field 'hostname' (a nil value)

Content above scrubbed for identifiable information. It appears to be this section of code:

      -- if set `host_header` is the original header to be preserved
      var.upstream_host = host_header or
          balancer_address.hostname..":"..balancer_address.port

Our kong instances are behind an ALB in AWS.  The end point only uses an IP restriction plugin. I'm not sure why we receive this error only 10 times out of 75,000 total, but it does seem that Kong should not fail in this instance - send an appropriate error message if the hostname is not set, or set the value to a default, not simply abort.

- Kong version: 0.10.3
- Operating System: Debian 8.9

Thanks!

**Comment by Tieske** [comment] 2017-12-29 23:51
Duplicate of https://github.com/Kong/kong/issues/2964

So please upgrade to `0.11.x`

**Closed** 2018-01-02 17:54 UTC
