### ISSUE TITLE
gRPC reflection in the grpc-gateway plugin

### ISSUE THREAD

**Issue by brian-scb** [Kong/kong#7710] opened 2021-08-13 16:09 UTC
### Enable ability to use gRPC reflection in the grpc-gateway plugin

Instead of providing a path to proto file, it would much easier if the plugin were able to take advantage of the [reflection protocol](https://github.com/grpc/grpc/blob/master/doc/server-reflection.md) to obtain the proto file

other tools capable of using reflection: [grpc-cli](https://github.com/grpc/grpc/blob/master/doc/command_line_tool.md), [Evans](https://github.com/ktr0731/evans)

**Comment by javierguerragiraldez** [comment] 2021-08-16 22:06
There have been a few proposals about how to avoid having to deploy the proto file with Kong, especially in the context of container images.  Options include:
1. specify a URL instead of a file path.  Kong would download it at startup.
2. include the whole content of the .proto file in the configuration.  Might be too heavy on declarative configurations, but workable if injected via the admin API.
3. this one: use gRPC reflection to pull the definitions from the service.

The first one (pull from an URL) is doable, but has little advantage, since it's hardly easier than making the file accessible, either by adding to a custom image, or by mounting a read-only volume with the required file(s).

Including in the database was proposed at first, but quickly dismissed when seeing not only the size of some .proto specs, but also the problem of adding imported definitions.  There was some possibility of precompiling into binary DescriptorProto bundles, but again, it results in many extra steps for little usability improvement.

gRPC reflection seems very tempting, especially since it's so easy to add on Golang gRPC services.  But the design of Nginx makes it surprisingly hard to initiate an HTTP/2 request that is not a redirection of the main request.  To have a Lua-initiated gRPC call would require an HTTP/2 client Lua library, which are still not stable enough.

Finally, remember that the .proto specification returned by a server via reflection describes the .proto file as it was when the server was compiled (or rather, when `protoc` compiler generated the gRPC/protoBuf stub code).  If the RESTish interface is added after that, the annotations required by this plugin to perform the transformation would not be there.  That means this option would probably help only for in-house services and not to expose third-party services.

In all, I don't want to discard any of these options, but so far all of them seem to provide limited benefit.

**Comment by brian-scb** [comment] 2021-08-16 22:54
Forgive me for spitballing here, I'm not super familiar with nginx, but could it be done like a write-though cache. Grab the protofile the first hit, cache it for subsequent, expire cache eventually?

**Comment by StarlightIbuki** [comment] 2023-10-11 06:23
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:23 UTC
Labels: task/feature, plugins/grpc-gateway
