### ISSUE TITLE
Odd Kong logs of HTTPStatus being set to 0? 

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#6611] opened 2020-11-30 15:17 UTC
### Summary

Seeing some odd HTTP Log tx's in our overall tx logs. Only 1,200+ of them usually in bursts last 7 days but they show a status of 0 and Kong access phase hitting a 5 second mark(This value correlates as it is also our DB timeout limit):

![image](https://user-images.githubusercontent.com/31913027/100627054-8897f080-32f4-11eb-9a59-0dff24546d6e.png)

BackendLatency -1 indicates we did not proxy for sure

```
{ [-]
   BackendLatency: -1
   ClientIP: 10.XXX.X.XX
   Consumer: opi.xxx.xxxxxxx
   GatewayHost: gateway.company.com
   GatewayPort: 443
   HTTPMethod: POST
   HTTPStatus: 0
   KongLatency: { [-]
     AccessTime: 5018
     BalancerTime: 0
     ReceiveTime: 0
     RewriteTime: 0
   }
   RequestSize: 1452
   ResponseSize: 0
   RoutingURL: myservice.company.com:443/api/enterprise/v2.0/service/log-requests
   ServiceName: rrt.service.stuff.v2
   TotalLatency: 5018
   Tries: { [-]
   }
   URI: /api/pdr/service/v2/log-requests
}
Show as raw text
host = gateway-company-dc.company.com source = kong-275-zx6hl sourcetype = AccessLog
```

Trying to talk with clients to figure out what kong "said" to these clients in response.. 

I am thinking that the way it's looking, when a possible DB timeout/error occurs this is the kinda HTTP Log Kong would produce? This proxy had (oauth2, acl, kong-spec-expose, rate-limiting, request-size-limiting) plugins on the route.

Ideally I would not think this specific proxy even needed to call the db though except once to cache resources... unsure why this happened unless maybe a fresh token was received another kong node initially generated and the time to query to check on that new token in this node exceeded the db timeout? First stab guess..

If so a db timeout log looks like this(does kinda feel like this?), I think Kong needs to correct the HTTP Status clients received, as well as the response size. So this can be classified as a bug I think. I don't think this is isolated to just 2.1.4 either, been around for prior versions I think(just mentioning the version we are currently on). 

My colleague @rsbrisci was also hypothesizing maybe Kong/Nginx was also just closing the connection L4 level so no status/response body was even there... but why would it have done that? Really wanna know what the client saw here. 

### Steps To Reproduce

1. Currently not sure. Maybe be able to produce a db timeout/error mid proxy call cause of a query made to the db?

### Additional Details & Logs

- Kong version 2.1.4

**Comment by StarlightIbuki** [comment] 2023-10-11 06:20
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:20 UTC
Labels: task/needs-investigation
