### ISSUE TITLE
`make test-integration` fails on the Mac

### ISSUE THREAD

**Issue by hishamhm** [Kong/kong#2802] opened 2017-08-14 18:38 UTC
### Summary

Integration tests fail when running locally on the Mac because of the recent change in which the prefix for installed rocks now lives inside the Kong cellar.

### Steps To Reproduce

1. Install Kong and its dependencies using Homebrew on macOS
2. Clone Kong repo: `git clone https://github.com/Mashape/kong`
3. Set up testing dependencies with `make dev`
4. Try to run integration tests with `make test-integration`: they will fail because /usr/local/opt/kong is deleted prior to running tests

**Comment by kikito** [comment] 2017-08-23 12:51
I've triaged the tests that provoke the issue:

* `spec/02-integration/02-cmd/02-start_stop_spec.lua @ 174`
* `spec/02-integration/05-proxy/09-balancer_spec.lua` this seems to fail completely - probably the setup triggers the condition.

By marking them as "pending", I have been able to run the integration tests several times on my machine without triggering the wrong behavior. Now I have to investigate how to fix it.

**Comment by thibaultcha** [comment] 2017-08-23 22:20
Strangely, I was not able to reproduce this issue with a Homebrew install on my side (even after having seen and investigated it from my own eyes a couple weeks ago). It seems to me like the integration tests already use the disposable tests prefix?

**Comment by hishamhm** [comment] 2017-08-23 22:27
When I looked at this problem, I added this hack to my local copy and ran the integration tests to see if any of them were trying to write outtside of servroot and that didn't seem to trigger

```diff
diff --git a/spec/helpers.lua b/spec/helpers.lua
index f93b90d2..e6eb3f64 100644
--- a/spec/helpers.lua
+++ b/spec/helpers.lua
@@ -857,6 +857,10 @@ end
 -- @name prepare_prefix
 local function prepare_prefix(prefix)
   prefix = prefix or conf.prefix
+  if not prefix:match("servroot") then
+    error("TEST NOT USING SERVROOT")
+  end
   exec("rm -rf " .. prefix .. "/*")
   return pl_dir.makepath(prefix)
 end
```

**Comment by thibaultcha** [comment] 2017-08-23 22:37
I did the same thing, didn't seem to be triggered on my end either

**Comment by thibaultcha** [comment] 2017-11-03 02:22
I think that if we were unable to replicate this, we should probably close this issue now? Has anyone been able to replicate?

**Comment by kikito** [comment] 2017-11-17 14:05
I am temptatively closing this down as I was not able to reproduce this in the last ~2 months or so.

**Closed by kikito** 2017-11-17 14:05 UTC
