### ISSUE TITLE
Balancer not invalidated when API is updated

### ISSUE THREAD

**Issue by thefosk** [Kong/kong#2581] opened 2017-05-30 23:42 UTC
The balancer is not being invalidated when the API `upstream_url` is being updated - which means that switching from a hostname to an IP address in the `upstream_url` will not invalidate the balancer and the timeouts values in the API object will not be respected.

**Comment by Tieske** [comment] 2017-06-07 09:22
@thefosk How do you reproduce this problem?

A specific balancer is not related to an api. The balancer is only related to the hostname used in the upstream url. No invalidation is required.

**Comment by p0pr0ck5** [comment] 2017-06-30 05:05
@thefosk any update? ^^

**Comment by Tieske** [comment] 2018-01-18 23:39
Cannot reproduce this. Closing.

**Comment by james-callahan** [comment] 2018-05-10 05:07
We think we replicated this today: add a target with an invalid domain. It will keep retrying to resolve the domain. Even after the upstream is deleted.

**Comment by Tieske** [comment] 2018-08-25 06:06
I still cannot reproduce.

I did:
```
$ http post :8001/upstreams name=tieske

$ http post :8001/upstreams/tieske/targets target=nonexxxisting.nl
# now there are repeating errors, which is as expected (30second retry interval)

$ http post :8001/upstreams/tieske/targets target=nonexxxisting.nl weight=0
# now retries stop again, as expected
```

closing again.

**Closed by Tieske** 2018-08-25 06:06 UTC
Labels: task/bug
