### ISSUE TITLE
how can i set limit_conn in Kong?

### ISSUE THREAD

**Issue by shinji3887** [Kong/kong#5778] opened 2020-04-13 14:57 UTC
I have read all over the docs and cannot find how to set connection limit in Kong
what I want to set is like below:
```bash
limit_conn_zone $binary_remote_addr zone=perip:10m;
limit_conn_zone $server_name zone=perserver:10m;

server {
    ...
    limit_conn perip 10;
    limit_conn perserver 100;
}
```
the origin docs is [here](http://nginx.org/en/docs/http/ngx_http_limit_conn_module.html)
can I set this parameter in services or upstreams?

**Comment by hutchic** [comment] 2020-04-13 16:20
nginx directives can't be specified per service or route and would be applied globally. Relevant documentation would be this page https://docs.konghq.com/2.0.x/configuration/#injecting-nginx-directives

**Comment by shinji3887** [comment] 2020-04-14 05:03
> nginx directives can't be specified per service or route and would be applied globally. Relevant documentation would be this page https://docs.konghq.com/2.0.x/configuration/#injecting-nginx-directives

thx!is this mean that I can only set connection limit with **nginx directives** and it would be applied **globally**?In nginx's configration file ,I can set this by different **location block**,is there any other way to set connection limit?

**Comment by shinji3887** [comment] 2020-04-24 13:55
I think I can use [lua-resty-limit-traffic](https://github.com/openresty/lua-resty-limit-traffic) module 桶get this work. But I don't know how to use this module in Kong, anyone has suggestion?

**Comment by StarlightIbuki** [comment] 2023-10-11 06:15
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:15 UTC
Labels: core/balancer
