### ISSUE TITLE
Request-transformer plugin incompatible after 0.9 to 0.10.3 upgrade

### ISSUE THREAD

**Issue by Tigraine** [Kong/kong#2630] opened 2017-06-16 12:46 UTC
### Summary

We just did a trial upgrade from 0.9 to 0.10.3. Thank god I did this on a new test setup to verify the upgrade path before doing it for the live environment.

It seems the field `rename` was added to the request-transformer plugin which is referenced in [1].
If the json in the database is not present or empty it will blow up with the following in error.log:

```
70#0: *242 lua entry thread aborted: runtime error: ...hare/lua/5.1/kong/plugins/request-transformer/access.lua:59: attempt to index local 'config_array' (a nil value)
stack traceback:
coroutine 0:
        ...hare/lua/5.1/kong/plugins/request-transformer/access.lua: in function '(for generator)'
        ...hare/lua/5.1/kong/plugins/request-transformer/access.lua:91: in function 'transform_headers'
        ...hare/lua/5.1/kong/plugins/request-transformer/access.lua:384: in function 'execute'
        ...are/lua/5.1/kong/plugins/request-transformer/handler.lua:12: in function 'access'
        /usr/local/share/lua/5.1/kong.lua:295: in function 'access'
        access_by_lua(nginx-kong.conf:94):2: in function <access_by_lua(nginx-kong.conf:94):1>, client: 10.112.16.104, server: kong, request: "GET /kong HTTP/1.1", host: "king-kong"
```

Kong API (GET `/plugins/<id>` continues to work but the rename is a empty object (`rename: {}`)

Since we use result-transformers to authenticate users upstream this broke everything for us.

We are using the official kong docker image with Cassandra3 as it's data store.

[1] : https://github.com/Mashape/kong/blob/0.10.3/kong/plugins/request-transformer/access.lua#L91

**Comment by Tieske** [comment] 2017-06-23 14:07
duplicate #2580

**Comment by ilucker** [comment] 2017-06-30 03:18
it should be reopened. the problem is with a particular field 'rename'.  we use cassandra and update to 0.10.3 broke everything for us as well.

**Comment by Tigraine** [comment] 2017-06-30 07:27
And tbh the fix is super simple. Do a check if the field exists before indexing into it

**Comment by Tieske** [comment] 2017-06-30 07:31
The fix, #2499, was postgres only. Reopening to investigate.

**Comment by sebastienc** [comment] 2018-02-28 15:55
Hi,

The migration in Cassandra doesn't seem to take into account the new rename action. I think the answer lies here:

https://github.com/Kong/kong/blob/0.10.4/kong/plugins/request-transformer/migrations/cassandra.lua#L12

I've looked at every tag/version until master and it isn't in there. Can someone confirm I understand this correctly? I'm willing to make a MR for it but I'm not really sure if I understand the mechanics of the migrations.

Regards,

Sebastien

**Comment by p0pr0ck5** [comment] 2019-01-12 03:46
Given the age and staleness of this issue, and the major rework that went into migrations for the release of 1.0, I'm closing this issue. If there's still a pending issue here that hasn't been addressed for a maintained version of Kong, please feel free to leave a note here and we can re-open this and look into it.

**Closed by p0pr0ck5** 2019-01-12 03:46 UTC
Labels: task/needs-investigation
