### ISSUE TITLE
Contradictory OAuth2 client_credentials documentation

### ISSUE THREAD

**Issue by Kitanotori** [Kong/kong#7424] opened 2021-06-07 09:31 UTC
### Summary
- OAuth2 plugin version: 2.1.x (latest)

Docs mention following:

> The Client Credentials flow will work out of the box, **without building any authorization page**. The clients will need to use the /oauth2/token endpoint to request an access token.

But also:

> **You must implement an authorization page** on your web application, that will talk with the plugin server-side. 

Source: https://docs.konghq.com/hub/kong-inc/oauth2/#client-credentials

Maybe issue with indentation (Authorization Code flow as subsection inside Client Credentials)? I feel the documentation for Client Credentials flow quite lacking.

Also another thing; we want to use our own token endpoint for generating access tokens, but I couldn't find information regarding how this could be achieved. Is this not supported by the plugin?

**Comment by jeremyjpj0916** [comment] 2021-06-21 06:15
> we want to use our own token endpoint for generating access tokens

You want kong to help generate these access tokens on a proxy path or you want a 3rd party OAuth2.0 server to generate and validate tokens and you want Kong to cache results of 3rd parties responses? OSS Kong has the oauth2 plugin to manage its own tokens. Only the enterprise "introspection" plugin can do 3rd party OAuth2.0 validation. Otherwise you will have to build your own(which I am actually doing now because I wanna run db-less but still support OAuth2.0 CC grant flow)

**Comment by StarlightIbuki** [comment] 2023-10-11 06:22
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:22 UTC
Labels: plugins/oauth2, core/docs
