### ISSUE TITLE
Error migrating Kong OSS from 2.8.3 to 3.1.1.

### ISSUE THREAD

**Issue by mayankmurari** [Kong/kong#11448] opened 2023-08-23 16:47 UTC
### Discussed in https://github.com/Kong/kong/discussions/11421

<div type='discussions-op-text'>

<sup>Originally posted by **mayankmurari** August 17, 2023</sup>
I am trying to migrate Kong from 2.8.3 to 3.1.1. Kong 3.1.1 pods are not coming up and below error is present in the logs.
Current Kong version is 2.8.3 with KIC 2.8.2 and Postgres DB.

```
 [emerg] 1#0: bind() to unix:/kong_prefix/worker_events.sock failed (98: Address in use)
 [notice] 1#0: try again to bind() after 500ms```</div>

**Comment by bungle** [comment] 2023-08-24 10:04
@mayankmurari, is it possible for you to test `3.4.0`, just to check if the issue has already been fixed? I remember we have done some changes there.

**Comment by mayankmurari** [comment] 2023-08-28 14:23
Hi @bungle 
I was able to upgrade Kong from 2.8.3 to 3.0.1 without any issues and I running with Kong 3.0.1 now.

After that I tried upgrading from 3.0.1 to 3.1.1 and got the same error.
```
2023/08/28 12:29:50 [emerg] 1#0: bind() to unix:/kong_prefix/worker_events.sock failed (98: Address in use)
nginx: [emerg] bind() to unix:/kong_prefix/worker_events.sock failed (98: Address in use)
2023/08/28 12:29:50 [notice] 1#0: try again to bind() after 500ms
```
Then as per you recommendation I tried upgrading to 3.4.0 from 3.0.1 and it worked. So now as per Kong documentation below is the recommended upgrade path and if we jump from 2.8.3-->3.0.1-->3.40 is it still recommended?

2.8.x	Traditional	No	Upgrade to 3.1.1.3, upgrade to 3.2.x, upgrade to 3.3.x, and then upgrade to 3.4.x.
[(https://docs.konghq.com/gateway/latest/upgrade/)]

**Comment by jeremyjpj0916** [comment] 2023-08-28 16:19
Would also be interested to know if docs vs whats actually feasible are not in order w minimal stepping stones. maybe 2.8.x latest to 3.1.1.x to 3.4.0 possible?

**Comment by mayankmurari** [comment] 2023-09-05 12:16
Updating this thread with one more observation which we see while upgrading to 3.0.1 from 2.8.3 or downgrading from 3.0.1 to 2.8.3.
In both the cases we are observing 404 on Kong routes while our pods are migrating. Also there are no other errors in kong logs during this time and after few minutes all the 404s are automatically resolved.
Also we do observe Kong response headers showing version as 2.7.1 intermittently while migrating from 2.8.3 to 3.0.1 and vice versa. Once migration is over we do not see 2.7.1 version in response headers.

**Comment by hanshuebner** [comment] 2023-10-09 07:33
@outsinre Do you have an answer for @jeremyjpj0916 ?

**Comment by outsinre** [comment] 2023-10-09 07:36
@hanshuebner from my memory, this is a bug. Probably upgrading to newer versions can help.

Will locate the fix commit.

**Comment by hanshuebner** [comment] 2023-10-09 07:37
@outsinre So you mean upgrade from 2.8.3 to 2.8.4 and then to 3.4.1?

**Comment by outsinre** [comment] 2023-10-09 07:50
Seems already fixed in `3.0`: https://github.com/Kong/kong/pull/9254. The root cause is the previous running socket file is not removed.

This is weird. If it is fixed in `3.0`, why not `3.1.1`.

**Comment by Tieske** [comment] 2023-10-09 08:10
seems related to internal ticket: https://konghq.atlassian.net/browse/KAG-328

**Comment by mayankmurari** [comment] 2023-10-09 08:25
@outsinre 
I do see issue with 3.0.1 as well sometimes and after restarting kong pod it goes away.
Tried same with 3.2.2 and I see dangling sockets are getting cleaned up and "address in use" error is not coming.

**Closed** 2023-10-25 08:28 UTC
