### ISSUE TITLE
Consistent hashing misconfiguration error is not helpful

### ISSUE THREAD

**Issue by rainest** [Kong/kong#9437] opened 2022-09-16 00:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.0.0

### Current Behavior

An upstream with 400 slots, 20 weight 100 targets, and consistent hashing will fail to select a target using the balancer. All requests that use this upstream will return a `{"message":"failure to get a peer from the ring-balancer"}`. 

At level info/notice, this misconfiguration emits a single error log when configuration is applied:

```
2022/09/15 23:45:17 [crit] 1116#0: *8 [lua] consistent_hashing.lua:108: afterHostUpdate(): consistent hashing balancer requires more entries to add the number of hosts requested, please increase the wheel size, context: ngx.timer
```
At level debug, individual requests will further emit:
```
2022/09/15 23:52:35 [debug] 1115#0: *336 [lua] consistent_hashing.lua:136: getPeer(): trying to get peer with value to hash: [10.244.0.1]
```
This looks like a standard log that does not indicate any sort of failure, however, just that the balancer is executing in consistent hashing mode.

Increasing the wheel size, in the strictest sense (e.g. by setting slots to 401), does not fix the issue.

[config.yaml.txt](https://github.com/Kong/kong/files/9579618/config.yaml.txt) demonstrates the issue when loaded into a DB-less instance.

### Expected Behavior

The log indicates the actual change necessary using terminology consistent with the admin API. For example:

```
[lua] consistent_hashing.lua:108: afterHostUpdate(): consistent hashing balancer requires a higher slots value on upstream "echo.default.80.svc" to add the number of targets requested, please increase slots to X or higher, context: ngx.timer
```
Random guessing tells me that 4000 is high enough, but ideally the log would just indicate the minimum value.

### Steps To Reproduce

```markdown
1. Create an upstream with 400 slots.
2. Add 20 targets with weight 100 to the upstream.
3. Configure a route and service using this upstream.
4. Send a request through the route.

Applying the attached config and sending a request to `/foo` should replicate the issue fine even though the targets won't be available, since the failure is decided before talking to any target.
```

### Anything else?

This was found while writing test configuration for the ingress controller. It's a possible risk for us (though apparently one that hasn't caused problems yet, so maybe not that risky?) since we choose weight automatically (AFAIK it's always 100) and don't usually instruct users to set slots. Users shouldn't have to set `slots` in most cases, however: the controller should be able to update it automatically to account for an increased target count after autoscaling.

I would update the log here and add that automatic `slots` selection in the controller, but I'm not actually sure of how the math breaks down. https://github.com/Kong/kong/blob/3.0.0/kong/runloop/balancer/consistent_hashing.lua#L84-L115 and https://github.com/Kong/kong/blob/3.0.0/kong/runloop/balancer/consistent_hashing.lua#L212-L219 are closest to the actual error, but I don't understand the relation between the internal points and the target count and target weights. As such, I'm looking for a formula that will give me the minimum value so I can use that as a floor value if we have no upstream configuration or it's below the minimum.

**Comment by Tieske** [comment] 2022-09-19 08:14
Agreed that the message is not helpful. That said; why did you reduce the size to begin with? according to docs (https://docs.konghq.com/gateway/latest/admin-api/#upstream-object) the default size is 10000. So 400 is very small.

**Comment by rainest** [comment] 2022-09-20 22:21
We had a guide that chose a very bad example value (10). I've updated that to the default. We'd still want to know the math though, since our target count is dynamic--probably much less likely to hit the ceiling at 10000, but not impossible.

**Comment by StarlightIbuki** [comment] 2023-10-11 08:33
Hi. It feels like the issue is solved. I'm closing the ticket, but please feel free to reopen if that's not the case or you have further concerns.

**Closed by StarlightIbuki** 2023-10-11 08:33 UTC
Labels: area/ingress-controller, core/balancer
