### ISSUE TITLE
"Disable" Route resource in Kong option.

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#7662] opened 2021-08-06 04:44 UTC
### Summary

Similar to being able to disable plugins, I think it would be neat to be able to disable a route resource if somehow that route caused impact to a customer vs having to delete it to resolve say a path conflict etc. 

This feature would need to cause a rebuild of the router table too as well in bg.

**Comment by Tieske** [comment] 2021-08-06 08:45
duplicate of https://github.com/Kong/kong/issues/1279

This is an old request...

**Closed by Tieske** 2021-08-06 08:45 UTC

**Comment by jeremyjpj0916** [comment] 2021-08-06 14:03
Ah, old request was closed because Kong didn't see value in it it I suppose. I was searching by open before I posted.

**Comment by Tieske** [comment] 2021-08-06 17:35
no no, there is value, it was just moved into a discussion
