### ISSUE TITLE
Consul DNS cannot work with dns_resolve?

### ISSUE THREAD

**Issue by iam-merlin** [Kong/kong#2574] opened 2017-05-29 21:38 UTC
### Summary
When I set the kong configuration with a dns_resolve to consul DNS (8600 or 53), kong will not work and the following error is shown on (`HTTP 500`) `http://localhost:8001/status` (or other endpoint) : `{"message":"An unexpected error occurred"}`

On the other hand... the DNS server is reachable (I can ping it, dig it and resolv) :

```
[root@0d3b3d385a3b /]# dig @172.18.0.2 -p 53 another.service.consul

; <<>> DiG 9.9.4-RedHat-9.9.4-38.el7_3.3 <<>> @172.18.0.2 -p 53 another.service.consul
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42931
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;another.service.consul.		IN	A

;; ANSWER SECTION:
another.service.consul.	0	IN	A	172.18.0.7

;; Query time: 1 msec
;; SERVER: 172.18.0.2#53(172.18.0.2)
;; WHEN: Mon May 29 21:35:03 UTC 2017
;; MSG SIZE  rcvd: 56
```

In the kong logs there is not a lot of informations but something wrong is happening :
```
2017/05/29 21:26:42 [error] 217#0: *1565 [lua] responses.lua:107: send_HTTP_INTERNAL_SERVER_ERROR(): [postgres error] [toip() name lookup failed]: dns server error; 2 server failure, client: 127.0.0.1, server: kong, request: "GET / HTTP/1.1", host: "localhost:8000"
2017/05/29 21:26:42 [error] 217#0: *1568 [lua] responses.lua:107: [postgres error] [toip() name lookup failed]: dns server error; 2 server failure, client: 127.0.0.1, server: kong_admin, request: "GET /status HTTP/1.1", host: "localhost:8001"
2017/05/29 21:26:42 [error] 217#0: *1572 [lua] certificate.lua:15: log(): [ssl] [postgres error] [toip() name lookup failed]: dns server error; 2 server failure, context: ssl_certificate_by_lua*, client: 127.0.0.1, server: 0.0.0.0:8443
2017/05/29 21:26:42 [crit] 217#0: *1566 SSL_do_handshake() failed (SSL: error:1408A179:SSL routines:ssl3_get_client_hello:cert cb error) while SSL handshaking, client: 127.0.0.1, server: 0.0.0.0:8443
```

### Additional Details & Logs

- Kong version : 0.10.3 (same with others version)
- Latest Docker image
- With --vv I can see that the address is set on the dns resolver is good : `2017/05/29 21:36:09 [debug] dns_resolver = {"172.18.0.2"}`
- Docker consul used : `https://hub.docker.com/_/consul/` (latest/0.8.3)

I previously tested `Progrium/Consul` and I've the same issue that's why I move to the official repository. Don't know why this error is happening again... if at least I can have more informations I'll be able to debug and fix kong or consul... now, I'm stucked

**Comment by Tieske** [comment] 2017-05-30 13:35
can you try again with `export KONG_LOG_LEVEL=debug` ? and check the `error.log` file again

**Comment by iam-merlin** [comment] 2017-05-30 17:13
```
2017/05/30 17:08:28 [debug] 318#0: *4664 [lua] client.lua:531: lookup(): [dns-client] querying 'another.service.consul' for type 33 took 19.999980926514
2017/05/30 17:08:28 [debug] 318#0: *4664 [lua] client.lua:574: lookup(): [dns-client] querying 'another.service.consul' for type 33: entries 0 error 3 name error
2017/05/30 17:08:28 [debug] 318#0: *4664 [lua] client.lua:531: lookup(): [dns-client] querying 'another.service.consul' for type 1 took 17.999887466431
2017/05/30 17:08:28 [debug] 318#0: *4664 [lua] client.lua:574: lookup(): [dns-client] querying 'another.service.consul' for type 1: entries 0 error 3 name error
2017/05/30 17:08:28 [debug] 318#0: *4664 [lua] client.lua:531: lookup(): [dns-client] querying 'another.service.consul' for type 28 took 22.000074386597
2017/05/30 17:08:28 [debug] 318#0: *4664 [lua] client.lua:574: lookup(): [dns-client] querying 'another.service.consul' for type 28: entries 0 error 3 name error
2017/05/30 17:08:28 [debug] 318#0: *4664 [lua] client.lua:531: lookup(): [dns-client] querying 'another.service.consul' for type 5 took 19.999980926514
2017/05/30 17:08:28 [debug] 318#0: *4664 [lua] client.lua:574: lookup(): [dns-client] querying 'another.service.consul' for type 5: entries 0 error 3 name error
2017/05/30 17:08:28 [error] 318#0: *4664 [lua] balancer.lua:304: balancer_execute(): name resolution failed for 'another.service.consul': dns server error; 3 name error, client: 172.18.0.1, server: kong, request: "GET /users HTTP/1.1", host: "localhost:8000"
```


For memo (and in this retry), 
Config (dns_resolver part) :
```
dns_resolver = 172.18.0.3:8600
```

Dig :
```
[root@b9933a5178f1 /]# dig @172.18.0.3 -p 8600 another.service.consul SRV

; <<>> DiG 9.9.4-RedHat-9.9.4-38.el7_3.3 <<>> @172.18.0.3 -p 8600 another.service.consul SRV
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27798
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;another.service.consul.		IN	SRV

;; ANSWER SECTION:
another.service.consul.	0	IN	SRV	1 1 4000 ac120007.addr.dc1.consul.

;; ADDITIONAL SECTION:
ac120007.addr.dc1.consul. 0	IN	A	172.18.0.7

;; Query time: 1 msec
;; SERVER: 172.18.0.3#8600(172.18.0.3)
;; WHEN: Tue May 30 17:12:25 UTC 2017
;; MSG SIZE  rcvd: 94
```

**Comment by depay** [comment] 2017-06-05 01:33
it may be a bug of consul.

1. dnslib req SRV record of `another.service.consul`, consul return the right result `ac120007.addr.dc1.consul:xxx`;
2. dnslib req SRV record of `ac120007.addr.dc1.consul`, as RFC, consul should return something like `no such record`, but it returns the A record, which may be regarded as an ERROR and dnslib won't try querying it any more.

**Comment by Tieske** [comment] 2017-06-07 09:35
if you look at the logs:
```
2017/05/30 17:08:28 [debug] 318#0: *4664 [lua] client.lua:531: lookup(): [dns-client] querying 'another.service.consul' for type 33 took 19.999980926514
2017/05/30 17:08:28 [debug] 318#0: *4664 [lua] client.lua:574: lookup(): [dns-client] querying 'another.service.consul' for type 33: entries 0 error 3 name error
```
type 33 is SRV record, result: `3 name error`

next up:
```
2017/05/30 17:08:28 [debug] 318#0: *4664 [lua] client.lua:531: lookup(): [dns-client] querying 'another.service.consul' for type 1 took 17.999887466431
2017/05/30 17:08:28 [debug] 318#0: *4664 [lua] client.lua:574: lookup(): [dns-client] querying 'another.service.consul' for type 1: entries 0 error 3 name error
```
type 1 is A record, result: `3 name error`

next up:
```
2017/05/30 17:08:28 [debug] 318#0: *4664 [lua] client.lua:531: lookup(): [dns-client] querying 'another.service.consul' for type 28 took 22.000074386597
2017/05/30 17:08:28 [debug] 318#0: *4664 [lua] client.lua:574: lookup(): [dns-client] querying 'another.service.consul' for type 28: entries 0 error 3 name error
```
type 28 is AAAA record, result: `3 name error`

next up:
```
2017/05/30 17:08:28 [debug] 318#0: *4664 [lua] client.lua:531: lookup(): [dns-client] querying 'another.service.consul' for type 5 took 19.999980926514
2017/05/30 17:08:28 [debug] 318#0: *4664 [lua] client.lua:574: lookup(): [dns-client] querying 'another.service.consul' for type 5: entries 0 error 3 name error
```
type 5 is CNAME record, result: `3 name error`

By now all queries failed, so now it returns the final error:
```
2017/05/30 17:08:28 [error] 318#0: *4664 [lua] balancer.lua:304: balancer_execute(): name resolution failed for 'another.service.consul': dns server error; 3 name error, client: 172.18.0.1, server: kong, request: "GET /users HTTP/1.1", host: "localhost:8000"
```

are you sure that `another.service.consul` is the fully qualified name? Considering the A record in your `dig` output being `ac120007.addr.dc1.consul`. So maybe `another.service.dc1.consul`?? please verify with the consul docs.

Also, what does `/etc/resolv.conf` look like?

**Comment by iam-merlin** [comment] 2017-06-07 10:13
@Tieske I'll try with `another.service.dc1.consul` butI'm sure I already test. Usually `another.service.consul` is a shortcut for the first datacenter with name `another.service.dc1.consul`. I retry and come back soon. Thx for helping me.

**Comment by iam-merlin** [comment] 2017-06-07 10:14
btw, I never tried. Kong can loadbalance using dns providing by `resolv.conf`?

**Comment by Tieske** [comment] 2017-06-08 13:50
Kong will by default use the settings in `resolv.conf`, currently implementation for `search` and `ndots` options is on its way (hence the requirement until then to use fully qualified names)

**Comment by adrianlop** [comment] 2017-10-12 11:57
hi, this is still failing in Kong v0.11 for me
I have `app1.service.consul`registered in consul and sometimes Kong will throw an error:
```
2017/10/12 11:48:38 [error] 15107#0: *480 [lua] balancer.lua:310: execute(): name resolution failed for 'app1.service.consul': dns server error: 3 name error, client: 10.212.77.53, server: kong, request: "GET /xxx/v2/api-docs HTTP/1.1", host: "xxx.com"
```

- First I didnt have defined the port in the consul service, so the SRV request returned port 0.
- After that, I configured the 8080 port for the service, SRV request started returning port 8080 properly, but Kong still fails
I've done a few hundreds of requests to that exact record using `dig` and it didnt fail once.
Kong resolution is failing 80% of the times.

The bad thing is that the behaviour is not consistent, I mean, it should fail 100% of times if something is wrong with the DNS, but is not, the API works sometimes.

Also, I've enabled debug logs in Kong but no useful info.
Any update on this? thanks.

**Comment by depay** [comment] 2017-10-13 02:10
@adrianlop you'd better looking for msg in consul query log

**Comment by Tieske** [comment] 2017-10-14 17:21
@adrianlop the error `3 name error` is not an error generated by Kong, but it is the actual response send by the DNS server. So from a Kong perspective it gets a proper/valid answer from the DNS server, it's just that the answer is "I don't know any system by that name".

What are your dns related setting in the Kong config file? and what's in your `/etc/resolv.conf` file?

**Comment by adrianlop** [comment] 2017-10-16 11:54
thanks for the responses guys @depay @Tieske
I will be taking a look at this when I switch back to Consul DNS again. I started pointing to a Route53 entry (AWS) and works OK.
please dont close the issue yet.

**Comment by Tieske** [comment] 2017-10-19 01:23
also: note that as a `3 name error` is considered a valid response, it will also be cached by Kong. In Kong 0.11 this is controlled by the `dns_not_found_ttl` setting, which defaults to 30 seconds. This might explain your 80% failures.

**Comment by thibaultcha** [comment] 2017-11-02 04:37
Hmmm this seems to have widely derived from the original issue reported by @iam-merlin... 

I would recommend upgrading to Kong 0.11.1 (our current latest), and thoroughly reviewing your DNS nameservers, records, and OS configurations... WE have found multiple cases of mis-configured DNS settings badly reflecting on Kong and tricking users into believing Kong was mis-behaving, when really, the root causes were DNS mis-configurations.

If you are encountering what you are *certain* is a bug, please do open another issue :) Otherwise, please do consult our other community support channels like Gitter or the mailing list, as we wish to reserve GitHub issues for bug reports only. Thank you!

**Closed by thibaultcha** 2017-11-02 04:37 UTC

**Comment by faizalpribadi** [comment] 2017-12-27 15:34
By default consul working on port `:8600`, you must set on kong dns_resolver `dns_resolver: HOST:8600`, for example, when you are running on localhost, you must check nameserver on `/etc/resolv.conf` you must set to localhost, this is working on `Kong >= 0.10.0` , after all , check the srv consul like this , example `dig @127.0.0.1 -p 8600 go-svc-1.service.consul`, and register on kong api as upstream_url like this `http://go-svc-1.service.consul`, i hope this help 😄

**Comment by adrianlop** [comment] 2017-12-28 01:22
@faizalpribadi thanks mate. we're running it behind `dnsmasq` so we can use :53 but I'll try that at some point too 👍

**Comment by DreamAndDead** [comment] 2018-06-06 02:31
any update?

**Comment by flowdopip** [comment] 2020-04-11 19:06
Hi all, im trying to do exactly the same, but is not working

kong 2.0.3
Consul:1.7.2
error

```
2020/04/10 14:49:08 [error] 27#0: *2072 [lua] balancer.lua:921: execute(): DNS resolution failed: dns server error: 2 server failure. Tried: ["(short)orders:(na) - cache-miss","orders:1 - cache-miss/scheduled/querying/dns server error: 2 server failure","orders:33 - cache-miss/scheduled/querying/dns server error: 2 server failure","orders:5 - cache-miss/scheduled/querying/dns server error: 2 server failure"], client: 172.16.238.1, server: kong, request: "GET /api/logistics/orders/3190d7b9-15c7-4312-840a-4e2fe023378a/deliveries HTTP/1.1", host: "localhost:8000"
```

consul:
    image: consul:latest
    command: consul agent -server -dev -log-level=debug -bootstrap -ui -client=0.0.0.0
    #-dns-port 53 
    hostname: consul
    container_name: consul
    networks:
      app_net:
        ipv4_address: 172.16.238.2

 kong:
    image: kong:2.0.3
    depends_on:
      - consul
    command: >
     sh -c "sh /docker-entrypoint.sh && kong start -c /etc/kong/kong.conf -vv docker-start"
    networks:
      app_net:
        ipv4_address: 172.16.238.4
    environment: 
      - KONG_DNS_RESOLVER=172.16.238.2:8600
    ports:

what is missing?

**Comment by Tieske** [comment] 2020-04-12 13:06
@flowdopip the error is `2 server failure` so check the Consul logs?

**Comment by flowdopip** [comment] 2020-04-13 07:04
I add the flag to consul -recursor 127.0.0.11 and it works, but I don´t know if is the best solution.

command: consul agent -server -recursor 127.0.0.11 -dev -log-level=debug -bootstrap -node -ui -client=0.0.0.0

recursors This flag provides addresses of upstream DNS servers that are used to recursively resolve queries if they are not inside the service domain for Consul. For example, a node can use Consul directly as a DNS server, and if the record is outside of the "consul." domain, the query will be resolved upstream. As of Consul 1.0.1 recursors can be provided as IP addresses or as go-sockaddr templates. IP addresses are resolved in order, and duplicates are ignored.

```
services:
- name: orders
  url: http://orders.service.dc1.consul/api/
  protocol:
  - http
  routes:
  - name: orders
    paths:
    - /(?i)api/logistics/
```

**Comment by Tieske** [comment] 2020-04-13 07:20
@flowdopip the error in your previous post suggests you're resolving the name `orders`. Whereas it apparently does not try alternative domains/searches. In your last snippet there is `orders.service.dc1.consul`.

Kong will use what it finds specified in `resolv.conf` you might want to update that file. See `domain`, `search` and `ndots` options.
