### ISSUE TITLE
After running Kong dbless, Kong fails to do a db_import

### ISSUE THREAD

**Issue by Tieske** [Kong/kong#9365] opened 2022-09-01 09:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.1

### Current Behavior

```
# have a local config file; ./kong.yml available
docker run -it --rm -v $(pwd)/kong.yml:/kong.yml kong:2.8.1 /bin/sh
unset KONG_NGINX_DAEMON

kong config db_import /kong.yml
# Error: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: connection refused
#
#   Run with --v (verbose) or --vv (debug) for more details

KONG_DATABASE=off KONG_DECLARATIVE_CONFIG=/kong.yml kong start
# Kong started

kong stop
# Kong stopped

kong config db_import /kong.yml
# Error: 'kong config db_import' only works with a database.
# When using database=off, reload your declarative configuration
# using the /config endpoint.
# 
#   Run with --v (verbose) or --vv (debug) for more details
```

### Expected Behavior

```
# Error: 'kong config db_import' only works with a database.
# When using database=off, reload your declarative configuration
# using the /config endpoint.
```
was unexpected, since the node was already stopped, and I didn't specify `database=off`. The same error as before was expected;
```
# Error: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: connection refused
#
#   Run with --v (verbose) or --vv (debug) for more details
```

### Anything else?

The workaround is to use a `prepare` first
```
kong prepare
kong config db_import /kong.yml
# Error: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: connection refused
#
#   Run with --v (verbose) or --vv (debug) for more details
```

It seems that the `config db_import` command is looking at the configuration file stored in the prefix. Instead of parsing the actual config passed.
This makes sens if the import command is expected to run against a running instance of Kong. But in this case Kong was not running, hence it should have never used that file, and only the actual passed in config.

**Comment by samugi** [comment] 2022-09-01 14:04
I think it's because [here](https://github.com/Kong/kong/blob/038cde8a86e329d868b792746c6560eaf92a50a8/kong/cmd/config.lua#L56-L59) when we load `<prefix>/.kong_env`, the previous value of `database` is loaded in `conf`, then [this](https://github.com/Kong/kong/blob/038cde8a86e329d868b792746c6560eaf92a50a8/kong/cmd/config.lua#L63-L67) happens.

**Comment by bungle** [comment] 2022-09-01 14:05
Isn't it expected?

**Comment by bungle** [comment] 2022-09-01 14:07
I am pretty sure almost all Kong commands try to load that env file.

**Comment by bungle** [comment] 2022-09-01 14:10
I think we need to draw a map of each kong commands that what they do.
- do they use prefix
- do they read .kong_env
- do they replace files in prefix or leave them untouched
- do they delete prefix
- how they behave when kong conf is given as parameter or env vars

**Comment by Tieske** [comment] 2022-09-01 15:14
maybe [this code](https://github.com/Kong/kong/blob/038cde8a86e329d868b792746c6560eaf92a50a8/kong/cmd/config.lua#L56-L59) should actually check not the existence of the file, but ALSO if the node is running.

**Comment by StarlightIbuki** [comment] 2023-10-11 06:36
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:36 UTC
Labels: core/configuration
