### ISSUE TITLE
Cannot see route which blocks deleting service

### ISSUE THREAD

**Issue by mirkoszy** [Kong/kong#4575] opened 2019-05-06 16:27 UTC
I have added some service, and route associated with this service.

I wanted to delete service but I obtain the following error 

> {
    "fields": {
        "@referenced_by": "routes"
    },
    "name": "foreign key violation",
    "code": 4,
    "message": "an existing 'routes' entity references this 'services' entity"
}

I cannot find route which blocks this operation. I cannot see it using admin API GET command neither via Admin GUI (I am using kong enterprise edition).

How can I delete this service  and "ghost" route?

**Comment by hbagdi** [comment] 2019-05-06 18:31
@mirkoszy You can list the routes associated with a service using `GET /services/{service_name_or_id}/routes`. Do you see any routes listed on that endpoint?
Also, which version of Kong Enterprise are you using?

**Comment by ninanung** [comment] 2019-05-07 06:35
I think i have same issue. I'm using `0.34-1-enterprise-edition` by Docker and can't see all the routes in GUI. I'm checking logs from docker. This is the logs.
```
2019/05/07 06:29:19 [error] 55#0: *18623224 lua coroutine: runtime error: /usr/local/share/lua/5.1/kong/core/handler.lua:139: attempt to compare number with userdata
stack traceback:
coroutine 0:
        [C]: in function 'sort'
        /usr/local/share/lua/5.1/kong/core/handler.lua:134: in function 'build_router'
        /usr/local/share/lua/5.1/kong/api/routes/routes.lua:86: in function 'rebuild_routes'
        /usr/local/share/lua/5.1/kong/api/routes/routes.lua:102: in function </usr/local/share/lua/5.1/kong/api/routes/routes.lua:101>
115.178.87.71 - - [07/May/2019:06:29:19 +0000] "GET /default/routes?size=100 HTTP/1.1" 500 54 "http://115.178.76.48:8002/default/routes" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
coroutine 1:
        [C]: in function 'resume'
        /usr/local/share/lua/5.1/lapis/application.lua:393: in function 'handler'
        /usr/local/share/lua/5.1/lapis/application.lua:130: in function 'resolve'
        /usr/local/share/lua/5.1/lapis/application.lua:161: in function </usr/local/share/lua/5.1/lapis/application.lua:159>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/lapis/application.lua:159: in function 'dispatch'
        /usr/local/share/lua/5.1/lapis/nginx.lua:215: in function 'serve_admin_api'
        content_by_lua(nginx-kong.conf:304):2: in function <content_by_lua(nginx-kong.conf:304):1>, client: 115.178.87.71, server: kong_admin, request: "GET /default/routes?size=100 HTTP/1.1", host: "115.178.76.48:8001", referrer: "http://115.178.76.48:8002/default/routes"
2019/05/07 06:29:19 [error] 55#0: *18623224 [lua] init.lua:146: handle_error(): /usr/local/share/lua/5.1/lapis/application.lua:397: /usr/local/share/lua/5.1/kong/core/handler.lua:139: attempt to compare number with userdata
stack traceback:
        [C]: in function 'sort'
        /usr/local/share/lua/5.1/kong/core/handler.lua:134: in function 'build_router'
        /usr/local/share/lua/5.1/kong/api/routes/routes.lua:86: in function 'rebuild_routes'
        /usr/local/share/lua/5.1/kong/api/routes/routes.lua:102: in function </usr/local/share/lua/5.1/kong/api/routes/routes.lua:101>

stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/lapis/application.lua:397: in function 'handler'
        /usr/local/share/lua/5.1/lapis/application.lua:130: in function 'resolve'
        /usr/local/share/lua/5.1/lapis/application.lua:161: in function </usr/local/share/lua/5.1/lapis/application.lua:159>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/lapis/application.lua:159: in function 'dispatch'
        /usr/local/share/lua/5.1/lapis/nginx.lua:215: in function 'serve_admin_api'
        content_by_lua(nginx-kong.conf:304):2: in function <content_by_lua(nginx-kong.conf:304):1>, client: 115.178.87.71, server: kong_admin, request: "GET /default/routes?size=100 HTTP/1.1", host: "115.178.76.48:8001", referrer: "http://115.178.76.48:8002/default/routes"
```

**Comment by mirkoszy** [comment] 2019-05-07 08:04
I am using version 0.34. I tried to list the routes associated with that service and there is no route.

**Comment by ninanung** [comment] 2019-05-07 08:11
In my case, after i create a second new route with GUI, routes just gone. I re-installed the server because of this issue and same problem occurred again.

**Comment by mirkoszy** [comment] 2019-05-07 13:07
I cannot delete deployment, especially cassandra DB. Do you have any idea how to solve this issue?

**Comment by RobSerafini** [comment] 2019-05-07 20:33
In 0.34 there is the concept of workspaces, and there is a workspace_entities table that contains references to the entities and their workspaces. Since kong does not use transactions, there is the possibility that a record in this table was orphaned. There is a row created in the workspace_entities table for each unique field an entity contains.

You can check the contents of the table with the following Admin API endpoint (assuming you did not specify some other workspace):

`:8001/workspaces/default/entities`

If you compare the uuid's for the routes in this table with what is found in your routes table, you can clean up the orphans with a DELETE request like: 

`:8001/workspaces/default/entities/<UUID>`

Hopefully this helps.

**Comment by RobSerafini** [comment] 2019-05-08 18:00
It sounds like you may have the opposite problem from the one I described. The consumer or route entity got left behind when the workspace entities entry was deleted. This would prevent you from seeing the route in the admin api. You will have to go into your database and find the consumer where username='foo' or routes where service_id = <UUID> and remove them from the consumers and routes table.

**Comment by bungle** [comment] 2019-12-20 22:42
As this seems to be relating to Kong Enterpise, I will close this. If you can provide a way we can reproduce it on Kong, please reopen.

**Closed by bungle** 2019-12-20 22:42 UTC
