### ISSUE TITLE
CPU high when update(delete and add) targets

### ISSUE THREAD

**Issue by vaxilicaihouxian** [Kong/kong#7654] opened 2021-08-04 02:48 UTC
### Summary
- Kong version 2.2.2
- A concise summary of the bug.

### Steps To Reproduce

1. create a service and a upstream
2. add 200 targets to this upstream
3. send some requests to this service
4. delete and add target for this upstream

### Additional Details & Logs
![image](https://user-images.githubusercontent.com/8603593/128114008-25cece21-b086-45f0-8627-912f533e5154.png)

production node's admin-error.log:
```
#admin-error.log
2021/08/04 02:45:09 [error] 91#0: *5414267 [lua] healthcheck.lua:1104: log(): [healthcheck] (1bdcdd5c-ecbc-4cb3    -b271-c5c4a3e03f56:xxxxx.xxxxx) failed to release lock 'lua-resty-healthcheck:1bdcdd5c-ecbc-4cb3-b271-c5c4a3e03    f56:xxx.xxxxx.xxxx:target_list_lock': unlocked, client: xx.xx.xx.xx, server: kong_admin, request: "GET /upstrea    ms/xxxx/targets?size=2000 HTTP/1.1", host: "xxx"
```

**Comment by vaxilicaihouxian** [comment] 2021-08-05 07:54
I found that my version is 2.2.2.
Anyone helps?

**Comment by vaxilicaihouxian** [comment] 2021-08-08 07:14
kong version is 2.2.2
I do some test:
1. make a shell to add / del targets in a loop:
```shell
#!/bin/bash
for i in {1..100}
do
  sh del.sh
  sh add.sh
  sleep 2
done
```
```shell
#!/bin/bash
for a in `cat ip.txt`
do
  curl --location --request POST '127.0.0.1:8001/upstreams/slef/targets' \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data-urlencode "target=$a:8879"
done
```
```shell
#!/bin/bash
for a in `cat ip.txt`
do
  curl --location --request DELETE "127.0.0.1:8001/upstreams/slef/targets/$a:8879"
done
```
2. monitor CPU:
![image](https://user-images.githubusercontent.com/8603593/128624118-81f452c9-5551-417b-8d0f-64b8f63781d6.png)

3. set kong's log_level to debug
```
log_level=debug
```
4. collect the log:
a lot of lines
```
2021/08/08 15:12:50 [debug] 4615#0: *98330 [lua] events.lua:211: do_event_json(): worker-events: handling event; source=mlcache, event=mlcache:invalidations:kong_core_db_cache, pid=4617, data=balancer:targets:dce2fc1a-03f0-4ede-b704-70e7a422170f
2021/08/08 15:12:50 [debug] 4615#0: *98330 [lua] events.lua:211: do_event_json(): worker-events: handling event; source=mlcache, event=mlcache:invalidations:kong_core_db_cache, pid=4617, data=balancer:targets:dce2fc1a-03f0-4ede-b704-70e7a422170f
2021/08/08 15:12:50 [debug] 4615#0: *98330 [lua] events.lua:211: do_event_json(): worker-events: handling event; source=mlcache, event=mlcache:invalidations:kong_core_db_cache, pid=4617, data=balancer:targets:dce2fc1a-03f0-4ede-b704-70e7a422170f
2021/08/08 15:12:50 [debug] 4615#0: *98330 [lua] events.lua:211: do_event_json(): worker-events: handling event; source=mlcache, event=mlcache:invalidations:kong_core_db_cache, pid=4617, data=balancer:targets:dce2fc1a-03f0-4ede-b704-70e7a422170f
2021/08/08 15:12:50 [debug] 4615#0: *98330 [lua] events.lua:211: do_event_json(): worker-events: handling event; source=mlcache, event=mlcache:invalidations:kong_core_db_cache, pid=4617, data=balancer:targets:dce2fc1a-03f0-4ede-b704-70e7a422170f
2021/08/08 15:12:50 [debug] 4615#0: *98330 [lua] events.lua:211: do_event_json(): worker-events: handling event; source=mlcache, event=mlcache:invalidations:kong_core_db_cache, pid=4617, data=balancer:targets:dce2fc1a-03f0-4ede-b704-70e7a422170f
2021/08/08 15:12:50 [debug] 4615#0: *98330 [lua] events.lua:211: do_event_json(): worker-events: handling event; source=mlcache, event=mlcache:invalidations:kong_core_db_cache, pid=4617, data=balancer:targets:dce2fc1a-03f0-4ede-b704-70e7a422170f
```

So,does the target add will cost a lot CPU???

**Comment by vaxilicaihouxian** [comment] 2021-08-11 10:10
Can we fix load-balancer issue?

**Comment by StarlightIbuki** [comment] 2023-10-11 06:23
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:23 UTC
Labels: core/balancer

**Comment by dream110fly** [comment] 2024-02-06 07:08
We also encountered this problem, how did you solve it?

**Comment by StarlightIbuki** [comment] 2024-02-20 10:06
@dream110fly It's expected for the current model of config sync. The decoding and application of the new config are costly.
We made the process yield when possible to mitigate the issue.
We are still improving the performance of config syncing. A suggestion for now would be to change the config in a batch.
