### ISSUE TITLE
Not possible to add custom plugin with kong version 1.1.1

### ISSUE THREAD

**Issue by Jojoooo1** [Kong/kong#4463] opened 2019-04-02 16:19 UTC
### Summary

Kong version 1.1.1. luarocks commands are not available anymore in kong container.

### Steps To Reproduce

1. Install kong version 1.1.1.
2. Load a custom plugin in kong container
3. Execute "luarocks make" in the custom plugin folder

**Comment by hutchic** [comment] 2019-04-02 16:25
Thanks for the report. This is a duplicate of https://github.com/Kong/docker-kong/issues/247 issue which includes the fix which is pending and a temporary workaround.

**Closed by hutchic** 2019-04-02 16:25 UTC
