### ISSUE TITLE
kong.request.get_method returns incorrect method if upstreams timeout

### ISSUE THREAD

**Issue by xuanit** [Kong/kong#4612] opened 2019-05-15 09:20 UTC
Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

kong.request.get_method returns incorrect method if services timeout

### Steps To Reproduce

1. set up a service which will timeout
2. set up a route for that service accepting POST method.
3. send a post request to the route

Expected:  In plugin code, kong.request.get_method return `POST` 
Actual: kong.request.get_method return `GET`

The function works correctly if services don't timeout
### Additional Details & Logs

- Kong version 1.0.3
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by p0pr0ck5** [comment] 2019-05-15 17:04
Duplicate of https://github.com/Kong/kong/issues/4025

**Closed by p0pr0ck5** 2019-05-15 17:04 UTC
