### ISSUE TITLE
Issue in calling Kong url(vip and internal) while using Kong Authplugin(LuaPlugin)

### ISSUE THREAD

**Issue by smathe19** [Kong/kong#7499] opened 2021-06-24 21:22 UTC
Getting 500 internal error while calling a service through Kong url configured in Kong Authplugin(LuaPlugin) which is enabled. No error when calling the service directly bypassing kong. 
Any suggestions appreciated?

kong Version - 2.04
Lua Version - LUAJIT2.1.0-beta3

Thanks

**Comment by dndx** [comment] 2021-06-28 10:50
Hello,

Which plugin are you using? Could you give the name and config you applied for the plugin?

**Comment by smathe19** [comment] 2021-06-29 13:57
Thanks for response. Provided below the Plugin name and configuration details.

Plugin using is - iex-kong-auth-plugin

consumer - <blank>
bypass - No
validation endpoint - https://iex-apigw-dev.mycompany.com/api/ie/usrmgmt/v2/authorize/token/validate
timeout - 10000
response - table
keepalive- 1000

**Comment by StarlightIbuki** [comment] 2023-10-11 06:22
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:22 UTC
Labels: question
