### ISSUE TITLE
I found that i can't use udp socket function in my plugin,why?

### ISSUE THREAD

**Issue by Tangqiaoyehua** [Kong/kong#3034] opened 2017-11-16 10:11 UTC
When i start Kong ,I got this error:
--------------------------------------------
Error:
/usr/local/share/lua/5.1/kong/cmd/start.lua:62: /usr/local/share/lua/5.1/kong/cmd/start.lua:51: nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:477: /usr/local/share/lua/5.1/kong/core/globalpatches.lua:332: no request found
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/tools/utils.lua:477: in function 'load_module_if_exists'
	/usr/local/share/lua/5.1/kong.lua:94: in function 'load_plugins'
	/usr/local/share/lua/5.1/kong.lua:154: in function 'init'
	init_by_lua:3: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:62: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:7: in function 'file_gen'
	init_worker_by_lua:38: in function <init_worker_by_lua:36>
	[C]: in function 'xpcall'
	init_worker_by_lua:45: in function <init_worker_by_lua:43>
---------------------------------------------------------

I checked the globalpatches.lua,but i still didn't found the reason.

**Comment by kikito** [comment] 2017-11-16 15:40
Hello, are you trying to use the UDP socket in the `init_by_lua` or `init_worker_by_lua` contexts, by any chance? Those contexts are not supported by [ngx.socket.udp](https://github.com/openresty/lua-nginx-module#ngxsocketudp). The `"no request found"` error points in that direction.

Since your issue is not a bug report, please continue this discussion on one of the channels we have habilitated for questions:

* The main place for questions is [gitter](https://gitter.im/Mashape/kong)
* Alternatively, there's also a [mailing list](https://groups.google.com/forum/#!forum/konglayer), in case you prefer that format.

I'll close this issue now. If you think this was not a question, please reopen.

**Closed by kikito** 2017-11-16 15:40 UTC

**Comment by Tangqiaoyehua** [comment] 2017-12-04 10:48
oh,I found reason and solution of this issue few days ago,but i forgot i had put this issue.
kong had a check action in load_plugins, and i wrote "local udp=ngx.socket.udp()" in lua script.I put it in function  ,so it's out of check domain and worked well.
