### ISSUE TITLE
"no API" Error if upstream is "http://app"

### ISSUE THREAD

**Issue by erutherford** [Kong/kong#2449] opened 2017-04-24 21:15 UTC
### Summary

We've tested this with multiple variations and it looks like having an upstream of "http://app" breaks routing.  We get an error ```{"message":"no API found with those values"}```

### Steps To Reproduce

1. We've tested changing the API resource name, changing the URI path and switching to host based routing.  If the upstream is ```http://app``` we get the no API Found error
2. We were using a custom docker image, so we switched to the Mashape kong image and we experienced the same problem
3. We were running this in a docker-compose environment so we ran this locally with a host file entry for app and experienced the same problem.
4. An upstream of ```http://apps``` and any other variant we could come up with works perfectly fine.

### Additional Details & Logs

- Kong version 0.10.1
- Operating System = official kong:0.10.1 (tested on OS X when it was tested outside of docker)

### Examples of working vs non-working setups
```bash
# Working examples
curl -XPOST localhost:8001/apis --data name=app --data uris=/app --data upstream_url=http://apps
curl -XPOST localhost:8001/apis --data name=app --data hosts=app.example.com --data upstream_url=http://apps

# Non-Working examples
curl -XPOST localhost:8001/apis --data name=app --data uris=/app --data upstream_url=http://app
curl -XPOST localhost:8001/apis --data name=apps --data uris=/app --data upstream_url=http://app
curl -XPOST localhost:8001/apis --data name=apps --data uris=/apps --data upstream_url=http://app
curl -XPOST localhost:8001/apis --data name=app --data hosts=app.example.com --data upstream_url=http://app
curl -XPOST localhost:8001/apis --data name=apps --data hosts=app.example.com --data upstream_url=http://app
curl -XPOST localhost:8001/apis --data name=apps --data hosts=apps.example.com --data upstream_url=http://app
```

Based on the Admin API output everything is setup properly.
```json
{
  "uris": [
    "/app"
  ],
  "id": "41c15c65-dc6d-48c1-a990-8b0b6a862f0e",
  "upstream_read_timeout": 60000,
  "preserve_host": false,
  "created_at": 1493067478000,
  "upstream_connect_timeout": 60000,
  "upstream_url": "http://app",
  "strip_uri": true,
  "https_only": false,
  "name": "app",
  "http_if_terminated": true,
  "upstream_send_timeout": 60000,
  "retries": 5
}
```

Please let me know if you need anything else to debug this.

**Comment by thibaultcha** [comment] 2017-04-24 22:44
Thanks for the report!

@bungle Do you want to take a look at this?

**Comment by bungle** [comment] 2017-04-25 07:28
@erutherford,

Can you also show us the failing and succesful requests (curls or urls)?

**Comment by bungle** [comment] 2017-04-25 07:48
I did wrote a small test suite, and it worked fine (I tested against latest `master` branch):

```lua

  describe("exec()", function()
    local spy_stub = {
      nop = function() end
    }

    local function mock_ngx(method, request_uri, headers)
      local _ngx
      _ngx = {
        re = ngx.re,
        var = setmetatable({
          request_uri = request_uri,
          http_kong_debug = headers.kong_debug
        }, {
          __index = function(_, key)
            if key == "http_host" then
              spy_stub.nop()
              return headers.host
            end
          end
        }),
        req = {
          set_uri = function(request_uri)
            _ngx.var.request_uri = request_uri
          end,
          get_method = function()
            return method
          end,
          get_headers = function()
            return headers
          end
        }
      }

      return _ngx
    end
    describe("finds an API", function()
      local checks = {
        -- name     upstream url    uris       hosts
        {  "app",   "http://apps",  "/app",   "",                 },
        {  "app",   "http://apps",  "",       "app.example.com"   },
        {  "app",   "http://app",   "/app",   ""                  },
        {  "apps",  "http://app",   "/app",   ""                  },
        {  "apps",  "http://app",   "/apps",  ""                  },
        {  "app",   "http://app",   "",       "app.example.com"   },
        {  "apps",  "http://app",   "",       "app.example.com"   },
        {  "apps",  "http://app",   "",       "apps.example.com"  },
      }

      for i, args in ipairs(checks) do

        it("[" .. i .. "]", function()

          local use_case_apis = {
            {
              name         = args[1],
              upstream_url = args[2],
            }
          }

          if args[3] ~= "" then
            use_case_apis[1]["uris"] = { args[3] }
          end

          local headers = {}

          if args[4] ~= "" then
            use_case_apis[1]["headers"] = {
              ["host"] = { args[4] }
            }

            headers["host"] = args[4]
          end

          local router = assert(Router.new(use_case_apis) )
          local uri    = args[3] ~= "" and args[3] or "/"

          local _ngx = mock_ngx("GET", uri, headers)
          local api, upstream, host_header = router.exec(_ngx)

          assert.same(use_case_apis[1], api)

        end)
      end
    end)
```

**Comment by erutherford** [comment] 2017-04-25 13:53
@bungle - I've stripped this down to the bare bones and I'm still able to reproduce the issue.  I have failed and successful requests below.  I've also created a gist for a docker-compose file using the mashape official docker image where this is easily reproducible.  I should have noted in the original ticket that we're also using postgres 9.4. 

https://gist.github.com/erutherford/d60f4dc8b5f2935d934853a291bffe18

Failed request:
```
$ curl localhost:8001/apis
{"data":[],"total":0}
$ curl -XPOST localhost:8001/apis --data name=app --data uris=/app --data upstream_url=http://app
{"http_if_terminated":true,"id":"0d0544c9-6eff-48f5-b6df-e33ccbd8e700","retries":5,"preserve_host":false,"created_at":1493127909000,"upstream_connect_timeout":60000,"upstream_url":"http:\/\/app","upstream_read_timeout":60000,"https_only":false,"upstream_send_timeout":60000,"strip_uri":true,"name":"app","uris":["\/app"]}
$ curl -v localhost/app
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 80 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /app HTTP/1.1
> Host: localhost
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Date: Tue, 25 Apr 2017 13:45:30 GMT
< Content-Type: application/json; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Server: kong/0.10.1
< X-Kong-Upstream-Latency: 1
< X-Kong-Proxy-Latency: 5
< Via: kong/0.10.1
<
{"message":"no API found with those values"}
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

Successful Request:
```
$ curl localhost:8001/apis
{"data":[],"total":0}
$ curl -XPOST localhost:8001/apis --data name=app --data uris=/app --data upstream_url=http://apps
{"http_if_terminated":true,"id":"ec65d25f-3663-4af6-9668-6e77964d31c8","retries":5,"preserve_host":false,"created_at":1493128075000,"upstream_connect_timeout":60000,"upstream_url":"http:\/\/apps","upstream_read_timeout":60000,"https_only":false,"upstream_send_timeout":60000,"strip_uri":true,"name":"app","uris":["\/app"]}
$ curl -v localhost/apps
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 80 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /apps HTTP/1.1
> Host: localhost
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 503 Service Temporarily Unavailable
< Date: Tue, 25 Apr 2017 13:48:23 GMT
< Content-Type: text/plain; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Server: kong/0.10.1
<
The upstream server is currently unavailable
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

**Comment by bungle** [comment] 2017-04-25 18:10
@erutherford, thanks a lot, I will continue on that.

**Comment by bungle** [comment] 2017-04-25 19:05
@erutherford I feel this is some kind of DNS related error as `app` seems to resolve to `127.0.53.53`. But that doesn't explain why you get

```json
{"message":"no API found with those values"}
```

**Comment by erutherford** [comment] 2017-04-25 19:21
yeah, even if kong can't resolve the upstream record, we shouldn't get the "no API found" error

**Comment by bungle** [comment] 2017-04-25 20:10
@erutherford do you get anything on Kong `error.log` (`.../kong/logs/error`)

**Comment by bungle** [comment] 2017-04-25 21:25
@erutherford if I provide you tomorrow a special version of `0.10.1``router.lua` with added debug statements, would you like test the problem with that. We are still unable to reproduce this.

**Comment by bungle** [comment] 2017-04-25 21:48
@erutherford one thing I'm a bit concerned is a fact that you provided this in your failed `curl` output:

```
X-Kong-Upstream-Latency: 1
X-Kong-Proxy-Latency: 5
Via: kong/0.10.1
```

I now believe that your Kong rerouted the request just fine, but that `app`pointed to the same Kong proxy. I mean it looks like your Kong proxied the request to same or another Kong proxy (I believe same).

1. you call this `localhost/app`
2. it goes to your Kong that `strips` the `/app` making the request to `app/`
3. now this `app` points to the same host as `localhost` and it gets the request, but there is no such API as the only API you have was for `/app`

I'm quite confident that this is the reason.

**Comment by erutherford** [comment] 2017-04-25 23:35
@bungle I'm using docker for mac, so the `localhost` in my curl isn't the same `localhost` that kong would see in docker.

I've created an upgraded [test environment](https://github.com/erutherford/kong-test) and documented steps and results in the README file.  It now has a simple node hello world express app so that I can actually test with a functioning upstream "app" server.  I'm more than willing to run code with debugging statements in it, but I'm curious to know what might be different in our testing scenarios since you're not seeing the same issue as I am.  I'd think it's highly likely that's where the issue lies. 

Have you had a chance to test with the docker-compose environments I've provided?  I'm able to consistently reproduce the same results.

**Comment by bungle** [comment] 2017-04-26 04:42
Please remember that Kong's DNS resolver doesn't neccessarily work the same as the system. Kong doesn't read `hosts` file. Can you show your `/etc/resolv.conf` inside your Kong? And if you connect to a name server (IPv4) listed there inside your Kong docker how does it resolver `app`?

**Comment by thibaultcha** [comment] 2017-04-26 05:16
> Kong doesn't read hosts file.

(It does (or should) as per the `dns_hostsfile` config property)

**Comment by Tieske** [comment] 2017-04-26 06:26
the `{"message":"no API found with those values"}` error is generated by the router, not by the dns module.

That said, we've had an issue before where a failure in setting the upstream values (from Lua land into nginx) caused a recursive loop back into Kong. In that case it kept looping and finally errored out. My guess here is that if it is dns related, that it does a similar thing, but then somewhere in the loop fails to match an api. Only problem is how to replicate this.

**Comment by Tieske** [comment] 2017-04-26 06:34
@erutherford can you share the contents of the `resolv.conf` and `hosts` files?

**Comment by bungle** [comment] 2017-04-26 08:52
@erutherford what if you change the port of the `app` upstream uri:
```
curl -XPOST localhost:8001/apis --data name=app --data uris=/app --data upstream_url=http://app:2007
```

This way there won't be a loopback to Kong.

**Comment by erutherford** [comment] 2017-04-26 12:12
The example I've provided you with uses docker-compose v3 and isn't using links/host file entries, it's using docker's DNS based discovery.  Also, while the examples I'm providing you with are docker, we were also able to reproduce this issue running kong directly on a mac...

Here's the proof that it's not using docker links/hosts file entries
```bash
$ docker-compose exec kong /bin/bash
[root@37c983700bdb /]# cat /etc/host
cat: /etc/host: No such file or directory
[root@37c983700bdb /]# cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.19.0.3	37c983700bdb
[root@37c983700bdb /]# cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0
```

I've provided you with a full docker-compose environment where this is extremely reproducible.  At this point we've already worked around this issue, I was trying to help resolve what looks to me like a bug.

**Comment by p0pr0ck5** [comment] 2017-04-26 20:16
Remember that `.app` is a gTLD, so root servers (and, pretty much everyone) is responding with an A record for `app` queries (remembering that this is technically a FQDN `app.`):

```
$ dig app @8.8.8.8 +short
127.0.53.53
```

So when Kong receives a request for an API with the upstream_url of `http://app`, and it does not find any upstream objects with the name `app`, it reverts to DNS resolution. Kong then sends the request on to `127.0.53.53`, and, depending on the environment (as @bungle and I suspect is happening here), Kong will handle this query as a loopback (remembering that by default, the `strip_uri` param is true, so Kong forwards the query to `127.0.53.53` as just `/`, which is then not found by the router).

@erutherford if you create a second API with `uris=/`, I'd be willing to bet you'll see that API handle the request as expected.

Thus, this is not a bug; this is simply Kong behaving as expected (and designed) as a result of DNS resolution on the `upstream_url`.

**Comment by bungle** [comment] 2017-04-26 20:42
@erutherford, well just what I though. I installed your docker environment and was able to reproduce this. Now the DNS resolution inside that Kong repository is the root cause for the problem as I suggested.

```bash
bungle@docker:~/kong-test$ sudo docker-compose exec kong bash
PING app (172.19.0.4) 56(84) bytes of data.
64 bytes from app.kongtest_default (172.19.0.4): icmp_seq=1 ttl=64 time=0.090 ms
```

Now outside to Kong container:

```bash
bungle@docker:~/kong-test$ http 127.0.0.11:8001/apis
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: false
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Wed, 26 Apr 2017 20:42:00 GMT
Server: kong/0.10.1
Transfer-Encoding: chunked
```

```json
{
    "data": [
        {
            "created_at": 1493239005000, 
            "http_if_terminated": true, 
            "https_only": false, 
            "id": "64163a61-5ba6-4cda-b34e-7b27a6dee649", 
            "name": "app", 
            "preserve_host": false, 
            "retries": 5, 
            "strip_uri": true, 
            "upstream_connect_timeout": 60000, 
            "upstream_read_timeout": 60000, 
            "upstream_send_timeout": 60000, 
            "upstream_url": "http://app", 
            "uris": [
                "/app"
            ]
        }, 
        {
            "created_at": 1493238979000, 
            "http_if_terminated": true, 
            "https_only": false, 
            "id": "a3dfbf6c-9072-4a0d-95c8-c0806cd6aacd", 
            "name": "apps", 
            "preserve_host": false, 
            "retries": 5, 
            "strip_uri": true, 
            "upstream_connect_timeout": 60000, 
            "upstream_read_timeout": 60000, 
            "upstream_send_timeout": 60000, 
            "upstream_url": "http://apps", 
            "uris": [
                "/apps"
            ]
        }
    ], 
    "total": 2
}
```

**Comment by bungle** [comment] 2017-04-26 20:52
Umm. I made a mistake here. I need to investigate this a bit more.

**Comment by erutherford** [comment] 2017-04-26 21:15
@p0pr0ck5 this was indeed a flaw in the original docker-compose file I provided and was why I created a new one that actually spins up a service named app and thus docker will create a DNS record for `app`.  Since docker is providing the DNS for this container, it should in theory take precedence over the tld of .app since it can service that request locally instead of hitting the loopback address and going back to kong.

**Comment by bungle** [comment] 2017-04-26 21:16
What happens there is really Kong proxying to same Kong:

```
127.0.0.1 - - [26/Apr/2017:21:01:51 +0000] "GET / HTTP/1.1" 404 56 "-" "curl/7.29.0"
127.0.0.1 - - [26/Apr/2017:21:01:51 +0000] "GET /app HTTP/1.1" 404 56 "-" "curl/7.29.0"
```

So it seems like `app` is resolving to `127.0.0.1` inside Nginx / Kong. Outside Nginx / Kong it seems to resolve to `172.19.0.4`. When requesting `localhost/apps`I do get only a single access log entry:

```
127.0.0.1 - - [26/Apr/2017:21:15:22 +0000] "GET /apps HTTP/1.1" 200 12 "-" "curl/7.29.0"
```

**Comment by erutherford** [comment] 2017-04-26 21:25
Kong resolves dns via the nameserver in resolve.conf correct? https://github.com/Mashape/kong/blob/master/kong/tools/dns.lua#L23-L30

```bash
[root@8406c4abe004 /]# cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0
[root@8406c4abe004 /]# nslookup
> server 127.0.0.11
Default server: 127.0.0.11
Address: 127.0.0.11#53
> app
Server:		127.0.0.11
Address:	127.0.0.11#53

Non-authoritative answer:
Name:	app
Address: 172.19.0.4
```
I understand that if there wasn't an app record, the .app tld record is set to a loopback address and that was causing kong to proxy to kong.  How is kong still resolving it to the loopback address if the nameserver it's supposed to be using is resolving it correctly?

**Comment by bungle** [comment] 2017-04-26 21:39
Ok here is the full answer:

1. Kong reads `resolv.conf`
2. Inside your container the app is actually `app.kongtest_default` and that means that Docker DNS has a search options added (?)
3. Now Kong balancer actually resolves `app` and gets `127.0.53.53` and it seems like your docker Kong image is listening all `127.x.x.x`.

There is a quite new commit here:
https://github.com/Mashape/lua-resty-dns-client/commit/0116f08ee823fcc10bcd77388836814975950dee

But I'm not sure if it resolves this.

**Comment by bungle** [comment] 2017-04-26 21:55
@Tieske mind you check this out as this may be related to the recent work you have done with `lua-resty-dns-client`. I can test it on my machine as I now have this working on a VM / Docker.

**Comment by XVincentX** [comment] 2017-07-02 11:12
I think I am having kind of the same error - I published a reproducible example here

https://github.com/XVincentX/kong-node-playground

The APIs are both reachable from the `kong` container

```bash
[root@b31ab0295c74 /]# ping customers
PING customers (172.18.0.4) 56(84) bytes of data.
64 bytes from customers.kongnode_default (172.18.0.4): icmp_seq=1 ttl=64 time=0.074 ms
64 bytes from customers.kongnode_default (172.18.0.4): icmp_seq=2 ttl=64 time=0.199 ms
^C
--- customers ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1028ms
rtt min/avg/max/mdev = 0.074/0.136/0.199/0.063 ms
[root@b31ab0295c74 /]# curl http://customers:3000
{"name":"Vincenzo","surname":"Chianese"}[root@b31ab0295c74 /]#
```

but if I try to forward a request to Kong, I'm getting an error:
```bash
vchianese@Vincenzos-MacBook-Pro:~/dev/kong_node$ curl http://localhost:8000/invoices
{"message":"Service unavailable"}
```


This is my API object
```json
{
  "data": [
    {
      "uris": [
        "/invoices"
      ],
      "id": "2bf6a0e7-6417-4f16-8dd8-ff3f89446b60",
      "upstream_read_timeout": 60000,
      "preserve_host": false,
      "created_at": 1498992108000,
      "upstream_connect_timeout": 60000,
      "upstream_url": "http://invoices:3000",
      "strip_uri": true,
      "https_only": false,
      "name": "invoices",
      "http_if_terminated": true,
      "upstream_send_timeout": 60000,
      "retries": 5
    }
  ],
  "total": 1
}
```

**Comment by Tieske** [comment] 2017-07-27 08:04
Whoops, sorry for the late reply, I missed this somehow 😞 

@bungle I think you are right, Kong tries to resolve `app` as it requires fully qualified names.

@erutherford what's the behaviour with the new Kong 0.11 RC releases? That version will honour the `search` and `ndots` directives from `/etc/resolv.conf`

**Comment by thibaultcha** [comment] 2017-11-02 04:48
Hmm closing this and considering it a "stale" issue, I am afraid... As @Tieske mentioned, we do have support for the `search` and `ndots` directive in Kong 0.11+, so I would advise giving this another try, or consderring it solved.

@erutherford If you have upgraded to our latest release (0.11.1) and still are encountering what you believe is a *bug*, please **do** open a new issue on this repository. Thank you!

**Closed by thibaultcha** 2017-11-02 04:48 UTC
Labels: task/feature
