### ISSUE TITLE
Demand: dynamic set ssl_protocols TLSv1 TLSv1.1 TLSv1.2 by certificate SNI 

### ISSUE THREAD

**Issue by taotao2014** [Kong/kong#4854] opened 2019-07-30 10:10 UTC
demand: dynamic set ssl_protocols TLSv1 TLSv1.1 TLSv1.2 by certificate SNI

kong:0.14.1

**Comment by jeremyjpj0916** [comment] 2019-07-30 15:22
Seems like a dup of https://github.com/Kong/kong/issues/4852

**Comment by kikito** [comment] 2019-07-30 18:19
Closing this as a duplicate of #4852

**Closed by kikito** 2019-07-30 18:19 UTC
