### ISSUE TITLE
Kong 1.0 failed to enable anonymous consumer in plugin "key-auth" in service

### ISSUE THREAD

**Issue by vietwow** [Kong/kong#4188] opened 2019-01-11 15:00 UTC
### Summary

I deployed Kong 1.0 on K8s using official helm chart, kong is running well, but when I try to enable anonymous consumer in plugin "key-auth" in service, then I got got error : 

{"message":"schema violation (config.anonymous: expected a valid UUID)","name":"schema violation","fields":{"config":{"anonymous":"expected a valid UUID"}},"code":2}

I have re-checked that ANONYMOUS_CONSUMER_ID is a4cc806c-e813-4a10-ad2e-c4e26a9d7b7e (this is auto-generated by Kong)

### Steps To Reproduce

1. Create service

curl -X POST -k https://127.0.0.1:8444/services \
--data "name=$SERVICE_NAME" \
--data "protocol=https" \
--data "host=$HOSTNAME" \
--data "port=443"

2. Create route with above service

curl -X POST -k https://127.0.0.1:8444/routes \
--data "name=$ROUTE_NAME" \
--data "protocols[]=http&protocols[]=https" \
--data "hosts[]=$DOMAIN" \
--data "service.id=$SERVICE_ID"

3. Create anonymous consumer

curl -X POST -k https://127.0.0.1:8444/consumers/ --data "username=$ANONYMOUS_CONSUMER_NAME"

ANONYMOUS_CONSUMER_ID=$(curl -s -k https://127.0.0.1:8444/consumers/$ANONYMOUS_CONSUMER_NAME | jq -r '.id')

4. Enable plugin key-auth on anonymous consumer

curl -X POST -k https://127.0.0.1:8444/services/$SERVICE_ID/plugins \
--data 'name=key-auth' \
--data 'config.run_on_preflight=false' \
--data 'config.anonymous=$ANONYMOUS_CONSUMER_ID'

=> Got error : {"message":"schema violation (config.anonymous: expected a valid UUID)","name":"schema violation","fields":{"config":{"anonymous":"expected a valid UUID"}},"code":2}

### Additional Details & Logs

- Kong version 1.0
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs :

kubectl logs -f kong-kong-9c5f6d948-csjxd

127.0.0.1 - - [11/Jan/2019:15:06:03 +0000] "POST /services/dd8b8ca2-65c8-4681-a425-2c3e54f54f84/plugins HTTP/1.1" 400 165 "-" "curl/7.54.0"

- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by bungle** [comment] 2019-01-11 22:05
The problem is that you used single quotes `'` in your last call:
```
curl -X POST -k https://127.0.0.1:8444/services/$SERVICE_ID/plugins 
--data 'name=key-auth' 
--data 'config.run_on_preflight=false' 
--data 'config.anonymous=$ANONYMOUS_CONSUMER_ID'
```
Change that to:
```
curl -X POST -k https://127.0.0.1:8444/services/$SERVICE_ID/plugins 
--data 'name=key-auth' 
--data 'config.run_on_preflight=false' 
--data "config.anonymous=$ANONYMOUS_CONSUMER_ID"
```

I close this. If I got it wrong, please reopen and provide more information.

**Closed by bungle** 2019-01-11 22:05 UTC
