### ISSUE TITLE
Wrong plugin being executed on routes

### ISSUE THREAD

**Issue by anuj147** [Kong/kong#6683] opened 2020-12-23 08:01 UTC
### Summary

**_Plugins are executed on the wrong route._** 
We have multiple routes where the request path of some is a substring of another like /test, /test-1 and /testa. In such scenarios: 
Scenario 1. We enable a plugin for only /test route. **We call /test-1 and /testa, this plugin is still executed for /test-1 and /testa routes.**
Scenario 2. We remove the plugin from /test route and enable it only on /test-1 route. **Now when we call /test-1 route, the problem is that no plugin is executed.**

**Expected behaviour:** For /test-1 route, a plugin enabled on /test route should never get executed.

### Steps To Reproduce

1. Create a simple service. 
2. Create 2 routes inside this service, GET /test and  GET /test-1
3. Add plugin at a route-level to /test route. Note: Do not add this plugin at a global level or to GET /test-1 route. 
4. Now call GET /test-1 route. You will see plugin enabled for /test route will be accessed which is a problem.

### Additional Details & Logs

- Kong version (`2.2.0`)
- Operating system : centos7

-------------------------------
**Scenario 1**

The response of LIST routes API: admin/routes

`{
    "next": null,
    "data": [
        {
            "id": "86dadaee-9842-4bde-8527-8efa872218ef",
            "tags": null,
            "paths": [
                "/test"
            ],
            "destinations": null,
            "headers": null,
            "protocols": [
                "http",
                "https"
            ],
            "strip_path": false,
            "created_at": 1608708938,
            "request_buffering": true,
            "hosts": null,
            "name": "chat-test",
            "updated_at": 1608708938,
            "snis": null,
            "preserve_host": true,
            "regex_priority": 0,
            "methods": [
                "GET"
            ],
            "sources": null,
            "response_buffering": true,
            "https_redirect_status_code": 426,
            "path_handling": "v1",
            "service": {
                "id": "321694c8-8096-493b-81cb-cd24ab26c39a"
            }
        },
        {
            "id": "b7e6fc10-0c0c-465d-b2da-5dc2a11fc59c",
            "tags": null,
            "paths": [
                "/test-1"
            ],
            "destinations": null,
            "headers": null,
            "protocols": [
                "http",
                "https"
            ],
            "strip_path": false,
            "created_at": 1608708982,
            "request_buffering": true,
            "hosts": null,
            "name": "test-1",
            "updated_at": 1608708982,
            "snis": null,
            "preserve_host": true,
            "regex_priority": 0,
            "methods": null,
            "sources": null,
            "response_buffering": true,
            "https_redirect_status_code": 426,
            "path_handling": "v1",
            "service": {
                "id": "321694c8-8096-493b-81cb-cd24ab26c39a"
            }
        } 
    ]
}`

The response of List plugins API: admin-host/plugins
`{
    "next": null,
    "data": [
        {
            "created_at": 1608709340,
            "id": "cc8f3d4d-4394-4e6d-badf-020b50699ad7",
            "tags": null,
            "enabled": true,
            "protocols": [
                "grpc",
                "grpcs",
                "http",
                "https"
            ],
            "name": "enrich-req",
            "consumer": null,
            "service": null,
            "route": {
                "id": "86dadaee-9842-4bde-8527-8efa872218ef"
            },
            "config": {
                "wls_details": true,
                "round_id_identifiers": "roundId, round-id",
                "add_round_details_to_body": false,
                "round_details": false,
                "wls_id_identifiers": "wls-id, wlsid, siteid, site-id"
            }
        }
    ]
}`

**Comment by anuj147** [comment] 2020-12-23 10:20
So we debugged more in **_router.lua_** and found out what was going wrong. It is happening because /test has request method as GET whereas /test-1 had no request method assigned to it. After adding request method GET to /test-1 also, it started working correctly. 
So it's not a problem now as we will add request method to the route.

However, even when GET wasn't added as request method to /test-1, it should never pick up the plugin enabled on /test route. So you can have a look at that.

**Comment by dndx** [comment] 2020-12-29 16:55
Hello @anuj147,

Your observation is correct and this is the expected behavior. See:

https://docs.konghq.com/2.2.x/proxy/#matching-priorities

Because the `/test` route contains more matching conditions than `/test-1`, so it will have a higher precedence. Think it as Kong will always match the Route that's the most specific, not in the sense of URI path, but number of matched criteria. 

As it is a documented feature, I'm closing this issue for now. Feel free to open another one if you have more questions!

**Closed by dndx** 2020-12-29 16:55 UTC
Labels: task/needs-investigation
