### ISSUE TITLE
kong_latency_bucket metrics value changed from FLOAT to INTEGER on upgrade to Kong version 2.8.1 from 2.4.1

### ISSUE THREAD

**Issue by arpit006** [Kong/kong#9163] opened 2022-07-29 10:37 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.1

### Current Behavior

I was using Kong version `2.4.1` and using the community [prometheus Kong plugin](https://docs.konghq.com/hub/kong-inc/prometheus/) to publish metrics related to Kong.

We recently upgraded to Kong version `2.8.1`, and the behaviour of  the value of the metrics exposed seems to have changed. We are now seeing `integer` values being published.
![Screenshot 2022-07-29 at 3 27 34 PM](https://user-images.githubusercontent.com/30981983/181741188-2509126e-05a2-4e9f-8a45-2331a0d3b175.png)

### Expected Behavior

The `kong_latency_bucket` metrics earlier used to expose `float` value and we had developed our SLO's dashboard around that to do benchmarking etc.
![Screenshot 2022-07-29 at 3 27 41 PM](https://user-images.githubusercontent.com/30981983/181740744-b5f31b70-c044-4be9-bc32-c839ef1d8e35.png)

I don't see any changelog related to this change from version `2.4.1` to `2.8.1`. 
Is this a bug or this is now the standard metrics format?

### Steps To Reproduce

```markdown
1. Upgrade to Kong version `2.4.1`
2. Enable prometheus plugin
3. hit the endpoint `http://localhost:8001/metrics` and check for `kong_latency_bucket` metrics
4. Repeat the same for Kong version `2.8.1`
```

**Comment by fffonion** [comment] 2022-08-22 22:39
Hi @arpit006 looks like we are indeed missing the changelog from upstream (https://github.com/knyar/nginx-lua-prometheus/blob/master/CHANGELOG.md#020210206).

**Comment by arpit006** [comment] 2022-09-12 09:01
@fffonion 
Thank you for the confirmation.
I think adding this in the changelog will help the users take any needful action.

As for our usecase, we  had built a SLI dashboard on top of these metrics for downtime budget for each time.
Due to change in this metric and no changelog on version upgrade, we got this in notice after sometime.

If it helps I can raise an MR for adding this to the changelog?

**Comment by StarlightIbuki** [comment] 2023-10-11 06:36
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:36 UTC
Labels: plugins/prometheus
