### ISSUE TITLE
kong go plugins not executed in some requests

### ISSUE THREAD

**Issue by ealogar** [Kong/kong#5586] opened 2020-02-19 18:33 UTC
### Summary

If you configure a go plugin (no matter if it's globally or linked to an specific service) mixed with another LUA plugin sometimes the go plugin is not being executed although it should.
The plugin is executed sometimes during some requests, and after some requests being executed you have a bunch of responses when the plugin is not executed.
With a RPS of 7, aproximately the 50% requests are calling the go plugin but the rest are not.
It's an strange behaviour that I will chase looking at the plugin iterator code.
You don't have an error but if the plugin is not called, it's a failure.

### Steps To Reproduce

1. Use docker-kong image 2.0.1 alpine and compile the go-hello plugin
2. Configure a service with a router (whatever)
3. Configure the go-hello globally or locally to the service
4. Do requests (e.g with jmeter) during 10 minutes
You will have the plugin being executed (and introducing the request header) in some requests and later a bunch of request not calling the plugin:

![Captura de pantalla 2020-02-19 a las 19 32 31](https://user-images.githubusercontent.com/2461944/74863721-a6402e80-534e-11ea-9b52-3ea82d95f593.png)

### Additional Details & Logs

- Kong version (docker alpine 2.0.1)
  
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system docker

**Comment by gszr** [comment] 2020-02-19 18:35
@ealogar Thanks for reporting. Do you see any errors on error logs?

**Comment by ealogar** [comment] 2020-02-19 18:36
@gszr I dont have any error, it's just that the plugin stop being called. dunno if the rpc message ir lost or whatever

**Comment by ealogar** [comment] 2020-02-19 18:45
I include a copy of the logs:
```
172.27.0.1 - - [19/Feb/2020:18:44:25 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
172.27.0.1 - - [19/Feb/2020:18:44:26 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
172.27.0.1 - - [19/Feb/2020:18:44:26 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
172.27.0.1 - - [19/Feb/2020:18:44:27 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
172.27.0.1 - - [19/Feb/2020:18:44:27 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
172.27.0.1 - - [19/Feb/2020:18:44:27 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
172.27.0.1 - - [19/Feb/2020:18:44:28 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
172.27.0.1 - - [19/Feb/2020:18:44:28 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
172.27.0.1 - - [19/Feb/2020:18:44:29 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
172.27.0.1 - - [19/Feb/2020:18:44:29 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
172.27.0.1 - - [19/Feb/2020:18:44:30 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
2020/02/19 18:44:30 [error] 134#0: *70881 [kong] go.lua:338 [go-hello2] Access go-hello, client: 172.27.0.1, server: kong, request: "POST /api1 HTTP/1.1", host: "localhost:8000"
172.27.0.1 - - [19/Feb/2020:18:44:30 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
2020/02/19 18:44:30 [error] 134#0: *70881 [kong] go.lua:338 [go-hello2] Access go-hello, client: 172.27.0.1, server: kong, request: "POST /api1 HTTP/1.1", host: "localhost:8000"
172.27.0.1 - - [19/Feb/2020:18:44:30 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
2020/02/19 18:44:31 [error] 134#0: *70881 [kong] go.lua:338 [go-hello2] Access go-hello, client: 172.27.0.1, server: kong, request: "POST /api1 HTTP/1.1", host: "localhost:8000"
172.27.0.1 - - [19/Feb/2020:18:44:31 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
2020/02/19 18:44:31 [error] 134#0: *70881 [kong] go.lua:338 [go-hello2] Access go-hello, client: 172.27.0.1, server: kong, request: "POST /api1 HTTP/1.1", host: "localhost:8000"
172.27.0.1 - - [19/Feb/2020:18:44:31 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
2020/02/19 18:44:32 [error] 134#0: *70881 [kong] go.lua:338 [go-hello2] Access go-hello, client: 172.27.0.1, server: kong, request: "POST /api1 HTTP/1.1", host: "localhost:8000"
172.27.0.1 - - [19/Feb/2020:18:44:32 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
172.27.0.1 - - [19/Feb/2020:18:44:32 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
172.27.0.1 - - [19/Feb/2020:18:44:33 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
172.27.0.1 - - [19/Feb/2020:18:44:33 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
172.27.0.1 - - [19/Feb/2020:18:44:33 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
172.27.0.1 - - [19/Feb/2020:18:44:34 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
172.27.0.1 - - [19/Feb/2020:18:44:34 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
172.27.0.1 - - [19/Feb/2020:18:44:35 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
172.27.0.1 - - [19/Feb/2020:18:44:35 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
172.27.0.1 - - [19/Feb/2020:18:44:36 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
172.27.0.1 - - [19/Feb/2020:18:44:36 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
2020/02/19 18:44:36 [error] 134#0: *70971 [kong] go.lua:338 [go-hello2] Access go-hello, client: 172.27.0.1, server: kong, request: "POST /api1 HTTP/1.1", host: "localhost:8000"
172.27.0.1 - - [19/Feb/2020:18:44:37 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
2020/02/19 18:44:37 [error] 134#0: *70971 [kong] go.lua:338 [go-hello2] Access go-hello, client: 172.27.0.1, server: kong, request: "POST /api1 HTTP/1.1", host: "localhost:8000"
172.27.0.1 - - [19/Feb/2020:18:44:37 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
2020/02/19 18:44:37 [error] 134#0: *70971 [kong] go.lua:338 [go-hello2] Access go-hello, client: 172.27.0.1, server: kong, request: "POST /api1 HTTP/1.1", host: "localhost:8000"
172.27.0.1 - - [19/Feb/2020:18:44:37 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
2020/02/19 18:44:38 [error] 134#0: *70971 [kong] go.lua:338 [go-hello2] Access go-hello, client: 172.27.0.1, server: kong, request: "POST /api1 HTTP/1.1", host: "localhost:8000"
172.27.0.1 - - [19/Feb/2020:18:44:38 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
2020/02/19 18:44:38 [error] 134#0: *70971 [kong] go.lua:338 [go-hello2] Access go-hello, client: 172.27.0.1, server: kong, request: "POST /api1 HTTP/1.1", host: "localhost:8000"
172.27.0.1 - - [19/Feb/2020:18:44:38 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
2020/02/19 18:44:39 [error] 134#0: *70997 [kong] go.lua:338 [go-hello2] Access go-hello, client: 172.27.0.1, server: kong, request: "POST /api1 HTTP/1.1", host: "localhost:8000"
172.27.0.1 - - [19/Feb/2020:18:44:39 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
2020/02/19 18:44:39 [error] 134#0: *70997 [kong] go.lua:338 [go-hello2] Access go-hello, client: 172.27.0.1, server: kong, request: "POST /api1 HTTP/1.1", host: "localhost:8000"
172.27.0.1 - - [19/Feb/2020:18:44:39 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
2020/02/19 18:44:40 [error] 134#0: *70997 [kong] go.lua:338 [go-hello2] Access go-hello, client: 172.27.0.1, server: kong, request: "POST /api1 HTTP/1.1", host: "localhost:8000"
172.27.0.1 - - [19/Feb/2020:18:44:40 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
2020/02/19 18:44:40 [error] 134#0: *70997 [kong] go.lua:338 [go-hello2] Access go-hello, client: 172.27.0.1, server: kong, request: "POST /api1 HTTP/1.1", host: "localhost:8000"
172.27.0.1 - - [19/Feb/2020:18:44:40 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
2020/02/19 18:44:40 [error] 134#0: *70997 [kong] go.lua:338 [go-hello2] Access go-hello, client: 172.27.0.1, server: kong, request: "POST /api1 HTTP/1.1", host: "localhost:8000"
172.27.0.1 - - [19/Feb/2020:18:44:40 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
172.27.0.1 - - [19/Feb/2020:18:44:41 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
172.27.0.1 - - [19/Feb/2020:18:44:41 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
172.27.0.1 - - [19/Feb/2020:18:44:42 +0000] "POST /api1 HTTP/1.1" 200 14 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_192)" "-" "-"
```

**Comment by gszr** [comment] 2020-02-19 19:30
Thanks @ealogar, we will do some digging on our side.

**Comment by ealogar** [comment] 2020-02-19 20:09
Hi @gszr , I just found now (after 20 minutes testing) that if you define he priority in the go module, it works as expected and it's being called always.
var Priority = 1
I discovered that the pluginserver is looking for this property through a lookup and I always had in mind to set it....
This may be a workaround for me but you may consider in your diggings, maybe write in documentation to define prirority or whatever.

**Comment by ealogar** [comment] 2020-02-24 21:13
@gszr I have not been able to reproduce the issue in a couple of days. It may be a memory related issue ?

**Comment by ealogar** [comment] 2020-04-06 23:15
@gszr I am having this problem sometimes, I am afraid I will stop using go plugins. Have you been able to do some investigation ?

**Comment by lmqytz** [comment] 2020-04-07 09:29
I had the same problem
but also,i wrote a plugin and let it act on two services with different configurion(use kong.yml).then i requested the services and found that the value of the configuration is not permanent,sometimes print value of plugin's configurion  who is binded to another service.

**Comment by ealogar** [comment] 2020-04-07 14:10
One thing that I am doing now (but only with one global go plugin and some more in lua) is increasing the file descriptors of the nginx workers and reducing the workers connections to the half of the value as I have seen than the go-pluginsserver is taking this value when it's spawned. The worst thing of this issue is that no logs apppear, they would be very useful to help fixing the issue

**Comment by gszr** [comment] 2020-05-07 21:58
Thanks for linking the issues, @ealogar! Both PRs are merged by now, so closing this.

**Closed by gszr** 2020-05-07 21:58 UTC
Labels: task/needs-investigation

**Comment by primableatom** [comment] 2020-05-13 20:47
Hey @ealogar , Unfortunately for me the issue is still there even with the above fix, I am using kong 2.0.3 in Heroku and just patched in **go.lua** and **plugins_iterator.lua** from the above PRs but still keep having this issue intermittently. 

One pattern I have noticed is - when it happens, it keeps happening more than 50% of the times until  I restart the app at which point it stops. Can you please suggest something to overcome this issue ? Initially I thought that the go pluginserver might be crashing but locally I can see that whenever it crashes it brings itself back and I assume that's what it should do in Heroku too.

**Comment by primableatom** [comment] 2020-05-14 13:36
I was able to patch the issue with this [PR](https://github.com/Kong/kong/pull/5903) .Not sure if this is the best way but it seems to work for me in Heroku.

PS: I am not that well versed with Lua. So please bare with me :-)

**Comment by ealogar** [comment] 2020-05-14 13:38
@primableatom fo my use case both prs fixed the issue when reloading the plugin. I think that what you're suffering is not the same thing....

**Comment by gszr** [comment] 2020-05-14 14:05
@primableatom Thanks for submitting the PR. That does look like a different issue. The team and I will look into the PR. Thanks again!

**Comment by ifree321** [comment] 2020-11-03 08:23
I encountered a similar problem like @primableatom . the kong version is 2.1.0. When the request was executed halfway in the go plugin, it was not executed, no response and no log. the the request appeared directly in the next level of service 。when i restart the kong-docker, everything is normal,Then I don’t know what happened, it went wrong again。
I have spend 4 month to write the big authorization go plugin, if the question can't be fixed, i just dont know what should i do.😿
