### ISSUE TITLE
Rate limiting not working while performing parallel connection 

### ISSUE THREAD

**Issue by viswaram1997** [Kong/kong#5790] opened 2020-04-16 09:10 UTC
In kong 1.4.2 while passing the concurrent request kong rate limit not working. I am having this configuration  {
            "config": {
                "day": null,
                "fault_tolerant": true,
                "hide_client_headers": false,
                "hour": null,
                "limit_by": "service",
                "minute": null,
                "month": null,
                "policy": "redis",
                "redis_database": 1,
                "redis_host": "10.229.127.109",
                "redis_password": null,
                "redis_port": 6379,
                "redis_timeout": 300000,
                "second": 40,
                "year": null
            },
            "consumer": null,
            "created_at": 1586786611,
            "enabled": true,
            "id": "147a5b59-b463-4ea1-82eb-5e2fa10930f7",
            "name": "rate-limiting",
            "protocols": [
                "grpc",
                "grpcs",
                "http",
                "https"
            ],
            "route": {
                "id": "65c0d9d8-4dbe-4f95-9a81-370023bf98c3"
            },
            "run_on": "first",
            "service": null,
            "tags": null
        },

i have tried local and redis policy. it not working out. if we hit cucurrent hit at same milisec it's not working.

**Comment by vasuharish** [comment] 2020-04-17 01:49
Hi @viswaram1997 , I believe the same issue was reported here https://github.com/Kong/kong/issues/5311 and bungle has answered it already. Thank you.

**Comment by bungle** [comment] 2020-04-17 16:42
Yes, could you please try: #5460.

**Comment by bungle** [comment] 2020-04-17 16:49
I am closing this as it is duplicate of #5311 and #5460 provides an alternative solution to this (we are still debating about it). @viswaram1997 feel free to join discussion on those two!

**Closed by bungle** 2020-04-17 16:49 UTC
