### ISSUE TITLE
Incorrect evaluation order with regex uris

### ISSUE THREAD

**Issue by EsotericVoid** [Kong/kong#3136] opened 2018-01-05 19:41 UTC
Related to #3111 probably, but I have the exact opposite issue.

These are my kong apis:

    {
       "total" : 5,
       "data" : [
          {
             "upstream_read_timeout" : 60000,
             "retries" : 5,
             "strip_uri" : false,
             "upstream_connect_timeout" : 60000,
             "created_at" : 1515179488893,
             "preserve_host" : false,
             "https_only" : false,
             "upstream_send_timeout" : 60000,
             "uris" : [
                "/users/\\d"
             ],
             "id" : "edbc93f2-e897-490f-a0a5-7fb627eb8748",
             "upstream_url" : "http://172.18.0.3:8002",
             "http_if_terminated" : false,
             "name" : "account"
          },
          {
             "upstream_send_timeout" : 60000,
             "id" : "2d76ec3e-df4d-43f1-8bbb-79e613f882a8",
             "uris" : [
                "/\\w"
             ],
             "upstream_url" : "http://172.18.0.3:8002",
             "http_if_terminated" : false,
             "name" : "login",
             "upstream_read_timeout" : 60000,
             "strip_uri" : false,
             "retries" : 5,
             "upstream_connect_timeout" : 60000,
             "created_at" : 1515179488936,
             "https_only" : false,
             "preserve_host" : false
          },
          {
             "name" : "event",
             "upstream_url" : "http://172.18.0.10:8004",
             "http_if_terminated" : false,
             "uris" : [
                "/users/\\d /calendars/\\d /events"
             ],
             "id" : "2f5c90de-dc09-43f3-92d4-7d798b6fd149",
             "upstream_send_timeout" : 60000,
             "preserve_host" : false,
             "https_only" : false,
             "retries" : 5,
             "strip_uri" : false,
             "upstream_connect_timeout" : 60000,
             "created_at" : 1515179488801,
             "upstream_read_timeout" : 60000
          },
          {
             "preserve_host" : false,
             "https_only" : false,
             "created_at" : 1515179488610,
             "retries" : 5,
             "strip_uri" : false,
             "upstream_connect_timeout" : 60000,
             "upstream_read_timeout" : 60000,
             "name" : "instructions",
             "http_if_terminated" : false,
             "upstream_url" : "http://172.18.0.13:8005",
             "uris" : [
                "/users/\\d /calendars/\\d /events/\\d /recurrence/\\d /instruction"
             ],
             "id" : "4e0462ff-3446-4f2a-9a54-d0e6fb385a2c",
             "upstream_send_timeout" : 60000
          },
          {
             "retries" : 5,
             "upstream_connect_timeout" : 60000,
             "strip_uri" : false,
             "created_at" : 1515179488849,
             "preserve_host" : false,
             "https_only" : false,
             "upstream_read_timeout" : 60000,
             "upstream_url" : "http://172.18.0.7:8003",
             "http_if_terminated" : false,
             "name" : "calendar",
             "upstream_send_timeout" : 60000,
             "uris" : [
                "/users/\\d /calendars"
             ],
             "id" : "1e12ba7e-571b-4d02-9e70-a6823db0606d"
          }
       ]
    }

which are created with these commands:

    # instructions
    curl -i -X POST http://localhost:8001/apis/ \
    	-d 'name=instructions' \
            -d 'upstream_url=http://172.18.0.13:8005' \
            -d 'uris=/users/\d+/calendars/\d+/events/\d+/recurrence/\d+/instruction' \
    	-d 'strip_uri=false'
    curl -i -X POST http://localhost:8001/apis/instructions/plugins --data "name=jwt"
    # event
    curl -i -X POST http://localhost:8001/apis/ \
    	-d 'name=event' \
            -d 'upstream_url=http://172.18.0.10:8004' \
            -d 'uris=/users/\d+/calendars/\d+/events' \
    	-d 'strip_uri=false'
    curl -i -X POST http://localhost:8001/apis/event/plugins --data "name=jwt"
    # calendar
    curl -i -X POST http://localhost:8001/apis/ \
    	-d 'name=calendar' \
            -d 'upstream_url=http://172.18.0.7:8003' \
            -d 'uris=/users/\d+/calendars' \
    	-d 'strip_uri=false'
    curl -i -X POST http://localhost:8001/apis/calendar/plugins --data "name=jwt"
    # account
    curl -i -X POST http://localhost:8001/apis/ \
    	-d 'name=account' \
            -d 'upstream_url=http://172.18.0.3:8002' \
            -d 'uris=/users/\d+' \
    	-d 'strip_uri=false'
    curl -i -X POST http://localhost:8001/apis/account/plugins --data "name=jwt"
    # login
    curl -i -X POST http://localhost:8001/apis/ \
    	-d 'name=login' \
            -d 'upstream_url=http://172.18.0.3:8002' \
            -d 'uris=/\w/' \
    	-d 'strip_uri=false'

If I try to access the `/users/3/calendars`, I get redirected to the `account` api (defined with `uris=/users/\d+`), but I'm expecting instead to be redirected to the `calendar` api (defined with `uris=/users/\d+/calendars`). From the [docs](https://getkong.org/docs/0.11.x/proxy/#evaluation-order):

> As previously mentioned, Kong evaluates prefix URIs by length: the longest prefix URIs are evaluated first. However, **Kong will evaluate regex URIs based on the order in which they are defined.** 

What am I doing wrong?
Thanks for your time.

**Comment by thibaultcha** [comment] 2018-01-05 21:13
Hi,

You are creating those APIs with form-urlencoded payloads. As a result, your regexes are not properly created because the Admin API will (always) url-decode your payload (rightfully so), and interpret characters such as `+` as ` ` (space).

For example, your calendar API's `uris` look like so:
```json
{
    "uris":["\/users\/\\d \/calendars"]
}
```

Which is indeed not matching your request: `/users/3/calendars`.

Your use-case works perfectly when I do the following on 0.11.1:
```
$ curl -i -X POST http://localhost:8001/apis/ \
        -d 'name=calendar' \
        -d 'upstream_url=...' \
        --data-urlencode 'uris=/users/\d+/calendars' \
        -d 'strip_uri=false'

$ curl -i -X POST http://localhost:8001/apis/ \
        -d 'name=account' \
        -d 'upstream_url=...' \
        --data-urlencode 'uris=/users/\d+' \
        -d 'strip_uri=false'

curl -i http://localhost:8000/users/3/calendars
```

Not that this properly URL-encodes the regex, causing the Admin API's URL-decode step to retrieve a properly formatted regex.

I will be closing this issue now, as it is behaving as intended. Thanks.

**Closed by thibaultcha** 2018-01-05 21:13 UTC

**Comment by thibaultcha** [comment] 2018-01-05 21:15
Note that a section of the Regex URIs documentation is dedicated on escaping special characters for form-urlencoded payloads: https://getkong.org/docs/0.11.x/proxy/#escaping-special-characters

**Comment by EsotericVoid** [comment] 2018-01-05 22:25
Thanks for the explanation, I've missed that part. Sorry for the misunderstanding.
