### ISSUE TITLE
chore(scripts) make-patch-release should not attempt merges with master

### ISSUE THREAD

**Issue by kikito** [Kong/kong#7866] opened 2021-09-21 17:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.5

### Current Behavior

When making a release with scripts/make-patch-release, one of the steps is "merge branch into master"

Given that with our new branching strategy the patch releases (like 2.5.1) are supposed to be tags on their release branch (`release/2.5`), the merging should never happen.

### Expected Behavior

Instead the merging, the step should be "cherry pick some commits to master".

For example: the changes to the changelog should be cherry-picked into master.

Part of solving this issue consists on figuring out what else needs to be cherry-picked. For example: it is unclear at the moment of this writing wether we should include the rockspec changes, or the changes in `kong/meta.lua`

For 2.5.1 this is the manual change we did: #7871

**Comment by StarlightIbuki** [comment] 2023-10-11 06:24
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:24 UTC
Labels: distribution
