### ISSUE TITLE
Healthcheckers warn spam with external service

### ISSUE THREAD

**Issue by cdrappier** [Kong/kong#8045] opened 2021-11-05 15:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.6.0 and Kong ingress 2.0.3

### Current Behavior

When I have an ingress linked to an external services linked to aws s3 url, I got my warn log spam with something looking like an infinite loop. (50+ logs second in production)

It look like their is an healthcheck bind on the external upstream.
It should not happen, cause it's not something managed by k8s

### Expected Behavior

The healthcheck should be disable.
By default the upstream healthchecks is set to 0 in interval, so the healthcheck should not be perform
```

{
    "algorithm": "round-robin",
    "client_certificate": null,
    "created_at": 1636125901,
    "hash_fallback": "none",
    "hash_fallback_header": null,
    "hash_on": "none",
    "hash_on_cookie": null,
    "hash_on_cookie_path": "/",
    "hash_on_header": null,
    "healthchecks": {
        "active": {
            "concurrency": 10,
            "healthy": {
                "http_statuses": [
                    200,
                    302
                ],
                "interval": 0,
                "successes": 0
            },
            "http_path": "/",
            "https_sni": null,
            "https_verify_certificate": true,
            "timeout": 1,
            "type": "tcp",
            "unhealthy": {
                "http_failures": 0,
                "http_statuses": [
                    429,
                    404,
                    500,
                    501,
                    502,
                    503,
                    504,
                    505
                ],
                "interval": 0,
                "tcp_failures": 0,
                "timeouts": 0
            }
        },
        "passive": {
            "healthy": {
                "http_statuses": [
                    200,
                    201,
                    202,
                    203,
                    204,
                    205,
                    206,
                    207,
                    208,
                    226,
                    300,
                    301,
                    302,
                    303,
                    304,
                    305,
                    306,
                    307,
                    308
                ],
                "successes": 0
            },
            "type": "http",
            "unhealthy": {
                "http_failures": 0,
                "http_statuses": [
                    429,
                    500,
                    503
                ],
                "tcp_failures": 0,
                "timeouts": 0
            }
        },
        "threshold": 0
    },
    "host_header": null,
    "id": "f4392773-53cc-52f4-9997-705413bae09d",
    "name": "s3.fpdevenv-ktemdg2p.443.svc",
    "slots": 10000,
    "tags": null
}

```

### Steps To Reproduce

1 - Install kong on k8s with standard configuration with the latest ingress-controller and latest kong version (1.3.2 and 2.5.0)
2 - Create an external service in your k8s

```
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: my-namespace
  labels:
    type: external
  annotations:
    konghq.com/plugins: ''
    konghq.com/protocol: https
spec:
  type: ExternalName
  sessionAffinity: None
  externalName: s3.eu-west-1.amazonaws.com
```

3 - Create an ingress in your k8s pointing on that service (I have my own tls certificate because kong serve that url in https)

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
  namespace: my-namespace
  annotations:
    konghq.com/https-redirect-status-code: '302'
    konghq.com/preserve-host: 'true'
    konghq.com/protocols: https
    konghq.com/strip-path: 'true'
    kubernetes.io/ingress.class: kong
spec:
  tls:
    - hosts:
        - myhost.io
      secretName: mysecrettls
  rules:
    - host: myhost.io
      http:
        paths:
          - path: /test
            pathType: ImplementationSpecific
            backend:
              service:
                name: test
                port:
                  number: 443
```

4 - Open the kong proxy logs

### Anything else?

The issue is link to https://github.com/Kong/kong/issues/7771
-> The previous error was resolve, but now we have that log issue

Log in debug mode before one warn
```

2021/11/05 15:25:23 [debug] 1098#0: *1039 [lua] targets.lua:235: executing requery for: s3.eu-west-1.amazonaws.com
2021/11/05 15:25:23 [debug] 1098#0: *1039 [lua] targets.lua:427: queryDns(): querying dns for s3.eu-west-1.amazonaws.com
2021/11/05 15:25:23 [debug] 1098#0: *1039 [lua] targets.lua:363: f(): new dns record entry for s3.eu-west-1.amazonaws.com: 52.218.106.59:nil
2021/11/05 15:25:23 [debug] 1098#0: *1039 [lua] targets.lua:392: f(): removed dns record entry for s3.eu-west-1.amazonaws.com: 52.218.93.67:nil
2021/11/05 15:25:23 [debug] 1098#0: *1039 [lua] targets.lua:408: f(): updating balancer based on dns changes for s3.eu-west-1.amazonaws.com
2021/11/05 15:25:23 [debug] 1098#0: *1039 [lua] targets.lua:418: f(): querying dns and updating for s3.eu-west-1.amazonaws.com completed
2021/11/05 15:25:23 [debug] 1098#0: *1040 [lua] events.lua:211: do_event_json(): worker-events: handling event; source=lua-resty-healthcheck [0dc6f45b-8f8d-40d2-a504-473544ee190b:s3.fpdevenv-ktemdg2p.443.svc], event=healthy, pid=1097, data=table: 0x7ff5abc84aa8
2021/11/05 15:25:23 [debug] 1098#0: *1040 [lua] healthcheck.lua:1126: log(): [healthcheck] (0dc6f45b-8f8d-40d2-a504-473544ee190b:s3.fpdevenv-ktemdg2p.443.svc) event: target added 's3.eu-west-1.amazonaws.com(52.218.106.59:443)'
2021/11/05 15:25:23 [debug] 1098#0: *1040 [lua] healthcheck.lua:1126: log(): [healthcheck] (0dc6f45b-8f8d-40d2-a504-473544ee190b:s3.fpdevenv-ktemdg2p.443.svc) event: target status 's3.eu-west-1.amazonaws.com(52.218.106.59:443)' from 'false' to 'true'
2021/11/05 15:25:23 [debug] 1098#0: *1040 [lua] events.lua:211: do_event_json(): worker-events: handling event; source=lua-resty-healthcheck [0dc6f45b-8f8d-40d2-a504-473544ee190b:s3.fpdevenv-ktemdg2p.443.svc], event=remove, pid=1097, data=table: 0x7ff5abc85588
2021/11/05 15:25:23 [debug] 1098#0: *1040 [lua] healthcheck.lua:1126: log(): [healthcheck] (0dc6f45b-8f8d-40d2-a504-473544ee190b:s3.fpdevenv-ktemdg2p.443.svc) event: target 's3.eu-west-1.amazonaws.com (52.218.105.98:443' removed
2021/11/05 15:25:23 [debug] 1098#0: *1040 [lua] events.lua:211: do_event_json(): worker-events: handling event; source=lua-resty-healthcheck [0dc6f45b-8f8d-40d2-a504-473544ee190b:s3.fpdevenv-ktemdg2p.443.svc], event=remove, pid=1100, data=table: 0x7ff5abc85848
2021/11/05 15:25:23 [debug] 1098#0: *1040 [lua] healthcheck.lua:1126: log(): [healthcheck] (0dc6f45b-8f8d-40d2-a504-473544ee190b:s3.fpdevenv-ktemdg2p.443.svc) event: target 's3.eu-west-1.amazonaws.com (52.218.93.67:443' removed
2021/11/05 15:25:23 [debug] 1098#0: *1040 [lua] events.lua:211: do_event_json(): worker-events: handling event; source=lua-resty-healthcheck [0dc6f45b-8f8d-40d2-a504-473544ee190b:s3.fpdevenv-ktemdg2p.443.svc], event=healthy, pid=1101, data=table: 0x7ff5abc85c10
2021/11/05 15:25:23 [debug] 1098#0: *1040 [lua] healthcheck.lua:1126: log(): [healthcheck] (0dc6f45b-8f8d-40d2-a504-473544ee190b:s3.fpdevenv-ktemdg2p.443.svc) event: target added 's3.eu-west-1.amazonaws.com(52.218.98.43:443)'
2021/11/05 15:25:23 [debug] 1098#0: *1040 [lua] healthcheck.lua:1126: log(): [healthcheck] (0dc6f45b-8f8d-40d2-a504-473544ee190b:s3.fpdevenv-ktemdg2p.443.svc) event: target status 's3.eu-west-1.amazonaws.com(52.218.98.43:443)' from 'false' to 'true'
2021/11/05 15:25:23 [warn] 1098#0: *1040 [lua] healthcheckers.lua:150: [healthchecks] failed setting peer status (upstream: 0dc6f45b-8f8d-40d2-a504-473544ee190b:s3.fpdevenv-ktemdg2p.443.svc): not a known address, context: ngx.timer
```

**Comment by locao** [comment] 2021-11-10 13:17
Hi @cdrappier! Thanks for your report.

Do these log entries ever stop to show? How many workers are being spawned?

**Comment by cdrappier** [comment] 2021-11-10 13:39
Hi,

It never stop to show.
It appear on all worker, I use 4 in production, and 1 to 4 in dev, same results.

**Comment by cdrappier** [comment] 2021-12-20 16:44
I've juste done the test with kong 2.7.0 and kong-ingress 2.0.6, bug is still here

**Comment by ebarped** [comment] 2022-05-19 11:55
Happening to us too:
- kong: 2.7.1 (dbless)
- KIC: 2.2.1

Upstream:
```json
{
    "hash_on_header": null,
    "name": "my-service.test.443.svc",
    "slots": 10000,
    "hash_fallback_header": null,
    "client_certificate": null,
    "algorithm": "round-robin",
    "hash_on_cookie_path": "/",
    "hash_fallback": "none",
    "tags": null,
    "created_at": 1652961003,
    "healthchecks": {
        "active": {
            "timeout": 1,
            "https_verify_certificate": true,
            "healthy": {
                "interval": 0,
                "successes": 0,
                "http_statuses": [
                    200,
                    302
                ]
            },
            "unhealthy": {
                "tcp_failures": 0,
                "interval": 0,
                "http_failures": 0,
                "timeouts": 0,
                "http_statuses": [
                    429,
                    404,
                    500,
                    501,
                    502,
                    503,
                    504,
                    505
                ]
            },
            "type": "http",
            "https_sni": null,
            "concurrency": 10,
            "http_path": "/"
        },
        "passive": {
            "type": "http",
            "healthy": {
                "successes": 0,
                "http_statuses": [
                    200,
                    201,
                    202,
                    203,
                    204,
                    205,
                    206,
                    207,
                    208,
                    226,
                    300,
                    301,
                    302,
                    303,
                    304,
                    305,
                    306,
                    307,
                    308
                ]
            },
            "unhealthy": {
                "http_statuses": [
                    429,
                    500,
                    503
                ],
                "tcp_failures": 0,
                "timeouts": 0,
                "http_failures": 0
            }
        },
        "threshold": 0
    },
    "host_header": null,
    "hash_on": "none",
    "id": "1ea2395c-fe6e-5133-8080-2af3fe4bb0e7",
    "hash_on_cookie": null
}
```

Logs:
```
ingress-kong-f9596f564-r9jsv proxy 2022/05/19 11:10:40 [warn] 1356#0: *45354 [lua] healthcheckers.lua:150: [healthchecks] failed setting peer status (upstream: 0dc6f45b-8f8d-40d2-a504-473544ee190b:my-service.test.443.svc): not a known address, client: redacted, server: kong, request: "GET /716889487 HTTP/1.1", host: "redacted"
```

I notice that the upstream ID in the config (1ea2395c-fe6e-5133-8080-2af3fe4bb0e7) the log is different from the one that the log is complaining (0dc6f45b-8f8d-40d2-a504-473544ee190b).
Moreover, this upstream ID (0dc6f45b-8f8d-40d2-a504-473544ee190b) does not even exist in the kong config under /upstreams.
The same is happening on your case @cdrappier

**Comment by StarlightIbuki** [comment] 2023-10-11 06:35
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:35 UTC
Labels: core/balancer
