### ISSUE TITLE
Old Upstream IPs not getting removed from postgres.

### ISSUE THREAD

**Issue by ksgnextuple** [Kong/kong#10619] opened 2023-04-05 15:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8

### Current Behavior

Hi we are facing this issue in KIC 2.5 and Kong 2.8 on k8s 1.24.6.

We see that the new pod IP does not get updated at all and the old target remains in the postgres DB, with weight as 100. We had to scale down the deployment, delete the data in postgres and restart the deployment. Noticed this for the past few days.

This happens when a new the endpoint IPs are updated on Kubernetes. It is intermittent.

**Comment by hbagdi** [comment] 2023-04-05 20:48
cc  @Kong/team-k8s

**Comment by rainest** [comment] 2023-04-05 21:16
Is the set of IPs in [a config dump](https://docs.konghq.com/kubernetes-ingress-controller/2.5.x/troubleshooting/#dumping-generated-kong-configuration) the same as the set returned by `kubectl get endpoints` for the affected Service? If so, do controller logs indicate any sync errors?

https://github.com/Kong/kubernetes-ingress-controller/issues/2031 was the only bug I know that caused this issue, and it was fixed in 2.1.

To be clear, are the old IPs actually being _used_ and visible in the admin API, or are you looking at Postgres alone? IIRC we handle the targets table in an odd way, but I think that involved deletes actually setting weights to 0 while keeping the row.

**Comment by ksgnextuple** [comment] 2023-04-06 05:02
Hi @rainest thanks for responding. The below is the situation we are facing.

When a new pod of the deployment comes up the endpoint IP of the affected Service do get updated correctly which we confirmed using the `kubectl get endpoints`. 

But on postgres targets collection the old IP remains with weight = 100 and the new IP also get's added with weight = 100.
When requests come in there is an increased latency as Kong tries to forward the request to both the targets.

We have not looked at the Admin API, and looking at Postgres Alone.

Another point to note we are running 3 instances of Ingress Controller Deployment and we have around **400-500** Ingress Resources in our Kubernetes Cluster. 

Attaching some screenshots for reference. You can see there are 2 entries. The first row has the correct latest Target IP. The second one is the stale one which has not been removed.

![image](https://user-images.githubusercontent.com/105336378/230275872-fb34995a-936b-4110-b7cb-83bccd2d18c8.png)

**Comment by ksgnextuple** [comment] 2023-04-06 16:04
Further analysing the logs on the KIC we are seeing the below, and these logs are seen continuously.

`time="2023-04-06T16:00:24Z" level=error msg="could not update kong admin" error="1 errors occurred:\n\tfailed to sync all entities: context deadline exceeded\n" subsystem=dataplane-synchronizer`

**Comment by xkkker** [comment] 2023-04-21 06:36
any updates?

**Comment by xkkker** [comment] 2023-04-21 06:46
I met the same issue here. Sometimes the old target can be deleted after the deployment rollout, the log shows "deleting target ... for upstream ..." .But sometimes it did't update and had the old and new target with 100 weight.

**Comment by ksgnextuple** [comment] 2023-04-22 06:24
Hi
We have not faced the issue after we added the --proxy-timeout-seconds flag to the ingress-controller container. We set this flag to 180 seconds and things are good now.

**Comment by StarlightIbuki** [comment] 2023-10-11 06:37
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:37 UTC
Labels: area/kubernetes, area/ingress-controller
