### ISSUE TITLE
Could not add more than one request-termination plugin

### ISSUE THREAD

**Issue by x-hermit** [Kong/kong#3288] opened 2018-03-13 06:17 UTC
NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

Could not add more than one request-termination plugin

### Steps To Reproduce

1. Create a new API
2. Add plugin request-termination
3. Add another request-termination again in the same API
4. Get a error name already exists

### Additional Details & Logs

- Kong version (0.12.3)
- Kong debug-level startup logs (none)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Centos 7

**Comment by bungle** [comment] 2018-03-19 18:56
What is the use case for multiple request termination plugin for the same API?

**Comment by thibaultcha** [comment] 2018-04-28 20:57
Hi,

This is indeed expected behaviour. The same plugin can only be added once to a given set of `{api_id, consumer_id}` in 0.12 (as well as in 0.13, but Services and Routes replace APIs). I will be closing this as not a bug (GitHub issues are reserved for bug reports only). If you have another use-case for this, please open a discussion on [Kong Nation](http://discuss.konghq.com/) instead (our community forum).

**Closed by thibaultcha** 2018-04-28 20:57 UTC
Labels: pending author feedback
