### ISSUE TITLE
How can i use the 3rd authentication for JWT or AUTH2.0?

### ISSUE THREAD

**Issue by robinwangrubin** [Kong/kong#4324] opened 2019-02-19 02:22 UTC
Hello,
I met a problem:
There are more than 1 million users in my website.
And i wanna use the JWT authentication or Auth2.0 for my users.
Must i create 1 million consumers by myself?

My dream flow is that:
1. User login my website.
2. My own authentication service will check the user's username and password.
3. If passed the check, my own auth service will set a  JWT token in the response header.
4. And then, every in come traffic will take the JWT token to my Kong.
5. The Kong will verify the JWT token by using the 3rd auth service (my own auth service)
6. If passed the check, let the traffic go, if not, reject it.

In this situation, what can i do? 
I know that the auth2.0 enterprise plugin support it. But, is there any open source solution?

in the end, sorry for my bad english.

**Comment by EmersonBrSouza** [comment] 2019-05-20 16:13
I'm curious about that too, because i have same problem. I hope we get a solution!

**Comment by bungle** [comment] 2020-11-25 18:18
Your 3rd party auth server can sign the token using asymmetric key (or even symmetric one), then you can make JWT plugin aware of that and verify by it. On EE there is OAuth 2.0 introspection that makes call to your IDPs introspection endpoint for validation and then there is OpenID Connect plugin that can do that and also verify signatures, and supports things like discovery of keys and endpoints and additional stuff. There is probably also 3rd party plugins that can help you with this.

**Comment by alihossein** [comment] 2021-01-20 11:49
I have the same problem.. anybody found an open-source solution or plugin?

**Comment by StarlightIbuki** [comment] 2023-10-11 06:20
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:20 UTC
Labels: plugins/jwt
