### ISSUE TITLE
I use type=tcp on upstream active health check,but it didn't work

### ISSUE THREAD

**Issue by soulshuangchen** [Kong/kong#5877] opened 2020-05-09 14:09 UTC
![image](https://user-images.githubusercontent.com/40876768/81475633-05238e80-9240-11ea-8a50-e94c5e71d156.png)

I use kong 2.0.3 and cassandra 3.11.4. Now i'am trying to use active health check which like this image, i set type = tcp, but it didn't work, the target can't from unhealth become health automatically . When i set type = http/https ,the active health check can work normally. I don't know why it didn't work, the service which use this upstream  i set protocol = http.  Can anyone  give  me some  suggestions? Thanks.

**Comment by panypopo** [comment] 2020-05-14 12:36
> ![image](https://user-images.githubusercontent.com/40876768/81475633-05238e80-9240-11ea-8a50-e94c5e71d156.png)
> 
> I use kong 2.0.3 and cassandra 3.11.4. Now i'am trying to use active health check which like this image, i set type = tcp, but it didn't work, the target can't from unhealth become health automatically . When i set type = http/https ,the active health check can work normally. I don't know why it didn't work, the service which use this upstream i set protocol = http. Can anyone give me some suggestions? Thanks.

the same issue

**Comment by AshayFernandes** [comment] 2021-04-23 08:18
Facing the same issue any updates on this?  kong version 2.0.4

**Comment by lastboy1228** [comment] 2022-05-27 13:28
I found the code causing the problem: #8872

**Comment by StarlightIbuki** [comment] 2023-10-11 06:35
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:35 UTC
Labels: core/balancer
