### ISSUE TITLE
Kong mixing the traffic for service when IP and Port reused. 

### ISSUE THREAD

**Issue by puneet739** [Kong/kong#7546] opened 2021-07-08 01:41 UTC
Hi Team,
There seem to be an issue with kong, how to work on this kind of scenario, is it a bug?

Problem: We have 2 services, ServiceA and ServiceB both are deployed in AWS ECS Container. And both of them have /status as there healthcheck point.
So Lets assume
ServiceA Deployed on IP-1:PortA
ServiceB Deployed on IP-1:PortB

both of them are successfully registered to kong gateway.

Now suppose ServiceA and ServiceB got restarted multiple times being in same ECS cluster Now serviceB got respaned With IP-1:PortA as that was free port and got reused.

Supposing the serviceB die abrubtly and dont have any gracefull termination policy.

Now when we access
kong.apigwatey.internal.com/serviceA → This traffic is served by both A and B service.

Reason being that Targets are not cleaned by kong and they are actively checked constantly if they turn healthy.

How to deal in this kind of scenario.

**Comment by bungle** [comment] 2021-07-08 07:22
@puneet739, how would you solve the issue?

**Comment by puneet739** [comment] 2021-07-08 07:34
We don't have a solution right now.. this is something common, thought there will be a way available with kong team regarding this.

**Comment by locao** [comment] 2021-07-08 19:41
@puneet739, what do you think about having SRV records with very short TTLs for those services? For example:

```
servicea.apigwatey.internal.com -> IP-1:PortA
serviceb.apigwatey.internal.com -> IP-1:PortB
```

Kong will have to resolve those records frequently, and if the service is out, you should get a name resolve error, thus the target will be marked as unhealthy.

**Comment by puneet739** [comment] 2021-07-08 19:52
@locao 
The problem still remains the same. 

Inital config 
servicea.apigwatey.internal.com -> IP-1:PortA
serviceb.apigwatey.internal.com -> IP-1:PortB


Now there were multiple restarts. Now new config is 
servicea.apigwatey.internal.com -> IP-1:PortX, IP-1:PortA(previously added SRV record , which was marked unhealhty now healhty again because of serviceB)
serviceb.apigwatey.internal.com -> IP-1:PortA(port got reissued to service A), IP-1:PortB(Previous record, which is not unhealthy)

Thus in this scenario. 
servicea.apigwatey.internal.com --> This will roundrobin to both ServiceA and ServiceB. 


Am i missing something here.

**Comment by puneet739** [comment] 2021-07-08 19:58
What i think can be a solution is to purge the unhealthy target on some TTL, that way once the instance got unhealthy and comes back after some time, a new entry is created and it wont mix with other previous records. 

is there anything like this available with kong?

**Comment by puneet739** [comment] 2021-07-08 20:50
Also one pointer, there isnt any specific service registry, the services are in different pods, some in AWS, some in AZURE. But they have and SDK which is responsible for sending requests. Via that we can do whatever we want, but once it will close there wont be a way to send a delete. 
One approach will be to run a cron for cleanup based on tags of last updated time(Custom created) but that wont be an ideal solution.

**Comment by puneet739** [comment] 2021-07-21 18:12
Hi @locao @bungle  any update on this

**Comment by locao** [comment] 2021-07-22 16:02
My suggestion was to update the SRV record every time the service changes its address, so Kong always resolve it and get the current IP/port pair. Other than that, currently Kong doesn't support anything like you need.

**Comment by StarlightIbuki** [comment] 2023-10-11 06:23
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:23 UTC
Labels: core/proxy
