### ISSUE TITLE
Support session storage in hybrid mode

### ISSUE THREAD

**Issue by bdecoste** [Kong/kong#7733] opened 2021-02-05 12:29 UTC
When running Kong in Hybrid mode (i.e. separate control and data planes) there is no way to persist the sessions (i.e. config.storage=kong). I'd like to be able to persist sessions when running in Hybrid mode.

**Comment by StarlightIbuki** [comment] 2023-10-11 06:23
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:23 UTC
Labels: plugins/session
