### ISSUE TITLE
Unable to run an ingress with multiple path

### ISSUE THREAD

**Issue by rachelang09** [Kong/kong#6982] opened 2021-03-31 05:42 UTC
### What was created 

- 2 separated services
- 1 ingress with 2 path

### Yaml file
```
apiVersion: v1
kind: Service
metadata:
  name: svc1
  namespace: rachel-test
  labels:
    app: hello-openshift
spec:
  ports:
    - name: http-service
      port: 8000
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello-openshift
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: svc2
  namespace: rachel-test
  labels:
    app: hello-openshift
spec:
  ports:
    - name: http-svc
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello-openshift
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    konghq.com/strip-path: "true"
    kubernetes.io/ingress.class: kong
  labels:
  name: double-service-ing
  namespace: rachel-test
spec:
  rules:
  - host: double-service.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: svc1
          servicePort: 8000
      - path: /bar 
        backend:
          serviceName: svc2
          servicePort: 8080
```
### What have I tried

1. 2 different services pointing to 2 different app label/selector
2. Paths with same `servicePort`

### Version of Kong and Kubernetes used

- Kong ingress controller 1.1
- Kubernetes 1.19 & 1.18

### Result of trying to curl the url
I tried to curl double-service.com -vvvv and it hit operation timed out

When I create 2 different ingresses with a single path, it works well. I want to be able to run multiple paths in a single ingress as the hostname is the same.

**Comment by EladKeyshawn** [comment] 2021-04-01 20:39
@kikito Hey, can I work on this ? 😄

**Comment by rachelang09** [comment] 2021-04-19 06:35
I recently tested multiple pathing again and it worked. But when I try to use it on grpc, it fails

**Comment by sabir-piludiya** [comment] 2021-05-10 12:08
@rachelang09 How did you solve this.? I wonder the same issue is in my ingress.

**Comment by fffonion** [comment] 2021-05-12 17:13
Closing as the issue is solved, please re-open if the issue persists : )

**Closed by fffonion** 2021-05-12 17:13 UTC
Labels: area/ingress-controller
