### ISSUE TITLE
Is kong.tools.batch_queue thread safe ?

### ISSUE THREAD

**Issue by shettyh** [Kong/kong#8215] opened 2021-12-18 05:25 UTC
### Discussed in https://github.com/Kong/kong/discussions/8199

<div type='discussions-op-text'>

<sup>Originally posted by **shettyh** December 15, 2021</sup>
Wanted to check if `kong.tools.batch_queue` is thread safe </div>

**Comment by Tieske** [comment] 2021-12-19 11:32
what are your specific concerns? OpenResty does not a standard threading model like most applications. It mixes cooperative multi threading (requests and light threads) with preemptive multi threading (workers and SHM access mostly).

So there is no straight forward answer to your question I'm afraid without more details

**Comment by shettyh** [comment] 2021-12-19 14:17
@Tieske thanks for the response. I am planning to use `batch_queue` for grouping and delaying the cache invalidations and writing to DB in batch. If this is the use case that involves DB IO, does it still safe to use batch queue without worrying about any race conditions ?

**Comment by Tieske** [comment] 2021-12-19 19:42
@kikito iirc you were involved with the queue, correct?

**Comment by kikito** [comment] 2021-12-20 12:58
Hello shettyh,

> does it still safe to use batch queue without worrying about any race conditions ?

The answer to that question is a Yes, but it has lots of asterisks. It will be thread-safe as long as:
* You don't use create or manipulate your own threads (with the `ngx.thread.*` family of functions)
* There is at most one queue per worker. Every call to `add` affects only said queue. (The way to typically achieve this would be having a "global to the module" variable on the Lua file using the queue, initializing it on the `init_worker` phase, and then calling `add` from that file when needed).
* There is no "sharing of pointers" between workers through backchannels/memory mapping/external libraries.

> and add method will be called from multiple light threads from a single worker ( as per my understanding )
The terminology of what a "light thread" means changes a lot, I think it's better to keep terms in POSIX when possible.

On nginx, each worker's job is executed by a single OS (POSIX/"heavy") thread, which does both proxy code and timer tasks. Each time the thread gets blocked by I/O it "switches" to a different task, but there there's never multiple CPUs executing timers and proxying for a single worker. So as long as queues are "local" to each worker, there can be no "multithread problems" - nothing else can call `add` while the thread is doing a `flush`.

This might help you understand the underlying threading model: https://konghq.com/blog/api-gateway-request/

**Comment by kikito** [comment] 2021-12-20 16:24
This is a dupe of #8199, so let's continue the discussion there.

**Closed by kikito** 2021-12-20 16:24 UTC
