### ISSUE TITLE
all the routes and upstreams will be put after only one k8s services/endpoints are rolling update

### ISSUE THREAD

**Issue by zffocussss** [Kong/kong#9051] opened 2022-07-05 08:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong 2.7

### Current Behavior

for example ,there are 10 services/routes ,which services are corresponding to k8s services.only service A is required to be under deployment/update.but the rest services/routes are updated,as I see many PUT request in admin log,many of which is not related with service A and upstream A.

### Expected Behavior

only the specific routes/upstreams are required to put/update

### Steps To Reproduce

```markdown
1.kubectl rollout restart deploy/mydepoy
2.kubetcl logs -f kong
3.there are many put requests to admin http api
```

**Comment by zffocussss** [comment] 2022-07-05 10:46
will kong rebuild all the routes and upstreams once only one of targets is updated?
in my case,only one k8s endpoint is updated,but the whole upstreams and routes are affected,I use k8s crds to configure kong ingress/router.

127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /plugins/schema/common HTTP/1.1" 200 107 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /upstreams?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 16103 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /upstreams/05d7fb3e-3626-4940-a19a-3ec177810640/targets?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 236 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /upstreams/2a5df009-3496-46e5-97c2-87f9fa8ed434/targets?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 234 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /mtls-auths?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 404 23 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /upstreams/41288b5e-d8e1-491f-8824-e3fed30c9a12/targets?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 247 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /services?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 7300 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /routes?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 12767 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /upstreams/428044bd-4a2c-4630-a7ec-f473478a670d/targets?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 235 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /plugins?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 6260 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /ca_certificates?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 23 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /snis?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 1449 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /jwts?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 23 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /consumers?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 23 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /key-auths?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 23 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /hmac-auths?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 23 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /oauth2?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 23 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /acls?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 23 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /basic-auths?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 23 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /upstreams/460fd591-2084-42e5-8dc3-3c54978e119a/targets?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 235 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /upstreams/4f1c3ee8-67f4-4f9c-a015-b50e9381dc49/targets?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 236 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /certificates?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 53229 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /upstreams/5ecb7b2b-371c-4074-b2eb-81c694ce5dda/targets?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 244 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /upstreams/8309afc4-f52d-406f-af4e-748e65d01d18/targets?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 244 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /upstreams/9c139daf-0ab6-4d8d-a614-e098a2437e7b/targets?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 243 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /upstreams/9c7e028b-a893-479c-8d70-b7d8ff05b416/targets?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 264 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /upstreams/acb92fe3-2768-4479-b989-6e22096ac14d/targets?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 236 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /upstreams/bc4bb0a2-e83f-447e-a140-9b9bb949a618/targets?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 236 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /upstreams/c60f4a78-d6ca-4296-88de-e84227d4cb4d/targets?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 253 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /upstreams/d51b0abe-ba88-4d05-8321-b9f88775d820/targets?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 249 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /upstreams/e83a9c60-968e-471c-9b95-6f789e643934/targets?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 235 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /upstreams/ef5632de-f2be-4899-8523-113d11d96cb3/targets?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 235 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:38 +0000] "GET /upstreams/f40cd34e-19d7-472a-b1f3-50c2981ec9cf/targets?size=1000&tags=managed-by-ingress-controller HTTP/1.1" 200 244 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:39 +0000] "PUT /upstreams/9c7e028b-a893-479c-8d70-b7d8ff05b416 HTTP/1.1" 200 936 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:39 +0000] "PUT /upstreams/41288b5e-d8e1-491f-8824-e3fed30c9a12 HTTP/1.1" 200 951 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:39 +0000] "PUT /upstreams/bc4bb0a2-e83f-447e-a140-9b9bb949a618 HTTP/1.1" 200 941 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:39 +0000] "PUT /upstreams/2a5df009-3496-46e5-97c2-87f9fa8ed434 HTTP/1.1" 200 941 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:39 +0000] "PUT /upstreams/428044bd-4a2c-4630-a7ec-f473478a670d HTTP/1.1" 200 937 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:39 +0000] "PUT /upstreams/4f1c3ee8-67f4-4f9c-a015-b50e9381dc49 HTTP/1.1" 200 937 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:39 +0000] "PUT /upstreams/9c139daf-0ab6-4d8d-a614-e098a2437e7b HTTP/1.1" 200 945 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:39 +0000] "PUT /upstreams/8309afc4-f52d-406f-af4e-748e65d01d18 HTTP/1.1" 200 946 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:39 +0000] "PUT /upstreams/5ecb7b2b-371c-4074-b2eb-81c694ce5dda HTTP/1.1" 200 949 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:39 +0000] "PUT /upstreams/c60f4a78-d6ca-4296-88de-e84227d4cb4d HTTP/1.1" 200 946 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:39 +0000] "PUT /upstreams/460fd591-2084-42e5-8dc3-3c54978e119a HTTP/1.1" 200 955 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:39 +0000] "PUT /upstreams/d51b0abe-ba88-4d05-8321-b9f88775d820 HTTP/1.1" 200 936 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:39 +0000] "PUT /upstreams/e83a9c60-968e-471c-9b95-6f789e643934 HTTP/1.1" 200 949 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:39 +0000] "PUT /upstreams/f40cd34e-19d7-472a-b1f3-50c2981ec9cf HTTP/1.1" 200 949 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:39 +0000] "PUT /upstreams/ef5632de-f2be-4899-8523-113d11d96cb3 HTTP/1.1" 200 954 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:39 +0000] "PUT /upstreams/acb92fe3-2768-4479-b989-6e22096ac14d HTTP/1.1" 200 948 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:39 +0000] "PUT /upstreams/05d7fb3e-3626-4940-a19a-3ec177810640 HTTP/1.1" 200 944 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:40 +0000] "PUT /routes/15b54849-38be-4d52-8134-ffaca89f2270 HTTP/1.1" 200 537 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:40 +0000] "PUT /routes/398239b1-61bc-4665-b5a4-61c4e4185684 HTTP/1.1" 200 544 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:40 +0000] "PUT /routes/72263fb7-1f01-4b45-ac1a-93e12f078062 HTTP/1.1" 200 595 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:40 +0000] "PUT /routes/8cbdd052-b9c0-4688-ad71-da132c7da9d4 HTTP/1.1" 200 546 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:40 +0000] "PUT /routes/93b8441e-9cd9-402f-a671-0f039361fe75 HTTP/1.1" 200 534 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:40 +0000] "PUT /routes/2e6968f7-24cf-4f30-90cc-a2753300987f HTTP/1.1" 200 540 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:40 +0000] "PUT /routes/25427918-a5be-4b1c-8e5c-aab46f7c00c0 HTTP/1.1" 200 531 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:40 +0000] "PUT /routes/16ccd293-2485-4f17-837e-64c2f3bcff00 HTTP/1.1" 200 520 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:40 +0000] "PUT /routes/3e4487a2-fbb9-4f8a-90d5-4b60fce668e8 HTTP/1.1" 200 545 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:40 +0000] "PUT /routes/40cae862-f8df-4020-9f51-d1fd00d6e09a HTTP/1.1" 200 577 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:40 +0000] "PUT /routes/4d62b0e7-3aab-46bf-b34a-49087c958c8f HTTP/1.1" 200 538 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:40 +0000] "PUT /routes/57f258bc-7dd9-499c-9ffc-6bd8bf843738 HTTP/1.1" 200 548 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:40 +0000] "PUT /routes/94b962df-9ff5-4a21-a374-431e2c4e7d12 HTTP/1.1" 200 577 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:40 +0000] "PUT /routes/3e50c379-0d53-4666-a56f-8c0b21e0dfe9 HTTP/1.1" 200 573 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:40 +0000] "PUT /routes/983245d9-7215-4908-98f9-df05f241df66 HTTP/1.1" 200 561 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:40 +0000] "PUT /routes/d51ea4c9-c338-440f-818d-4c1936c4a493 HTTP/1.1" 200 535 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:40 +0000] "PUT /routes/c146eeea-67d5-46cb-b30d-be381b6ee7ab HTTP/1.1" 200 525 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:40 +0000] "PUT /routes/a74559f9-9caa-4c18-be4d-8b2115cb2825 HTTP/1.1" 200 544 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:40 +0000] "PUT /routes/e434134f-385c-496f-8004-64f488bd773a HTTP/1.1" 200 645 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:40 +0000] "PUT /routes/c60711b6-6206-46c3-a0da-406952cc5fa5 HTTP/1.1" 200 555 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:40 +0000] "PUT /routes/ea7ce3ce-1fcf-4427-b036-25b34f7bd38e HTTP/1.1" 200 575 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:40 +0000] "PUT /routes/f39e6464-f91e-4800-88d9-53e18a4f2b75 HTTP/1.1" 200 533 "-" "Go-http-client/1.1"
127.0.0.1 - - [05/Jul/2022:07:39:40 +0000] "PUT /routes/ff1b2003-a931-468d-a9fc-f374151ce67e HTTP/1.1" 200 544 "-" "Go-http-client/1.1"

**Comment by fffonion** [comment] 2022-08-22 22:53
cc @Kong/team-k8s

**Comment by rainest** [comment] 2022-08-23 19:25
Which KIC version is this? Best guess is that this is/was the discrepancy between what deck expected as defaults and what the actual defaults were for a given Kong version in previous releases: there were a number of fields were we didn't have a hard-coded default in deck, but that were automatically populated by Kong, and any time you needed some unrelated change, we thought we needed to remove the auto-populated field.

Current versions use a revised system where deck interrogates the admin API to determine default fields, so it no longer issues unnecessary updates.

**Comment by StarlightIbuki** [comment] 2023-10-11 06:36
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:36 UTC
Labels: area/kubernetes
