### ISSUE TITLE
SNI can't be used if upstream target definition using IP:Port

### ISSUE THREAD

**Issue by dmitriivoronov** [Kong/kong#9785] opened 2022-11-18 12:38 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues
Linked discussion:
https://github.com/Kong/kong/discussions/9247

### Kong version (`$ kong version`)

2.8.1

### Current Behavior

One of our applications is using Kong for HTTPS connection to external system. During the communication we also must send SNI hostname as a value which is CN/SAN value of the server certificate or a hostname which is covered by a CN/SAN of wildcard server certificate.
_CN= Common Name
SAN=Subject Alternative Name_
> Problem: SNI based upstream target can not be used if upstream needs to be called based on ip-address and port

We cannot resolve the DNS name for the upstream partner (different company private network without possible DNS resolution on our side).
For this reason we need to use IP-address and port in upstream / target configuration to be able to use SNI based endpoint selection on the upstream partner side during TLS handshake a correct SNI value needs to be send correlating to the server certificate they use on their side.
(They also run on their side ingress controller which selects endpoint based on information of hostname / sni-name)
This is currently not possible in kong to configure it this way.

We tried to analyze current implementation of SNI and it looks only on upstream name and does not look for any sni configuration with or without client-certificate configurations.
>
[SNI code](https://github.com/Kong/kong/blob/2.8.3/kong/templates/nginx_kong_stream.lua#L125) which looks only on [upstream](https://github.com/Kong/kong/blob/2.8.3/kong/templates/nginx_kong_stream.lua#L76)

### Expected Behavior

When we request a particular service with a configured route in kong it should look to the configured kong service which references the relevant upstream and finally upstream targets.
The upstream config needs to be extended with an optional value of **“https_sni”** which needs to be used during the TLS handshake with the upstream target host and port.
This **_SNI-name_** should be by default the name of the upstream object of kong. 
If an optional value of **“https_sni”** is configured, this value needs to be used for the TLS handshake as **SNI** value.

_Additional hint:
The possibility to configure **“https_sni”** on kong upstream objects is already existing for the “healthcheck” configuration possibility. But not for the upstream object and the configured targets behind the upstream config itself._

### Steps To Reproduce

```markdown
1.	Create service which will be looking on some service, e.g haproxy with nginx as background
- should have multiple server certificates listening to multiple hostnames. All hostnames need to use the same IP address.
2.	Create route /test-route in kong
3.	Configure service and upstream using ip address and port of the haproxy or nginx upstream server
Use the name “upstream-name.remote” for the upstream object in the kong configuration
4.	Run some traffic sniff on kong instance, e.g tcpdump(or kubectl sniff pod) to capture a traffic
5.	Run a curl or postman GET request to https://kong/test-route
6.	Check traffic sniffed output for SNI.
(There should be the name of the upstream object “upstream-name.remote” as value of SNI during the handshake be visible, which is not the case)
```

### How it should work after implementation:
1.	Create service which will be looking on some service, e.g haproxy with nginx as background should have multiple server certificates listening to multiple hostnames. All hostnames/certificates need to use the same ip-address:

- -	default (should be default certificate)
- -	upstream-name.remote
- -	upstream-name.overwritten

These are the hostnames of upstream destination service which needs to be used for this test case.

2.	Create route /test-route in kong
3.	Configure service and upstream using IP address and Port of the haproxy or nginx upstream server
Use the name **“upstream-name.remote”** for the upstream object in the kong configuration
4.	Configure for the upstream object **“upstream-name.remote”** the optional **“https_sni”** key to the value **“upstream-name.overwritten”**
5.	Run some traffic sniff on kong instance, e.g tcpdump to capture a traffic
6.	Run a curl or postman GET request to https://kong/test-route
7.	Check traffic sniffed output for SNI.
(There should be the value of **“upstream-name.overwritten”** used as **SNI** name during the TLS handshake).

**Comment by mayocream** [comment] 2022-11-30 04:06
Hi @dmitriivoronov, thanks for reporting this; we have created an internal task to track this issue. KAG-129

**Comment by ZeeFiix** [comment] 2022-12-05 16:14
Hi @mayocream 
i think it is related to the last discussions in https://github.com/Kong/kong/issues/5580

**Comment by StarlightIbuki** [comment] 2023-10-18 08:42
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md?rgh-link-date=2023-10-18T08%3A39%3A47Z) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-18 08:42 UTC
Labels: core/proxy
