### ISSUE TITLE
Default db_update_frequency config value seems to breaks cache when db dies

### ISSUE THREAD

**Issue by scooper91** [Kong/kong#3068] opened 2017-12-01 14:47 UTC
Hi!

I asked in the Kong Gitter chat about this yesterday (30/11) and were advised to make an issue here.

### Summary

When no override for `db_update_frequency` is provided in `kong.conf`, killing the underlying database results in an instant 404 when hitting a cached route. Expected behaviour would be for the cache ttl to be honoured.

> Kong maintains a cache of this data so that there is no need for a database round-trip while proxying requests

When overriding `db_update_frequency` in `kong.conf`, killing the underlying database results in the cache ttl being honoured.

### Steps To Reproduce

1. Using docker-compose to spin up a PostgreSQL database, and a Kong-router instance (using official images)
2. Add route to proxy any URL
3. Do not override `db_update_frequency`
4. Start both containers 
5. Hit the route (to warm the cache)
6. Stop (`docker stop`) the database container
7. Hit the same route again

Results in 404 as soon as database container is stopped.

Expected behaviour: Route is still cached (for 60 minutes).

### Additional Details & Logs

Using Kong:0.11.1 official Docker container.

The endpoint is not configured using any plugins.

Using default `db_update_frequency` (not set in `kong.conf`)
```sh
[root@60cabb76bbbf /]# kong start -vv
2017/12/01 12:25:07 [verbose] Kong: 0.11.1
2017/12/01 12:25:07 [debug] ngx_lua: 10008
2017/12/01 12:25:07 [debug] nginx: 1011002
2017/12/01 12:25:07 [debug] Lua: LuaJIT 2.1.0-beta2
2017/12/01 12:25:07 [verbose] reading config file at /etc/kong/kong.conf
...
2017/12/01 12:25:07 [debug] database = "postgres"
2017/12/01 12:25:07 [debug] db_cache_ttl = 20
2017/12/01 12:25:07 [debug] db_update_frequency = 5
```

Overriding `db_update_frequency`
```sh
[root@16637ce1b636 /]# kong start --vv
2017/12/01 12:28:05 [verbose] Kong: 0.11.1
2017/12/01 12:28:05 [debug] ngx_lua: 10008
2017/12/01 12:28:05 [debug] nginx: 1011002
2017/12/01 12:28:05 [debug] Lua: LuaJIT 2.1.0-beta2
2017/12/01 12:28:05 [verbose] reading config file at /etc/kong/kong.conf
...
2017/12/01 12:28:05 [debug] database = "postgres"
2017/12/01 12:28:05 [debug] db_cache_ttl = 20
2017/12/01 12:28:05 [debug] db_update_frequency = 10
```

We're also seeing different behaviour if we use `docker kill` rather than `docker stop` to kill the db container, but we can create a separate issue if necessary.

Let me know if you need any more details.

Thanks!

(@danjamesmay)

**Comment by bungle** [comment] 2017-12-08 00:25
@scooper91 thank you for the report. Let us investigate this a bit.

**Comment by thibaultcha** [comment] 2018-01-31 03:01
@scooper91 Hi,

Thanks for reporting this. I have investigated, reproduced and narrowed down the issue. Unfortunately, we'll need some time to provide a complete fix for this. The cache is per NGINX worker, and if some never get woken up to process request while the database is up and running, they will eventually once the database is unreachable, except that they won't be able to retrieve the update list.

For now, know that Kong will be more resilient to such databases failure scenarios if you stop and restart Kong _once your APIs are added_. I will write a more thorough explanation once I have some more time, or maybe a fix.

**Comment by thibaultcha** [comment] 2018-02-16 19:22
When I reproduced this on my side, it seemed to boil down to the worker-based nature of NGINX. Each worker maintains its own router in their own Lua VMs, and this router is lazily built (upon the first request) _and_ rebuilt upon configuration changes (invalidation events from other workers or nodes in the cluster).

Since the kernel will distribute workload across the different workers, different requests can (and will) be handled by different workers at times, which means hitting different Lua VMs.

Now let's take a detour into how the router is being built: as of today, we select _all_ APIs at once (making the router build itself incrementally is still on our TODO list), and each worker will query the database on its own and directly build its router in the Lua VM. Usually, we store such database-fetched values in an shared memory zone to avoid cache stampede effects on the database, but we do not in that one particular case to save shared memory and because we initially considered "router rebuilds" to be occasional.

But that is precisely the issue: start a fresh Kong node without a router built. Make a few requests that are handled by one worker (which builds its router). Stop the database. Make a few requests that are handled by another router -> oops, the database is unreachable.
Building the router when starting Kong fixes this issue but it does not fix cache invalidation rebuilds.

Hope that helps anybody who is investigating this issue or thinking of a fix - PRs welcome!

**Comment by bungle** [comment] 2019-01-03 19:30
I think this PR is a try to fix most of the issues around this: #4102 (it does not implement incremental router rebuilding).

**Comment by thibaultcha** [comment] 2019-01-03 19:57
This should have been fixed already by 2 changes:
- First, by updating the default value of `db_cache_ttl` to `0` (https://github.com/Kong/kong/pull/3492), which always was the long term goal (`db_cache_ttl` was introduced as a safety measure against stale values when we first rolled out the new DB caching implementation). Now, the cache does not expire anymore unless changes are made through the Admin API. It is worth noting that one can already safely make this change to this config value on their side, without upgrading their Kong node to a new version or anything.
- Second, by the new "resurrect stale" feature of mlcache (https://github.com/thibaultcha/lua-resty-mlcache/pull/52), which is leveraged by Kong since [0.14.0](https://github.com/Kong/kong/blob/master/CHANGELOG.md#0140---20180705) and ensures that stale cached values are served when the database is down. Users _do need_ to upgrade Kong to 0.14.0+ to benefit from this.

**Comment by thibaultcha** [comment] 2019-01-03 19:59
Oh, I overlooked something, which is that router rebuilds bypassed the cache _and_ always used a `0` TTL value since day one... One of the "quick and easy" solutions I suggested back then was to store Routes and Services in the cache to benefit from those 2 points above, but @bungle's solution is more valid, even without incremental router rebuilds.

Sorry for the noise!

**Comment by bungle** [comment] 2019-08-15 14:57
We have reworked this quite a bit with `1.2.x` release, so I think I will close this for now. There is also https://github.com/Kong/kong/pull/4903 that will make Kong even more resilient.

**Closed by bungle** 2019-08-15 14:57 UTC
Labels: task/needs-investigation
