### ISSUE TITLE
Restore check if schema exists before trying to create in bootstrap

### ISSUE THREAD

**Issue by DeoMortis** [Kong/kong#5327] opened 2019-12-12 08:14 UTC
### Summary
In Kong 0.12.2 there was a feature introduced: to not require schema creation permission during migration if the schema already exists.
https://github.com/Kong/kong/commit/9beaa6258ae924a766d09bb0e9ddcf44866eb2cc
But it is no longer present on Kong 1.X.

Old file responsible: https://github.com/Kong/kong/blob/0.12.2/kong/dao/migrations/cassandra.lua line 34
New file responsible: https://github.com/Kong/kong/blob/1.4.2/kong/db/strategies/cassandra/connector.lua line 877

Now the migration fails if cassandra user for Kong doesn't have permissions to create schema.
I think that was a nice feature.
Is there some reason why it was dropped?

**Comment by bungle** [comment] 2019-12-12 11:11
The comment there says (https://github.com/Kong/kong/blob/1.4.2/kong/db/strategies/cassandra/connector.lua#L877):
```
 -- create keyspace if not exists
```

Arguably it does not do what the comment says, so I will mark this as a bug then.

**Comment by hishamhm** [comment] 2019-12-16 15:25
Looks like the root of the problem is that if you have permissions to _use_ a keyspace but not to _create_ it, then `CREATE KEYSPACE IF NOT EXISTS` fails even if the keyspace already exists.

If that's the case, then yes, we should add that check from 0.x back into our migrations logic.

**Comment by bungle** [comment] 2019-12-20 21:20
Closing this as we added it back with #5361. Sorry for all inconvenience, must have something to do with switching the migration framework.

**Closed by bungle** 2019-12-20 21:20 UTC
Labels: task/bug
