### ISSUE TITLE
Healthchecks not respecting configured intervals

### ISSUE THREAD

**Issue by onematchfox** [Kong/kong#7409] opened 2021-06-01 07:47 UTC
### Summary
- Kong version - `2.4.1`

When an upstream fails to respond to an active healthcheck in under `100ms`, additional healthchecks are subsequently scheduled rather than waiting the the current one to complete. This leads to excessive healthchecks and, depending on configuration, this can result in upstreams being marked as unhealthy after a "single" healthcheck interval as well as a thundering herd issue.

### Additional Details & Logs

See https://github.com/Kong/lua-resty-healthcheck/pull/72

**Comment by StarlightIbuki** [comment] 2023-10-11 06:35
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:35 UTC
Labels: core/balancer
