### ISSUE TITLE
balancer.lua:672: attempt to index local 'upstreams_dict' (a nil value)

### ISSUE THREAD

**Issue by luo985** [Kong/kong#6302] opened 2020-09-03 01:39 UTC
### Summary

i found some request return error message 'An unexpected error occurred';  the kong error log is:

[error] 73818#0: *26008196135 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/runloop/balancer.lua:672: attempt to index local 'upstreams_dict' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/kong/runloop/balancer.lua: in function 'get_upstream_by_name'
	/usr/local/share/lua/5.1/kong/runloop/balancer.lua:693: in function 'get_balancer'
	/usr/local/share/lua/5.1/kong/runloop/balancer.lua:1080: in function 'execute'
	/usr/local/share/lua/5.1/kong/runloop/handler.lua:891: in function 'balancer_execute'
	/usr/local/share/lua/5.1/kong/runloop/handler.lua:1264: in function 'after'
	/usr/local/share/lua/5.1/kong/init.lua:789: in function 'access'
	access_by_lua(nginx.conf:124):2: in main chunk,

### Additional Details & Logs

- Kong version (2.1.3)

**Comment by bungle** [comment] 2020-09-03 07:46
Any clues of how ro reproduce would be helpful.

**Comment by murillopaula** [comment] 2020-09-03 11:42
can you try this? https://github.com/Kong/kong/pull/6104

**Comment by luo985** [comment] 2020-09-07 05:58
config is：
worker_consistency = eventual
worker_state_update_frequency = 20

**Comment by murillopaula** [comment] 2020-09-07 13:08
please try #6104

**Comment by luo985** [comment] 2020-09-11 09:21
@murillopaula 
i try your commit,  problems  still exist。get new  error message :
`2020/09/11 17:13:13 [error] 18279#0: *7879463 [lua] balancer.lua:1123: execute(): DNS resolution failed: dns server error: 3 name error. Tried: ["(short)upstream.cl.debug.1.pyf0910.system.1599740418431crk:(na) - cache-miss","upstream.cl.debug.1.pyf0910.system.1599740418431crk:33 - cache-hit/dns server error: 3 name error","upstream.cl.debug.1.pyf0910.system.1599740418431crk:1 - cache-hit/dns server error: 3 name error","upstream.cl.debug.1.pyf0910.system.1599740418431crk:5 - cache-hit/dns server error: 3 name error"], client: 192.168.251.197, server: kong, request: "GET / HTTP/1.1", host: "pyf0910.101.com"`

**Comment by murillopaula** [comment] 2020-09-11 13:10
@luo985 ok, thanks for trying the commit

what are the steps you are taking to reproduce? based on your comment here

> when change upstream info, it happened.

it seems like you are doing an upstream PATCH while at the same time making requests to this upstream?

it's in our roadmap to verify the stability of the balancer concurrency (especially in the `eventual` worker consistency) to fix problems like this one

**Comment by luo985** [comment] 2020-09-14 01:04
@murillopaula 
`it seems like you are doing an upstream PATCH while at the same time making requests to this upstream?`
yes, this way can reproduce

**Comment by jeremyjpj0916** [comment] 2021-01-26 16:00
Looks like we saw this issue as well:

Luckily occurred in our Stage region, DB's seemed un-impacted and were healthy during the incident. Rolling redeploying Kong node fixed traffic, customers were getting the typical 500 HTTP Status and standard Kong error response when there are internal issues(an unexpected error has occurred or w/e it is). 

Note we use eventual consistency setting as well:

![image](https://user-images.githubusercontent.com/31913027/105869644-6ef9e900-5fc5-11eb-8f5c-13d9d406291a.png)

```
stack traceback:
coroutine 0:
	...al/kong/luarocks/share/lua/5.1/kong/runloop/balancer.lua: in function 'get_upstream_by_name'
	...al/kong/luarocks/share/lua/5.1/kong/runloop/balancer.lua:693: in function 'get_balancer'
	...al/kong/luarocks/share/lua/5.1/kong/runloop/balancer.lua:1080: in function 'execute'
	...cal/kong/luarocks/share/lua/5.1/kong/runloop/handler.lua:891: in function 'balancer_execute'
	...cal/kong/luarocks/share/lua/5.1/kong/runloop/handler.lua:1264: in function 'after'
	/usr/local/kong/luarocks/share/lua/5.1/kong/init.lua:788: in function 'access'
	access_by_lua(nginx.conf:146):2: in main chunk, client: 74.203.202.5, server: kong, request: "POST /api/stage/service/v2.0/ HTTP/1.1", host: "gateway-stage.company.com"
2021/01/18 10:56:20 [error] 85#0: *3776668 lua entry thread aborted: runtime error: ...al/kong/luarocks/share/lua/5.1/kong/runloop/balancer.lua:672: attempt to index local 'upstreams_dict' (a nil value)
```

Kong version: 

```
/ $ kong version --vv
2021/01/26 15:36:40 [verbose] Kong: 2.1.4
2021/01/26 15:36:40 [debug] ngx_lua: 10015
2021/01/26 15:36:40 [debug] nginx: 1015008
2021/01/26 15:36:40 [debug] Lua: LuaJIT 2.1.0-beta3
```

Are there newer releases > the 2.1.4 series that likely have a fix in place? I suspect its a rare edge case because we have been running 2.1.4 for months and only seen this in one non-prod customer facing environment. Nonetheless would like to iterate to a newer version with a suspected fix so I don't have to worry about this happening in prod. Guessing some case where realtime traffic paired with admin API updates and underlying shard dicts in a state of being reconciled and updated caused the npe, which I know used to cause issues on router updates but eventual consistency helped leverage an "old" copy of the router when a new router was being built out in flight. Maybe a similar approach can be used with the ```upstreams_dict``` list of upstreams?

**Comment by jeremyjpj0916** [comment] 2021-02-05 08:51
cc @bungle , any idea what could be causing the above ^ ? Only seen it once in the few months we have been on 2.1.4 so its likely not something to come up frequently but anything you can think of that would prevent ```upstreams_dict``` from being nilled at runtime?

**Comment by jeremyjpj0916** [comment] 2021-02-12 15:49
Seems the code was this block:
```
------------------------------------------------------------------------------
-- Finds and returns an upstream entity. This function covers
-- caching, invalidation, db access, et al.
-- @param upstream_name string.
-- @return upstream table, or `false` if not found, or nil+error
local function get_upstream_by_name(upstream_name)
  local ws_id = workspaces.get_workspace_id()

  local upstreams_dict, err = get_all_upstreams()
  if err then
    return nil, err
  end

  local upstream_id = upstreams_dict[ws_id .. ":" .. upstream_name]
  if not upstream_id then
    return false -- no upstream by this name
  end

  return get_upstream_by_id(upstream_id)
end
```
Where ```upstreams_dict``` can be nil from the response of ```get_all_upstreams()```, maybe a check should be put in place to retry ```get_all_upstreams()``` again, or something to avoid getting a npe?

**Comment by StarlightIbuki** [comment] 2023-10-11 06:20
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:20 UTC
Labels: task/bug, core/balancer
