### ISSUE TITLE
Upstream prematurely closed connection while reading response header from upstream

### ISSUE THREAD

**Issue by shettyh** [Kong/kong#10165] opened 2023-01-25 05:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.3

### Current Behavior

After we upgraded kong from 2.0.3 to 2.8.3 we started seeing increase in `502` errors from Kong with log `Upstream prematurely closed connection while reading response header from upstream`. Because of this about 1 request fails every 2 seconds during peak traffic.

Number of 502 increase as the number of requests increase, we are seeing increased nginx timer delay and increased number of connections in waiting state. 

![Screenshot 2023-01-25 at 11 01 49 AM](https://user-images.githubusercontent.com/13759916/214487611-e3bca9d3-5505-4412-b95d-32208fe34fd6.png)

![image](https://user-images.githubusercontent.com/13759916/214487954-0fd1d027-9ee3-4369-8615-8c6c09eb0c93.png)

This issue is observed only with a upstream that is a PHP backend and behind Apache server, this upstream is serving high traffic.

We have tried tweaking upstream keepalive setting but no luck. 
#### Previous Config
-  KONG_NGINX_UPSTREAM_KEEPALIVE : 3600
- KONG_NGINX_UPSTREAM_KEEPALIVE_REQUESTS: 1000

#### New config ( as part of tweaking )
- KONG_UPSTREAM_KEEPALIVE_POOL_SIZE: 100
- KONG_UPSTREAM_KEEPALIVE_MAX_REQUESTS: 1000
- Removed both previous configs
 

Also after upgrading we started seeing increased latency to other services from Kong, like redis and other http calls to microservices, because of this lot of these requests are timing out or p99 is very high comparatively. Both of the issues can be related but not sure

### Expected Behavior

No `502` errors at Kong due to this error

### Steps To Reproduce

- Upgrade the Kong from 2.0.3 to 2.8.3 with same configurations as before

**Comment by locao** [comment] 2023-01-26 15:53
Hi @shettyh! Thanks for your report. 

Do you see any `[error]` level log messages when this issue happens? Can you share them?

Some plugins can block Nginx workers for long periods and that can cause requests to fail. What plugins are you using, even on unrelated routes? Are there any custom plugins?

**Comment by shettyh** [comment] 2023-01-28 04:09
@locao thanks for the response. Other than this error log below, not seeing any other error log 
```
[error] 1122#0: *58876376 upstream prematurely closed connection while reading response header from upstream, client: 
```

>Some plugins can block Nginx workers for long periods and that can cause requests to fail. What plugins are you using, even on unrelated routes? Are there any custom plugins?

Nothing new we are using with 2.8.3, all are same as before (2.0.3). Is there any specific changes in new version that can cause this ?.

There is only one custom plugin that uses `timer` other than `zipkin` plugin, custom plugin is just doing http call on specified interval using timers

**Comment by locao** [comment] 2023-01-30 13:45
Using `timer` is not a problem in this case. The issue exists when Nginx is blocked in a non-yielding code for long time. In Kong 2.8.3 this has been seen with Prometheus plugin, but only in special cases.

You may want to take a look at #3785, it might be the same case.

**Comment by shettyh** [comment] 2023-02-06 05:09
@locao thanks for the reply. We were able to fix this issue by following below steps

- Disable new upstream keep-alive by setting `KONG_UPSTREAM_KEEPALIVE_POOL_SIZE` to `0`
- Enabled Nginx keep-alive by setting `KONG_NGINX_UPSTREAM_KEEPALIVE`

Any inputs on what could be wrong ?

**Comment by xuezier** [comment] 2023-03-02 09:46
This problem is because apache closed the connection earlier than kong. 

You can view this document: https://httpd.apache.org/docs/2.4/mod/core.html#keepalivetimeout, the keepalivetimeout of apache is default 5s，kong is 60s. You can set apache keepalivetimeout to 65s to ensure that kong closes the connection earlier than apache

**Comment by hbagdi** [comment] 2023-03-02 18:50
Closing considering the issue is sufficiently resolved, please reopen if needed.

**Closed by hbagdi** 2023-03-02 18:50 UTC
Labels: pending author feedback

**Comment by zffocussss** [comment] 2024-06-12 10:06
I met the same errors in the kong log,but the upstream did not received the request from kong
