### ISSUE TITLE
[Cassandra error] failed to insert cluster lock: [Invalid] TTL is not yet supported.

### ISSUE THREAD

**Issue by agarwal-nitesh** [Kong/kong#5819] opened 2020-04-24 14:53 UTC
### Summary
Trying to setup kong with aws MCS. After all the configurations, I am getting an error while running `kong migrations up -c kong/kong.conf --vv` 

### Steps To Reproduce

1. Setup kong with database set to Cassandra,
2. Try starting the kong, it will ask to run kong migrations up with database information,
3. Run kong migrations up -c </path/to/kong.conf> --vv

### Additional Details & Logs

```
2020/04/24 14:46:58 [debug] loading subsystems migrations...
2020/04/24 14:46:58 [verbose] retrieving keyspace schema state...
2020/04/24 14:46:58 [verbose] schema state retrieved
Error: 
/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:108: [Cassandra error] failed to insert cluster lock: [Invalid] TTL is not yet supported.
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:108: in function 'up'
	/usr/local/share/lua/5.1/kong/cmd/migrations.lua:172: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:9: in function 'file_gen'
	init_worker_by_lua:50: in function <init_worker_by_lua:48>
	[C]: in function 'xpcall'
	init_worker_by_lua:57: in function <init_worker_by_lua:55>
```

- Kong version : 2.0.3

- Kong debug-level startup logs `$ kong start -c <path/to/kong.conf> --vv`
```
2020/04/24 14:53:10 [debug] testing nginx configuration: KONG_NGINX_CONF_CHECK=true /usr/local/openresty/nginx/sbin/nginx -t -p /usr/local/kong -c nginx.conf
2020/04/24 14:53:10 [verbose] could not start Kong, stopping services
2020/04/24 14:53:10 [debug] sending signal to pid at: /usr/local/kong/pids/nginx.pid
2020/04/24 14:53:10 [debug] kill -0 `cat /usr/local/kong/pids/nginx.pid` >/dev/null 2>&1
2020/04/24 14:53:10 [verbose] stopped services
Error: 
/usr/local/share/lua/5.1/kong/cmd/start.lua:75: /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:20: New migrations available; run 'kong migrations up' to proceed
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:75: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:9: in function 'file_gen'
	init_worker_by_lua:49: in function <init_worker_by_lua:47>
	[C]: in function 'xpcall'
	init_worker_by_lua:56: in function <init_worker_by_lua:54>
```

- Operating system - Ubuntu

**Comment by lukaszjankowski** [comment] 2020-05-04 13:59
I'm getting the same here, the same setup.

**Comment by kikito** [comment] 2020-05-04 14:46
Hi, which version of Cassandra are you using? Kong requires [2.2 or above](https://docs.konghq.com/2.0.x/configuration/#datastore-section)

**Comment by lukaszjankowski** [comment] 2020-05-04 14:52
> SELECT cql_version FROM system.local
> 3.4.4

**Comment by agarwal-nitesh** [comment] 2020-05-04 15:40
As mentioned above, I have been using AWS MCS (Managed Cassandra). They claim in their documentation that they implement Apache Cassandra version 3.11 CQL API.
On querying the version on the platform it is 3.4.4

**Comment by lukaszjankowski** [comment] 2020-05-04 16:04
@agarwal-nitesh : I'm also using AWS MCS, :
![image](https://user-images.githubusercontent.com/2827866/80986971-a0c49180-8e31-11ea-93d0-7dba2bdf8d07.png)

**Comment by agarwal-nitesh** [comment] 2020-05-05 08:36
@lukaszjankowski I used Postgres for persistence instead. It works. I think it is not a bad idea to set up a cluster using Postgres as the configurations are cached. Please correct me if I am wrong.

**Comment by lukaszjankowski** [comment] 2020-05-05 11:45
Well, I will do the same. But I hoped to use MCS, as it's serverless, so should be cheaper.

**Comment by ezerd-dev** [comment] 2020-11-01 11:59
Experiencing same error here when using AWS Keyspaces (for Apache Cassandra)

**Comment by kikito** [comment] 2020-11-24 14:35
Hello, since your issue seems to be "resolved" (by not using MCS) I am closing this for now. Please reopen if necessary.

**Closed by kikito** 2020-11-24 14:35 UTC
Labels: pending author feedback

**Comment by scavmartin** [comment] 2020-12-13 15:27
Can this be re-opened? The issue is that keyspace by AWS does not support TTL. Could we have a KONG option to disable TTL for cassandra connections? That should resolve the issue and allow people to utilize AWS Keyspace which is serverless cassandra.

**Comment by jackdcasey** [comment] 2021-04-13 06:29
Adding a +1 for this issue, I was looking into a serverless Kong configuration and was super keen to use MCS. Does anyone have any insight into the repercussions of not using TTL? Is this done for functionality, or for database cleanup?

**Comment by jpsalamarcara** [comment] 2021-04-14 22:11
I tried with the specific ddl for all the kong tables in the keyspace service on AWS, I found there is not support for creating indexes, default_time_to_live greater than 0 and frozen nested collections as used in kong.routes. So the TTL issue is just one of several for having a Kong API Gateway backed on AWS Keyspaces
