### ISSUE TITLE
High latency on the Admin API root endpoint

### ISSUE THREAD

**Issue by chaitany6143** [Kong/kong#9117] opened 2022-07-18 18:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.5

### Current Behavior

**Background:** 
- We currently have kong (with db) deployed in all our environments as a pass-through (no plugins other than the prometheus and request termination)
- We are in the process of enabling JWT validation and rate limiting plugins on the consumers. We just seeded the postgres database with about **500k consumers with JWT and rate limiting applied to each**. 

**Configuration:**
- Ingress controller and proxy runs on the same pod as separate containers
- mem_cache_size is set to 4096m 
-  Pod Resources (requests):
   - CPU: 1
   - Memory: 8G
   
**Problem:** 

After seeding our database with all the consumers + plugins, we noticed that the ingress controller is unable to fetch the metadata via Admin API's root endpoint during the start-up process.
-  **The Admin API root endpoint seems to be very slow and is taking about ~18 seconds to return the config**
- Other admin API endpoints seem to have low latency. Example: /consumers endpoint returns the result in about ~150ms.

<img width="843" alt="Screen Shot 2022-07-18 at 12 58 14 PM" src="https://user-images.githubusercontent.com/1827694/179565100-bc97bf7c-1059-454e-b34f-f3a000033352.png">

**Ingress controller logs:** 

```
-------------------------------------------------------------------------------
Kong Ingress controller
  Release:    1.3.4
  Build:      9d1dec56
  Repository: git@github.com:Kong/kubernetes-ingress-controller.git
  Go:         go1.16.13
-------------------------------------------------------------------------------

W0718 16:50:24.977351       1 client_config.go:614] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2022-07-18T16:50:24Z" level=info msg="version of kubernetes api-server: 1.20+" api-server-host="https://172.20.0.1:443" git_commit=03450cdabfc4162d4e447e6d8c5037efe6d29742 git_tree_state=clean git_version=v1.20.15-eks-a64ea69 major=1 minor=20+ platform=linux/amd64
time="2022-07-18T16:50:28Z" level=info msg="retry 1 to fetch metadata from kong: making HTTP request: Get \"https://localhost:8444/\": context deadline exceeded"
time="2022-07-18T16:50:33Z" level=info msg="retry 2 to fetch metadata from kong: making HTTP request: Get \"https://localhost:8444/\": context deadline exceeded"
time="2022-07-18T16:50:40Z" level=info msg="retry 3 to fetch metadata from kong: making HTTP request: Get \"https://localhost:8444/\": context deadline exceeded"
time="2022-07-18T16:50:51Z" level=info msg="retry 4 to fetch metadata from kong: making HTTP request: Get \"https://localhost:8444/\": context deadline exceeded"
```

After retries, the pods become unhealthy and are blocking our deployment.  

### Expected Behavior

The ingress controller should be able to get the metadata from the Kong Admin API root endpoint within the expected timeout and have a successful start-up.

I have currently disabled the ingress controller in one of our non-prod environments to unblock the deployment + test the feature. Since we maintain the ingress rules, plugins etc in kubernetes, ingress controller would be preferred as a part of the kong ecosystem.

**Comment by kikito** [comment] 2022-07-19 15:01
> 2.5

That version of Kong is getting older, you might be hitting an already-resolved bug.

> 500k consumers

That is a high number of consumers to start with. Does the gateway work correctly with the consumers installed, but no extra plugins?

> with JWT and rate limiting applied to each.

Does this mean that you are adding 500K JWT plugins and 500 rate-limiting plugins? That could be one source of problems. These plugins are supposed to work on Routes or whole Services. Installing them on a Customer should be the *exception* (for example, to temporarily override a customer if he was ratelimited by mistake), not the rule.

**Comment by chaitany6143** [comment] 2022-07-19 16:01
> That version of Kong is getting older, you might be hitting an already-resolved bug.

That's something in our roadmap a bit later to upgrade the version. 

> That is a high number of consumers to start with. Does the gateway work correctly with the consumers installed, but no extra plugins?

We haven't tried it yet on this scale. 

> Does this mean that you are adding 500K JWT plugins and 500 rate-limiting plugins? That could be one source of problems. These plugins are supposed to work on Routes or whole Services. Installing them on a Customer should be the exception (for example, to temporarily override a customer if he was ratelimited by mistake), not the rule.

That's correct. Our requirement is to have rate limiting defined on the user level (so that we can sell it in future). 

Based on your suggestion, sounds like we should enable the JWT plugin + rate limiting plugin on the service level. To handle our use-case for having rate limiting for a subset of users, let me know if this makes sense:  
 
**Quick background:** We currently set the key_claim_name as a custom claim `namespace/user_id=consumer_custom_id`. During JWT creation, we set the consumer_custom_id which maps to our platform user ID. Using this existing logic, we can do the following in favor of low LOE: 

- Add the rate limiting + JWT plugin on the service level with key_claim_name set to `namespace/user_id`
- Create an anonymous consumer and set the `JWT plugin's anonymous attribute` to this consumer ID
   - This will be used for all the users that don't need custom rate limiting
- For the users that need custom rate limiting, we create separate consumers, and apply the JWT and rate limiting plugin. 

Let me know if this makes sense. Thank you so much!

**Comment by StarlightIbuki** [comment] 2023-10-11 06:36
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:36 UTC
Labels: plugins/jwt, plugins/rate-limiting
