### ISSUE TITLE
Overriding the KONG_NGINX_EVENTS_WORKER_CONNECTIONS environment variable crashes kong

### ISSUE THREAD

**Issue by secat** [Kong/kong#5491] opened 2020-01-22 18:36 UTC
### Summary

By setting the Kong override environment variable named `KONG_NGINX_EVENTS_WORKER_CONNECTIONS` in order to override `nginx_events_worker_connections` will crash the Kong application.

### Steps To Reproduce

1. Start Kong with the environment variable `KONG_NGINX_EVENTS_WORKER_CONNECTIONS` set to any numeric value

### Additional Details & Logs

output logs:
```
Error: could not prepare Kong prefix at /usr/local/kong: nginx configuration is invalid (exit code 1):
nginx: [emerg] unknown directive "events_worker_connections" in /usr/local/kong/nginx.conf:6
nginx: configuration file /usr/local/kong/nginx.conf test failed
```

**Comment by bungle** [comment] 2020-01-22 18:44
@secat what version of `Kong` are you trying it? Are you using custom Nginx template?

**Comment by secat** [comment] 2020-01-22 19:10
@bungle I am using version `docker.io/kong:2.0.0`

**Comment by bungle** [comment] 2020-01-22 19:21
@secat ok, thanks for report, I tried this locally on `master`, `next` and `2.0.0` but couldn't reproduce, thus I am labeling this `needs investigation`. Let's see if there is issues with `docker image` or is this something else. And can you confirm, your docker is `clean` and doesn't contain anything from perhaps previous, I guess the answer is yes, and you don't use `custom Nginx template`?

**Comment by bungle** [comment] 2020-01-22 19:47
I also tried `docker`:

```
bungle@pro:~/Sources/kong$ docker exec -it 44d80b647d9c1a4b01796543337b1eb3e8794c266377c9eb85ca8a563c488332 sh
/ $ cd /usr/local/kong/
/usr/local/kong $ cat nginx.conf 
pid pids/nginx.pid;
error_log /dev/stderr notice;

# injected nginx_main_* directives
daemon off;
worker_rlimit_nofile 16384;
worker_processes auto;

events {
    # injected nginx_events_* directives
    worker_connections 5000;
    multi_accept on;
}

http {
    include 'nginx-kong.conf';
}
```

This is what I used to start it:
```
docker run -d --name kong \
     --network=kong-net \
     -e "KONG_DATABASE=postgres" \
     -e "KONG_PG_HOST=kong-database" \
     -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
     -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
     -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
     -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
     -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
     -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
     -e "KONG_NGINX_EVENTS_WORKER_CONNECTIONS=5000" \
     -p 8000:8000 \
     -p 8443:8443 \
     -p 8001:8001 \
     -p 8444:8444 \
     kong:latest
```

**Comment by secat** [comment] 2020-01-22 20:23
@bungle it was an error on my side: I was experimenting on which environment variable I needed to use...

I just realized that I had two environment variables set:
- `KONG_NGINX_EVENTS_WORKER_CONNECTIONS=5000` and
- `KONG_NGINX_MAIN_EVENTS_WORKER_CONNECTIONS=5000` <-- faulty variable

I confirm that removing `KONG_NGINX_MAIN_EVENTS_WORKER_CONNECTIONS` and using only `KONG_NGINX_EVENTS_WORKER_CONNECTIONS` fixes the problem.

Thank you and sorry for the inconvenience

You can close this issue

Thanks again

**Comment by bungle** [comment] 2020-01-22 20:26
@secat thank you getting back on this, and I am glad we didn't have a bug there. Yes, at somepoint we may add some sanity checks on `injections`. So closing this.

**Closed by bungle** 2020-01-22 20:26 UTC
Labels: pending author feedback
