### ISSUE TITLE
Upstream healthcheck metrcis turns on targets healthchecks in both subsystem

### ISSUE THREAD

**Issue by fffonion** [Kong/kong#7676] opened 2021-04-27 17:29 UTC
When stream_listener is enabled, prometheus pulls stream subsystem metrics from an internal endpoint.

A Upstream/Target defined in http subsystem result in it also being visible in stream subsystem,
making unwanted healthcheckers are created and also metrics duplication.

```
# TYPE kong_upstream_target_health gauge
kong_upstream_target_health{upstream="mock-upstream",target="127.0.0.1:15555",address="127.0.0.1:15555",state="dns_error"} 0
kong_upstream_target_health{upstream="mock-upstream",target="127.0.0.1:15555",address="127.0.0.1:15555",state="healthchecks_off"} 0
kong_upstream_target_health{upstream="mock-upstream",target="127.0.0.1:15555",address="127.0.0.1:15555",state="healthy"} 0
kong_upstream_target_health{upstream="mock-upstream",target="127.0.0.1:15555",address="127.0.0.1:15555",state="unhealthy"} 1
kong_upstream_target_health{upstream="mock-upstream",target="127.0.0.1:8001",address="127.0.0.1:8001",state="dns_error"} 0
kong_upstream_target_health{upstream="mock-upstream",target="127.0.0.1:8001",address="127.0.0.1:8001",state="healthchecks_off"} 0
kong_upstream_target_health{upstream="mock-upstream",target="127.0.0.1:8001",address="127.0.0.1:8001",state="healthy"} 0
kong_upstream_target_health{upstream="mock-upstream",target="127.0.0.1:8001",address="127.0.0.1:8001",state="unhealthy"} 1
kong_upstream_target_health{upstream="mock-upstream",target="some-random-dns:80",address="",state="dns_error"} 1
kong_upstream_target_health{upstream="mock-upstream",target="some-random-dns:80",address="",state="healthchecks_off"} 0
kong_upstream_target_health{upstream="mock-upstream",target="some-random-dns:80",address="",state="healthy"} 0
kong_upstream_target_health{upstream="mock-upstream",target="some-random-dns:80",address="",state="unhealthy"} 0
kong_upstream_target_health{upstream="mock-upstream-healthchecksoff",target="127.0.0.1:15555",address="127.0.0.1:15555",state="dns_error"} 0
kong_upstream_target_health{upstream="mock-upstream-healthchecksoff",target="127.0.0.1:15555",address="127.0.0.1:15555",state="healthchecks_off"} 1
kong_upstream_target_health{upstream="mock-upstream-healthchecksoff",target="127.0.0.1:15555",address="127.0.0.1:15555",state="healthy"} 0
kong_upstream_target_health{upstream="mock-upstream-healthchecksoff",target="127.0.0.1:15555",address="127.0.0.1:15555",state="unhealthy"} 0
# HELP kong_upstream_target_health Health status of targets of upstream. States = healthchecks_off|healthy|unhealthy|dns_error, value is 1 when state is populated.
# TYPE kong_upstream_target_health gauge
kong_upstream_target_health{upstream="mock-upstream",target="127.0.0.1:15555",address="127.0.0.1:15555",state="dns_error"} 0
kong_upstream_target_health{upstream="mock-upstream",target="127.0.0.1:15555",address="127.0.0.1:15555",state="healthchecks_off"} 0
kong_upstream_target_health{upstream="mock-upstream",target="127.0.0.1:15555",address="127.0.0.1:15555",state="healthy"} 1
kong_upstream_target_health{upstream="mock-upstream",target="127.0.0.1:15555",address="127.0.0.1:15555",state="unhealthy"} 0
kong_upstream_target_health{upstream="mock-upstream",target="127.0.0.1:8001",address="127.0.0.1:8001",state="dns_error"} 0
kong_upstream_target_health{upstream="mock-upstream",target="127.0.0.1:8001",address="127.0.0.1:8001",state="healthchecks_off"} 0
kong_upstream_target_health{upstream="mock-upstream",target="127.0.0.1:8001",address="127.0.0.1:8001",state="healthy"} 1
kong_upstream_target_health{upstream="mock-upstream",target="127.0.0.1:8001",address="127.0.0.1:8001",state="unhealthy"} 0
kong_upstream_target_health{upstream="mock-upstream",target="some-random-dns:80",address="",state="dns_error"} 1
kong_upstream_target_health{upstream="mock-upstream",target="some-random-dns:80",address="",state="healthchecks_off"} 0
kong_upstream_target_health{upstream="mock-upstream",target="some-random-dns:80",address="",state="healthy"} 0
kong_upstream_target_health{upstream="mock-upstream",target="some-random-dns:80",address="",state="unhealthy"} 0
kong_upstream_target_health{upstream="mock-upstream-healthchecksoff",target="127.0.0.1:15555",address="127.0.0.1:15555",state="dns_error"} 0
kong_upstream_target_health{upstream="mock-upstream-healthchecksoff",target="127.0.0.1:15555",address="127.0.0.1:15555",state="healthchecks_off"} 1
kong_upstream_target_health{upstream="mock-upstream-healthchecksoff",target="127.0.0.1:15555",address="127.0.0.1:15555",state="healthy"} 0
kong_upstream_target_health{upstream="mock-upstream-healthchecksoff",target="127.0.0.1:15555",address="127.0.0.1:15555",state="unhealthy"} 0
```

**Comment by StarlightIbuki** [comment] 2023-10-11 06:23
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:23 UTC
Labels: plugins/prometheus
