### ISSUE TITLE
X-Forwarded-For can not be reset as request header to upstream service

### ISSUE THREAD

**Issue by zffocussss** [Kong/kong#8677] opened 2022-04-12 15:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.6

### Current Behavior

X-Forwarded-For can not be set

### Expected Behavior

X-Forwarded-For  can be set

### Steps To Reproduce

```markdown
write a custom plugin to use kong.service.request.clear_header("X-Forwarded-For ")
```

**Comment by bungle** [comment] 2022-04-12 17:47
@zffocussss, you need to set `ngx.var.upstream_x_forwarded_for = ""`, I think.

**Comment by zffocussss** [comment] 2022-04-13 01:34
> 

in which phase I should reset it?

**Comment by mayocream** [comment] 2022-04-13 04:34
The `var.upstream_x_forwarded_for` was set in `access.before` phase, you can reset it in `access` phase.

ref: https://github.com/Kong/kong/blob/5b7676cee6a1f16d5575db78eda16410047a4ac8/kong/runloop/handler.lua#L1412-L1420

**Comment by zffocussss** [comment] 2022-04-13 05:04
> ngx.var.upstream_x_forwarded_for = ""

it is not working,X-Forwarded-For is still sent to upstream.I set it in access phase of cluster plugin.
so I seems like X-Forwarded-For will be taken and managed only by kong self,even though it was maniputed by custom plugin.

**Comment by bungle** [comment] 2022-04-13 05:57
> > ngx.var.upstream_x_forwarded_for = ""
> 
> it is not working,X-Forwarded-For is still sent to upstream.I set it in access phase of cluster plugin. so I seems like X-Forwarded-For will be taken and managed only by kong self,even though it was maniputed by custom plugin. can you check the lua code and confirm the workflow?

In what phase did you try to remove it?

**Comment by bungle** [comment] 2022-04-13 06:03
This is something we might want to vreak with 3.0, @fffonion what is you take?

**Comment by bungle** [comment] 2022-04-13 06:05
@fffonion, aka revisit this: https://github.com/Kong/kong/pull/7766

**Comment by zffocussss** [comment] 2022-04-13 06:31
> > > ngx.var.upstream_x_forwarded_for = ""
> > 
> > 
> > it is not working,X-Forwarded-For is still sent to upstream.I set it in access phase of cluster plugin. so I seems like X-Forwarded-For will be taken and managed only by kong self,even though it was maniputed by custom plugin. can you check the lua code and confirm the workflow?
> 
> In what phase did you try to set the value of ngx.var.upstream_x_forwarded_for?
> 
> Oh nevermind, you said access. Can you show the code?
> 
> Not sure if tou need to do
> 
> ```lua
> ngx.var.upstream_x_forwarded_for = nil
> ```

```
function plugin:access(plugin_conf)
     -- your custom code here
     ngx.var.upstream_x_forwarded_for = ""
+end
```

**Comment by zffocussss** [comment] 2022-04-13 07:28
@bungle it is working by setting ngx.var.upstream_x_forwarded_for in access phase.
L4 load balancer ->kong -> upstream service
```
    -- runs in the 'access_by_lua_block'
    function plugin:access(plugin_conf)
         -- your custom code here
         kong.log.inspect("forwarded ip: ",kong.client.get_forwarded_ip(),"client ip: ",kong.client.get_ip())
         local http_x_forwarded_for = ngx.var.http_x_forwarded_for
         if http_x_forwarded_for then
             ngx.var.upstream_x_forwarded_for = ngx.var.http_x_forwarded_for .. ", " .. kong.client.get_ip()
         else
             ngx.var.upstream_x_forwarded_for = kong.client.get_ip()
         end
    end

```

**Comment by zffocussss** [comment] 2022-04-13 08:56
L7 load balancer ->kong -> upstream service
    -- runs in the 'access_by_lua_block'
    function plugin:access(plugin_conf)
         -- your custom code here
         -- kong.log.inspect("forwarded ip: ",kong.client.get_forwarded_ip(),"client ip: ",kong.client.get_ip())
         if re_match(kong.request.get_path(), [[kong_debug]],"jo") then
           kong.log.inspect("forwarded ip: ",kong.client.get_forwarded_ip(),"remote ip: ",ngx.var.http_x_forwarded_for)
           kong.log.notice("X-Forwarded-For", ngx.var.http_x_forwarded_for)
           -- not work
           -- kong.service.request.set_header("X-Forwarded-For", ngx.var.http_x_forwarded_for)
           -- work
           ngx.var.upstream_x_forwarded_for = ngx.var.http_x_forwarded_for
         end
         -- ngx.var.upstream_x_forwarded_for = ""
    end

**Comment by zffocussss** [comment] 2022-04-13 09:13
the conclusion is kong.service.request.set_header("X-Forwarded-For", ngx.var.http_x_forwarded_for) does not work,but ngx.var.upstream_x_forwarded_for work

**Comment by ADD-SP** [comment] 2022-04-13 09:36
> > ngx.var.upstream_x_forwarded_for = ""
> 
> it is not working,X-Forwarded-For is still sent to upstream.I set it in access phase of cluster plugin. so I seems like X-Forwarded-For will be taken and managed only by kong self,even though it was maniputed by custom plugin. can you check the lua code and confirm the workflow?

@zffocussss I can't reproduce it.

I started an http server locally to echo the request headers. Then I ran `ngx.var.upstream_x_forwarded_for = ""` in the access phase using a plugin and the request header `X-Forwarded-For` was not sent to my server.

Would you mind trying to reproduce it on `localhost`?

**Comment by zffocussss** [comment] 2022-04-13 09:44
> > > ngx.var.upstream_x_forwarded_for = ""
> > 
> > 
> > it is not working,X-Forwarded-For is still sent to upstream.I set it in access phase of cluster plugin. so I seems like X-Forwarded-For will be taken and managed only by kong self,even though it was maniputed by custom plugin. can you check the lua code and confirm the workflow?
> 
> @zffocussss I can't reproduce it.
> 
> I started an http server locally to echo the request headers. Then I ran `ngx.var.upstream_x_forwarded_for = ""` in the access phase using a plugin and the request header `X-Forwarded-For` was not sent to my server.
> 
> Would you mind trying to reproduce it on `localhost`?

my environment is Azure application gateway + kong ingress controller

**Comment by zffocussss** [comment] 2022-04-13 09:45
@ADD-SP  I suggest that you can try to run kong behind a reverse proxy like nginx/haproxy etc.

**Comment by ADD-SP** [comment] 2022-04-13 10:31
Here is the conclusion of my test (Kong 2.6.1)

`kong.service.request.set_header("X-Forwarded-For", "")` and `kong.service.request.clear_header("X-Forwarded- For")` cannot clear the request header `X-Forwarded-For` that was sent to upstream.

`ngx.var.upstream_x_forwarded_for = nil` and `ngx.var.upstream_x_forwarded_for = ""` can clear the request header `X-Forwarded-For` that was sent to upstream. .

I think the reason why the second way doesn't work for you might be that something else changes the request headers after Kong sends the request, like CDN. so I would suggest testing on `localhost`.

**Comment by zffocussss** [comment] 2022-04-13 11:46
> Here is the conclusion of my test (Kong 2.6.1)
> 
> `kong.service.request.set_header("X-Forwarded-For", "")` and `kong.service.request.clear_header("X-Forwarded- For")` cannot clear the request header `X-Forwarded-For` that was sent to upstream.
> 
> `ngx.var.upstream_x_forwarded_for = nil` and `ngx.var.upstream_x_forwarded_for = ""` can clear the request header `X-Forwarded-For` that was sent to upstream.
> 
> I think the reason why the second way doesn't work for you might be that something else changes the request headers after Kong sends the request, like CDN. so I would suggest testing on `localhost`.

no no no,access phase is during the time before request is sent to upstream.

**Comment by ADD-SP** [comment] 2022-04-13 12:07
> > Here is the conclusion of my test (Kong 2.6.1)
> > `kong.service.request.set_header("X-Forwarded-For", "")` and `kong.service.request.clear_header("X-Forwarded- For")` cannot clear the request header `X-Forwarded-For` that was sent to upstream.
> > `ngx.var.upstream_x_forwarded_for = nil` and `ngx.var.upstream_x_forwarded_for = ""` can clear the request header `X-Forwarded-For` that was sent to upstream.
> > I think the reason why the second way doesn't work for you might be that something else changes the request headers after Kong sends the request, like CDN. so I would suggest testing on `localhost`.
> 
> no no no,access phase is during the time before request is sent to upstream.

Maybe I didn't make it clear, what I meant was that the request header may change after it was sent by Kong.

For example, Kong accesses upstream through another proxy (e.g. CDN). So I would suggest testing on `localhost`.

**Comment by zffocussss** [comment] 2022-04-13 12:47
> > > Here is the conclusion of my test (Kong 2.6.1)
> > > `kong.service.request.set_header("X-Forwarded-For", "")` and `kong.service.request.clear_header("X-Forwarded- For")` cannot clear the request header `X-Forwarded-For` that was sent to upstream.
> > > `ngx.var.upstream_x_forwarded_for = nil` and `ngx.var.upstream_x_forwarded_for = ""` can clear the request header `X-Forwarded-For` that was sent to upstream.
> > > I think the reason why the second way doesn't work for you might be that something else changes the request headers after Kong sends the request, like CDN. so I would suggest testing on `localhost`.
> > 
> > 
> > no no no,access phase is during the time before request is sent to upstream.
> 
> Maybe I didn't make it clear, what I meant was that the request header may change after it was sent by Kong.
> 
> For example, Kong accesses upstream through another proxy (e.g. CDN). So I would suggest testing on `localhost`.

there is no middleware between kong  and upstream services.I am definitely certain

**Comment by StarlightIbuki** [comment] 2023-10-11 06:35
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:35 UTC
Labels: task/needs-investigation, core/pdk

**Comment by guoard** [comment] 2024-12-04 12:20
What is the current status of this issue? The `X-Forwarded-For` header is currently spoofable.
Is there a way to control or modify its value, similar to how it's handled in NGINX configurations?

![image](https://github.com/user-attachments/assets/01a79ee8-d8fe-4650-8418-592c8f0c860f)
