### ISSUE TITLE
Disable descriptive errors

### ISSUE THREAD

**Issue by serafimpinto** [Kong/kong#7453] opened 2021-06-15 09:32 UTC
### Summary

I did not find a way to fix this using the current version so is a feature suggestion.

The Kong API returns detailed internal error messages in several cases. These messages reveal implementation details, that provide hackers important clues on how the application functions and ease the discovery of potential flaws.

Example:
https://imgur.com/xvpBeAf

**Comment by mheap** [comment] 2021-06-16 14:52
The provided example is an excellent error message imo. We should not leave consumers guessing why their request is failing.

What are your security concerns around telling the user how to authenticate correctly? They still wouldn't have the HMAC secret etc

**Comment by serafimpinto** [comment] 2021-06-16 15:59
@mheap I agree and in fact, is a very good message. But my point is having the option to enable/disable these kinds of messages. Why not?

Sometimes you can find a use case where you will have desktop/mobile/etc apps running on people's devices where the app communicates with a Kong server doing the auth, for example. A bad actor can try to bypass the application and the communication with the server and these kinds of messages will help him.

**Comment by mheap** [comment] 2021-07-09 10:35
If this is an optional feature (off by default) then I'd give it a 👍

**Comment by StarlightIbuki** [comment] 2023-10-11 06:23
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:23 UTC
Labels: task/feature
