### ISSUE TITLE
Why more resty_XXXXXXX file in /tmp ？ How to auto deleted？

### ISSUE THREAD

**Issue by mlick** [Kong/kong#6979] opened 2021-03-30 06:28 UTC
![image](https://user-images.githubusercontent.com/8747500/112943525-2c3ec380-9164-11eb-8e89-e14b6159b03a.png)

**Comment by fffonion** [comment] 2021-03-31 12:54
Duplicate of #6898, it will be fixed in kong 2.4. To keep discussion centralized, I'm closing this one.

**Closed by fffonion** 2021-03-31 12:54 UTC

**Comment by mlick** [comment] 2021-04-28 05:53
@fffonion  thanks！
