### ISSUE TITLE
Intermittent Invalid authentication credentials for key auth

### ISSUE THREAD

**Issue by vaibhavkhurana2018** [Kong/kong#6813] opened 2021-02-08 13:21 UTC
### Summary

Authentication Plugin fails with "Invalid authentication credentials" intermittently. I have configured authentication plugin on kong use key auth for some of the use case. The setup is working with intermittent failures. On debugging, i found that the issue was only scoped to a couple of pods of the kong setup. 

Whenever the request landed on 2 of the 6 pods, kong reverted with a 401 status. 

Tested the below endpoints locally from the affected pods: 

1. curl localhost:8001/consumers/kong-admin : Got a response validating the presence of the consumer
2. curl localhost:8001/consumers/<id_from_1>/key-auth: Validated the credentials. 

So effectively the connectivity to the backend (cassandra) was fine and was able to get the things fine. 

- Tried deleting one pod(replacing with another one): Left with only 1 affected pod now. So it is kong cache that is causing this. 

### Additional Details & Logs

- Kong version (`$ kong version`): 2.0.3

**Comment by bungle** [comment] 2021-02-09 09:18
Seems to relate to #6808

**Comment by StarlightIbuki** [comment] 2023-10-11 06:20
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:20 UTC
Labels: task/bug, plugins/key-auth
