### ISSUE TITLE
JWT plugin does not like custom secret beginning with "$"

### ISSUE THREAD

**Issue by rowanthorpe** [Kong/kong#1898] opened 2016-12-15 17:26 UTC
### Summary

While building a custom auth system based on JWTs signed by bcrypt-hashed passwords, I discovered that while the JWT plugin works fine for verifying against all kinds of custom secrets, it always returns "Invalid signature" when verifying against a secret beginning with the $ (dollar-sign) character (such as is generated by bcrypt-hashing). Important to note: I am using a heavily customised Kong (openresty compiled from source, extra nginx modules, custom-created .debs with FHS layouts, patched configs/templates, etc), but have made no modifications to any kong plugins (or kong at all, other than the config-templates), and I went to great pains to isolate that the problem is happening below the server-level, on the plugin-level, and does so even in a minimal context. I have been running it with other plugins (key-auth, CORS, request transformer) in production for months without problem. If necessary I could try to find somewhere to install a vanilla Kong to test, but that would probably take much longer than for someone else to reproduce from the below steps on an existing install (please?). Also, I verified a jwt (signed by a secret starting with $) at http://jwt.io as valid, but the same jwt was deemed invalid in kong. If someone could point me to which part of the plugin's lua code deals with the decoding/validating of jwt's I might be able to help debug more quickly...

### Steps To Reproduce

1. add an api
2. add jwt plugin to an api
3. add consumer
3. add/update jwt-cred to consumer with custom secret (long, short, whatever, but not beginning with $)
4. sign a jwt using that cred
5. request against the api with that jwt (success)
6. do steps 3 to 5 with lots of variations (success)
7. update that jwt-cred to set a custom secret beginning with $
8. sign a jwt using that secret
9. request against the api with that jwt (fail)

### Additional Details & Logs

- Kong version
    - 0.9.3
- Kong debug-level startup logs
    ```
    2016/12/15 18:51:23 [verbose] Kong: 0.9.3
    2016/12/15 18:51:23 [debug] ngx_lua: 10006
    2016/12/15 18:51:23 [debug] nginx: 1011002
    2016/12/15 18:51:23 [debug] Lua: LuaJIT 2.1.0-beta2
    2016/12/15 18:51:23 [verbose] no config file found at /usr/local/etc/kong.conf
    2016/12/15 18:51:23 [verbose] reading config file at /usr/local/etc/kong/kong.conf
    2016/12/15 18:51:23 [debug] admin_listen = "[::]:8101"
    2016/12/15 18:51:23 [debug] anonymous_reports = false
    2016/12/15 18:51:23 [debug] cassandra_consistency = "ONE"
    2016/12/15 18:51:23 [debug] cassandra_contact_points = {"127.0.0.1"}
    2016/12/15 18:51:23 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
    2016/12/15 18:51:23 [debug] cassandra_keyspace = "kong"
    2016/12/15 18:51:23 [debug] cassandra_port = 9042
    2016/12/15 18:51:23 [debug] cassandra_repl_factor = 1
    2016/12/15 18:51:23 [debug] cassandra_repl_strategy = "SimpleStrategy"
    2016/12/15 18:51:23 [debug] cassandra_ssl = false
    2016/12/15 18:51:23 [debug] cassandra_ssl_verify = false
    2016/12/15 18:51:23 [debug] cassandra_timeout = 5000
    2016/12/15 18:51:23 [debug] cassandra_username = "kong"
    2016/12/15 18:51:23 [debug] cluster_listen = "0.0.0.0:7946"
    2016/12/15 18:51:23 [debug] cluster_listen_rpc = "127.0.0.1:7373"
    2016/12/15 18:51:23 [debug] cluster_profile = "wan"
    2016/12/15 18:51:23 [debug] cluster_ttl_on_failure = 3600
    2016/12/15 18:51:23 [debug] custom_plugins = {}
    2016/12/15 18:51:23 [debug] database = "postgres"
    2016/12/15 18:51:23 [debug] dns_resolver = "127.0.0.1"
    2016/12/15 18:51:23 [debug] dnsmasq = false
    2016/12/15 18:51:23 [debug] dnsmasq_port = 53
    2016/12/15 18:51:23 [debug] log_level = "debug"
    2016/12/15 18:51:23 [debug] lua_code_cache = "on"
    2016/12/15 18:51:23 [debug] lua_package_cpath = ""
    2016/12/15 18:51:23 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
    2016/12/15 18:51:23 [debug] lua_ssl_verify_depth = 1
    2016/12/15 18:51:23 [debug] mem_cache_size = "128m"
    2016/12/15 18:51:23 [debug] nginx_daemon = "on"
    2016/12/15 18:51:23 [debug] nginx_optimizations = true
    2016/12/15 18:51:23 [debug] nginx_worker_processes = "auto"
    2016/12/15 18:51:23 [debug] pg_database = "kong"
    2016/12/15 18:51:23 [debug] pg_host = "127.0.0.1"
    2016/12/15 18:51:23 [debug] pg_password = "******"
    2016/12/15 18:51:23 [debug] pg_port = 5432
    2016/12/15 18:51:23 [debug] pg_ssl = false
    2016/12/15 18:51:23 [debug] pg_ssl_verify = false
    2016/12/15 18:51:23 [debug] pg_user = "kong"
    2016/12/15 18:51:23 [debug] prefix = "/usr/local/share/kong/"
    2016/12/15 18:51:23 [debug] proxy_listen = "[::]:8100"
    2016/12/15 18:51:23 [debug] proxy_listen_ssl = "[::]:8443"
    2016/12/15 18:51:23 [debug] serf_path = "/usr/local/bin/serf"
    2016/12/15 18:51:23 [debug] ssl = true
    2016/12/15 18:51:23 [debug] ssl_cert = "/etc/letsencrypt/live/olathens.org/fullchain.pem"
    2016/12/15 18:51:23 [debug] ssl_cert_key = "/etc/letsencrypt/live/olathens.org/privkey.pem"
    2016/12/15 18:51:23 [debug] ssl_only = "on"
    2016/12/15 18:51:23 [verbose] prefix in use: /usr/local/share/kong
    2016/12/15 18:51:23 [verbose] preparing nginx prefix directory at /usr/local/share/kong
    2016/12/15 18:51:23 [verbose] saving serf identifier to /usr/local/share/kong/serf/serf.id
    2016/12/15 18:51:23 [debug] searching for OpenResty 'resty' executable
    2016/12/15 18:51:23 [debug] /usr/local/bin/resty -V: 'nginx version: openresty/1.11.2.1'
    2016/12/15 18:51:23 [debug] found OpenResty 'resty' executable at /usr/local/bin/resty
    2016/12/15 18:51:23 [verbose] saving serf shell script handler to /usr/local/share/kong/serf/serf_event.sh
    2016/12/15 18:51:23 [verbose] running datastore migrations
    2016/12/15 18:51:23 [verbose] migrations up to date
    2016/12/15 18:51:23 [verbose] serf agent not running, deleting /usr/local/share/kong/pids/serf.pid
    2016/12/15 18:51:23 [debug] checking 'serf' executable from 'serf_path' config setting
    2016/12/15 18:51:23 [debug] /usr/local/bin/serf version: 'Serf v0.8.0'
    2016/12/15 18:51:23 [debug] starting serf agent: nohup /usr/local/bin/serf agent -profile 'wan' -rpc-addr '127.0.0.1:7373' -event-handler 'member-join,member-leave,member-failed,member-update,member-reap,user:kong=/usr/local/share/kong/serf/serf_event.sh' -bind '0.0.0.0:7946' -node 'node01_0.0.0.0:7946_465a78ad93cc432ea8369824d49506d6' -log-level 'err' > /usr/local/share/kong/logs/serf.log 2>&1 & echo $! > /usr/local/share/kong/pids/serf.pid
    2016/12/15 18:51:23 [verbose] waiting for serf agent to be running
    2016/12/15 18:51:23 [debug] sending signal to pid at: /usr/local/share/kong/pids/serf.pid
    2016/12/15 18:51:23 [debug] kill -0 `cat /usr/local/share/kong/pids/serf.pid` >/dev/null 2>&1
    2016/12/15 18:51:23 [verbose] serf agent started
    2016/12/15 18:51:23 [verbose] auto-joining serf cluster
    2016/12/15 18:51:23 [verbose] no other nodes found in the cluster
    2016/12/15 18:51:23 [verbose] registering serf node in datastore
    2016/12/15 18:51:23 [verbose] cluster joined and node registered in datastore
    2016/12/15 18:51:23 [debug] searching for OpenResty 'nginx' executable
    2016/12/15 18:51:23 [debug] /usr/local/sbin/nginx -v: 'nginx version: openresty/1.11.2.1'
    2016/12/15 18:51:23 [debug] found OpenResty 'nginx' executable at /usr/local/sbin/nginx
    2016/12/15 18:51:23 [debug] starting nginx: /usr/local/sbin/nginx -p /usr/local/share/kong -c nginx.conf
    2016/12/15 18:51:24 [debug] nginx started
    2016/12/15 18:51:24 [info] Kong started
    ```
- Kong error logs
    ```
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:48: load_plugins(): Discovering used plugins
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: syslog
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: ldap-auth
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: rate-limiting
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: correlation-id
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: jwt
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: runscope
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: tcp-log
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: http-log
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: hmac-auth
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: response-transformer
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: basic-auth
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: key-auth
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: request-transformer
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: acl
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: oauth2
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: galileo
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: udp-log
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: cors
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: file-log
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: ip-restriction
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: request-size-limiting
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: ssl
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: datadog
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: loggly
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: statsd
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: response-ratelimiting
    2016/12/15 18:51:23 [debug] 21290#21290: [lua] kong.lua:74: load_plugins(): Loading plugin: bot-detection
    2016/12/15 18:51:23 [notice] 21290#21290: using the "epoll" event method
    2016/12/15 18:51:23 [notice] 21290#21290: openresty/1.11.2.1
    2016/12/15 18:51:23 [notice] 21290#21290: built by gcc 4.9.2 (Debian 4.9.2-10) 
    2016/12/15 18:51:23 [notice] 21290#21290: OS: Linux 3.16.0-4-amd64
    2016/12/15 18:51:23 [notice] 21290#21290: getrlimit(RLIMIT_NOFILE): 65536:65536
    2016/12/15 18:51:23 [notice] 21303#21303: start worker processes
    2016/12/15 18:51:23 [notice] 21303#21303: start worker process 21304
    2016/12/15 18:51:23 [debug] 21304#21304: REAPER: start reaper memstore message with tick time of 5 sec
    2016/12/15 18:51:23 [debug] 21304#21304: REAPER: start reaper memstore nobuffer message with tick time of 2 sec
    2016/12/15 18:51:23 [debug] 21304#21304: REAPER: start reaper chanhead with tick time of 4 sec
    2016/12/15 18:51:23 [debug] 21304#21304: REAPER: start reaper chanhead churner with tick time of 10 sec
    2016/12/15 18:51:23 [debug] 21304#21304: MEMSTORE:00: init memstore worker pid:21304 slot:0 max workers :1 or 1
    2016/12/15 18:51:23 [debug] 21304#21304: MEMSTORE:00: found my procslot (ngx_process_slot 0, procslot 0)
    2016/12/15 18:51:23 [debug] 21304#21304: MEMSTORE:00: shm: 00007FE9D20FFB50, shdata: 00007FE9C0720000
    2016/12/15 18:51:23 [debug] 21304#21304: WEBSOCKET_PUBLISHER:init WS publisher llist
    2016/12/15 18:51:23 [debug] 21304#21304: THINGCACHE: init fd_cache 00007FE9D2106300
    ```
- Kong configuration (registered APIs/Plugins & configuration file)
    - Test was done on empty test API with only the JWT plugin activated. If parts of the server-configuration are needed I can spam you with them on request, but I suspect it isn't relevant. As for kong-configs, it seems that is covered by the debug startup log output above anyway.
- Operating System
    - Debian Jessie

**Comment by rowanthorpe** [comment] 2016-12-16 10:10
I forgot to mention the obvious - that I encountered this problem while using the HS256 algo. I haven't even used RS256 yet, but at some point later on will migrate to that. Having drilled down a bit, I can see [at this point in the parser-code](https://github.com/Mashape/kong/blob/57f94ccf12fc9c2200204f52b5e3ca1334d010c8/kong/plugins/jwt/jwt_parser.lua#L31) that it doesn't seem to do any weird data-massaging before passing the the secret to luacrypto for verification, so I wonder if something is happening [at this point in the handler code](https://github.com/Mashape/kong/blob/57f94ccf12fc9c2200204f52b5e3ca1334d010c8/kong/plugins/jwt/handler.lua#L85). The [dao](https://github.com/Mashape/kong/blob/57f94ccf12fc9c2200204f52b5e3ca1334d010c8/kong/plugins/jwt/daos.lua) doesn't look like it does anything strange though, so I think it is getting to a low-and-messy enough point that I will wait to hear what others suggest before trying to dig any deeper. For now I am using a workaround of just chomping the leading $ from secrets when signing and verifying JWTs.

**Comment by brycehemme** [comment] 2018-03-28 18:27
Due to some recent work with the JWT plugin I decided to give this a try. I used a secret of "$abcdefghaijklmn" with HS256 and can't reproduce this issue. I'm running the current state of the repo built from source as my testing instance. It is possible that this there is some other edge case at play here or this is no longer an issue with the current version of Kong.

**Comment by rowanthorpe** [comment] 2018-03-28 19:46
Having not had the opportunity to use Kong for a while now, I would expect a *lot* has changed under the hood, and would be surprised if whatever bug this was has not been at least partially impacted/corrected by now, even if not directly intentionally. Perhaps at this stage, especially given that @brycehemme was able to show recent code **not** reproducing it, it is better to just close the bug as "whether valid or not at the time, it doesn't apply now, and so much has changed since then that we should just bury it and move on"...?

I will leave the issue open, but whichever maintainer/collaborator wants to make the decision to close this issue, feel free.

**Comment by thibaultcha** [comment] 2018-03-29 02:17
Closing this then, thank you for giving this a try @brycehemme!

**Closed by thibaultcha** 2018-03-29 02:17 UTC
Labels: task/needs-investigation
