### ISSUE TITLE
Kong db-less: Cannot serialise table: excessively sparse array

### ISSUE THREAD

**Issue by Ehekatl** [Kong/kong#5768] opened 2020-04-09 12:08 UTC
### Summary

after upgrade to kong version from 1.4.x to 2.0.x, ingress controller fail to post config, with error:
`Cannot serialise table: excessively sparse array`

### Steps To Reproduce

couldn't not reproduce on other env
only happens on kubernetes cluster with complex (but valid) ingress

### Additional Details & Logs

[ingress-kong-stgaing-9cc59f496-z2v4p] 2020/04/09 12:04:41 [error] 26#0: *948 [kong] api_helpers.lua:260 Cannot serialise table: excessively sparse array, client: 127.0.0.1, server: kong_admin, request: "POST /config?check_hash=1 HTTP/1.1", host: "localhost:8444"

**Comment by bungle** [comment] 2020-04-09 16:59
@Ehekatl, thanks for reporting, we need to investigate it.

**Comment by hbagdi** [comment] 2020-04-09 22:24
@Ehekatl Thanks for reporting. Could you share the configuration that you have in your k8s cluster that is causing this? It would help a lot if we get a reproducible config that causes this.

**Comment by Tieske** [comment] 2020-04-12 08:10
Fyi; This is a known issue with the cjson, library if you try to serialize a Lua table that only has a few numerical indices far apart

**Comment by hbagdi** [comment] 2020-04-13 22:10
ping @Ehekatl

**Comment by Ehekatl** [comment] 2020-04-14 11:00
@hbagdi looks like we trigger this error by an invalid cors config (when use without validation controller)

here is the problematic part in config json, change method "*" to valid value fix this issue

```
{
    "name": "cors",
    "config": {
      "credentials": true,
      "exposed_headers": ["*"],
      "headers": ["*"],
      "methods": ["*"],
      "origins": ["*"],
      "preflight_continue": true
    },
    "route": "xxxx.00",
    "enabled": true,
    "protocols": ["http", "https"]
  }
```

**Comment by hbagdi** [comment] 2020-04-14 18:44
@Ehekatl The above plugin configuration doesn't trigger the error described originally (sparse array). Do you have a config which actually triggers that error?

If not, we have to close this issue due to lack of reproducible steps.

**Comment by Ehekatl** [comment] 2020-04-15 05:00
I do have the full config, it’s just very weird, 
when cors is included in the config, it trigger this error

when I randomly remove some stuff in the config, the error change to “invalid method” which is the correct behavior.

I’ll post some example later.

**Comment by Ehekatl** [comment] 2020-04-15 16:54
@hbagdi 
I craft a minimum json config to reproduce this issue, please check the archive below

debug-1.json: Cannot serialise table: excessively sparse array
debug-2.json (change `"methods": ["*"]` to `"methods": ["GET"]`): valid config without error
debug-3.json (remove any other plugin in the config): `{"fields":{"plugins":[null,null,null,null,null,null,null,null,null,{"config":{"methods":["expected one of: GET, HEAD, PUT, PATCH, POST, DELETE, OPTIONS, TRACE, CONNECT"]}}]},"name":"invalid declarative configuration","code":14,"message":"declarative config is invalid: {plugins={[10]={config={methods={\"expected one of: GET, HEAD, PUT, PATCH, POST, DELETE, OPTIONS, TRACE, CONNECT\"}}}}}"}` 

[debug.zip](https://github.com/Kong/kong/files/4482597/debug.zip)

**Comment by hbagdi** [comment] 2020-04-15 18:42
I can reproduce, thanks @Ehekatl.
We are investigating this internally.

**Closed** 2020-05-13 17:25 UTC
Labels: task/bug
