### ISSUE TITLE
Kong Linux command client did not run and return data

### ISSUE THREAD

**Issue by drakenguyencvn** [Kong/kong#5016] opened 2019-09-10 09:52 UTC
### Summary

I installed kong on my Ubuntu 18.04 bionic as intructions:
https://docs.konghq.com/install/ubuntu/?_ga=2.27228475.749820824.1568107389-1191384212.1567663353
However, when I run Kong command on the command line it did not return anything

I also try to run Kong commnand on Kong Docker container by official image and the output was the same.

### Steps To Reproduce

1. Install Kong: https://docs.konghq.com/install/ubuntu/?_ga=2.27228475.749820824.1568107389-1191384212.1567663353
2. Open cmd and run, nothing returned in the cmd
> kong
3. Install Docker
4. Run Kong docker container on https://hub.docker.com/_/kong
5. Run kong and nothing returned

### Additional Details & Logs

- Kong version (`1.3.0`)
- Linux version (`bionic 18.04`)
- I did not know what is the cause

**Comment by hutchic** [comment] 2019-09-10 11:53
try `kong -vv` for verbose output

**Comment by drakenguyencvn** [comment] 2019-09-11 03:25
> try `kong -vv` for verbose output

I tried but the result was still the same. I re-install Ubuntu but the error is still there

![Screenshot from 2019-09-11 10-23-17](https://user-images.githubusercontent.com/49779341/64665899-82fb8400-d47e-11e9-820a-15eac3e7c2a1.png)

**Comment by drakenguyencvn** [comment] 2019-09-11 03:28
> try `kong -vv` for verbose output

I tried and also re-install Ubuntu the the result is still the same

![Screenshot from 2019-09-11 10-23-17](https://user-images.githubusercontent.com/49779341/64665980-d968c280-d47e-11e9-972d-5a3793cda059.png)

**Comment by hutchic** [comment] 2019-09-11 12:20
output of:
```
whereis kong
kong version
sudo kong
```

I have a high degree of confidence that Kong 1.3.0 works on Ubuntu 18.04 as we specifically test that our releases can be installed / ran and not seeing a ton of similar reports

**Comment by drakenguyencvn** [comment] 2019-09-11 16:35
I have changed CPU to Intel Core and it worked. I have also tested on other PCs and kong command worked as usual on those computers. But the PC with AMD CPU as above did not

**Comment by hutchic** [comment] 2019-09-16 13:07
I tried this on a m5a on AWS and wasn't able to reproduce

```
ubuntu@ip-172-31-69-229:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

ubuntu@ip-172-31-69-229:~$ uname -a
Linux ip-172-31-69-229 4.15.0-1044-aws #46-Ubuntu SMP Thu Jul 4 13:38:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

ubuntu@ip-172-31-69-229:~$ curl -fsSLo kong.deb https://bintray.com/kong/kong-deb/download_file?file_path=kong-1.3.0.bionic.amd64.deb

ubuntu@ip-172-31-69-229:~$ sudo dpkg -i kong.deb
Selecting previously unselected package kong.
(Reading database ... 56638 files and directories currently installed.)
Preparing to unpack kong.deb ...
Unpacking kong (1.3.0) ...
Setting up kong (1.3.0) ...

ubuntu@ip-172-31-69-229:~$ kong version
1.3.0
```

**Comment by kikito** [comment] 2019-10-11 16:59
As we can't reproduce this issue, and

> I have changed computer with to Intel Core CPU and it worked

I'm concluding that this was due to a local machine's configuration and closing this. Please reopen if needed.

**Closed by kikito** 2019-10-11 16:59 UTC
