### ISSUE TITLE
K8S pod deletion causing upstream routing issue

### ISSUE THREAD

**Issue by mleader1** [Kong/kong#8450] opened 2022-02-23 18:44 UTC
Hi,

We recently encountered K8S deployment restart issue which caused a few times of deployment restart, what we discovered was that the Kong Ingress uses the pod IP in the Upstream Targets instead of the service IP (which is understandable), however when the pod gets deleted the upstream targets seem to not updating responsively.

Can anyone give some lights how and when the deleted pods' ips will be removed from Kong's upstream targets?

I myself also tried to setup passive & active health checks, however it marks all Pod IPs as 'healthy' even though the pods are no longer available (deleted)?

Any explanation on this issue will be helpful pls.

**Comment by mayocream** [comment] 2022-03-08 05:22
Hi @mleader1,

There is one annotation [`ingress.kubernetes.io/service-upstream`](https://docs.konghq.com/kubernetes-ingress-controller/2.2.x/references/annotations/#ingresskubernetesioservice-upstream), used to set the upstream as K8s svc IP.

also, ping @Kong/team-k8s for help.

**Comment by mflendrich** [comment] 2022-03-08 13:00
> Can anyone give some lights how and when the deleted pods' ips will be removed from Kong's upstream targets?

For each Kubernetes service, Kubernetes maintains an `Endpoints` object that links a Kubernetes `Service` with pods that are available and ready to serve traffic.

Depending on the `ingress.kubernetes.io/service-upstream` setting referenced above, the ingress controller will either target the service IP (when set to `true`) or each individual endpoint from the `Endpoints` object associated with the `Service` (when set to `false`/by default).

The process of updating Kong's upstream targets upon pod deletion has two steps:
1. A Kubernetes control plane component (specifically: the endpoints controller running in controller-manager) ensures that deleted pods get removed from the `Endpoints` object associated with your service
2. Kong Ingress Controller (which watches the `Endpoints object` in K8s) notices that the endpoint associated with the deleted pod has disappeared from the `subsets.addresses` [field of the `Endpoints` object](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#endpoints-v1-core) and updates Kong's upstream targets accordingly.

If you see that a change in `Endpoints` doesn't result in a corresponding change in Kong's upstream targets, please see the logs of the ingress controller container and file a bug with the [Kong ingress controller](https://github.com/Kong/kubernetes-ingress-controller).

**Comment by StarlightIbuki** [comment] 2023-10-11 06:35
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:35 UTC
Labels: area/kubernetes, area/ingress-controller, core/balancer
