### ISSUE TITLE
Plugin no longer applies if disabled and re-enabled - AWS hosted

### ISSUE THREAD

**Issue by fabianschoenleitner** [Kong/kong#8436] opened 2022-02-21 12:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.4.1

### Current Behavior

When I disable a plugin and re-enable it, the plugin no longer applies even though it is enabled. 

After I create a plugin, everything works as expected. (e.g. acl, request terminiation) 
If I disable and re-enable the plugin, it will no longer work and anonymous users are able to send requests to my service.

This behavior only occurs in my AWS setup, Kong is hosted via ECS Fargate-Cluster, after I upgraded to 2.4.1 from 1.4. 
I'm not able to reproduce this issue on my local docker setup.
If I redeploy Kong, everything works again, but if I disable and re-enable a plugin, I have the same bug as explained above.
Our current setup also requires us to have 3 different Kong instances running and they use the same Postgres database, could this be an issue?

### Expected Behavior

When I disable a plugin and re-enable it, I expect the plugin to work again. 

### Steps To Reproduce

```markdown
1. Create Service

$ curl -X POST --url https://kong:8001/services/ --data 'name=test-api' --data 'url=https://test-api:8080'

response:

{
   "host":"test-api",
   "connect_timeout":60000,
   "id":"30671beb-26f0-4bb8-a45c-b78b8c4e1dbd",
   "protocol":"https",
   "name":"my-api",
   "read_timeout":60000,
   "port":8080,
   ...
}

2. Create Route

$ curl -X POST --url https://kong:8001/services/test-api/routes --data 'paths[]=/test'

response:

{
   "id":"f0eabb2c-e208-4916-bc14-a1dbed4d1486",
   "path_handling":"v0",
   "paths":[
      "\/test"
   ],
   "destinations":null,
   "headers":null,
   "protocols":[
      "http",
      "https"
   ],
   "methods":null,
   "snis":null,
   "service":{
      "id":"30671beb-26f0-4bb8-a45c-b78b8c4e1dbd"
   },

3. Call Service

$ curl -i -X GET --url http://kong:8000/test
Via: kong/2.4.1

test


4. Create request termination plugin, will return 401 if the user is annonymous

$ curl --request POST \
  --url https://kong:8001/services/30671beb-26f0-4bb8-a45c-b78b8c4e1dbd/plugins \
  --header 'Content-Type: application/json' \
  --data '{
  "config": {
    "body": "{\"message\": \"Unauthorized - Provide Authentication\"}",
    "content_type": "application/json",
    "message": null,
    "status_code": 401
  },
  "consumer": {
    "id": "0cbb22ad-a93c-420d-9584-7ca4e27d19e8"
  },
  "created_at": 1643730092,
  "enabled": true,
  "name": "request-termination",
  "protocols": [
    "grpc",
    "grpcs",
    "http",
    "https"
  ],
  "route": null,
  "service": {
    "id": "30671beb-26f0-4bb8-a45c-b78b8c4e1dbd"
  },
  "tags": null
}'



5. Call Service

$ curl -i -X GET --url http://kong:8000/test
Via: kong/2.4.1
{
	"message": "Unauthorized - Provide Authentication"
}


6. Disable Plugin

$ curl --request PATCH \
  --url https://kong:8001/services/30671beb-26f0-4bb8-a45c-b78b8c4e1dbd/plugins/c4303182-4e66-44ea-8f02-b9fd3b944285 \
  --header 'Content-Type: application/json' \
  --data '{
  "enabled": false,
}'

7. Call Service
$ curl -i -X GET --url http://kong:8000/test
Via: kong/2.4.1

test


8. Re-enable Plugin
$ curl --request PATCH \
  --url https://kong:8001/services/30671beb-26f0-4bb8-a45c-b78b8c4e1dbd/plugins/c4303182-4e66-44ea-8f02-b9fd3b944285 \
  --header 'Content-Type: application/json' \
  --data '{
  "enabled": true,
}'


9. Call Service
$ curl -i -X GET --url http://kong:8000/test
Via: kong/2.4.1

test
```

**Comment by StarlightIbuki** [comment] 2023-10-11 06:35
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:35 UTC
Labels: task/needs-investigation
