### ISSUE TITLE
Cannot delete plugin by name

### ISSUE THREAD

**Issue by mikob** [Kong/kong#2953] opened 2017-10-13 03:16 UTC
### Summary

I cannot delete a plugin by name despite the docs saying I should be able to, and apparently https://github.com/Mashape/kong/pull/2252 being merged.

### Steps To Reproduce

1. Create a plugin
Here you can see it's created
```
$ http localhost:8001/apis/example-api/plugins                                                                                                [12:13:58 PM]
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Fri, 13 Oct 2017 03:13:59 GMT
Server: kong/0.11.0
Transfer-Encoding: chunked

{
    "data": [
        {
            "api_id": "df0576ee-5da1-4790-b2d7-88ae8f1593be",
            "config": {
                "keys": [
                    "uuid3|happy3"
                ]
            },
            "created_at": 1507863887000,
            "enabled": true,
            "id": "769fc3b2-4db6-4f51-818f-eb056bc84dce",
            "name": "en-to-jp-hack-kong-plugin"
        }
    ],
    "total": 1
}
```
2. Try to delete it by name
```
$ http DELETE localhost:8001/apis/example-api/plugins/en-to-jp-hack-kong-plugin                                                               [12:14:53 PM]
HTTP/1.1 400 Bad Request
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Fri, 13 Oct 2017 03:14:53 GMT
Server: kong/0.11.0
Transfer-Encoding: chunked

{
    "id": "en-to-jp-hack-kong-plugin is not a valid uuid"
}
```

### Additional Details & Logs

- Kong version 0.11.0 running from official kong docker container with postgres db

**Comment by hbagdi** [comment] 2017-10-13 15:54
+1

**Comment by thefosk** [comment] 2017-10-17 22:03
The reason why this is not allowed is because you may have more than one plugin with the same name on the same API: for example you may have a rate-limiting global for one API, and a rate-limiting for the same API but also a Consumer (via the `consumer_id` property). 

In that case the system would delete both plugins, and we haven't brainstormed enough if that's the behavior we want to have.

**Comment by hbagdi** [comment] 2017-10-18 14:57
@thefosk Even if there's a single plugin with the same name, the behaviour is not as we would expect.
I create an API and then add a plugin to the API.
Now, a request like:
```
GET localhost:8001/apis/30941171-77e0-4fec-8b17-cd32f68b89c6/plugins/key-auth
or 
DELETE localhost:8001/apis/30941171-77e0-4fec-8b17-cd32f68b89c6/plugins/key-auth
```
always returns:
```
400 Bad Request
{
    "id": "key-auth is not a valid uuid"
}
```

I've tried this with multiple combinations but doesn't seem to work.

**Comment by mikob** [comment] 2017-10-20 04:14
@thefosk forcing users to delete by uuid would make things a bit more cumbersome for those of us without multiple overlapping plugins (seems like a more niche use case?). How about only returning the error when there's multiple plugins with the same name, but deleting the plugin as expected when there's no ambiguity because the plugin name is unique. Something like "name is ambiguous between 2 or more plugins, must use uuid to delete" when there's multiple plugins with the same name could work perhaps?

**Comment by tylerauerbeck** [comment] 2017-10-23 23:13
@thefosk @mikob If that would be the way to handle it, would it make sense to return the uuid's of the offending plugins? Rather than making the user go hunt down the uuid's with additional steps.

**Comment by thibaultcha** [comment] 2017-11-02 01:21
This is indeed the expected behavior and will likely stay so in the short term. Indeed, plugins with the same name can be added several times to a single API and overlap with plugins also configured with a `consumer_id`; and that is a very common use-case @mikob.

*However*, please do not believe for a second that we are fully satisfied with this approach. We do understand how cumberstone this can feel for simpler use-cases. There are various UX improvements that we want to make to plugins and how they are configured and we will tackle them in the coming month/year.

I'll be closing this as I believe the question has been answered ("why can't I delete a plugin by its name?"), but we won't come to a resolution in the scope of this single issue. Thanks!

Regards,

**Closed by thibaultcha** 2017-11-02 01:21 UTC
Labels: task/needs-investigation
