### ISSUE TITLE
Kong returns kong-default.crt when injected nginx_proxy directives are configured for different certs

### ISSUE THREAD

**Issue by scorpioty** [Kong/kong#8740] opened 2022-04-30 00:08 UTC
Using kong:2.8.0-alpine, I've configured -e KONG_NGINX_PROXY_SSL_CERTIFICATE and -e KONG_NGINX_PROXY_SSL_CERTIFICATE_KEY to point to cert/key files that are volume mounted into the container.  In /usr/local/kong/nginx-kong.conf, I can see the configuration below (truncated):

...
ssl_certificate /usr/local/kong/ssl/kong-default.crt;
ssl_certificate_key /usr/local/kong/ssl/kong-default.key
ssl_certificate /usr/local/kong/ssl/kong-default-ecdsa.crt;
ssl_certificate_key /usr/local/kong/ssl/kong-default-ecdsa.key;
ssl_session_cache shared:SSL:10m;
ssl_certificate_by_lua_block {
Kong.ssl_certificate()
}

# injected nginx_proxy_* directives
real_ip_header X-Real-IP;
real_ip_recursive off;
ssl_certificate /certs/server.crt;
ssl_certificate_key /certs/server.key;
ssl_client_certificate /certs/ca.crt;
ssl_password_file /certs/server.key.pass;
ssl_protocols TLSv1.1 TLSv1.2;
ssl_verify_client on;
ssl_verify_depth 3;
....

When I mount this file into the container, and comment out the kong-default lines, my (server.crt) is returned on requests, otherwise, kong-default.crt is always returned, despite the injected configurations happen afterwards.

**Comment by scorpioty** [comment] 2022-05-04 22:51
This error happens with Java (using apache httpClient libs) and Python requests, when making calls from within the docker network to the Kong container.

**Comment by StarlightIbuki** [comment] 2023-10-11 06:35
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:35 UTC
Labels: task/needs-investigation
