### ISSUE TITLE
Passive health Check is not working in Kong after configure the same with a nonresponsive  target

### ISSUE THREAD

**Issue by ArunPillai-Sysfore** [Kong/kong#6112] opened 2020-07-14 17:24 UTC
We have configured the passive health checks for an upstream URL with a nonresponsive target, but it is not recognized it. Anybody can help how to configure the same.

**Comment by kikito** [comment] 2020-07-15 17:19
Hi, could you give us some more information about your issue? What version of Kong are you using? What database? What is the expected outcome of your configuration? What do you mean by "recognized it"?

**Comment by ArunPillai-Sysfore** [comment] 2020-07-15 17:30
We are using Kong Community 2.0.4. We have deployed this on Azure Kubernetes services and are using Azure Postgresql database as the external database for Kong. Our use case is to have a passive health check configured and enabled for our backend services. 
We have configured the same using Active Health checks by specifying the unhealthy timeouts and errors and were able to see it function when service was down. But when we do the same using Passive health checks, we do not see any change in the status of the service and it is always shown as healthy. 
From the documentation what we understand is that Active Health checks end up adding to the traffic to the backend services so it was recommended to have passive health checks enabled for the healthy services and have Active health checks enabled for the unhealthy services. But from what we are seeing this is not the behaviour that is shown.

**Comment by StarlightIbuki** [comment] 2023-10-11 06:19
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:19 UTC
Labels: core/balancer
