### ISSUE TITLE
Credential_ID functions in place of Client_ID in Client Credentials Flow

### ISSUE THREAD

**Issue by rsbrisci** [Kong/kong#4773] opened 2019-07-03 14:34 UTC
### Summary

You can use your `credential_id` in place of `client_id` to generate a token in the OAuth Client Credentials flow.

### Steps To Reproduce

1. Create a proxy with the OAuth 2 plugin - enable Client Credentials & Global Credentials
2. Create a consumer with OAuth credentials
3. Post `application/x-www-form-urlencoded` data with `client_id=<CREDENTIAL_ID>&client_secret=<client_secret>&grant_type=client_credentials` to the token creation endpoint
4. Observe token in response

### Additional Details & Logs

- Kong version `1.0.3`
- Operating system `Kong Alpine`

**Comment by jeremyjpj0916** [comment] 2020-09-13 21:50
@rsbrisci can this still be done on the 2.x series lol? This sounds like a weird one.

**Comment by bungle** [comment] 2020-09-17 15:56
hard to say if this is a bug or feature. it seems like it finds in from cache.

**Comment by StarlightIbuki** [comment] 2023-10-11 09:07
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 09:07 UTC
Labels: task/code quality, plugins/oauth2
