### ISSUE TITLE
Optionally don't fall back to ip on limit_by

### ISSUE THREAD

**Issue by nicholasklem** [Kong/kong#6837] opened 2021-02-12 12:02 UTC
We want to rate-limit on a header X-Forwarded-For. When this header
does not exist it usually is an internal service. Falling back to
source ip gives us disastrous results.

This commit adds an option to fail instead of falling back to ip. I made a 
patch that does this: https://github.com/Kong/kong/pull/6836

**Comment by StarlightIbuki** [comment] 2023-10-11 06:20
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:20 UTC
Labels: plugins/rate-limiting
