### ISSUE TITLE
Multi-region lambda configurations

### ISSUE THREAD

**Issue by tjrivera** [Kong/kong#7639] opened 2021-03-01 16:07 UTC
Hi Folks, 

I have some internal teams that have begun leveraging this plugin. One use-case that we've encountered, is that teams will deploy the same lambda function into multiple regions for an active-active setup. 

For context, on the gateway side, we have instances that run in multiple regions, we recommend teams configure non-lambda-based services to the gateway with a latency-based DNS record in their configuration so that an incoming request that hits our west region, would then proxy to an upstream in west, vice versa for east, or any other region. 

With lambdas we can't rely on latency-based DNS routing, and our configuration is global. This means teams can only configure a single lambda per-service. 

We've thought about some workarounds that involve configuring multiple services per-region and then a global service that refers to those Kong services, but this isn't ideal. 

I imagine it may be a great deal of work to passively healthcheck configured lambdas to enable failover to another arn, but I wanted to get this out there to get folks thoughts on a possible solution. In this case our primary goal is availability and not necessarily improved latency via geolocation.

**Comment by StarlightIbuki** [comment] 2023-10-11 06:23
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:23 UTC
Labels: plugins/aws-lambda
