### ISSUE TITLE
Default proxy retries exceeded

### ISSUE THREAD

**Issue by dcarley** [Kong/kong#8931] opened 2022-06-10 14:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.2

### Current Behavior

We have seen some requests that have been retried more than the service's specified/default number of retries. We've observed these from the [Zipkin plugin balancer spans](https://docs.konghq.com/hub/kong-inc/zipkin/#spans) and logs from the backend service.

12 retries:
![image](https://user-images.githubusercontent.com/260438/172641221-da7f6381-917f-4755-b461-7e2d561ef884.png)

37 retries:
![image](https://user-images.githubusercontent.com/260438/172641473-0bb33383-9c9f-4f84-b095-035a809e1664.png)

### Expected Behavior

We expected the request to be retried a maximum of 5 times according to the default on the [Service object](https://docs.konghq.com/gateway/2.8.x/admin-api/#service-object) and observed here from the running configuration:
```
% yq '.services[] | select(.host == "test-results-api-v1.default.80.svc") | .retries' kong-prod.yaml
5
```

### Steps To Reproduce

The service in question is using Kong Ingress Controller with `Ingress` and `Service` resources and no `KongIngress` customisation. We haven't yet been able to reproduce this under controlled circumstances, such as using an upstream that closes the connection before writing a response. 

### Anything else?

I can't see how this would be possible from my reading of the code but would be happy to provide more details if necessary and work with someone to debug it further.

**Comment by mayocream** [comment] 2022-06-13 08:54
Hi @dcarley, would you mind to share us the steps to reproduce the problem? And is this issue only occurring with the 2.8.2 image (I think we haven't released this version yet)?

**Comment by flrgh** [comment] 2022-06-13 20:07
Interesting! I am suspicious that there's something that is silently munging the balancer data. Purely speculating here, but that sounds slightly more likely than the bug being in the balancer code itself.

I have a couple other questions in addition to @mayocream's:

* Are you using any custom nginx config template/injected nginx directives? I'll assume 'no' based on what you've said about there being no `KongIngress` customizations, but it's good to double check.
* What other plugins are active for the service/route in question?
* This is a difficult one, but any chance that you've been able to observe this behavior from the perspective of your upstream/backend server (i.e. is it possible to validate that these retries are really happening rather than the data just being wrong?)

**Comment by StarlightIbuki** [comment] 2023-10-11 06:35
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:35 UTC
Labels: core/balancer
