### ISSUE TITLE
Why 'override' responses for some of the status codes only?

### ISSUE THREAD

**Issue by buch11** [Kong/kong#5638] opened 2020-03-05 00:20 UTC
Hi Guys,

We were building a custom plugin to do some checks and whenever I tried to respond with error code "500", I was not able to pass my custom message. Digging deeper, I stumbled upon this block here -
 https://github.com/Kong/kong/blob/28e4baf323a3b01ede1be4301fd490408a1e5d6c/kong/tools/utils.lua#L917

Just wondering why is kong **overriding** response messages for only three status codes i.e. 405, 500 and 502 ?

**Comment by kikito** [comment] 2020-11-04 23:22
Hello, this has been somewhat difficult to dig out because the code responsible for generating/providing response bodies has moved several times in the git history.

I identified the first commit which "overrides" the response body, here:

https://github.com/Kong/kong/commit/d2c50f3f2c159b005aadd93bc1eadc7a9dee8885

Other subsequent commits add similar "overrides" for the methods you have mentioned.

Unfortunately neither the commit message nor the Changelog for Kong 0.3.0, where this change was shipped, add an explanation for this. But I think I can venture an explanation.

The 500 status in particular is easy to understand. It is a "default error code".

The use you are trying to give to the 500 status code is the *expected* usecase. Your code is actively detecting a condition and returning the status code.

However, there are situations that the Kong source code *might not be prepared to expect*. *Exceptions*, if you will. Consider the following: For some combination of circumstances (maybe a bug) Kong is expecting to read and use a row from the database via a `SELECT`, but instead of getting it it gets an error message. Kong can't continue so it must abort the current request and return an error code. 500 is the "default" http status code for such responses, when no other status code has been specified.

Now consider what the response body should be. A naive approach would be returning "whatever error message has caused the problem". In the previous case, that would be the database's error message. You can probably see what the problem is now: said message could be `The query 'SELECT id from Users where id=123456 and secret_code_that_shouldnt_be_public=55667' returned returned no rows`. This kind of "unmanaged" response is thus very dangerous, since it can be used to reveal private information.

So that's what the override is there for: it is the last-line of defense against revealing private information by mistake. The cost of that defense is that a 500 message always will return `Unknown server error` in the response body. You can still **print as much valuable information as you can on the logs**, for the admins.

I'm pretty sure that's what's happening here because I've seen it done before. Rails, for example, [handles 500 errors like this when deployed to a production environment](https://github.com/rails/rails/blob/6-1-stable/actionpack/lib/action_dispatch/middleware/show_exceptions.rb#L19-L24).

I am slightly less sure about why 405 and 502 are also part of the overrides. I suspect they are used as default on certain occasions, and as a result they might "leak".  So the way to return information on those is by printing it in the log. This is my suspicion, I am afraid I don't have the time to confirm this.

In any case, I hope this explanation satisfies your curiosity.

I am closing this issue for now, if you need to discuss it further, please reopen.

**Closed by kikito** 2020-11-04 23:22 UTC
Labels: core/pdk
