### ISSUE TITLE
IP normalization issues from #3679

### ISSUE THREAD

**Issue by Tieske** [Kong/kong#4311] opened 2019-02-14 13:37 UTC
The PR introduced a number of issues:

- [This line](https://github.com/Kong/kong/blob/master/kong/tools/utils.lua#L797) should not be doing a normalization. The function is for formatting. Formatting is cheap, normalization is not, hence the distinction. Even the doc comments are out of sync (they still describe the desired (=old) behaviour). See this comment: https://github.com/Kong/kong/pull/3679#discussion_r215864911

- the above leads to double normalization in other places. See https://github.com/Kong/kong/pull/3679#discussion_r216082396

- Tests are missing for normalized comparison. See https://github.com/Kong/kong/pull/3679#discussion_r215866232

**Comment by Tieske** [comment] 2019-02-14 13:38
![](https://github.trello.services/images/mini-trello-icon.png) [Create issues from comments](https://trello.com/c/C5qFghul/103-create-issues-from-comments)

**Comment by james-callahan** [comment] 2019-02-14 23:37
I think renaming the functions might be helpful, the functionality required is:

  - validate address
  - canonicalize address (e.g. for use as a table key)
  - format addresses for human consumption

**Comment by Opiumreg18** [comment] 2019-02-18 07:08
> Я думаю, что переименование функций может быть полезно, требуемая функциональность:
> 
> * проверить адрес
> * адрес canonicalize (например, для использования в качестве ключа таблицы)
> * форматирование адресов для потребления человеком

**Comment by kikito** [comment] 2022-01-26 12:05
Possibly related: https://github.com/Kong/kong/pull/8140

**Comment by kikito** [comment] 2022-11-02 08:53
@StarlightIbuki @bungle I believe this issue can be closed after the changes in normalization we did in 3.0 . Could you confirm?

**Comment by StarlightIbuki** [comment] 2022-11-02 10:12
> @StarlightIbuki @bungle I believe this issue can be closed after the changes in normalization we did in 3.0 . Could you confirm?

Seems not related. This issue is about the IP address(CIDR), and the merged PR is about the URL(and the keypoint is the path).

**Comment by StarlightIbuki** [comment] 2023-10-18 08:40
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md?rgh-link-date=2023-10-18T08%3A39%3A47Z) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-18 08:40 UTC
Labels: core/pdk
