### ISSUE TITLE
curl: (7) Failed to connect to localhost port 8001: Connection refused getting this error on windows and ubuntu 16.4

### ISSUE THREAD

**Issue by asdubey91** [Kong/kong#3035] opened 2017-11-16 10:39 UTC
### Steps To Reproduce
Go through the installation.
1. https://getkong.org/install/docker/
2. curl -i http://localhost:8001/ is not working.

**Comment by kikito** [comment] 2017-11-16 15:02
I appreciate you took the time to open an issue for this. However, kong github issues are for bug reports only. I kindly ask you to repeat your question on the channels we have habilitated for it:

* The main place for questions is [gitter](https://gitter.im/Mashape/kong)
* Alternatively, there's also a [mailing list](https://groups.google.com/forum/#!forum/konglayer), in case you prefer that format.

I'll close this issue now. If you think this was not a question, please reopen.

**Closed by kikito** 2017-11-16 15:02 UTC

**Comment by asdubey91** [comment] 2017-11-16 15:07
Thanks for your king response. I solved it.

**Comment by souravPwC** [comment] 2018-03-14 08:10
I am getting the same issue . Could you please tell me how you solved the issue?

**Comment by asdubey91** [comment] 2018-03-14 09:49
Sure, Please share your scenario.

**Comment by souravPwC** [comment] 2018-03-14 11:07
Hi , I am installing kong using docker on windows 7. I have successfully setup docker on windows 7 using oracle VM. then I have done the following necessary step for kong installation , 
1.Run Docker PosgreSQL database container
2. Run migration
3.Start Kong
4.These are env variable I have set :  KONG_ADMIN_LISTEN (value : 0.0.0.0:8001) , KONG_DATABASE(value : postgres).
5.Both my docker container is up , while testing with curl , I am getting curl: (7) Failed to connect to localhost port 8001: Connection refused.

![image](https://user-images.githubusercontent.com/33145296/37398836-c2a89688-27a5-11e8-9ac2-b4b0f49d69dd.png)


Please help.

**Comment by asdubey91** [comment] 2018-03-14 12:57
Hi Sourav,

You need to perform all there step to config kong.
https://getkong.org/install/docker/?_ga=2.19672186.378379253.1521030870-95009692.1521030870
shown in this doc.
I got this  issue because of linking in step 2. You need to delete this old images pull the latest one and build again



If your issue still persist we can debug.

**Comment by souravPwC** [comment] 2018-03-14 15:03
Following are the commands I ran,

1. docker run -d --name kong-database -p 5432:5432 -e "POSTGRES_USER=kong" -e "POSTGRES_DB=kong" postgres:9.4
2. docker run --rm --link kong-database:kong-database -e "KONG_DATABASE=postgres" -e "KONG_PG_HOST=kong-database" -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" kong:latest kong migrations up.
 
3. docker run -d --name kong --link kong-database:kong-database -e "KONG_DATABASE=postgres" -e "KONG_PG_HOST=kong-database" -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" -e "KONG_PROXY_ERROR_LOG=/dev/stderr" -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" -e "KONG_ADMIN_LISTEN=0.0.0.0:8001" -e "KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444" -p 8000:8000 -p 8443:8443 -p 8001:8001 -p 8444:8444 kong:latest.

**Comment by hutchic** [comment] 2018-03-14 15:56
These types of issues should be discussed at https://discuss.konghq.com/

but I copy and pasted your commands and could not reproduce

```
ubuntu@ip-172-31-24-121:~$ docker run -d --name kong-database -p 5432:5432 -e "POSTGRES_USER=kong" -e "POSTGRES_DB=kong" postgres:9.4

ubuntu@ip-172-31-24-121:~$ docker run --rm --link kong-database:kong-database -e "KONG_DATABASE=postgres" -e "KONG_PG_HOST=kong-database" -e "KONG_CASS

ubuntu@ip-172-31-24-121:~$ docker run -d --name kong --link kong-database:kong-database -e "KONG_DATABASE=postgres" -e "KONG_PG_HOST=kong-database" -e
G_CASSANDRA_CONTACT_POINTS=kong-database" -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" -e "KONG_PROXY_ERROR_LOG=/dev/s
r" -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" -e "KONG_ADMIN_LISTEN=0.0.0.0:8001" -e "KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444" -p 8000:8000 -p 8443:8443 -p 8001:
 -p 8444:8444 kong:latest

ubuntu@ip-172-31-24-121:~$ curl -I localhost:8001
HTTP/1.1 200 OK
Server: openresty/1.11.2.5
Date: Wed, 14 Mar 2018 15:53:59 GMT
Content-Type: application/json
Connection: keep-alive
Access-Control-Allow-Origin:

ubuntu@ip-172-31-24-121:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
ubuntu@ip-172-31-24-121:~$ docker --version
Docker version 17.05.0-ce, build 89658be

ubuntu@ip-172-31-24-121:~$ docker images | grep kong
kong                                latest              6afbb6ef6005        40 hours ago        314MB
```

double check the kong image SHA you're running matches the latest (in the debug above)

try running the curl command from inside the kong image
```
ubuntu@ip-172-31-24-121:~$ docker exec -it kong curl localhost:8001
```

**Comment by sateeshBangarugiri** [comment] 2019-07-31 04:49
chmod +x edgex_provision.sh
./edgex_provision.sh
> Provisioning Addressibles
curl: (7) Failed to connect to localhost port 48081: Connection refused

curl: (7) Failed to connect to localhost port 48081: Connection refused

> Provisioning Value Descriptors
curl: (7) Failed to connect to localhost port 48080: Connection refused

curl: (7) Failed to connect to localhost port 48080: Connection refused

curl: (7) Failed to connect to localhost port 48080: Connection refused

curl: (7) Failed to connect to localhost port 48080: Connection refused

curl: (7) Failed to connect to localhost port 48080: Connection refused

> Creating Device Profile
curl: (7) Failed to connect to localhost port 48081: Connection refused

> Creating Device Service
curl: (7) Failed to connect to localhost port 48081: Connection refused

> Creating Device
curl: (7) Failed to connect to localhost port 48081: Connection refused
....plz anyone tel how to resolve this??
