### ISSUE TITLE
Opentracing / Zipkin Plugin

### ISSUE THREAD

**Issue by sonicaghi** [Kong/kong#1865] opened 2016-12-02 04:25 UTC
I was asked regarding http://zipkin.io/ today - Perhaps a Kong plugin to have proper tracing from client to upstream is a nice visual addition.

**Comment by Tieske** [comment] 2016-12-02 09:23
I think that would be implementing http://opentracing.io/ instead of something zipkin specific.

**Comment by sinzone** [comment] 2016-12-03 02:34
correct @Tieske

**Comment by sonicaghi** [comment] 2017-09-24 21:27
https://github.com/Mashape/kong/issues/1330

**Comment by thefosk** [comment] 2018-04-27 21:15
Duplicate of #1330. @james-callahan is working on it right now and we should have it very very soon.

**Closed by thefosk** 2018-04-27 21:15 UTC
Labels: idea/new plugin
