### ISSUE TITLE
odd behavior on worker restart (hybrid mode)

### ISSUE THREAD

**Issue by flrgh** [Kong/kong#7619] opened 2021-07-28 23:01 UTC
### Summary
- Kong version (`2.4.1`)
- Odd behavior on worker restart

### Details

Recently I've seen a few instances where worker process 0 dies unexpectedly due to $reason (this is its own mystery):

> 2021/07/28 05:35:01 [alert] 1#0: worker process 60 exited on signal 11

The NGINX master process, of course, spins up a new process with id of 0 to replace it. Worker 0, as we all know, is responsible for lots of singleton-ish timers and such, so these are all kicked off.
 
#### Observation 1: config is reloaded from the filesystem cache

> 2021/07/28 05:35:02 [info] 1093#0: *22608082 [lua] clustering.lua:866: init_worker(): found cached copy of data-plane config, loading.., context: init_worker_by_lua*

In most cases this is probably fine, because the declarative module does do some locking around config reload steps, but it does open the door to interesting race conditions that would be really really hard to debug.

Example: what if the old, now defunct worker 0 died after loading a new config (`declarative.load_into_cache_with_events()`) but _before_ it could persist the new config blob to disk? In that case, the new worker 0 process is going to load what is now stale/old config into memory.

IMO even if we're in crazy edge case land, it's a bug that the replacement process is trying to reload the config from cache in the first place. The single worker restart scenario is not uncommon but certainly not so uncommon that it's safe to disregard. Heck, I'd say in most cases that worker 0 is going to allocate more RAM than the other workers, making it more attractive to the OOM Killer. Kong should differentiate the worker replacement from a fresh start/reload and skip this branch of execution.
 
#### Observation 2: config update failures

I have evidence of this happening at least twice in our environment. After a replacement worker 0 process starts up, about ~20-40% of config updates start to fail with this error:

> 2021/07/28 05:38:17 [error] 1093#0: *22625684 [lua] clustering.lua:223: unable to update running config: timeout, context: ngx.timer

It seems to persist as well. Once Kong gets into this state, I haven't seen the errors fully go away (even 8+ hours later after peak hours) without a full restart. For context, this is in a busy cluster with lots of steady traffic but also lots of frequent config updates. We have `db_update_frequency` set to 60 just to throttle update events, because there is typically a config change at least once per minute.

I don't think this seems like a side-effect of my first observation, rather a comorbidity, and I don't know what the bug is, so I'm just putting it out there in case anyone's run into this before. Seems like the timeout _most likely_ occurs when waiting for all workers to ACK the `flip_config` event, so maybe somebody more familiar with that can chime in. I would expect these errors to be accompanied by other errors (like failed `post()`/`poll()` in the events subsystem), but nope. Do y'all have any suggestions on what I can do to debug (or any potential bandaids to remediate)? 

### Steps To Reproduce

Replicating the config reload on worker 0 process replacement is pretty easy. Just `kill -9` the pid of the current worker 0 and watch the replacement proc start up.

I have not been able to reproduce the config reload failures from observation 2, unfortunately.

### Additional Details & Logs

Can't give away too many details about our environment without running afoul of policy, unfortunately,but I'll share what I can.

- Kong 2.4.1
- OS/runtime: docker, using kong's centos upstream image as a build base
- Hybrid mode, using PKI for DP <--> CP comms
- DB: postgres (for the CP anyhow)
- DP nodes are decently beefy: 12 CPU w/ 64GB RAM
- worker_processes = auto (so, 12 workers)
- _Large_ configuration: the environment I'm debugging right now has ~6k services and roughly the same number of routes, and `{{prefix}}/config.cache.json.gz` is ~7MB (had to patch MAX_PAYLOAD in `kong.clustering` to accommodate this).

The large config is likely a contributing factor here--would happily accept any advice on further tuning Kong/NGINX for this :)

**Comment by dndx** [comment] 2021-08-04 17:16
Hello @flrgh,

Thanks for the detailed analysis. For observation 1, I think your interpretation is correct. If we haven't guarded correctly against worker 0 crashing and loading from cached config when it respawns, then we could potentially overwrite newer config inside the shdict with an old cache. That should definitely be fixed.

For observation 2, I haven't tried this kind of scenario in the past, but my immediate reaction is that the timeout message may come from either the config flip lock or sending the declarative config update to the stream subsystem via the unix domain socket. Quick question, have you enabled the `stream_listen` in your config?

**Comment by flrgh** [comment] 2021-08-04 19:12
Hiya :wave:

> Quick question, have you enabled the stream_listen in your config?

Yup! It's _very_ lightly used, like <10 services/routes. I'm not very knowledgeable on how the http/stream subsystems coexist (i.e. which resources/limits are shared between the two), so I'd be really grateful for any other thoughts you have about how having stream proxy enabled might be affecting us.

---

One thing I've noticed after going over our logs some more is that the config update timeouts often coincide with exhaustion of running timer slots. Example:

> 2021/08/01 09:51:48 [alert] 63#0: lua failed to run timer with function defined at @/usr/local/share/lua/5.1/resty/dns/balancer/base.lua:1358: 4096 lua_max_running_timers are not enough

The most common functions I see showing up in this type of log entry are:

* DNS balancer callbacks (i.e. the example entry I just included)
* resty.counter sync callbacks (presumably from prometheus metrics)
* The [update_balancer_state function](https://github.com/Kong/kong/blob/bab602e53f10626b2ee0d0319da4a2db095712ff/kong/runloop/balancer.lua#L858) in `kong.runloop.balancer`

It's really difficult to separate cause from effect, but this has lead me to what I think is another bug. At times I'm seeing _thousands_ of errors for `update_balancer_state` in the span of an hour, which stuck out to me because it shouldn't run more than once every `worker_state_update_frequency` seconds (15s for us) per worker process. After some digging, I found that `kong.runloop.handler` calls `balancer.init()` in its [event handler](https://github.com/Kong/kong/blob/bab602e53f10626b2ee0d0319da4a2db095712ff/kong/runloop/handler.lua#L312-L347), which effectively re-schedules the `update_balancer_state` function. I added extra logging to confirm this--every time a config flip happens, the number of pending timers increases and never seems to come back down.

It seems like the (unlikely) combo of db-less/hybrid mode with `worker_consistency = "eventual"` might not have been considered as a test case. I'm not even sure if it's a legitimate use case? For us this setting was just leftover in our config templates from before we switched from classic mode to hybrid, so it was more of an oversight than a deliberate decision. The way I see it either `balancer.init()` should be smarter about not scheduling additional `update_balancer_state` timers _or_ Kong should just force the behavior of `worker_consistency = "strict"` when in db-less/hybrid mode.

**Comment by flrgh** [comment] 2021-08-04 23:53
Update: `worker_consistency = "strict"` has not fixed the problem :(

To reproduce this scenario, we loaded up a control-plane with a comparable config and took a few steps to accelerate the timeline of bad-ness:

1. `db_update_frequency = 5` in the CP
2. Lowered max running/pending timers to 512/2048 in the DP nodes
3. Wrote a script to update a service several times per minute
4. Fired a reasonable amount of traffic at the DP nodes

6 nodes, split 3/3 between eventual/strict worker consistency.

I have a thread that logs pending/running timers every few seconds and observed the following:

1. Nodes with eventual worker_consistency have a steadily increasing count of pending timers, whereas nodes with strict do not. This is as expected
2. Three nodes (two strict, one eventual) saw their running timer count steadily increase over time until they maxed out the 512 limit
3. Three nodes have increased over time, but seem to have leveled off around ~300-400 running timers

So it looks like update_balancer_state wasn't necessarily the smoking gun--back to the drawing board there.

**Comment by flrgh** [comment] 2021-08-06 00:44
Update: I did a whole bunch of debugging by patching `ngx.timer.at` and `ngx.timer.every` to do some extra logging and accounting. Maybe I'm misunderstanding something, but I think this code in the healthchecker module is buggy:

https://github.com/Kong/lua-resty-healthcheck/blob/1.4.2/lib/resty/healthcheck.lua#L1457-L1509

`healthcheck.new()` is called many times in quick succession when updating the balancer state for a config change, so `check_healthcheck_timer` gets scheduled several times when (I think) it should be scheduled only once. It's not yet clear to me how this leads to an ever-increasing number of timers, because it seems as though this branch of code shouldn't be executed after `active_check_timer` is scheduled the first time, but I have definitely witnessed it.

**Comment by dndx** [comment] 2021-08-18 17:04
@javierguerragiraldez any thoughts on the above comment regarding health checker's timer usage?

**Comment by javierguerragiraldez** [comment] 2021-08-19 07:18
Hi,
on a first reading of that part of the code, I don't think the `active_check_timer` could be started more than once; but the `check_healthcheck_timer`, on the other hand, is started once for each call of `healthcheck.new()`, and there's no specific terminating point.  so these could pile up indefinitely.  Of course, those aren't anchored anywhere, so they **should** be caught by the garbage collector and stopped, but that's very undefined.  there's not even a guarantee that they would survive long enough to even try to `self:get_periodic_lock()`

I think a more reliable way would be to set those timers as `detached = true` so they won't be garbage-collected, and add a `self:cancel()` call when they succeed in setting the first `active_check_timer`.

It would probably be worthwhile to reverse the `if self:get_periodic_lock() and not active_check_timer then` condition, so any "latecomer" wouldn't try to grab the lock after the `active_check_timer` has been set.

after this, I thought of putting these as an issue in the Kong/lua-resty-healthcheck repo, but it seems we're using version 1.4.2, while the version 2.0.0 is completely different in how it uses timers.  Perhaps we should either move to the master branch, or at least backport the timer changes.

**Comment by flrgh** [comment] 2021-08-30 20:00
Thanks @javierguerragiraldez :)

Re: lua-resty-healthcheck, I had the same thought about that code path simply not existing in the 2.x branch. Would be awesome to see that dependency updated for some potential stability wins, but I understand that's probably a big undertaking due to how tightly-coupled it is with lua-resty-worker-events, which (I think) would need to be updated as well.

**Comment by flrgh** [comment] 2021-08-30 20:14
Thanks everyone for helping debug and rubber-duck with me on this! As of now I think three different bugs have been identified here:

1. config is reloaded from FS cache on worker #0 replacement
2. `db = off` + `worker_consistency = eventual` leaks timer instances on config reload
3. lua-resty-healthcheck 1.4.2 leaks timer instances on config reload

They are all pretty much independent of one another. Should I create new, separate issues for these items and retire this one so that there are some more manageable tickets for the backlog, or should I leave everything as-is?

**Comment by javierguerragiraldez** [comment] 2021-08-31 13:19
> Re: lua-resty-healthcheck, I had the same thought about that code path simply not existing in the 2.x branch.

The history is complicated, I've asked and it seems that we're using a fork of 1.4.2 precisely because of timer management improvements that weren't merged upstream, so moving to 2.x would be a serious regression.

that PR is about fixing what i think is a serious bug on reload; it fails at least one test that i'm not sure is appropriate anymore.   so i'd like to know if it improves the situation you've identified before trying to improve the test itself.   could you try it and see if it makes a difference?

**Comment by flrgh** [comment] 2021-09-17 17:36
Hey @javierguerragiraldez sorry it's taken a while to follow up. The patch I wound up using in our environment addresses the issue by anchoring `check_healthcheck_timer` at the module scope and adding an extra nil check for it. It looks something like this:

```patch
diff --git a/lib/resty/healthcheck.lua b/lib/resty/healthcheck.lua
index b115ca3..6e759ff 100644
--- a/lib/resty/healthcheck.lua
+++ b/lib/resty/healthcheck.lua
@@ -155,6 +155,7 @@ local hcs = setmetatable({}, {
 })

 local active_check_timer
+local check_healthcheck_timer

 -- TODO: improve serialization speed
 -- serialize a table to a string
@@ -1456,11 +1457,10 @@ function _M.new(opts)

   -- if active checker is needed and not running, start it
   if (self.checks.active.healthy.active or self.checks.active.unhealthy.active)
-    and active_check_timer == nil then
+    and check_healthcheck_timer == nil and active_check_timer == nil then

     self:log(DEBUG, "starting timer to check active checks")
-    local err
-    local check_healthcheck_timer, err = resty_timer({
+    check_healthcheck_timer, err = resty_timer({
       recurring = true,
       -- check if no worker is actively checking health status every 10 check
       -- periods
```

It's admittedly a hastily thrown together patch, so I'm unsure if there are any regressions it's causing, but it's been in place for almost a month now with no new reports of healthcheck problems (and it has indeed fixed the runaway timer issue).

Since that patch seems to fix our problem, I haven't been able to prioritize a tryout of Kong/lua-resty-healthcheck#81, though at a glance it looks like it should work and is probably a better solution than the patch that I came up with :)

**Comment by javierguerragiraldez** [comment] 2021-09-17 17:54
nice patch, i'm glad it works for you.   on a quick read, it seems it avoid the problem of a `check_healthcheck_timer` being cancelled too soon, while avoiding spawning extra timers.

but now the `check_healthcheck_timer` stays running forever, and keeps blocking any new one.  I'm not sure it's a bad thing, but doesn't seem right.  probably it could be slightly safer by adding

```
check_healthcheck_timer:cancel()
check_healthcheck_timer = nil
```
after it succeeds in launching the `active_check_timer`.   can you try if this doesn't spoil your fix?  and if so, it would be great if you submit a PR!

**Closed** 2022-10-28 23:22 UTC
Labels: core/clustering
