### ISSUE TITLE
logging plugins violate entity schema for empty tag array

### ISSUE THREAD

**Issue by Morl99** [Kong/kong#6469] opened 2020-10-14 09:13 UTC
### Summary

We noticed a problem in our production kong instance. We use the tcp-log plugin to send analytics data to elasticsearch. The data that is send includes the consumer which in turn includes the tags. In our instance some consumers have tags while others don't. This leads to the following two serialisations (the other properties are left out for brevity):

**consumer with tags**
```json
"consumer": {
    "created_at": 1600857126,
    "ws_id": "3b85afc8-5892-44f2-a206-7a9d1efd0ae8",
    "id": "5e174d20-e8ce-47b8-b8fd-b2ac0b587116",
    "tags": [
      "tag1"
    ],
    "username": "username-1"
  }
```

**consumer without tags**

```json
"consumer": {
    "created_at": 1600857586,
    "ws_id": "3b85afc8-5892-44f2-a206-7a9d1efd0ae8",
    "id": "4b974693-13c2-42bc-bf70-36e6971868d7",
    "tags": { },
    "username": "username-2"
  }
```
_(We observe the same behaviour for file-log as well, this might be easier to debug)_
This throws the elasticsearch mapping off board. Tags really should be an empty array instead of an empty object. We are unsure, if this happens in other properties as well.

### Steps To Reproduce

1. Create consumer username-1 with tag "tag1", create an api key
2. Create consumer username-2 without tags, create an api key
3. Create Service and Route with file-log plugin and key-auth plugin
4. Call the route with both consumers and read the log. Observe the different json schemas (`consumer.tags`).

### Additional Details & Logs

- Kong version: 2.1.4
- Operating system --> official kong:2.1.4-alpine docker image

**Comment by Tieske** [comment] 2020-10-14 09:24
similar issue here: https://github.com/Kong/kong/issues/6390

**Comment by Morl99** [comment] 2020-10-14 16:56
Thanks for the cross reference, I agree. We did look for issues before posting, but did not find the one you created. This confirms that the problem is not only confined to consumer.tags.

**Comment by bungle** [comment] 2020-10-14 17:49
> difference being that in this case the consumer data is most likely retrieved from the DAO, hence that is where the fix should be. Whereas in the linked issue

It is questionable to add any metatables to DAO output for JSON encoding. Perhaps our DAOs should have instead something like dao:to_json().

**Comment by Tieske** [comment] 2020-10-15 07:43
> It is questionable to add any metatables to DAO output for JSON encoding

agreed.

But if you do it in the log-phase only, then it means we have to copy the entire consumer object, before attaching the array_mt. (if we wouldn't copy it, it would technically be identical to doing it in the DAO, since it is a passed-by-reference-read-only object)

shouldn't we be attaching the array_mt by default, for any schema defining the type as "array"? (this might actually be the most consistent way of dealing with it?)

**Comment by Tieske** [comment] 2020-11-01 09:04
@Morl99 do you have reproduction steps? also, what datastore do you use and what deployment (traditional or hybrid)

**Comment by Morl99** [comment] 2020-11-01 16:01
Well, they are included in the description. But I guess they lack the appropriate amount of details. I can quickly answer the other questions today, maybe it helps:
We have a traditional deployment using a Postgres SQL Database as a datastore.

So @bungle if you recreate the data as described, it actually logs correctly with an empty tags array? That is weird, and it means we have to find the difference in the setup. Let me know what additional details would help you with that.

**Comment by Tieske** [comment] 2020-11-02 07:50
@Morl99 here's what I did;

```shell

export LOGPATH=/kong-plugin/servroot/logs/filelog.log
kong migrations bootstrap --force
kong restart

http -f :8001/consumers username=username-1 tags[]=tag1
http -f :8001/consumers username=username-2
http :8001/consumers/username-1/key-auth key=user1
http :8001/consumers/username-2/key-auth key=user2

http :8001/services name=test url=http://httpbin.org/anything
http -f :8001/services/test/routes name=test paths[]=/

http -f :8001/plugins name=file-log config.path=$LOGPATH
http -f :8001/plugins name=key-auth

http :8000/ apikey:user1 > /dev/null
sleep 1
cat $LOGPATH | jq .consumer
rm $LOGPATH

http :8000/ apikey:user2 > /dev/null
sleep 1
cat $LOGPATH | jq .consumer
rm $LOGPATH
```

The result being (last bit);
```
[Kong-2.1.4:/kong]# http :8000/ apikey:user1 > /dev/null
[Kong-2.1.4:/kong]# sleep 1
[Kong-2.1.4:/kong]# cat $LOGPATH | jq .consumer
{
  "created_at": 1604303167,
  "id": "3fd78f05-6571-4d05-a57a-eb5a1d2a310c",
  "tags": [
    "tag1"
  ],
  "username": "username-1"
}
[Kong-2.1.4:/kong]# rm $LOGPATH
[Kong-2.1.4:/kong]#
[Kong-2.1.4:/kong]# http :8000/ apikey:user2 > /dev/null
[Kong-2.1.4:/kong]# sleep 1
[Kong-2.1.4:/kong]# cat $LOGPATH | jq .consumer
{
  "created_at": 1604303168,
  "id": "0c971af4-e167-4ae5-95a9-6e57cd273e57",
  "username": "username-2"
}
[Kong-2.1.4:/kong]# rm $LOGPATH
```

So how did you create the consumers? since you get an empty array/object whereas I get `NULL`?

**Comment by bungle** [comment] 2020-11-02 11:41
I tried @Tieske example with:
```
update consumers set tags = '{}' where tags is null;
```

but that resulted `[]` in the log file.

**Comment by Morl99** [comment] 2020-11-12 21:09
I doubt that it as anything to do on how I create the consumer, but rather on how the log is created. I forgot a tiny bit of detail (which won't help you anyways, because you cannot access the code): We have forked the file-log and tcp-log plugins a while ago. So it is entirely possible, that this issue is not reproducible with the current version of kong. Let me try to repeat your steps in a version of kong where I remove our forks and see if that solves the problem. If so, I "just" need to rebase our forked plugins, that would be good news.

(Just a sidenote why we forked those plugins: We need to be able to not log headers and query params)

**Comment by Morl99** [comment] 2020-11-12 21:52
Weird enough, I can confirm that the steps you posted lead to the correct log output, i.e. one without a tags: key for user2. This happens even with our forked plugin... 

Even worse, when I redo the steps that we did in production (creating the consumer with konga), it now leads to an output with an empty array (as @bungle described). So now I am afraid, that this is not really reproducible any longer, but that this was due to old/stale data in the database (because the consumer was actually created with a much older version of Kong and Konga).

Unless I can think of anything else, I think we can close this issue. Sorry for the disturbance, and thanks for all the helpful input.

@Tieske many thanks for showing me httpie, that tool is new to me, and I love it.

**Comment by Tieske** [comment] 2020-11-13 08:26
Let's close this for now, and reopen if it comes back.

**Closed by Tieske** 2020-11-13 08:26 UTC
Labels: core/pdk
