### ISSUE TITLE
Cannot fetch an upstream named auth

### ISSUE THREAD

**Issue by susmitpy** [Kong/kong#13845] opened 2024-11-07 08:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.8.0.0

### Current Behavior

Using a fresh kong image in DB mode after running `kong migrations bootstrap`, when an attempt is made to get an upstream named 'auth' by making the request 
```bash 
curl http://localhost:8001/upstreams/auth
```

The below error is returned
```json
{"code":10,"name":"invalid unique name","message":"must not be one of: workspaces, consumers, certificates, services, routes, snis, upstreams, targets, consumer_groups, plugins, tags, ca_certificates, clustering_data_planes, parameters, vaults, key_sets, keys, filter_chains, files, legacy_files, workspace_entity_counters, consumer_reset_secrets, credentials, audit_requests, audit_objects, rbac_users, rbac_roles, rbac_user_roles, rbac_role_entities, rbac_role_endpoints, admins, developers, document_objects, applications, application_instances, groups, group_rbac_roles, login_attempts, keyring_meta, keyring_keys, event_hooks, licenses, consumer_group_plugins, consumer_group_consumers, rbac_user_groups"}
```

The same behaviour is seen when an upstream named 'auth' is already created. 
```console
❯ curl http://localhost:8001/upstreams/auth
{"code":10,"name":"invalid unique name","message":"must not be one of: workspaces, consumers, certificates, services, routes, snis, upstreams, targets, consumer_groups, plugins, tags, ca_certificates, clustering_data_planes, parameters, vaults, key_sets, keys, filter_chains, files, legacy_files, workspace_entity_counters, consumer_reset_secrets, credentials, audit_requests, audit_objects, rbac_users, rbac_roles, rbac_user_roles, rbac_role_entities, rbac_role_endpoints, admins, developers, document_objects, applications, application_instances, groups, group_rbac_roles, login_attempts, keyring_meta, keyring_keys, event_hooks, licenses, consumer_group_plugins, consumer_group_consumers, rbac_user_groups"}%
❯ curl http://localhost:8001/upstreams
{"next":null,"data":[{"id":"1f698911-8d82-4466-a06b-4650e6d16ae2","hash_on_cookie":null,"hash_on_cookie_path":"/","slots":10000,"hash_fallback":"none","hash_fallback_header":null,"hash_fallback_query_arg":null,"hash_fallback_uri_capture":null,"updated_at":1730964342,"created_at":1730964342,"tags":null,"client_certificate":null,"name":"auth","host_header":null,"hash_on":"none","algorithm":"round-robin","use_srv_name":false,"hash_on_header":null,"healthchecks":{"active":{"concurrency":10,"headers":null,"http_path":"/","https_sni":null,"https_verify_certificate":true,"healthy":{"interval":0,"http_statuses":[200,302],"successes":0},"unhealthy":{"http_failures":0,"http_statuses":[429,404,500,501,502,503,504,505],"interval":0,"tcp_failures":0,"timeouts":0},"timeout":1,"type":"http"},"passive":{"unhealthy":{"http_failures":0,"timeouts":0,"tcp_failures":0,"http_statuses":[429,500,503]},"type":"http","healthy":{"successes":0,"http_statuses":[200,201,202,203,204,205,206,207,208,226,300,301,302,303,304,305,306,307,308]}},"threshold":0},"hash_on_query_arg":null,"hash_on_uri_capture":null},{"id":"3e833591-788c-4c09-a487-78b85fbbf242","hash_on_cookie":null,"hash_on_cookie_path":"/","slots":10000,"hash_fallback":"none","hash_fallback_header":null,"hash_fallback_query_arg":null,"hash_fallback_uri_capture":null,"updated_at":1730964342,"created_at":1730964342,"tags":null,"client_certificate":null,"name":"monitor","host_header":null,"hash_on":"none","algorithm":"round-robin","use_srv_name":false,"hash_on_header":null,"healthchecks":{"active":{"concurrency":10,"headers":null,"http_path":"/","https_sni":null,"https_verify_certificate":true,"healthy":{"interval":0,"http_statuses":[200,302],"successes":0},"unhealthy":{"http_failures":0,"http_statuses":[429,404,500,501,502,503,504,505],"interval":0,"tcp_failures":0,"timeouts":0},"timeout":1,"type":"http"},"passive":{"unhealthy":{"http_failures":0,"timeouts":0,"tcp_failures":0,"http_statuses":[429,500,503]},"type":"http","healthy":{"successes":0,"http_statuses":[200,201,202,203,204,205,206,207,208,226,300,301,302,303,304,305,306,307,308]}},"threshold":0},"hash_on_query_arg":null,"hash_on_uri_capture":null}]}%
``` 

### Expected Behavior

`auth` should either be allowed or it should be included in the reserved names list which is sent in the error message.

### Anything else?

Referring to the main branch, `auth` is not part of the `CORE_ENTITIES` defined in `kong/constants.lua`.
Still somehow the error mentioned in file `spec/01-unit/01-db/01-schema/15-workspaces_spec.lua` as part of the test `rejects reserved names` is thrown 

Additional Suggestion: Instead of hardcoding the disallowed names in the test, if somehow `CORE_ENTITIES` is iterated upon and the message is formed programmatically, it will ensure consistency for later and reduce manual efforts whenever `CORE_ENTITIES` is to be updated

**Comment by xianghai2** [comment] 2024-11-07 09:53
Not sure the intention of this use case. 
Refer to folloing link for the authentication configuration:
https://docs.konghq.com/gateway/latest/kong-plugins/authentication/reference/

**Comment by susmitpy** [comment] 2024-11-07 10:02
Hi @xianghai2 

Actually I had created an upstream named auth and I was writing a Python script to automate the process. The script would first attempt to get the upstream by its name. If it does not exists ,then it would create the upstream

That's when I discovered this bug.
The name of any upstream being auth creates an issue

**Comment by susmitpy** [comment] 2024-11-07 10:03
Nothing to do with authentication in essence

**Comment by xianghai2** [comment] 2024-11-08 00:29
A ticket created to track this: https://konghq.atlassian.net/browse/KAG-5787

**Comment by xianghai2** [comment] 2024-11-18 02:00
Close this, and track with Jira KAG ticket.

**Closed by xianghai2** 2024-11-18 02:00 UTC
Labels: task/bug

**Comment by ProBrian** [comment] 2024-12-24 07:25
@susmitpy  could your provide your python script that you succeed to produce this issue? That would help us re-produce the issue, Thanks.

**Comment by susmitpy** [comment] 2024-12-24 08:36
[src copy.zip](https://github.com/user-attachments/files/18237624/src.copy.zip)

Hi @ProBrian 
Sharing the minimal setup to reproduce the issue.

You can run the setup with `docker compose up`
Check the logs of `srccopy-kong-setup-service-1`

The python script that throws the error is in `kong-setup-service/run.py`
The same error is thrown even if an upstream named `auth` has been created.

**Comment by ProBrian** [comment] 2025-01-02 02:49
@susmitpy Thanks for the response, we can reproduce this issue now. 
The route cause is there are some limitation on the route matching where reserved url route rule may cause conflicts. We are looking for a practical solution.
If you want to quickly workaround this issue, just don't use `auth` as the upstream name, since `auth` is an reserved name in kong. e.g. you can try to name your upstream like `authz`, then accessing `/upstreams/authz`.

**Comment by susmitpy** [comment] 2025-01-02 04:56
Yes @ProBrian 

A check against all the reserved names would help raise an exception with an informative message.
