### ISSUE TITLE
CORS with oauth2 strips the response header

### ISSUE THREAD

**Issue by sumeetn** [Kong/kong#2604] opened 2017-06-07 10:55 UTC
Kong 0.10.2

### Summary
When using oauth2 and CORS plugin for simultaneously for same api, the Kong response header strips the response header
This is what we get 
`response header:
Connection:keep-alive
Content-Length:2132
Content-Type:text/html; charset=utf-8
Date:Wed, 07 Jun 2017 08:26:03 GMT
Via:kong/0.10.2
X-Kong-Proxy-Latency:0
X-Kong-Upstream-Latency:5`

instead of 
`Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:content-type
Access-Control-Allow-Methods:GET
Access-Control-Allow-Origin:http://localhost:4200
Access-Control-Max-Age:3600`

### Steps To Reproduce

1. Add api 
`curl -i -X POST 
--url kong:8001/apis/ 
--data 'name=uigateway' 
--data 'uris=/api/gateway/ui' 
--data 'upstream_url= http://some-domain:some-port'`
2.
`curl -X POST http://kong:8001/apis/ask_GET/plugins 
--data "name=acl" 
--data "config.whitelist=root,022a038e-7080-4878-a84a-ae41b530be76"`
3.
`curl -X POST http://kong:8001/apis/ask_GET/plugins 
    --data "name=oauth2" 
    --data "config.enable_client_credentials=true" 
    --data "config.global_credentials" `
4.
`curl -X POST http://kong:8001/apis/ask_GET/plugins 
    --data "name=cors" 
    --data "config.origins=*" 
    --data "config.methods=GET,POST,PUT" 
    --data "config.headers=origin,content-type,accept,authorization,authentication,Access-Control-Allow-Headers,Access-Control-Allow-Origin,X-Total-Count" 
    --data "config.exposed_headers=origin,content-type,accept,authorization,authentication,Access-Control-Allow-Headers,Access-Control-Allow-Origin,X-Total-Count" 
    --data "config.preflight_continue=true" 
    --data "config.max_age=3600"`
Get request to api  gives 
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 404.

**Comment by fxaguessy** [comment] 2021-02-16 12:53
Hello, 
same problem here. Did you succeed to fix this ?

**Comment by StarlightIbuki** [comment] 2023-10-11 06:20
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:20 UTC
Labels: task/needs-investigation, plugins/oauth2
