### ISSUE TITLE
Can't update kong from 1.0.0rc2 to 1.0.0rc3

### ISSUE THREAD

**Issue by pocketdigi** [Kong/kong#4042] opened 2018-12-02 02:17 UTC
### Summary
Can't update kong from 1.0.0rc2 to 1.0.0rc3
Current version:1.0.0rc2
Database type:PostgreSQL
OS: CentOS 7

### Steps To Reproduce
After I install 1.0.0rc3, and execute
```
kong migrations up
```
it just show `database is already up-to-date`,but nothing happened,then I start Kong
```
kong start
```
show an error:

```
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:52: nginx: [warn] [lua] getssl.lua:10: OpenResty patch missing. See https://github.com/Kong/openresty-patches
nginx: [warn] [lua] init.lua:260: init(): missing "ngx.balancer".set_ssl_ctx API. Dynamic client SSL_CTX* will be unavailable
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:292: [postgres] ERROR: column "run_on" does not exist (154)
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/init.lua:292: in function 'init'
	init_by_lua:3: in main chunk


  Run with --v (verbose) or --vv (debug) for more details
```

If I use a new database, Kong can start normally, so I think 1.0.0rc3 is install successfully,but the migration script may have some problems.

**Comment by ZTzha** [comment] 2018-12-05 09:07
i have the same problem

**Comment by asomir** [comment] 2018-12-06 12:38
i have the same problem

**Comment by asomir** [comment] 2018-12-06 12:58
A hope, it help for you
[root@kong-01 ~]# kong migrations reset -c /etc/kong/kong.conf
> Are you sure? This operation is irreversible. [Y/n] y
resetting database...
database successfully reset
[root@kong-01 ~]# systemctl start kong
Job for kong.service failed because the control process exited with error code. See "systemctl status kong.service" and "journalctl -xe" for details.
[root@kong-01 ~]# less /usr/local/kong/logs/error.log
[root@kong-01 ~]# kong migrations bootstrap -c /etc/kong/kong.conf
bootstrapping database...
migrating core on database 'kong'...
core migrated up to: 000_base (executed)
core migrated up to: 001_14_to_15 (executed)
migrating oauth2 on database 'kong'...
oauth2 migrated up to: 000_base_oauth2 (executed)
oauth2 migrated up to: 001_14_to_15 (executed)
migrating acl on database 'kong'...
acl migrated up to: 000_base_acl (executed)
acl migrated up to: 001_14_to_15 (executed)
migrating jwt on database 'kong'...
jwt migrated up to: 000_base_jwt (executed)
jwt migrated up to: 001_14_to_15 (executed)
migrating basic-auth on database 'kong'...
basic-auth migrated up to: 000_base_basic_auth (executed)
basic-auth migrated up to: 001_14_to_15 (executed)
migrating key-auth on database 'kong'...
key-auth migrated up to: 000_base_key_auth (executed)
key-auth migrated up to: 001_14_to_15 (executed)
migrating rate-limiting on database 'kong'...
rate-limiting migrated up to: 000_base_rate_limiting (executed)
rate-limiting migrated up to: 001_14_to_15 (executed)
migrating hmac-auth on database 'kong'...
hmac-auth migrated up to: 000_base_hmac_auth (executed)
hmac-auth migrated up to: 001_14_to_15 (executed)
migrating response-ratelimiting on database 'kong'...
response-ratelimiting migrated up to: 000_base_response_rate_limiting (executed)
response-ratelimiting migrated up to: 001_14_to_15 (executed)
18 migrations processed
18 executed
database is up-to-date
[root@kong-01 ~]# systemctl start kong
[root@kong-01 ~]# systemctl status kong
● kong.service - kong service
   Loaded: loaded (/etc/systemd/system/kong.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2018-12-06 13:55:35 CET; 7s ago
  Process: 20245 ExecStart=/usr/local/bin/kong start (code=exited, status=0/SUCCESS)
 Main PID: 20290 (nginx)
   CGroup: /system.slice/kong.service
           ├─20290 nginx: master process /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong -c nginx.conf
           ├─20291 nginx: worker process
           └─20292 nginx: worker process

**Comment by ZTzha** [comment] 2018-12-07 02:37
@asomir I try it as you advice , but the same problem still append

**Comment by pocketdigi** [comment] 2018-12-07 02:49
> I hope, it help for you
> [root@kong-01 ~]# kong migrations reset -c /etc/kong/kong.conf
> 
> > Are you sure? This operation is irreversible. [Y/n] y
> > resetting database...
> > database successfully reset
> > [root@kong-01 ~]# systemctl start kong
> > Job for kong.service failed because the control process exited with error code. See "systemctl status kong.service" and "journalctl -xe" for details.
> > [root@kong-01 ~]# less /usr/local/kong/logs/error.log
> > [root@kong-01 ~]# kong migrations bootstrap -c /etc/kong/kong.conf
> > bootstrapping database...
> > migrating core on database 'kong'...
> > core migrated up to: 000_base (executed)
> > core migrated up to: 001_14_to_15 (executed)
> > migrating oauth2 on database 'kong'...
> > oauth2 migrated up to: 000_base_oauth2 (executed)
> > oauth2 migrated up to: 001_14_to_15 (executed)
> > migrating acl on database 'kong'...
> > acl migrated up to: 000_base_acl (executed)
> > acl migrated up to: 001_14_to_15 (executed)
> > migrating jwt on database 'kong'...
> > jwt migrated up to: 000_base_jwt (executed)
> > jwt migrated up to: 001_14_to_15 (executed)
> > migrating basic-auth on database 'kong'...
> > basic-auth migrated up to: 000_base_basic_auth (executed)
> > basic-auth migrated up to: 001_14_to_15 (executed)
> > migrating key-auth on database 'kong'...
> > key-auth migrated up to: 000_base_key_auth (executed)
> > key-auth migrated up to: 001_14_to_15 (executed)
> > migrating rate-limiting on database 'kong'...
> > rate-limiting migrated up to: 000_base_rate_limiting (executed)
> > rate-limiting migrated up to: 001_14_to_15 (executed)
> > migrating hmac-auth on database 'kong'...
> > hmac-auth migrated up to: 000_base_hmac_auth (executed)
> > hmac-auth migrated up to: 001_14_to_15 (executed)
> > migrating response-ratelimiting on database 'kong'...
> > response-ratelimiting migrated up to: 000_base_response_rate_limiting (executed)
> > response-ratelimiting migrated up to: 001_14_to_15 (executed)
> > 18 migrations processed
> > 18 executed
> > database is up-to-date
> > [root@kong-01 ~]# systemctl start kong
> > [root@kong-01 ~]# systemctl status kong
> > ● kong.service - kong service
> > Loaded: loaded (/etc/systemd/system/kong.service; enabled; vendor preset: disabled)
> > Active: active (running) since Thu 2018-12-06 13:55:35 CET; 7s ago
> > Process: 20245 ExecStart=/usr/local/bin/kong start (code=exited, status=0/SUCCESS)
> > Main PID: 20290 (nginx)
> > CGroup: /system.slice/kong.service
> > ├─20290 nginx: master process /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong -c nginx.conf
> > ├─20291 nginx: worker process
> > └─20292 nginx: worker process


**kong migrations reset will reset the database,and lost all config!** .

**Comment by asomir** [comment] 2018-12-07 13:19
Yeah, sorry! 
for me it was not so critical. in any case, you can try to put a config to it and execute

`kong migrations up -c /etc/kong/kong.conf`

Here /etc/kong/kong.conf is path to my kong konfig, your path may be different.

**Comment by p0pr0ck5** [comment] 2019-01-04 17:53
Since this issue is related to two previous RC releases, and the issue is no longer relevant, I will close this out. Thank you!

**Closed by p0pr0ck5** 2019-01-04 17:53 UTC
