### ISSUE TITLE
set_raw_query has no effect

### ISSUE THREAD

**Issue by pingcognito** [Kong/kong#9492] opened 2022-09-30 17:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.0.0

### Current Behavior

I am developing the ping-auth plugin, an authentication plugin that allows policy providers to modify requests as they go through Kong. It is then possible that a requests URL can be updated during the access phase to include a query string, which is implemented using [kong.service.request::get_raw_query](https://docs.konghq.com/gateway/latest/plugin-development/pdk/kong.service.request/#kongservicerequestset_raw_queryquery).  See the source code [here](https://github.com/pingidentity/kong-plugin-ping-auth/blob/main/ping-auth/access.lua#L259).

The following log message indicates that `set_raw_query` is being called:

```
2022/09/30 17:19:58 [debug] 876534#0: *302 [lua] access.lua:259: update_request(): [ping-auth] Updating URL query based on response from policy provider ("hello=nothing" => "hello=world&goodnight=moon")
```

However, the upstream URL is not modified:

```
{
  "args": {
    "hello": "nothing"
  },
  ...
  "url": "https://postman-echo.com/get?hello=nothing"
}
```

### Expected Behavior

`kong.service.request::set_raw_query` should modify the query string of the upstream URL.

### Anything else?

I'm not sure if this helps, but there's a closed [openresty issue](https://github.com/openresty/lua-nginx-module/issues/495) that indicates that `ngx.req::set_uri_args` has no effect when executed before a `proxy_pass` directive, and my `nginx-kong.conf` file makes it look like the `access_by_lua_block` is always before a `proxy_pass` directive.  If that's the case, a workaround could be to modify `$upstream_uri`, which it [looks like](https://github.com/Kong/kong/blob/master/kong/pdk/service/request.lua#L151) `kong.service.request::set_path` does, but according to the [`kong.service.request::set_path` documentation](https://docs.konghq.com/gateway/latest/plugin-development/pdk/kong.service.request/#kongservicerequestset_pathpath), "Input should not include the query string."

Our plugin source is found at https://github.com/pingidentity/kong-plugin-ping-auth.

**Comment by samugi** [comment] 2022-10-04 16:08
Hello @pingcognito, I have tested `set_raw_query()` on a simplified version of your plugin and couldn't reproduce the issue.
I would recommend starting by only executing some hardcoded example like: `kong.service.request.set_raw_query("foo=bar")` in the access phase of a test plugin like our https://github.com/Kong/kong-plugin to ensure it works, then move on to troubleshooting the more complex scenario introducing the remaining complexity. Let me know if that helps.

**Comment by pingcognito** [comment] 2022-10-04 19:13
Hi @samugi.

Thanks for the help and the suggestion.  I think I've narrowed it down to being caused by `kong.request.get_raw_query()` called before `kong.service.request.set_raw_query()`.

Here is a patch for https://github.com/Kong/kong-plugin to reproduce:

```
diff --git a/kong/plugins/myplugin/handler.lua b/kong/plugins/myplugin/handler.lua
index ada2079..fe1b8fc 100644
--- a/kong/plugins/myplugin/handler.lua
+++ b/kong/plugins/myplugin/handler.lua
@@ -67,7 +67,9 @@ function plugin:access(plugin_conf)
 
   -- your custom code here
   kong.log.inspect(plugin_conf)   -- check the logs for a pretty-printed config!
-  kong.service.request.set_header(plugin_conf.request_header, "this is on a request")
+
+  local raw_query = kong.request.get_raw_query() -- comment this out to get set_raw_query() working
+  kong.service.request.set_raw_query("hello=world&goodnight=moon")
 
 end --]]
 
```

**Comment by samugi** [comment] 2022-10-05 08:01
Hi @pingcognito,
I reproduced this using the [lua-nginx-module](https://github.com/openresty/lua-nginx-module#ngxreqset_uri_args); basically the problem occurs when you do:
```
local args = ngx.var.args
ngx.req.set_uri_args("foo=bar")
```
i.e. mixing direct access to ngx variables and then a function call to `ngx.req.set_uri_args`.

What works instead:
```
local args = kong.request.get_raw_query() -- gets ngx.var.args
ngx.var.args = "foo=bar"
```
or
```
local args = ngx.req.get_uri_args()
kong.service.request.set_raw_query("foo=bar") -- uses ngx.req.set_uri_args()
```

**Comment by pingcognito** [comment] 2022-10-05 16:56
Thanks again, @samugi. I switched to using `ngx.req.get_uri_args()` and `ngx.req.set_uri_args()` and it appears to work.

Would you like me to close this issue?

**Comment by samugi** [comment] 2022-10-06 07:06
glad that worked @pingcognito! I'm closing this.

**Closed by samugi** 2022-10-06 07:06 UTC
