### ISSUE TITLE
Client IP missing in X-FORWARDED-FOR 

### ISSUE THREAD

**Issue by rubenhak** [Kong/kong#6448] opened 2020-10-08 07:17 UTC
### Summary

Client IP present on X-FORWARDED-FOR on HTTP request, but missing in HTTPS request.

The value received in X-FORWARDED-FOR header on HTTP request is "\<the-client-ip\>, \<the-k8s-node-ip\>". 
Yet in case of HTTPS request the value is "\<the-k8s-node-ip\>". The client-ip is lost. 

Running in DigitalOcean environment in case it makes difference. 

### Steps To Reproduce

Kong installation values:
```yaml
proxy:
  enabled: true
  http:
    enabled: true
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "true"
```
Not sure what other steps to include.

### Additional Details & Logs

- Kong version: 2.1
- Kong Helm Chart version: kong-1.11.0

**Comment by Tieske** [comment] 2020-10-08 07:35
how have you configured the trusted ips?

**Comment by Tieske** [comment] 2020-10-08 07:35
see https://docs.konghq.com/2.1.x/configuration/#trusted_ips

**Comment by rubenhak** [comment] 2020-10-08 08:08
> how have you configured the trusted ips?

I tried setting the trusted ip in the chart, but it doesn't change anything. Doesn't seem like related to trusted ip because i can see the client ip in the HTTP request.

```yaml
env:
  trusted_ips: "0.0.0.0/0,::/0"
```

**Comment by Tieske** [comment] 2020-10-08 09:21
also check https://docs.konghq.com/2.1.x/configuration/#real_ip_header and real_ip_recursive

**Comment by bungle** [comment] 2020-10-08 12:25
@rubenhak, are you sure the problem is with Kong and not in Kubernetes? Can you try without any Kubernetes load balancing and TLS directly to Kong?

**Comment by bungle** [comment] 2020-10-08 12:49
I could not reproduce:

#### Setup

1. `KONG_TRUSTED_IPS="0.0.0.0/0,::/0" KONG_REAL_IP_HEADER=X-Forwarded-For kong start`
2. `http put :8001/services/bin url=http://httpbin.org/headers`
3. `http put :8001/services/bin/routes/bin paths=/ -f`

#### Tests

##### HTTP

```
$ http :8000?show_env=1
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 431
Content-Type: application/json
Date: Thu, 08 Oct 2020 12:49:14 GMT
Server: gunicorn/19.9.0
Via: kong/2.1.4
X-Kong-Proxy-Latency: 43
X-Kong-Upstream-Latency: 294

{
    "headers": {
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate",
        "Host": "httpbin.org",
        "User-Agent": "HTTPie/2.2.0",
        "X-Amzn-Trace-Id": "Root=1-5f7f0aca-00fbecb55670813a062c84d6",
        "X-Forwarded-For": "127.0.0.1, 82.203.225.15",
        "X-Forwarded-Host": "localhost",
        "X-Forwarded-Path": "/",
        "X-Forwarded-Port": "80",
        "X-Forwarded-Proto": "http",
        "X-Real-Ip": "127.0.0.1"
    }
}
```

##### HTTPS

```
$ https :8443?show_env=1 --verify no
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 431
Content-Type: application/json
Date: Thu, 08 Oct 2020 12:48:13 GMT
Server: gunicorn/19.9.0
Via: kong/2.1.4
X-Kong-Proxy-Latency: 47
X-Kong-Upstream-Latency: 281

{
    "headers": {
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate",
        "Host": "httpbin.org",
        "User-Agent": "HTTPie/2.2.0",
        "X-Amzn-Trace-Id": "Root=1-5f7f0a8d-02c7c383424e6d483b3b75ee",
        "X-Forwarded-For": "127.0.0.1, 82.203.225.15",
        "X-Forwarded-Host": "localhost",
        "X-Forwarded-Path": "/",
        "X-Forwarded-Port": "80",
        "X-Forwarded-Proto": "http",
        "X-Real-Ip": "127.0.0.1"
    }
}
```

**Comment by rubenhak** [comment] 2020-10-09 00:11
@Tieske, @bungle guys, thanks for quick response and cooperation. Turns out that since I was using SSL passthrough, it didn't allow the LB to inject the X-FORWARDED-FOR header. That's the reason that this all works for HTTP, but fails for HTTPS.

While trying to make this work I configured SSL termination which did the trick, now I see the client IP injected to the header, but the problem is that the LB tries to forward using HTTP to HTTPS port of the Kong Proxy. I understand that the question is now different from the original issue reported, but could you guys direct to the right direction? 

This is happening in DigitalOcean. Would appreciate if you could help to determine if this is a request to Kong or DO.  I submitted another request there as well:  https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/351

**Comment by StarlightIbuki** [comment] 2023-10-11 06:19
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:19 UTC
Labels: core/proxy
