### ISSUE TITLE
Some incorrect installation wizards at "Install Kong Gateway on Docker" on the website: https://docs.konghq.com/gateway/3.2.x/install/docker/

### ISSUE THREAD

**Issue by liupenghui-owen** [Kong/kong#10523] opened 2023-03-20 07:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.2.1

### Current Behavior

I was always failed to install the Kong following the  installation wizard on "Install Kong Gateway on Docker".
In following 2 steps.

"Prepare the Kong database:"
docker run --rm --network=kong-net \
  -e "KONG_DATABASE=postgres" \
  -e "KONG_PG_HOST=kong-database" \
  -e "KONG_PG_PASSWORD=kongpass" \
 kong:3.2.1 kong migrations bootstrap

and 
"Run the following command to start a container with Kong Gateway:"
docker run -d --name kong-gateway \
  --network=kong-net \
  -e "KONG_DATABASE=postgres" \
  -e "KONG_PG_HOST=kong-database" \
  -e "KONG_PG_USER=kong" \
  -e "KONG_PG_PASSWORD=kongpass" \
  -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
  -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
  -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
  -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
  -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
  -p 8000:8000 \
  -p 8443:8443 \
  -p 127.0.0.1:8001:8001 \
  -p 127.0.0.1:8444:8444 \
  kong:3.2.1

docker: Error response from daemon: manifest for kong:3.2.1 not found: manifest unknown: manifest unknown.

### Expected Behavior

Succeed to install Kong on Docker.

### Steps To Reproduce

I was always failed to install the Kong following the  installation wizard on "Install Kong Gateway on Docker".
In following 2 steps.

"Prepare the Kong database:"
docker run --rm --network=kong-net \
  -e "KONG_DATABASE=postgres" \
  -e "KONG_PG_HOST=kong-database" \
  -e "KONG_PG_PASSWORD=kongpass" \
 kong:3.2.1 kong migrations bootstrap

and 
"Run the following command to start a container with Kong Gateway:"
docker run -d --name kong-gateway \
  --network=kong-net \
  -e "KONG_DATABASE=postgres" \
  -e "KONG_PG_HOST=kong-database" \
  -e "KONG_PG_USER=kong" \
  -e "KONG_PG_PASSWORD=kongpass" \
  -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
  -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
  -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
  -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
  -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
  -p 8000:8000 \
  -p 8443:8443 \
  -p 127.0.0.1:8001:8001 \
  -p 127.0.0.1:8444:8444 \
  kong:3.2.1

docker: Error response from daemon: manifest for kong:3.2.1 not found: manifest unknown: manifest unknown.

### Anything else?

I succeed to install it using following commands:

"Prepare the Kong database:"
docker run --rm \
    --network=kong-net \
    --link kong-database:kong-database \
    -e "KONG_DATABASE=postgres" \
    -e "KONG_PG_HOST=kong-database" \
    -e "KONG_PG_USER=kong" \
    -e "KONG_PG_PASSWORD=kongpass" \
   -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
    kong/kong-gateway kong migrations bootstrap

"Run the following command to start a container with Kong Gateway:"
docker run -d --name kong-gw \
    --network=kong-net \
    --link kong-database:kong-database \
    -e "KONG_DATABASE=postgres" \
    -e "KONG_PG_HOST=kong-database" \
    -e "KONG_PG_PASSWORD=kongpass" \
    -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" \
    -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
    -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
    -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
    -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
    -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
    -p 8000:8000 \
    -p 8443:8443 \
    -p 8001:8001 \
    -p 8444:8444 \
    kong/kong-gateway

**Comment by liupenghui-owen** [comment] 2023-03-20 07:21
I succeed to install it using following commands, hope this helps to correct the Website page. :)

"Prepare the Kong database:"
docker run --rm
--network=kong-net
--link kong-database:kong-database
-e "KONG_DATABASE=postgres"
-e "KONG_PG_HOST=kong-database"
-e "KONG_PG_USER=kong"
-e "KONG_PG_PASSWORD=kongpass"
-e "KONG_CASSANDRA_CONTACT_POINTS=kong-database"
kong/kong-gateway kong migrations bootstrap

"Run the following command to start a container with Kong Gateway:"
docker run -d --name kong-gw
--network=kong-net
--link kong-database:kong-database
-e "KONG_DATABASE=postgres"
-e "KONG_PG_HOST=kong-database"
-e "KONG_PG_PASSWORD=kongpass"
-e "KONG_CASSANDRA_CONTACT_POINTS=kong-database"
-e "KONG_PROXY_ACCESS_LOG=/dev/stdout"
-e "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
-e "KONG_PROXY_ERROR_LOG=/dev/stderr"
-e "KONG_ADMIN_ERROR_LOG=/dev/stderr"
-e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl"
-p 8000:8000
-p 8443:8443
-p 8001:8001
-p 8444:8444
kong/kong-gateway

**Comment by sabertobihwy** [comment] 2023-03-20 17:45
`kong:3.2.1` -> `kong:3.2.1.0` ?

**Comment by hbagdi** [comment] 2023-03-20 22:41
cc @Kong/devrel

**Comment by hanshuebner** [comment] 2023-03-21 10:43
@liupenghui-owen We still have issues with the 3.2.1 Docker images being unavailable from Docker hub, but this is being worked on.  In the mean time, using `kong:latest` or `kong/kong-gateway` is a suitable workaround.

**Comment by rspurgeon** [comment] 2023-03-28 13:33
CC @Kong/team-docs

**Comment by StarlightIbuki** [comment] 2023-10-11 06:37
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:37 UTC
Labels: docker images
