### ISSUE TITLE
Bot-detection regexp breaks server request to kong 

### ISSUE THREAD

**Issue by alexagc** [Kong/kong#6626] opened 2020-12-04 10:19 UTC
### Summary

The new regular expression made in this [pull](https://github.com/Kong/kong/pull/5772) breaks all the request from nodejs (Axios and plain request with https module) and another languajes, rejected all the request made from servers to kong.

### Steps To Reproduce

1. Create a service and route
2. Add bot-plugin (global)
3. Make a request with this code

```javascript
const https = require("https");

https
  .get(
    "http://localhost:8000/test-route",
    (res) => {
      console.log("statusCode:", res.statusCode);
      console.log("headers:", res.headers);

      res.on("data", (d) => {
        process.stdout.write(d);
      });
    }
  )
  .on("error", (e) => {
    console.error(e);
  });
```

### Additional Details & Logs

- Kong version 2.2.x

**Comment by bungle** [comment] 2020-12-04 15:56
@alexagc, I tried this and could not reproduce.

**Comment by bungle** [comment] 2020-12-04 15:59
```
$ http :8001/services
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 377
Content-Type: application/json; charset=utf-8
Date: Fri, 04 Dec 2020 15:57:42 GMT
Server: kong/2.2.1
X-Kong-Admin-Latency: 2

{
    "data": [
        {
            "ca_certificates": null,
            "client_certificate": null,
            "connect_timeout": 60000,
            "created_at": 1607097144,
            "host": "bin.test",
            "id": "f1085a80-60c4-4dc2-b972-7f7b7cd15d38",
            "name": "bin",
            "path": "/anything",
            "port": 80,
            "protocol": "http",
            "read_timeout": 60000,
            "retries": 5,
            "tags": null,
            "tls_verify": null,
            "tls_verify_depth": null,
            "updated_at": 1607097144,
            "write_timeout": 60000
        }
    ],
    "next": null
}
```

```
$ http :8001/routes
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 495
Content-Type: application/json; charset=utf-8
Date: Fri, 04 Dec 2020 15:58:15 GMT
Server: kong/2.2.1
X-Kong-Admin-Latency: 2

{
    "data": [
        {
            "created_at": 1607096845,
            "destinations": null,
            "headers": null,
            "hosts": null,
            "https_redirect_status_code": 426,
            "id": "be637e94-02d0-45d5-bc5c-d139464de395",
            "methods": null,
            "name": "bin",
            "path_handling": "v0",
            "paths": [
                "/"
            ],
            "preserve_host": false,
            "protocols": [
                "http",
                "https"
            ],
            "regex_priority": 0,
            "request_buffering": true,
            "response_buffering": true,
            "service": {
                "id": "f1085a80-60c4-4dc2-b972-7f7b7cd15d38"
            },
            "snis": null,
            "sources": null,
            "strip_path": true,
            "tags": null,
            "updated_at": 1607096845
        }
    ],
    "next": null
}
```

```
$ http :8001/plugins
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 262
Content-Type: application/json; charset=utf-8
Date: Fri, 04 Dec 2020 15:57:16 GMT
Server: kong/2.2.1
X-Kong-Admin-Latency: 1

{
    "data": [
        {
            "config": {
                "allow": [],
                "deny": []
            },
            "consumer": null,
            "created_at": 1607097168,
            "enabled": true,
            "id": "813c4611-ab9e-4632-86fc-b119f9254436",
            "name": "bot-detection",
            "protocols": [
                "grpc",
                "grpcs",
                "http",
                "https"
            ],
            "route": null,
            "service": null,
            "tags": null
        }
    ],
    "next": null
}
```

```
$ cat as.js 
process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;
const https = require("https");

https
  .get(
    "https://localhost:8443/",
    (res) => {
      console.log("statusCode:", res.statusCode);
      console.log("headers:", res.headers);

      res.on("data", (d) => {
        process.stdout.write(d);
      });
    }
  )
  .on("error", (e) => {
    console.error(e);
  });
```

```
$ node as.js 
(node:68571) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
statusCode: 200
headers: {
  'content-type': 'application/json',
  'content-length': '311',
  connection: 'close',
  server: 'gunicorn/19.9.0',
  date: 'Fri, 04 Dec 2020 15:58:55 GMT',
  'access-control-allow-origin': '*',
  'access-control-allow-credentials': 'true',
  'x-kong-upstream-latency': '3',
  'x-kong-proxy-latency': '1',
  via: 'kong/2.2.1'
}
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Connection": "keep-alive", 
    "Host": "bin.test", 
    "X-Forwarded-Host": "localhost", 
    "X-Forwarded-Path": "/"
  }, 
  "json": null, 
  "method": "GET", 
  "origin": "127.0.0.1", 
  "url": "https://localhost/anything"
}
```

**Comment by alexagc** [comment] 2020-12-04 17:00
@bungle sorry, but when I posted the problem I didn't remember that I had a go outgoing-proxy that uses `Go-http-client / 1.1` as user-agent that has the error too, the following code snippet is with axios and you see the error clairly
```javascript
const axios = require('axios').default;

process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = 0;

(async () => {
  try {
    await axios.get('https://localhost:8443/');
    process.exit(0);
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
})();
```
The big problem is that by default some of the user-agents that was added in the pull break a lot of libraries used in servers or cli tools like Go-http-client, axios, scalaj-http.. and i don't know if that's the feature required by default

**Comment by bungle** [comment] 2020-12-04 17:27
@alexagc, yes I have no doubts about it. That is one huge of blob of regexes that is really hard to validate. Thus it stayed very long there until we merged, and it took two community members to suggest exactly the same. Now that feels like a mistake. Let's see how we can adjust it.

Yes I can reproduce this with `axios`.

I think the `Downloaders ...` should be removed from the list.

**Comment by bungle** [comment] 2020-12-04 17:33
Axios seems to be on default bot-list here too:
https://github.com/omrilotan/isbot/blob/main/list.json#L25

So quite reasonable to say it is mostly used as a bot?

**Comment by kikito** [comment] 2020-12-09 18:16
@alexagc While we decide what to do about this, you could try sidestepping the issue by [modifying Axios useragent](https://github.com/axios/axios/issues/2560)

**Comment by alexagc** [comment] 2020-12-10 10:04
@bungle yeah i agree it's hard to say if is a bot or not, in my case i have some consumers that consume my api from nodejs/go servers using axios/Go-http-client. It's not a big problem because i added that's two UA to the whitelist.

@kikito It was more easy to add that UA to the whitelist because i can't change my external consumers UA.

**Comment by kikito** [comment] 2020-12-16 18:25
Hello, 

I had not thought about the whitelist. Of course it was an option!

I have decided to close down this issue as "not an issue". I think Axios could be considered a "Bot", and the issue is easily sidestepped.

**Closed by kikito** 2020-12-16 18:25 UTC
Labels: plugins/bot-detection

**Comment by lgelfan** [comment] 2022-06-22 21:31
It would be nice, btw, if this was clarified in the plug-in documentation. It's pretty obvious in hindsight but not everyone is going to look through that big default regex block and it's also not entirely clear (without testing) what happens if there are _both_ `allow` and `deny` values (ie, evaluation rules). The ip-restriction plug-in, e.g., [makes this clear](https://docs.konghq.com/hub/kong-inc/ip-restriction/).

**Comment by jrnail23** [comment] 2023-09-06 01:55
FWIW, this issue (denying Axios) cost us about 20 wasted developer hours today. Seriously though, API consumers running Axios on nodejs would get 403s for no apparent reason -- how is that acceptable?
