### ISSUE TITLE
[OAUTH2 Plugin] Content Type for GET?

### ISSUE THREAD

**Issue by DanielTimLee** [Kong/kong#3076] opened 2017-12-07 02:27 UTC
### Summary

As far as I know,  there won't be necessary for having `Content-Type` Header field in GET Request,
But my kong-log keeps giving me this error.

I assume this might be a bug.

> 2017/12/07 02:13:36 [error] 151#0: *2644 [lua] public.lua:84: get_body_info(): don't know how to parse request body (no Content-Type), client: 172.17.0.1, server: kong, request: "GET /hi HTTP/1.0", host: "kong.example.com"

```
2017/12/07 02:21:20 [debug] 150#0: *4950 [lua] base_plugin.lua:20: rewrite(): executing plugin "oauth2": rewrite
2017/12/07 02:21:20 [debug] 150#0: *4950 [lua] base_plugin.lua:24: access(): executing plugin "oauth2": access
2017/12/07 02:21:20 [error] 150#0: *4950 [lua] public.lua:84: get_body_info(): don't know how to parse request body (no Content-Type), client: 172.17.0.1, server: kong, request: "GET /hi HTTP/1.0", host: "kong.example.com"
2017/12/07 02:21:20 [debug] 150#0: *4950 [lua] base_plugin.lua:28: header_filter(): executing plugin "oauth2": header_filter
2017/12/07 02:21:20 [debug] 150#0: *4950 [lua] base_plugin.lua:32: body_filter(): executing plugin "oauth2": body_filter
2017/12/07 02:21:20 [debug] 150#0: *4950 [lua] base_plugin.lua:32: body_filter(): executing plugin "oauth2": body_filter
```

https://stackoverflow.com/questions/5661596/do-i-need-a-content-type-for-http-get-requests

### Steps To Reproduce

1. Install Kong
2. Enable OAuth2 Plugin
3. Send GET Request
4. Whyyyyyyyyyyyyyyyy Content-Type?

### Additional Details & Logs

- Kong version (`$ kong version`) `- v0.11.2`
- Kong debug-level startup logs (`$ kong start --vv`)
```
2017/11/06 07:13:11 [verbose] Kong: 0.11.1
2017/11/06 07:13:11 [debug] ngx_lua: 10008
2017/11/06 07:13:11 [debug] nginx: 1011002
2017/11/06 07:13:11 [debug] Lua: LuaJIT 2.1.0-beta2
2017/11/06 07:13:11 [verbose] no config file found at /etc/kong/kong.conf
2017/11/06 07:13:11 [verbose] no config file found at /etc/kong.conf
2017/11/06 07:13:11 [verbose] no config file, skipping loading
2017/11/06 07:13:11 [debug] admin_access_log = "logs/admin_access.log"
2017/11/06 07:13:11 [debug] admin_error_log = "logs/error.log"
2017/11/06 07:13:11 [debug] admin_http2 = false
2017/11/06 07:13:11 [debug] admin_listen = "0.0.0.0:8001"
2017/11/06 07:13:11 [debug] admin_listen_ssl = "0.0.0.0:8444"
2017/11/06 07:13:11 [debug] admin_ssl = true
2017/11/06 07:13:11 [debug] anonymous_reports = true
2017/11/06 07:13:11 [debug] cassandra_consistency = "ONE"
2017/11/06 07:13:11 [debug] cassandra_contact_points = {"127.0.0.1"}
2017/11/06 07:13:11 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2017/11/06 07:13:11 [debug] cassandra_keyspace = "kong"
2017/11/06 07:13:11 [debug] cassandra_lb_policy = "RoundRobin"
2017/11/06 07:13:11 [debug] cassandra_port = 9042
2017/11/06 07:13:11 [debug] cassandra_repl_factor = 1
2017/11/06 07:13:11 [debug] cassandra_repl_strategy = "SimpleStrategy"
2017/11/06 07:13:11 [debug] cassandra_schema_consensus_timeout = 10000
2017/11/06 07:13:11 [debug] cassandra_ssl = false
2017/11/06 07:13:11 [debug] cassandra_ssl_verify = false
2017/11/06 07:13:11 [debug] cassandra_timeout = 5000
2017/11/06 07:13:11 [debug] cassandra_username = "kong"
2017/11/06 07:13:11 [debug] client_body_buffer_size = "8k"
2017/11/06 07:13:11 [debug] client_max_body_size = "0"
2017/11/06 07:13:11 [debug] client_ssl = false
2017/11/06 07:13:11 [debug] custom_plugins = {}
2017/11/06 07:13:11 [debug] database = "postgres"
2017/11/06 07:13:11 [debug] db_cache_ttl = 3600
2017/11/06 07:13:11 [debug] db_update_frequency = 5
2017/11/06 07:13:11 [debug] db_update_propagation = 0
2017/11/06 07:13:11 [debug] dns_error_ttl = 1
2017/11/06 07:13:11 [debug] dns_hostsfile = "/etc/hosts"
2017/11/06 07:13:11 [debug] dns_no_sync = false
2017/11/06 07:13:11 [debug] dns_not_found_ttl = 30
2017/11/06 07:13:11 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2017/11/06 07:13:11 [debug] dns_resolver = {}
2017/11/06 07:13:11 [debug] dns_stale_ttl = 4
2017/11/06 07:13:11 [debug] error_default_type = "text/plain"
2017/11/06 07:13:11 [debug] http2 = false
2017/11/06 07:13:11 [debug] latency_tokens = true
2017/11/06 07:13:11 [debug] log_level = "notice"
2017/11/06 07:13:11 [debug] lua_package_cpath = ""
2017/11/06 07:13:11 [debug] lua_package_path = "./?.lua;./?/init.lua;"
2017/11/06 07:13:11 [debug] lua_socket_pool_size = 30
2017/11/06 07:13:11 [debug] lua_ssl_verify_depth = 1
2017/11/06 07:13:11 [debug] mem_cache_size = "128m"
2017/11/06 07:13:11 [debug] nginx_daemon = "on"
2017/11/06 07:13:11 [debug] nginx_optimizations = true
2017/11/06 07:13:11 [debug] nginx_user = "nobody nobody"
2017/11/06 07:13:11 [debug] nginx_worker_processes = "auto"
2017/11/06 07:13:11 [debug] pg_database = "kong"
2017/11/06 07:13:11 [debug] pg_host = "127.0.0.1"
2017/11/06 07:13:11 [debug] pg_port = 5432
2017/11/06 07:13:11 [debug] pg_ssl = false
2017/11/06 07:13:11 [debug] pg_ssl_verify = false
2017/11/06 07:13:11 [debug] pg_user = "kong"
2017/11/06 07:13:11 [debug] prefix = "/usr/local/kong/"
2017/11/06 07:13:11 [debug] proxy_access_log = "logs/access.log"
2017/11/06 07:13:11 [debug] proxy_error_log = "logs/error.log"
2017/11/06 07:13:11 [debug] proxy_listen = "0.0.0.0:8000"
2017/11/06 07:13:11 [debug] proxy_listen_ssl = "0.0.0.0:8443"
2017/11/06 07:13:11 [debug] real_ip_header = "X-Real-IP"
2017/11/06 07:13:11 [debug] real_ip_recursive = "off"
2017/11/06 07:13:11 [debug] server_tokens = true
2017/11/06 07:13:11 [debug] ssl = true
2017/11/06 07:13:11 [debug] ssl_cipher_suite = "modern"
2017/11/06 07:13:11 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2017/11/06 07:13:11 [debug] trusted_ips = {}
2017/11/06 07:13:11 [debug] upstream_keepalive = 60
2017/11/06 07:13:11 [verbose] prefix in use: /usr/local/kong
2017/11/06 07:13:11 [verbose] preparing nginx prefix directory at /usr/local/kong
2017/11/06 07:13:11 [verbose] SSL enabled, no custom certificate set: using default certificate
2017/11/06 07:13:11 [verbose] default SSL certificate found at /usr/local/kong/ssl/kong-default.crt
2017/11/06 07:13:11 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2017/11/06 07:13:11 [verbose] admin SSL certificate found at /usr/local/kong/ssl/admin-kong-default.crt
2017/11/06 07:13:11 [debug] searching for OpenResty 'nginx' executable
2017/11/06 07:13:11 [debug] /usr/local/openresty/nginx/sbin/nginx -v: 'nginx version: openresty/1.11.2.4'
2017/11/06 07:13:11 [debug] found OpenResty 'nginx' executable at /usr/local/openresty/nginx/sbin/nginx
2017/11/06 07:13:11 [debug] starting nginx: /usr/local/openresty/nginx/sbin/nginx -p /usr/local/kong -c nginx.conf
2017/11/06 07:13:11 [verbose] could not start Kong, stopping services
2017/11/06 07:13:11 [verbose] stopped services
```
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System `Kong-Docker:latest (0.11.2)`

**Comment by thefosk** [comment] 2017-12-07 19:36
Is this a custom plugin?

**Comment by hishamhm** [comment] 2017-12-08 16:10
@DanielTimLee Thanks for reporting!

This may be a bug indeed. It seems this part of the plugin is looking at the body and requesting a Content-Type:

https://github.com/Kong/kong/blob/master/kong/plugins/oauth2/access.lua#L98

How are you passing the OAuth2 parameters in your GET request? Via the query string?

**Comment by hishamhm** [comment] 2017-12-08 17:59
Just checked and this is a duplicate of #3055. Closing this one then!

**Closed by hishamhm** 2017-12-08 17:59 UTC
Labels: pending user feedback
