### ISSUE TITLE
Exclude balancer retries against upstream from Kong latency

### ISSUE THREAD

**Issue by dcarley** [Kong/kong#8637] opened 2022-04-05 11:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.7.1

### Current Behavior

The `kong_latency` metric that's reported by the [Datadog plugin](https://docs.konghq.com/hub/kong-inc/datadog/#metrics) includes the time spent waiting for an upstream to respond for failed and retried requests.

We use this metric to alert the team administering Kong that they need to take action, e.g. fix a misbehaving plugin. However the current behaviour means that these alerts aren't actionable because they include upstream failures that are outside of their control and mask Kong's own latency.

### Expected Behavior

The `kong_latency` metric (and other log processors that depend on the same underlying data) to only include latency that Kong itself is adding to the request, excluding balancer retries.

This would be a partial revert of https://github.com/Kong/kong/pull/2494 (although the code has changed a lot since then). My understanding is that it could still include the last balancer try, but not the previous tries. Though maybe that's not useful, if the balancer is always quick and the comment about DNS lookups happening in the access phase is still true?

### Steps To Reproduce

1. Configure an upstream that accepts requests and doesn't respond
1. Configure the Datadog plugin (can use [statsd-logger](https://hub.docker.com/r/catkins/statsd-logger))
1. Make a request against Kong and the upstream
1. Observe that the `kong_latency` metric includes timed out and retried requests against the upstream

### Anything else?

N/A

**Comment by dcarley** [comment] 2022-08-12 08:39
Could we get some feedback on this?

Although the reproduction uses Datadog and the issue with tagged with `plugins/datadog`, it would affect other plugins like logging and tracing.

**Comment by StarlightIbuki** [comment] 2023-10-11 06:36
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:36 UTC
Labels: plugins/datadog

**Comment by FelixHarvey** [comment] 2024-08-21 06:38
Hey team - we are facing the same issue, would greatly appreciate if this issue could be revisited 🙏 

@dcarley did you end up finding a workaround or resolution?
