### ISSUE TITLE
BUG  kong in k8s not WORK !!!!!

### ISSUE THREAD

**Issue by lnsane** [Kong/kong#7711] opened 2021-08-14 07:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm install new version k8s

using flannel in k8s

I'm install kubectl apply -f https://bit.ly/k4k8s

namespace/kong created
serviceaccount/kong-serviceaccount created
service/kong-proxy created
service/kong-validation-webhook created
deployment.apps/ingress-kong created
unable to recognize "https://bit.ly/k4k8s": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "https://bit.ly/k4k8s": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "https://bit.ly/k4k8s": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "https://bit.ly/k4k8s": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "https://bit.ly/k4k8s": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "https://bit.ly/k4k8s": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1"
unable to recognize "https://bit.ly/k4k8s": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"

![1628907651(1)](https://user-images.githubusercontent.com/20310872/129431555-14481c2d-4e22-427d-92a8-35e95640f905.png)

![image](https://user-images.githubusercontent.com/20310872/129431658-dceab3b0-91c3-4f73-b73d-3bc37f3c9285.png)

### Steps To Reproduce

```markdown
sudo kubeadm init  --pod-network-cidr=100.10.0.0/8

kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

kubectl apply -f https://bit.ly/k4k8s
```

### Kubernetes version

```shell
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by lnsane** [comment] 2021-08-14 07:36
The apiextensions.k8s.io/v1beta1 API version of CustomResourceDefinition is no longer served as of v1.22.

The apiextensions.k8s.io/v1beta1 API version of CustomResourceDefinition is no longer served as of v1.22.

The apiextensions.k8s.io/v1beta1 API version of CustomResourceDefinition is no longer served as of v1.22.



!!!!!!

**Comment by mflendrich** [comment] 2021-08-14 13:40
@lnsane,

Thank you for your report.

Kong Ingress Controller 1.3.x is compatible with Kubernetes up to 1.21, as our [version compatibility matrix](https://docs.konghq.com/kubernetes-ingress-controller/1.3.x/references/version-compatibility/#kubernetes) says.

We have a recent 2.0.0-beta.1 release that is intended to support 1.22. If you want to run 2.0.0-beta.1 in your 1.22 cluster, please try this link: https://github.com/Kong/kubernetes-ingress-controller/blob/main/deploy/single-v2/all-in-one-dbless.yaml

If you face any problems with KIC 2.0.0-beta.1 on your 1.22 cluster, please report your concern here: https://github.com/Kong/kubernetes-ingress-controller/issues/1683

Thanks!

**Comment by mflendrich** [comment] 2021-08-14 13:41
Duplicate of https://github.com/Kong/kubernetes-ingress-controller/issues/801

**Closed by mflendrich** 2021-08-14 13:40 UTC
