### ISSUE TITLE
bug: function `encode_args_value`  is using the wrong URI-escape interface.

### ISSUE THREAD

**Issue by Miss-you** [Kong/kong#6378] opened 2020-09-22 06:00 UTC
### Summary
The encode_args_value function functions as escape-uri.  In openresty, if you want to encode uri or args, you should use the `ngx.escape_uri` interface instead of the `socket.url.escape` interface. According to the [ngxescape_uri](https://github.com/openresty/lua-nginx-module#ngxescape_uri)

https://github.com/Kong/kong/blob/254deec3cceef78654a1cba6eb32798c417e993a/kong/tools/utils.lua#L264

For example, args is `b-c`, using `socket.url.escape` results in `b%2dc` (not as expected), using `ngx.escape_uri` results in `b-c` (as expected).

On the other hand, if we look at the `socket.url.escape` code, we can see that it converts all the characters except for letters, numbers and underscores.
```
-----------------------------------------------------------------------------
-- Encodes a string into its escaped hexadecimal representation
-- Input
--   s: binary string to be encoded
-- Returns
--   escaped representation of string binary
-----------------------------------------------------------------------------
function _M.escape(s)
    return (string.gsub(s, "([^A-Za-z0-9_])", function(c)
        return string.format("%%%02x", string.byte(c))
    end))
end
```
### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by bungle** [comment] 2020-09-22 08:15
It seems like `oauth2` plugin is the only one that is using it.

**Comment by StarlightIbuki** [comment] 2023-10-11 06:14
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:14 UTC
Labels: task/code quality
