### ISSUE TITLE
bug: duplicated entries on nginx.conf

### ISSUE THREAD

**Issue by vasartori** [Kong/kong#5044] opened 2019-09-17 17:15 UTC
### Summary

When we set the environment variable nginx_http_charset, a message of duplicated entry is raised.
When this environment varibale is set, kongs set it on nginx.conf, but the charset is hardcoded on nginx_kong.conf.
With this approach, we are not abble to use a charset difrerent of UTF-8

The default value of nginx is off. 

This behaviour broke applications who uses eg iso-8859-1 charsets.

### Steps To Reproduce

1. export the environment variable NGINX_HTTP_CHARSET=off

### Additional Details & Logs

- 1.3.0

**Comment by StarlightIbuki** [comment] 2023-10-11 06:14
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:14 UTC
Labels: task/code quality
