### ISSUE TITLE
Grafana Dashboard Healthy Status wrong information

### ISSUE THREAD

**Issue by mhkarimi1383** [Kong/kong#9834] opened 2022-11-27 12:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.8

### Current Behavior

`* -1` in related query is making result reverse (I think)
I comparing results with the related table near `Healthy Status` panel

### Expected Behavior

values should match what with other dashboards

### Steps To Reproduce

```markdown
removed `* -1` and the panel is Okay
```

### Anything else?

We are running kong inside K8s with KIC

**Comment by mayocream** [comment] 2022-11-30 04:09
Hi @mhkarimi1383, thank you for reporting this.

Could you provide more details about this issue? Screenshots of the problematic grafana dashboard and the version of the grafana dashboard would be enough. Do you have a proposed fix for this issue?

**Comment by mhkarimi1383** [comment] 2022-11-30 04:11
Hello
Fixed by removing `*-1` in query
I'm using what is on the main branch in this repository
I will attach a photo as soon as possible

**Comment by StarlightIbuki** [comment] 2023-10-11 08:35
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 08:35 UTC
Labels: area/kubernetes, plugins/prometheus
