### ISSUE TITLE
Multiple authentications - No consumer check between plugins

### ISSUE THREAD

**Issue by mideuger** [Kong/kong#8541] opened 2022-03-15 10:05 UTC
I reopen this issue as the current behaviour is not properly documented and a bit misleading.

As the OP said, there is currently no check regarding the consumer if multiple authentications plugins are used with the `AND` method. The current [documentation](https://docs.konghq.com/gateway/2.8.x/configure/auth/) states that _the last plugin executed will be the one setting the credentials passed to the upstream service_ . It kind of suggests it, but does not necessarily imply that there is no consumer check. I was actually surprised when I went testing “just for the sake of it” only to find out that it didn’t.

We could add a `enforce_unique_consumer` flag to every authentication plugin configuration. If set, a plugin that successfully authenticates a consumer would check against a previously authenticated consumer, if it exists. This flag would not be set by default for retro-compatibility.

I think another thing to do would be to update the documentation to be a bit more explicit on that regard.

### Discussed in https://github.com/Kong/kong/discussions/7301

<div type='discussions-op-text'>

<sup>Originally posted by **Smoke-0** March 23, 2020</sup>
### Summary
In our project we are using two authentication plugins globally (Key Authentication and JWT) and ACL plugin on routes to whitelist authorized consumer-groups.

When providing mismatching (but valid) authentication credentials, the consumer is identified improperly, therefore assigned to improper consumer-group and in the end - allowed access to APIs he should not reach. 

**Example:**  
If I use apikey from one consumer and bearer token from different one I am allowed to access, and the consumer is assigned based on apikey as key-auth is processed later (with lower priority). Expected - as the authentication credentials don't match the same consumer no access should be granted.

### Steps To Reproduce

1. Configure JWT and Key Authorization plugins globally.
2. Configure two consumer-groups "allowed" and "restricted"
3. Create two consumers:
  A. Consumer with apikey_A and token claim token_A belonging to group "allowed"
  B. Consumer with apikey_R and token claim token_R belonging to group "restricted"
4. Create route with acl plugin having "allowed" group whitelisted.
5. Call the route providing apikey_A and token_R. 

### Additional Details & Logs

- Kong version 2.0.1 CE
</div>

**Comment by mideuger** [comment] 2022-03-15 10:13
I've submitted a pull request at #8542 that shows the described behaviour on a single plugin.

**Comment by StarlightIbuki** [comment] 2023-10-11 06:35
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:35 UTC
Labels: task/feature, plugins/hmac-auth
