### ISSUE TITLE
Will routes add a name attribute ?

### ISSUE THREAD

**Issue by gohonsen** [Kong/kong#3445] opened 2018-05-09 10:07 UTC
Use route ID, hosts, paths, or methods to distinguish a route is not friendly enough, if the route has a name attribute would be better

**Comment by bungle** [comment] 2018-05-09 11:52
Can you describe your use case for naming routes?

**Comment by bungle** [comment] 2018-05-09 12:15
Also check if this answers any of your concerns:
https://github.com/Kong/kong/issues/3444#issuecomment-387717375

**Comment by thibaultcha** [comment] 2018-05-09 15:55
A more detailed discussion on naming routes (in fact, this issue is a duplicate of that one): https://github.com/Kong/kong/issues/3425

**Closed** 2018-05-09 17:17 UTC
