### ISSUE TITLE
Kong with Socket.io (namespace)

### ISSUE THREAD

**Issue by CHOMNANP** [Kong/kong#5266] opened 2019-11-27 06:59 UTC
### Summary

Is there any tutorial on how to integrate use socket.io with namespace 

For example, 

We have 2 socket server.

192.168.10.10:8082/customer
192.168.10.10:8083/merchant

Then we want to have this in kong

socket.mydomain.com/customer => 192.168.10.10:8082/customer
socket.mydomain.com/merchant => 192.168.10.10:8083/merchant

I tried and does not get it working. Can anyone share me how to achieve this?

**Comment by marlonfan** [comment] 2019-11-28 06:41
What are the unusable representations? Perhaps you can provide some details?

**Comment by CHOMNANP** [comment] 2019-11-28 07:06
So let say the client is trying connect to "socket.mydomain.com/customer". The way that client making a request in socket client is "ws://socket.mydomain.com/socket.io/?station_id=2&EIO=3&transport=websocket". 

The client does not provide path "customer" as the namespace during the request. So that in the route configuration. We can only configure "socket.mydomain.com" to point to "192.168.10.10:8082". 

For "socket.mydomain.com/merchant", we cannot do any configuration because "socket.mydomain.com" has been used by the "customer" name space.

![image](https://user-images.githubusercontent.com/5925050/69784141-ac0ef380-11e7-11ea-983f-a7f4b1c8f0f2.png)
Please refer to the image above.

**Comment by marlonfan** [comment] 2019-11-28 07:25
maybe you can change socket.io default namespace?

**Comment by CHOMNANP** [comment] 2019-11-29 03:39
> maybe you can change socket.io default namespace?

@marlonfan, this is helpful. I try looking in socket.io document and have not find any option to do that. Can you share me how to do that?

Thanks,
Punleu

**Comment by marlonfan** [comment] 2019-11-29 05:28
yep, you just change this namespace on your project

```js
const socket = io('/your custom namespace');
```

**Comment by CHOMNANP** [comment] 2019-12-01 15:24
Hi @marlonfan, I tried changing this and it does not work. Maybe, I can share a project later.

**Comment by StarlightIbuki** [comment] 2023-10-11 06:19
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:19 UTC
Labels: core/proxy
