### ISSUE TITLE
question: Kong v2.x high memory usage per worker.

### ISSUE THREAD

**Issue by mayocream** [Kong/kong#6659] opened 2020-12-16 09:13 UTC
### Summary
Running Kong 2.1.4 on ubuntu 18.04, the memory usage is roughly 900Mb per worker.
I have near 650 routes, each route is assign with a service, upstream, and a target.
![image](https://user-images.githubusercontent.com/35420264/102327020-1693fc80-3fc0-11eb-8844-f351b825c96c.png)

### Steps To Reproduce
Running a Kong node on 8c 16g ubuntu 18.04, with below config:
```
db_update_frequency = 5
error_default_type = application/json
pg_host = ..
stream_listen = 0.0.0.0:7000 reuseport backlog=16384
pg_user = kong
prefix = /kong
database = postgres
real_ip_recursive = off
pg_password = ...
nginx_worker_processes = 4
proxy_listen = 0.0.0.0:80 reuseport backlog=16384, 0.0.0.0:443 http2 ssl reuseport backlog=16384
plugins = bundled
status_access_log = off
port_maps =
admin_listen = 0.0.0.0:8001 reuseport backlog=16384, 0.0.0.0:8444 http2 ssl reuseport backlog=16384
pg_port = ...
status_listen = 0.0.0.0:8100
real_ip_header =
anonymous_reports = off
pg_name = kong
admin_access_log = off
trusted_ips = 127.0.0.1/16
```

Run a script to register entities.
```bash
#!/bin/bash

ADMIN_URL=http://192.168.2.80:8001

for ((i=1; i<=1000; i++));
do
    curl -X "PUT" $ADMIN_URL/upstreams/test-$i;

    curl -X "POST" $ADMIN_URL/upstreams/test-$i/targets -d "target=192.168.2.90";

    curl -X "PUT" $ADMIN_URL/services/test-$i -d "host=upstream-$i";

    curl -X "PUT" $ADMIN_URL/services/test-$i/routes/test-$i -d "hosts[]=test-$i.com";

done
```

Test result:
1k routes:    500Mb mem usage per worker
6k routes:    2.2Gb   mem  usage per worker

Is this normal? and why high memory usage when entities increase.

**Comment by gitsrc** [comment] 2020-12-16 09:13
The same question

**Comment by mayocream** [comment] 2020-12-16 09:26
```
kong-test_1  | 2020/12/16 07:19:01 [warn] 499#0: *9103226 [kong] handler.lua:32 memory_stats: {"workers_lua_vms":[{"http_allocated_gc":"92.2 MiB","pid":498},{"http_allocated_gc":"71.3 MiB","pid":499}],"lua_shared_dicts":{"kong_locks":{"allocated_slabs":"0.1 MiB","capacity":"8.0 MiB"},"tracing_buffer":{"allocated_slabs":"0.8 MiB","capacity":"128.0 MiB"},"kong":{"allocated_slabs":"0.0 MiB","capacity":"5.0 MiB"},"kong_process_events":{"allocated_slabs":"3.0 MiB","capacity":"5.0 MiB"},"kong_healthchecks":{"allocated_slabs":"3.0 MiB","capacity":"5.0 MiB"},"kong_cluster_events":{"allocated_slabs":"0.0 MiB","capacity":"5.0 MiB"},"kong_db_cache":{"allocated_slabs":"0.8 MiB","capacity":"128.0 MiB"},"kong_core_db_cache_miss":{"allocated_slabs":"0.1 MiB","capacity":"12.0 MiB"},"kong_core_db_cache":{"allocated_slabs":"13.1 MiB","capacity":"128.0 MiB"},"prometheus_metrics":{"allocated_slabs":"0.0 MiB","capacity":"5.0 MiB"},"kong_db_cache_miss":{"allocated_slabs":"0.1 MiB","capacity":"12.0 MiB"},"kong_rate_limiting_counters":{"allocated_slabs":"0.1 MiB","capacity":"12.0 MiB"}}}, context: ngx.timer
```

I write a plugin to print `kong.node.get_memory_stats("m", 1)`, it shows Kong does not have full use of Nginx shared memory.
We know Kong sotres routes, services in L1 cache, is there a option to limit the max memory size usage?

**Comment by mayocream** [comment] 2020-12-16 11:15
I noticed that without creating upstream, it way different memory usage from the last test.

```bash
#!/bin/bash

ADMIN_URL=http://192.168.2.80:8001

for ((i=1; i<=1000; i++));
do

    curl -X "PUT" $ADMIN_URL/services/test-$i -d "host=192.168.2.80";

    curl -X "PUT" $ADMIN_URL/services/test-$i/routes/test-$i -d "hosts[]=test-$i.com";

done
```

Just create service with a route, repeat 1000 times, and memory usage per worker is 126MB.
![image](https://user-images.githubusercontent.com/35420264/102341406-c1151b00-3fd2-11eb-94dd-050a7350b9f0.png)

Does a upstream with a target cost much more memory usage?

**Comment by bungle** [comment] 2020-12-18 09:08
I have reduced the scope of this issue to these lines:
https://github.com/Kong/lua-resty-dns-client/blob/master/src/resty/dns/balancer/ring.lua#L437-L495

If you remove them, the memory usage will drop a lot.

**Comment by bungle** [comment] 2020-12-18 09:14
If I change this line:
https://github.com/Kong/lua-resty-dns-client/blob/master/src/resty/dns/balancer/ring.lua#L447

```
self.wheelSize = opts.wheelSize or 1000 -- number of entries (indices) in the wheel
```
to
```
self.wheelSize = 1
```

the memory usage drops.

**Comment by bungle** [comment] 2020-12-18 11:50
I think the problem is in `random_list` function.

**Comment by bungle** [comment] 2020-12-18 11:57
I am starting to believe it is a leak in `lrandom` that this library has dependency to. We should remove that dependency as there is no need for that.

**Comment by bungle** [comment] 2020-12-18 12:05
Yes, I can confirm:

1. remove this: https://github.com/Kong/lua-resty-dns-client/blob/master/src/resty/dns/balancer/ring.lua#L38
2. remove this: https://github.com/Kong/lua-resty-dns-client/blob/master/src/resty/dns/balancer/ring.lua#L378
3. change this: https://github.com/Kong/lua-resty-dns-client/blob/master/src/resty/dns/balancer/ring.lua#L382
```lua
local n = math_floor(randomizer() * size) + 1
```
to
```lua
local n = math_floor(math.random() * size) + 1
```

Why in earth there was this `lrandom` ever?

**Comment by bungle** [comment] 2020-12-18 13:00
Actually it was not tha, :-(, but we are getting close. This surely needs to be fixed.

**Comment by gitsrc** [comment] 2020-12-18 13:42
> Actually it was not that, :-(, but we are getting close. This surely needs to be fixed.

thanks

**Comment by dndx** [comment] 2020-12-18 17:21
Hello @mayocream,

I spent some time to look into the example you gave, indeed the memory usage is high. After some collaboration with @bungle I was able to understand what happened here.

Basically, when a new `Upstream` object is created, the default `algorithm` is `round-robin`, which uses the `ring` balancer from lua-resty-dns-client as @bungle pointed out above.

When creating a balancer instance, one important parameter is the `Upstream.slots` config, which corresponds to the `wheelSize` option of the ring balancer object. If the `slots` is set to a very large value, then the ring balancer code will allocate two giant Lua tables of `slots` in size and that causes the memory usage to go up quickly.

In your example, each `Upstream` only have one `Target` in it, so the default `slots` of `10000` is way too large for just a single `Target` and the memory will grow very quickly.

One way to mitigate it, if you know only small number of `Targets` will be added for each `Upstream`, then changing the request to:

```
curl -X "PUT" $ADMIN_URL/upstreams/test-$i -d "slots=100";
```

will reduce the slots allocated for the balancer, and will make the memory consumption significantly smaller.

The reason why `slots` is a large number by default is because we do not know exactly how much `Targets` people will create for them ahead of time, so it is safer to just use a larger default. We may revisit that in the future too.

**Comment by mayocream** [comment] 2020-12-19 14:00
Thanks to @dndx , now we know that upstream `slots` option is the key to solve the question.
I also found description in `balancer/ring`:
> The wheelSize cannot be altered, only a new wheel can be created, but then all consistency would be lost. On a similar note; making it too big, will have a performance impact when the wheel is modified as too many indices will have to be moved between targets. A value of 50 to 200 indices per entry seems about right.

I use ingress controller, and it seems to be there's no configuration to set default value of upstream slots. So it will create 1000 slots, and case high memory usage.

**Comment by rainest** [comment] 2021-01-12 15:04
@mayocream [KongIngress resources](https://docs.konghq.com/kubernetes-ingress-controller/1.1.x/references/custom-resources/#kongingress) attached to a Service will allow you to set the upstream slots.

**Comment by dndx** [comment] 2021-01-13 18:12
Closing this since we understood and found a mitigation for the memory usage, but we are also evaluating internally on ways to optimize the default.

**Closed by dndx** 2021-01-13 18:12 UTC
Labels: core/performance, task/bug
