### ISSUE TITLE
Ldap with JWT with no consumers added

### ISSUE THREAD

**Issue by hanymorcos** [Kong/kong#6809] opened 2021-02-06 20:26 UTC
### Summary

Hello, 

If our system has thousands of users, we wish not to add a consumer for every user, but to use the current ldap system for user to authenticate. Upon authentication we request that Kong provide JWT token, that user can use in the system and also for different microservices to know the user username to filter proper authorization using Spring Framework. If there is currently the capability, can you please provide a simple kong.yml? 

thanks,

H

**Comment by StarlightIbuki** [comment] 2023-10-11 06:20
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:20 UTC
Labels: plugins/jwt
