### ISSUE TITLE
DB-less mode allows resources with duplicate unique fields

### ISSUE THREAD

**Issue by rainest** [Kong/kong#6732] opened 2021-01-13 22:00 UTC
### Summary
Loading a declarative configuration that contains resources with identical unique field values but distinct IDs creates both resources. This affects at least consumers and services, and presumably affects all other entities.

### Steps To Reproduce

1. Start Kong with `KONG_DATABASE=off` set.
1. Load [dup_consumer_id.yaml.txt](https://github.com/Kong/kong/files/5811231/dup_consumer_id.yaml.txt)
2. Check the `GET /consumers` endpoint. Both resources exist, e.g. 
[example_output.txt](https://github.com/Kong/kong/files/5811211/example_output.txt)

### Additional Details & Logs

Tested on Kong 2.3.0.

Kong also accepts similar configuration without IDs, e.g. [dup_consumer_id.yaml.txt](https://github.com/Kong/kong/files/5811238/dup_consumer_id.yaml.txt). Excluding IDs overwrites results in a single resource (the last resource defined in the configuration) only. However, if other resources are linked (e.g. service->plugin relationships), the result is two distinct resources, e.g. from 
[dup_consumer_noid_plugin.yaml.txt](https://github.com/Kong/kong/files/5811254/dup_consumer_noid_plugin.yaml.txt).

In practice I don't think this is likely to cause serious issues--attempting to request resources from the admin API by unique field no longer really works (it only returns one entity), but routing logic presumably still entirely relies on IDs. The overwrites _may_ be a concern, but I'm unsure if they'd matter because the override doesn't occur when entities are linked to others, and offhand I'm not aware of entities that do much of anything when not linked.

One practical implication is that the ingress controller can easily overwrite entities unintentionally as a result of user error, but the same caveat about linking applies (I only encountered this because I was intentionally trying to cause a conflict with unlinked consumers).

Throwing this out there in case anyone can think of more severe implications. If not, and we don't want to bother changing this behavior, it should be fine to simply document this.

**Comment by StarlightIbuki** [comment] 2023-10-11 06:20
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:20 UTC
Labels: task/bug, core/db
