### ISSUE TITLE
[2.1.0 GA] Location Header Messed UP! 

### ISSUE THREAD

**Issue by carnei-ro** [Kong/kong#6141] opened 2020-07-21 16:44 UTC
### Summary

From Kong 2.1.0, the Location Header from an 301/302 response is messed up.

### Steps To Reproduce

It needs more investigation, but, I have an Apache Airflow that proxying with Kong 2.0.5 and GET `/home`, I got redirected to the right place, but Kong 2.1.0 it does not happen as expected.

I tried to reproduce locally, but without success. But I created the Repo https://github.com/carnei-ro/kong-bug-location-header trying to explain.

**Comment by gszr** [comment] 2020-07-21 17:03
Thanks for the report, @carnei-ro. As this is a duplicate of https://github.com/Kong/kong/issues/6132, I'm closing it, let's continue the discussion over there!

**Closed by gszr** 2020-07-21 17:03 UTC
