### ISSUE TITLE
mlcache crash: attempt to index field with nil value

### ISSUE THREAD

**Issue by leosunmo** [Kong/kong#4812] opened 2019-07-18 23:01 UTC
### Summary
First of all, I'm running the Kong Kubernetes Ingress Controller v 0.4.0. All nodes are running in DB-less mode.

Overnight I've suddenly started seeing a lot of crashes on one of 3 Kong nodes in my Kubernetes cluster. Nothing in the infrastructure has changed and all three Kong instances have been up for at least a week without issue. I don't know if a restart will fix it as I didn't want to lose the logs and have therefore not restarted anything yet (they're still passing Kubernetes healthchecks). 
Stacktrace:
```
100.96.31.0 - - [18/Jul/2019:22:47:56 +0000] "GET /status HTTP/1.1" 200 223 "-" "ELB-HealthChecker/2.0" <----- passes healthchecks fine

2019/07/18 22:47:59 [error] 309#0: *12711834 lua coroutine: runtime error: /usr/local/share/lua/5.1/resty/mlcache.lua:666: attempt to index field 'lru' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/share/lua/5.1/resty/mlcache.lua: in function 'get'
	/usr/local/share/lua/5.1/kong/cache.lua:126: in function 'get'
	/usr/local/share/lua/5.1/kong/db/declarative/init.lua:223: in function 'post_upstream_crud_delete_events'
	/usr/local/share/lua/5.1/kong/db/declarative/init.lua:428: in function 'load_into_cache_with_events'
	/usr/local/share/lua/5.1/kong/api/routes/config.lua:42: in function 'fn'
	/usr/local/share/lua/5.1/kong/api/init.lua:45: in function </usr/local/share/lua/5.1/kong/api/init.lua:28>
coroutine 1:
	[C]: in function 'resume'
	/usr/local/share/lua/5.1/lapis/application.lua:393: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:130: in function 'resolve'
	/usr/local/share/lua/5.1/lapis/application.lua:161: in function </usr/local/share/lua/5.1/lapis/application.lua:159>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/lapis/application.lua:159: in function 'dispatch'
	/usr/local/share/lua/5.1/lapis/nginx.lua:215: in function 'serve_admin_api'
	content_by_lua(nginx-kong.conf:155):2: in function <content_by_lua(nginx-kong.conf:155):1>, client: 127.0.0.1, server: kong_admin, request: "POST /config HTTP/1.1", host: "localhost:8444"
2019/07/18 22:47:59 [error] 309#0: *12711834 [lua] init.lua:161: handle_error(): /usr/local/share/lua/5.1/lapis/application.lua:397: /usr/local/share/lua/5.1/resty/mlcache.lua:666: attempt to index field 'lru' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/resty/mlcache.lua: in function 'get'
	/usr/local/share/lua/5.1/kong/cache.lua:126: in function 'get'
	/usr/local/share/lua/5.1/kong/db/declarative/init.lua:223: in function 'post_upstream_crud_delete_events'
	/usr/local/share/lua/5.1/kong/db/declarative/init.lua:428: in function 'load_into_cache_with_events'
	/usr/local/share/lua/5.1/kong/api/routes/config.lua:42: in function 'fn'
	/usr/local/share/lua/5.1/kong/api/init.lua:45: in function </usr/local/share/lua/5.1/kong/api/init.lua:28>

stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/lapis/application.lua:397: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:130: in function 'resolve'
	/usr/local/share/lua/5.1/lapis/application.lua:161: in function </usr/local/share/lua/5.1/lapis/application.lua:159>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/lapis/application.lua:159: in function 'dispatch'
	/usr/local/share/lua/5.1/lapis/nginx.lua:215: in function 'serve_admin_api'
	content_by_lua(nginx-kong.conf:155):2: in function <content_by_lua(nginx-kong.conf:155):1>, client: 127.0.0.1, server: kong_admin, request: "POST /config HTTP/1.1", host: "localhost:8444"
127.0.0.1 - - [18/Jul/2019:22:47:59 +0000] "POST /config HTTP/1.1" 500 42 "-" "Go-http-client/1.1"    <------ always a /config POST around the failures.
172.21.53.221 - - [18/Jul/2019:22:47:59 +0000] "GET /status HTTP/1.1" 200 223 "-" "kube-probe/1.10"
```

The way this manifests itself is intermittent 500s for end-users, since only 1 of 3 nodes are in this state. 

I do see long lists of errors on the other nodes occasionally, which look like they might be caused by the failing node, but the `/config` call does succeed in the end. Sample:

```
2019/07/18 22:45:44 [error] 424#0: *12677982 [lua] events.lua:345: post(): worker-events: dropping event; waiting for event data timed out, id: 15565003, client: 127.0.0.1, server: kong_admin, request: "POST /config HTTP/1.1", host: "localhost:8444"
2019/07/18 22:45:44 [error] 424#0: *12677982 [lua] events.lua:345: post(): worker-events: dropping event; waiting for event data timed out, id: 15565005, client: 127.0.0.1, server: kong_admin, request: "POST /config HTTP/1.1", host: "localhost:8444"
2019/07/18 22:45:44 [error] 424#0: *12677982 [lua] events.lua:345: post(): worker-events: dropping event; waiting for event data timed out, id: 15565007, client: 127.0.0.1, server: kong_admin, request: "POST /config HTTP/1.1", host: "localhost:8444"
2019/07/18 22:45:44 [error] 424#0: *12677982 [lua] events.lua:345: post(): worker-events: dropping event; waiting for event data timed out, id: 15565009, client: 127.0.0.1, server: kong_admin, request: "POST /config HTTP/1.1", host: "localhost:8444"
2019/07/18 22:45:44 [error] 424#0: *12677982 [lua] events.lua:345: post(): worker-events: dropping event; waiting for event data timed out, id: 15565011, client: 127.0.0.1, server: kong_admin, request: "POST /config HTTP/1.1", host: "localhost:8444"
2019/07/18 22:45:44 [error] 424#0: *12677982 [lua] events.lua:345: post(): worker-events: dropping event; waiting for event data timed out, id: 15565013, client: 127.0.0.1, server: kong_admin, request: "POST /config HTTP/1.1", host: "localhost:8444"
2019/07/18 22:45:44 [error] 424#0: *12677982 [lua] events.lua:345: post(): worker-events: dropping event; waiting for event data timed out, id: 15565015, client: 127.0.0.1, server: kong_admin, request: "POST /config HTTP/1.1", host: "localhost:8444"
2019/07/18 22:45:44 [error] 424#0: *12677982 [lua] events.lua:345: post(): worker-events: dropping event; waiting for event data timed out, id: 15565017, client: 127.0.0.1, server: kong_admin, request: "POST /config HTTP/1.1", host: "localhost:8444"
127.0.0.1 - - [18/Jul/2019:22:45:44 +0000] "POST /config HTTP/1.1" 201 43517 "-" "Go-http-client/1.1"
```

### Steps To Reproduce

Unsure how to reproduce.

### Additional Details & Logs

- Kong version (`$ kong version`)
1.1.2
- Kong debug-level startup logs (`$ kong start --vv`)

<details>
<summary>Kong start config</summary>

```
# kong start -vv
2019/07/18 22:52:58 [verbose] Kong: 1.1.2
2019/07/18 22:52:58 [debug] ngx_lua: 10013
2019/07/18 22:52:58 [debug] nginx: 1013006
2019/07/18 22:52:58 [debug] Lua: LuaJIT 2.1.0-beta3
2019/07/18 22:52:58 [verbose] no config file found at /etc/kong/kong.conf
2019/07/18 22:52:58 [verbose] no config file found at /etc/kong.conf
2019/07/18 22:52:58 [verbose] no config file, skip loading
2019/07/18 22:52:58 [debug] reading environment variables
2019/07/18 22:52:58 [debug] KONG_ADMIN_LISTEN ENV found with "0.0.0.0:8444"
2019/07/18 22:52:58 [debug] KONG_PROXY_ACCESS_LOG ENV found with "/dev/stdout"
2019/07/18 22:52:58 [debug] KONG_PROXY_LISTEN ENV found with "0.0.0.0:8000"
2019/07/18 22:52:58 [debug] KONG_DATABASE ENV found with "off"
2019/07/18 22:52:58 [debug] KONG_ADMIN_ACCESS_LOG ENV found with "/dev/stdout"
2019/07/18 22:52:58 [debug] KONG_ADMIN_ERROR_LOG ENV found with "/dev/stderr"
2019/07/18 22:52:58 [debug] KONG_PROXY_ERROR_LOG ENV found with "/dev/stderr"
2019/07/18 22:52:58 [debug] KONG_NGINX_DAEMON ENV found with "off"
2019/07/18 22:52:58 [debug] admin_access_log = "/dev/stdout"
2019/07/18 22:52:58 [debug] admin_error_log = "/dev/stderr"
2019/07/18 22:52:58 [debug] admin_listen = {"0.0.0.0:8444"}
2019/07/18 22:52:58 [debug] anonymous_reports = true
2019/07/18 22:52:58 [debug] cassandra_consistency = "ONE"
2019/07/18 22:52:58 [debug] cassandra_contact_points = {"127.0.0.1"}
2019/07/18 22:52:58 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2019/07/18 22:52:58 [debug] cassandra_keyspace = "kong"
2019/07/18 22:52:58 [debug] cassandra_lb_policy = "RequestRoundRobin"
2019/07/18 22:52:58 [debug] cassandra_port = 9042
2019/07/18 22:52:58 [debug] cassandra_repl_factor = 1
2019/07/18 22:52:58 [debug] cassandra_repl_strategy = "SimpleStrategy"
2019/07/18 22:52:58 [debug] cassandra_schema_consensus_timeout = 10000
2019/07/18 22:52:58 [debug] cassandra_ssl = false
2019/07/18 22:52:58 [debug] cassandra_ssl_verify = false
2019/07/18 22:52:58 [debug] cassandra_timeout = 5000
2019/07/18 22:52:58 [debug] cassandra_username = "kong"
2019/07/18 22:52:58 [debug] client_body_buffer_size = "8k"
2019/07/18 22:52:58 [debug] client_max_body_size = "0"
2019/07/18 22:52:58 [debug] client_ssl = false
2019/07/18 22:52:58 [debug] database = "off"
2019/07/18 22:52:58 [debug] db_cache_ttl = 0
2019/07/18 22:52:58 [debug] db_resurrect_ttl = 30
2019/07/18 22:52:58 [debug] db_update_frequency = 5
2019/07/18 22:52:58 [debug] db_update_propagation = 0
2019/07/18 22:52:58 [debug] dns_error_ttl = 1
2019/07/18 22:52:58 [debug] dns_hostsfile = "/etc/hosts"
2019/07/18 22:52:58 [debug] dns_no_sync = false
2019/07/18 22:52:58 [debug] dns_not_found_ttl = 30
2019/07/18 22:52:58 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2019/07/18 22:52:58 [debug] dns_resolver = {}
2019/07/18 22:52:58 [debug] dns_stale_ttl = 4
2019/07/18 22:52:58 [debug] error_default_type = "text/plain"
2019/07/18 22:52:58 [debug] headers = {"server_tokens","latency_tokens"}
2019/07/18 22:52:58 [debug] log_level = "notice"
2019/07/18 22:52:58 [debug] lua_package_cpath = ""
2019/07/18 22:52:58 [debug] lua_package_path = "./?.lua;./?/init.lua;"
2019/07/18 22:52:58 [debug] lua_socket_pool_size = 30
2019/07/18 22:52:58 [debug] lua_ssl_verify_depth = 1
2019/07/18 22:52:58 [debug] mem_cache_size = "128m"
2019/07/18 22:52:58 [debug] nginx_admin_directives = {}
2019/07/18 22:52:58 [debug] nginx_daemon = "off"
2019/07/18 22:52:58 [debug] nginx_http_directives = {}
2019/07/18 22:52:58 [debug] nginx_optimizations = true
2019/07/18 22:52:58 [debug] nginx_proxy_directives = {}
2019/07/18 22:52:58 [debug] nginx_sproxy_directives = {}
2019/07/18 22:52:58 [debug] nginx_stream_directives = {}
2019/07/18 22:52:58 [debug] nginx_user = "nobody nobody"
2019/07/18 22:52:58 [debug] nginx_worker_processes = "auto"
2019/07/18 22:52:58 [debug] origins = {}
2019/07/18 22:52:58 [debug] pg_database = "kong"
2019/07/18 22:52:58 [debug] pg_host = "127.0.0.1"
2019/07/18 22:52:58 [debug] pg_port = 5432
2019/07/18 22:52:58 [debug] pg_ssl = false
2019/07/18 22:52:58 [debug] pg_ssl_verify = false
2019/07/18 22:52:58 [debug] pg_timeout = 5000
2019/07/18 22:52:58 [debug] pg_user = "kong"
2019/07/18 22:52:58 [debug] plugins = {"bundled"}
2019/07/18 22:52:58 [debug] prefix = "/usr/local/kong/"
2019/07/18 22:52:58 [debug] proxy_access_log = "/dev/stdout"
2019/07/18 22:52:58 [debug] proxy_error_log = "/dev/stderr"
2019/07/18 22:52:58 [debug] proxy_listen = {"0.0.0.0:8000"}
2019/07/18 22:52:58 [debug] real_ip_header = "X-Real-IP"
2019/07/18 22:52:58 [debug] real_ip_recursive = "off"
2019/07/18 22:52:58 [debug] ssl_cipher_suite = "modern"
2019/07/18 22:52:58 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2019/07/18 22:52:58 [debug] stream_listen = {"off"}
2019/07/18 22:52:58 [debug] trusted_ips = {}
2019/07/18 22:52:58 [debug] upstream_keepalive = 60
2019/07/18 22:52:58 [verbose] prefix in use: /usr/local/kong
2019/07/18 22:52:58 [debug] sending signal to pid at: /usr/local/kong/pids/nginx.pid
2019/07/18 22:52:58 [debug] kill -0 `cat /usr/local/kong/pids/nginx.pid` >/dev/null 2>&1
Error:
/usr/local/share/lua/5.1/kong/cmd/start.lua:23: Kong is already running in /usr/local/kong <--- expected obviously, ran it in a deployed container.
```

</details>

- Kong configuration (the output of a GET request to Kong's Admin port
<details>
<summary>Kong admin port config</summary>

```
{
    "plugins": {
        "enabled_in_cluster": [
            "cors"
        ],
        "available_on_server": {
            "response-transformer": true,
            "oauth2": true,
            "acl": true,
            "ip-restriction": true,
            "correlation-id": true,
            "statsd": true,
            "jwt": true,
            "cors": true,
            "request-transformer": true,
            "basic-auth": true,
            "key-auth": true,
            "rate-limiting": true,
            "file-log": true,
            "http-log": true,
            "prometheus": true,
            "hmac-auth": true,
            "ldap-auth": true,
            "datadog": true,
            "tcp-log": true,
            "zipkin": true,
            "post-function": true,
            "syslog": true,
            "bot-detection": true,
            "kubernetes-sidecar-injector": true,
            "request-size-limiting": true,
            "azure-functions": true,
            "udp-log": true,
            "response-ratelimiting": true,
            "aws-lambda": true,
            "pre-function": true,
            "loggly": true,
            "request-termination": true
        }
    },
    "tagline": "Welcome to kong",
    "configuration": {
        "plugins": [
            "bundled"
        ],
        "admin_ssl_enabled": false,
        "lua_ssl_verify_depth": 1,
        "trusted_ips": {},
        "prefix": "/usr/local/kong",
        "loaded_plugins": {
            "response-transformer": true,
            "request-termination": true,
            "loggly": true,
            "pre-function": true,
            "ip-restriction": true,
            "statsd": true,
            "jwt": true,
            "cors": true,
            "aws-lambda": true,
            "basic-auth": true,
            "key-auth": true,
            "rate-limiting": true,
            "response-ratelimiting": true,
            "http-log": true,
            "ldap-auth": true,
            "hmac-auth": true,
            "syslog": true,
            "datadog": true,
            "tcp-log": true,
            "zipkin": true,
            "post-function": true,
            "request-size-limiting": true,
            "acl": true,
            "kubernetes-sidecar-injector": true,
            "bot-detection": true,
            "azure-functions": true,
            "udp-log": true,
            "file-log": true,
            "request-transformer": true,
            "prometheus": true,
            "correlation-id": true,
            "oauth2": true
        },
        "cassandra_username": "kong",
        "dns_resolver": {},
        "pg_user": "kong",
        "mem_cache_size": "128m",
        "ssl_ciphers": "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256",
        "nginx_admin_directives": {},
        "nginx_http_directives": [
            {
                "value": "prometheus_metrics 5m",
                "name": "lua_shared_dict"
            }
        ],
        "pg_host": "127.0.0.1",
        "nginx_acc_logs": "/usr/local/kong/logs/access.log",
        "proxy_listen": [
            "0.0.0.0:8000"
        ],
        "client_ssl_cert_default": "/usr/local/kong/ssl/kong-default.crt",
        "ssl_cert_key_default": "/usr/local/kong/ssl/kong-default.key",
        "db_update_frequency": 5,
        "db_update_propagation": 0,
        "stream_listen": [
            "off"
        ],
        "nginx_err_logs": "/usr/local/kong/logs/error.log",
        "cassandra_port": 9042,
        "dns_order": [
            "LAST",
            "SRV",
            "A",
            "CNAME"
        ],
        "dns_error_ttl": 1,
        "headers": [
            "server_tokens",
            "latency_tokens"
        ],
        "cassandra_lb_policy": "RequestRoundRobin",
        "nginx_optimizations": true,
        "origins": {},
        "database": "off",
        "pg_database": "kong",
        "nginx_worker_processes": "auto",
        "lua_package_cpath": "",
        "admin_acc_logs": "/usr/local/kong/logs/admin_access.log",
        "lua_package_path": "./?.lua;./?/init.lua;",
        "nginx_pid": "/usr/local/kong/pids/nginx.pid",
        "upstream_keepalive": 60,
        "proxy_access_log": "/dev/stdout",
        "admin_access_log": "/dev/stdout",
        "client_ssl": false,
        "nginx_conf": "/usr/local/kong/nginx.conf",
        "proxy_listeners": [
            {
                "transparent": false,
                "ssl": false,
                "ip": "0.0.0.0",
                "proxy_protocol": false,
                "port": 8000,
                "http2": false,
                "listener": "0.0.0.0:8000"
            }
        ],
        "proxy_ssl_enabled": false,
        "cassandra_ssl": false,
        "cassandra_schema_consensus_timeout": 10000,
        "enabled_headers": {
            "latency_tokens": true,
            "X-Kong-Proxy-Latency": true,
            "Via": true,
            "server_tokens": true,
            "Server": true,
            "X-Kong-Upstream-Latency": true,
            "X-Kong-Upstream-Status": false
        },
        "dns_no_sync": false,
        "ssl_cert_csr_default": "/usr/local/kong/ssl/kong-default.csr",
        "db_resurrect_ttl": 30,
        "lua_socket_pool_size": 30,
        "cassandra_consistency": "ONE",
        "db_cache_ttl": 0,
        "admin_error_log": "/dev/stderr",
        "pg_ssl_verify": false,
        "dns_not_found_ttl": 30,
        "pg_ssl": false,
        "cassandra_repl_factor": 1,
        "nginx_kong_conf": "/usr/local/kong/nginx-kong.conf",
        "cassandra_repl_strategy": "SimpleStrategy",
        "cassandra_contact_points": [
            "127.0.0.1"
        ],
        "pg_timeout": 5000,
        "nginx_stream_directives": {},
        "nginx_sproxy_directives": {},
        "kong_env": "/usr/local/kong/.kong_env",
        "real_ip_header": "X-Real-IP",
        "dns_hostsfile": "/etc/hosts",
        "admin_listeners": [
            {
                "transparent": false,
                "ssl": false,
                "ip": "0.0.0.0",
                "proxy_protocol": false,
                "port": 8444,
                "http2": false,
                "listener": "0.0.0.0:8444"
            }
        ],
        "ssl_cipher_suite": "modern",
        "nginx_proxy_directives": {},
        "cassandra_timeout": 5000,
        "admin_ssl_cert_key_default": "/usr/local/kong/ssl/admin-kong-default.key",
        "cassandra_ssl_verify": false,
        "dns_stale_ttl": 4,
        "error_default_type": "text/plain",
        "real_ip_recursive": "off",
        "proxy_error_log": "/dev/stderr",
        "client_ssl_cert_key_default": "/usr/local/kong/ssl/kong-default.key",
        "nginx_daemon": "off",
        "anonymous_reports": true,
        "log_level": "notice",
        "nginx_kong_stream_conf": "/usr/local/kong/nginx-kong-stream.conf",
        "pg_port": 5432,
        "admin_ssl_cert_default": "/usr/local/kong/ssl/admin-kong-default.crt",
        "client_body_buffer_size": "8k",
        "ssl_preread_enabled": true,
        "stream_listeners": {},
        "client_max_body_size": "0",
        "cassandra_keyspace": "kong",
        "ssl_cert_default": "/usr/local/kong/ssl/kong-default.crt",
        "cassandra_data_centers": [
            "dc1:2",
            "dc2:3"
        ],
        "admin_listen": [
            "0.0.0.0:8444"
        ]
    },
    "version": "1.1.2",
    "node_id": "fe377c66-4ec0-4f62-a9a5-c3eeff097f10",
    "lua_version": "LuaJIT 2.1.0-beta3",
    "prng_seeds": {
        < long list of PIDs >
    },
    "timers": {
        "pending": 3,
        "running": 0
    },
    "hostname": "private-ingress-kong-74d886998-c8lmj"
}
```

</details>

- Operating system
Official Kubernetes Ingress Controller 0.4.0 container, 
`kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.4.0`

**Comment by hbagdi** [comment] 2019-07-22 18:32
I might be wrong here, but I think this is related to https://github.com/Kong/lua-resty-worker-events/issues/19, which will be resolved in https://github.com/Kong/kong/pull/4810. This will be included in Kong 1.3.

ping @Tieske for additional insight into this issue.

**Comment by thibaultcha** [comment] 2019-07-22 18:41
I was looking at this issue at the same moment (and been thinking about it since Friday).

@hbagdi What makes you say that? This seems unrelated to me. mlcache 2.3.0 (used in Kong 1.1.2) was not updated to use `lru:flush_all()` yet (mlcache 2.4.0 in later Kong version uses it). It used to rebuild the LRU like so on `:purge()`: https://github.com/thibaultcha/lua-resty-mlcache/blob/2.3.0/lib/resty/mlcache.lua#L117-L141. This caused a memory issue which I recalled was brought up recently from KIC.

That being said, even without `lru:flush_all()`, I don't see why mlcache's `lru` attribute would ever be `nil` at this point (unless manipulated by third-party code I am not aware of), given the `rebuild_lru()` operation should not yield, and the `lru_size` should always be valid (`resty_lru.new()` should not fail).

**Comment by Tieske** [comment] 2019-08-25 07:37
Just looking at this;

* the stack trace is from lapis so the error originates from the management API
* why do users get 500s in this case?
* worker events doesn't use ttl's in its cache, it relies on lru, assuming that the oldest events being evicted have already been dealt with. The expected error if this assumption goes bad, is indeed the "waiting for event data timed out" message

I don't know top of mind how often worker events gets triggered (the interval) to handle the events, but if the number of events and the associated data within that short period is more than the worker events cache size, then eviction will happen before all workers have dealt with the data.

And if this were to happen, than I'd assume using Kic would be one of the first places this would occur. Since it can post a lot of config data in a short period of time.

@leosunmo is the problem reproducible? How big is your overall configuration? How many entities do you store?

**Comment by Tieske** [comment] 2019-08-25 07:41
The above does of course not explain the relation with mlcache.

**Comment by kikito** [comment] 2020-11-24 22:24
@leosunmo I'm closing this due to lack of activity, please reopen if necessary.

**Closed by kikito** 2020-11-24 22:24 UTC
Labels: task/needs-investigation
