### ISSUE TITLE
kong migrations up fails when /etc/resolv.conf file is empty

### ISSUE THREAD

**Issue by sotroyalta** [Kong/kong#3104] opened 2017-12-18 07:32 UTC
### Summary
Let's just say that my use-case involves using kong on a RHEL6 host with empty /etc/resolv.conf file (I use only /etc/hosts file and add hosts manually there). I use Cassandra as data store.  For settings that would require host name (like cassandra_contact_points), I just use bare IPv4 addresses. When I run 'kong migrations up' command, it fails with an error:
Error: 
/usr/local/share/lua/5.1/resty/dns/client.lua:450: Invalid configuration, no valid nameservers found

This is the part of my kong.conf file (# DNS RESOLVER section). Indeed I did not set the dns_resolver.
#dns_resolver =
#dns_hostsfile = /etc/hosts
#dns_order = LAST,SRV,A,CNAME
#dns_stale_ttl = 4
#dns_not_found_ttl = 30
#dns_error_ttl = 1
#dns_no_sync = off

Why is there the checking for empty resolv.conf?

### Steps To Reproduce
1. Have an empty /etc/resolv.conf file
2. Install kong
3. Run command 'kong migrations up'

### Additional Details & Logs
- Kong version: 0.11.1
- Kong debug-level startup logs (`$ kong start --vv`)
[root@euca-10-254-80-8 ~]# kong start --vv
2017/12/18 09:31:27 [verbose] Kong: 0.11.1
2017/12/18 09:31:27 [debug] ngx_lua: 10008
2017/12/18 09:31:27 [debug] nginx: 1011002
2017/12/18 09:31:27 [debug] Lua: LuaJIT 2.1.0-beta2
2017/12/18 09:31:27 [verbose] reading config file at /etc/kong/kong.conf
2017/12/18 09:31:27 [debug] admin_access_log = "/var/log/kong/admin_access.log"
2017/12/18 09:31:27 [debug] admin_error_log = "/var/log/kong/error.log"
2017/12/18 09:31:27 [debug] admin_http2 = false
2017/12/18 09:31:27 [debug] admin_listen = "127.0.0.1:8902"
2017/12/18 09:31:27 [debug] admin_listen_ssl = "0.0.0.0:8901"
2017/12/18 09:31:27 [debug] admin_ssl = true
2017/12/18 09:31:27 [debug] admin_ssl_cert = "/opt/kong/kong.crt"
2017/12/18 09:31:27 [debug] admin_ssl_cert_key = "/opt/kong/kong.key"
2017/12/18 09:31:27 [debug] anonymous_reports = false
2017/12/18 09:31:27 [debug] cassandra_consistency = "ONE"
2017/12/18 09:31:27 [debug] cassandra_contact_points = {"1.1.1.1"}
2017/12/18 09:31:27 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2017/12/18 09:31:27 [debug] cassandra_keyspace = "kong"
2017/12/18 09:31:27 [debug] cassandra_lb_policy = "RoundRobin"
2017/12/18 09:31:27 [debug] cassandra_password = "******"
2017/12/18 09:31:27 [debug] cassandra_port = 9042
2017/12/18 09:31:27 [debug] cassandra_repl_factor = 1
2017/12/18 09:31:27 [debug] cassandra_repl_strategy = "SimpleStrategy"
2017/12/18 09:31:27 [debug] cassandra_schema_consensus_timeout = 10000
2017/12/18 09:31:27 [debug] cassandra_ssl = true
2017/12/18 09:31:27 [debug] cassandra_ssl_verify = true
2017/12/18 09:31:27 [debug] cassandra_timeout = 5000
2017/12/18 09:31:27 [debug] cassandra_username = "kong"
2017/12/18 09:31:27 [debug] client_body_buffer_size = "8k"
2017/12/18 09:31:27 [debug] client_max_body_size = "0"
2017/12/18 09:31:27 [debug] client_ssl = false
2017/12/18 09:31:27 [debug] custom_plugins = {}
2017/12/18 09:31:27 [debug] database = "cassandra"
2017/12/18 09:31:27 [debug] db_cache_ttl = 3600
2017/12/18 09:31:27 [debug] db_update_frequency = 5
2017/12/18 09:31:27 [debug] db_update_propagation = 1
2017/12/18 09:31:27 [debug] dns_error_ttl = 1
2017/12/18 09:31:27 [debug] dns_hostsfile = "/etc/hosts"
2017/12/18 09:31:27 [debug] dns_no_sync = false
2017/12/18 09:31:27 [debug] dns_not_found_ttl = 30
2017/12/18 09:31:27 [debug] dns_order = {"LAST","SRV","A","CNAME"}
2017/12/18 09:31:27 [debug] dns_resolver = {}
2017/12/18 09:31:27 [debug] dns_stale_ttl = 4
2017/12/18 09:31:27 [debug] error_default_type = "text/plain"
2017/12/18 09:31:27 [debug] http2 = false
2017/12/18 09:31:27 [debug] latency_tokens = false
2017/12/18 09:31:27 [debug] log_level = "notice"
2017/12/18 09:31:27 [debug] lua_package_cpath = ""
2017/12/18 09:31:27 [debug] lua_package_path = "./?.lua;./?/init.lua;"
2017/12/18 09:31:27 [debug] lua_socket_pool_size = 30
2017/12/18 09:31:27 [debug] lua_ssl_trusted_certificate = "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
2017/12/18 09:31:27 [debug] lua_ssl_verify_depth = 1
2017/12/18 09:31:27 [debug] mem_cache_size = "128m"
2017/12/18 09:31:27 [debug] nginx_daemon = "on"
2017/12/18 09:31:27 [debug] nginx_optimizations = true
2017/12/18 09:31:27 [debug] nginx_user = "kong kong"
2017/12/18 09:31:27 [debug] nginx_worker_processes = "auto"
2017/12/18 09:31:27 [debug] pg_database = "kong"
2017/12/18 09:31:27 [debug] pg_host = "127.0.0.1"
2017/12/18 09:31:27 [debug] pg_port = 5432
2017/12/18 09:31:27 [debug] pg_ssl = false
2017/12/18 09:31:27 [debug] pg_ssl_verify = false
2017/12/18 09:31:27 [debug] pg_user = "kong"
2017/12/18 09:31:27 [debug] prefix = "/opt/kong"
2017/12/18 09:31:27 [debug] proxy_access_log = "/var/log/kong/access.log"
2017/12/18 09:31:27 [debug] proxy_error_log = "/var/log/kong/error.log"
2017/12/18 09:31:27 [debug] proxy_listen = "127.0.0.1:8903"
2017/12/18 09:31:27 [debug] proxy_listen_ssl = "0.0.0.0:1234"
2017/12/18 09:31:27 [debug] real_ip_header = "X-Real-IP"
2017/12/18 09:31:27 [debug] real_ip_recursive = "off"
2017/12/18 09:31:27 [debug] server_tokens = false
2017/12/18 09:31:27 [debug] ssl = true
2017/12/18 09:31:27 [debug] ssl_cert = "/opt/kong/kong.crt"
2017/12/18 09:31:27 [debug] ssl_cert_key = "/opt/kong/kong.key"
2017/12/18 09:31:27 [debug] ssl_cipher_suite = "modern"
2017/12/18 09:31:27 [debug] ssl_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
2017/12/18 09:31:27 [debug] trusted_ips = {}
2017/12/18 09:31:27 [debug] upstream_keepalive = 60
2017/12/18 09:31:27 [verbose] prefix in use: /opt/kong
Error: 
/usr/local/share/lua/5.1/resty/dns/client.lua:450: Invalid configuration, no valid nameservers found
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/resty/dns/client.lua:450: in function 'init'
	/usr/local/share/lua/5.1/kong/tools/dns.lua:37: in function </usr/local/share/lua/5.1/kong/tools/dns.lua:7>
	/usr/local/share/lua/5.1/kong/conf_loader.lua:527: in function 'conf_loader'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:9: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:7: in function 'file_gen'
	init_worker_by_lua:38: in function <init_worker_by_lua:36>
	[C]: in function 'xpcall'
	init_worker_by_lua:45: in function <init_worker_by_lua:43>

- Kong error logs (`<KONG_PREFIX>/logs/error.log`): empty
- Kong configuration (registered APIs/Plugins & configuration file): none registered/enabled yet
- Operating System: Red Hat Enterprise Linux Server release 6.5 (Santiago)

[kong.conf.zip](https://github.com/Kong/kong/files/1566987/kong.conf.zip)

**Comment by Tieske** [comment] 2017-12-18 08:58
Kong doesn't know that you're proving all IPs, hence the error is thrown when it initializes the dns resolver.

If you're not using dns resolution, then adding a fake nameserver, eg. 127.0.0.1 would suffice probably as a workaround.

fwiw; the issue is with the dns library (if you want to call it an issue)

**Comment by kikito** [comment] 2017-12-18 15:39
We have made a change in the DNS library which should fix this issue. We should close this issue once the library is released and used by kong.

**Comment by thibaultcha** [comment] 2018-05-07 17:59
This should have now been resolved since Kong 0.12 and 0.13. Thank you for reporting @sotroyalta

**Closed by thibaultcha** 2018-05-07 17:59 UTC
Labels: task/needs-investigation
