### ISSUE TITLE
kong custom plugin

### ISSUE THREAD

**Issue by tavisca-syedave** [Kong/kong#2785] opened 2017-08-08 05:56 UTC
Hi,

I have created one custom kong plugin using key-auth standard plugin.
Copied key-auth plugin code and updated error messages as we need our custom error messages.
Kong version : kong-0.10.3-0

Steps executed on kong server :
1. Created rockspec  package
2. Installed using luarocks make command
3. Edited kong.conf file to include custom plugins
4. kong reload
5. Checked plugin list using below api request :
curl -i -X GET \
	  --url http://localhost:8001/plugins/enabled

The custom plugin is not getting displayed in the enabled plugin list 
I have also tried adding the custom plugin on one of api but it's not getting executed.

The custom plugin works when I add custom plugin entry in constants.lua file (file path : /usr/local/share/lua/5.1/kong) under local plugins section.

Questions - 
1. am I missing something here?
2. does custom plugin registration requires updating constants.lua file or not?

**Comment by thibaultcha** [comment] 2017-08-08 06:06
Hi,

We have recently encountered such an issue as well with `kong reload`. May I suggest that you give a try with `kong restart`? There should be a file at `<prefix>/.kong_env`. This file should have the updated `custom_plugins` value after a `kong restart`.

**Comment by thibaultcha** [comment] 2017-11-02 03:55
Closing due to lack of follow up and since the issue is over 2 months old by now... This is very much likely to be related to our faulty `kong reload` behavior, which is already internally tracked.

Thanks for the report!

**Closed by thibaultcha** 2017-11-02 03:55 UTC
