### ISSUE TITLE
Kong rate-limiting plugin seems to expire redis keys too soon.

### ISSUE THREAD

**Issue by maraswrona** [Kong/kong#4076] opened 2018-12-12 15:02 UTC
### Summary

I have the rate-limiting plugin enabled on my API. I'm using redis to store the rate-limit counters. One of the consumers has monthly limit configured. I wanted to check what was that consumer's usage for the last month, but I realized that the counters disappear from the cache automatically after some time, so I checked how it's done. Apparently the plugin configures the keys to expire after some time automatically in redis. So I checked the ttl of the current monthly counter (December 2018) for that consumer:

```
ttl ratelimit:d212fe49-3f85-4452-8074-8af71c5e19d9:b6f276b2-fd49-4e16-9947-c197d10996ba:1543622400000:month
(integer) 1593814
```
The result is seconds left until the key will expire. This was done just now, which is 1544622040797ms since epoch, which is Wed Dec 12 2018 13:40:40 UTC. 

1544622040797 + 1593814 * 1000 = 1546215854797 which is **Mon Dec 31 2018 00:24:14 UTC** - the monthly counter will expire 1 day too soon, which will make the calculations incorrect. I guess new counter will be created in that case, which overall will grant the consumer more requests than he is eligible for in that given month.

I think I even found the code responsible for this: https://github.com/Kong/kong/blob/fc46f23c57db3b0b57d6c7d8dd44bf470493f9e4/kong/plugins/rate-limiting/policies/init.lua

The plugin sets keys to expire after these amounts of seconds:
```
local EXPIRATIONS = {
  second = 1,
  minute = 60,
  hour = 3600,
  day = 86400,
  month = 2592000,
  year = 31536000,
}
```

It works fine for second, minute, hour and day counters, since number of seconds in these is always the same. But months vary, same as years. The code assumes each month is 30 days long (2592000s) and that each year is 365 days long (2592000s). Clearly 31 day long months and leap years (366 days) are not considered. 

### Steps To Reproduce
It is not easy to reproduce the exact same symptoms I see in my system as it depends on the dates when you do certain actions. But let's try.

First, assume you start at the month which is 30 days long (e.g. November). Let's say it is the middle of the month (15th).
1. Create API with rate-limit plugin enabled. Configure monthly and/or yearly limits for the API and use redis policy to store counters.
2. Generate some requests to the API so that counters are initialized. Make sure API is used constantly (e.g. every minute or so), so that when the month passes, new counter is allocated almost immediately.
3. Connect to your redis instance and check the ttl of existing counters. At this moment you will see that the created monthly counter will expire in ~30 days, which is some time during the next month (around 15th of December), which is fine. For now.
4. Wait till December. Keep using the API. 
5. In December connect to your redis again and check the ttl of new counters. Now you will see that the counter (which was most likely created just after midnight Dec 1st) it will have its expiration date set to 31st of December, which is 1 day too soon.

### Fix suggestions

The simple way to fix that is basically increase the `month` and `year` values in `EXPIRATIONS` structure so that they cover 31 day long months, and 366 day long years. So simply:
```
local EXPIRATIONS = {
  second = 1,
  minute = 60,
  hour = 3600,
  day = 86400,
  month = 2678400,
  year = 31622400,
}
```
This will fix the main problem described by this ticket, but actually the approach used in the plugin seems to be a little bit wasteful. If we create an API in December with yearly limit, then that counter will be used until the end of this year, then new one will be created on Jan 1st and the old one will be kept in the cache for another 11 months, which isn't very big deal, but could be done better. 

E.g. consider expiring keys not after fixed period (as it is now) but calculate this period based on current date. That way when creating a yearly counter in December, this counter should expire on Jan 1st, and not 12 months later.

Finally, it may be useful to have this behavior configurable. E.g. in my case I would like to keep yearly and monthly counters forever, e.g. to be able to check the API usage, for billing etc. If I need I may be able to remove them myself later. This is just a thought, probably deserves its own ticket.

### Additional Details & Logs

- Kong version 0.13.1

**Comment by subnetmarco** [comment] 2018-12-14 02:03
> Clearly 31 day long months and leap years (366 days) are not considered.

Calculating the exact duration of months and years would be preferable to make the feature more mature (that could also be used by any other plugin that relies on timing).

**Comment by maraswrona** [comment] 2018-12-14 10:12
> Google says:
> 
> ```
> 1 month = 2 629 743.83 seconds
> 1 year = 31 556 926 seconds
> ```

I fail to see how that's relevant. 

The feature, if I understood correctly, is supposed to expire the key not sooner than the period of its particular counter. For second, minute, hour and day based limits it is fine to expire them exactly after 1, 60, 3600 and 86400 seconds. For month and year based limits the expiration time should cover the longest possible month and year, respectively, to make sure the keys are not expired too soon. It doesn't matter what are "exact", or "average", or "typical" number of seconds per month/year, it's not what the feature is about.

**Comment by maraswrona** [comment] 2019-06-28 13:00
Any idea when this issue could be fixed? 

As an immiediate solution you can use my fix proposal, or even I can contribute via PR if that's fine. You can work then on the more longterm improvement (the calculated exact expiration durations) in a separate issue. What do you say?

**Comment by maraswrona** [comment] 2019-11-19 15:38
Is there any update on this issue? 

I may have chosen unfortunate wording in the issue title, as it suggest the issue is some minor oddity. It is not. It is quite a serious bug, especially for someone who is using rate-limiting plugin with redis and relies on it e.g. to charge the clients for API usage. 

I provided simple (but not perfect) way to fix it. Can I at least provide a PR with a fix proposal?

**Comment by StarlightIbuki** [comment] 2023-10-11 06:19
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Comment by maraswrona** [comment] 2023-10-12 13:34
Well, I'm not working with kong anymore so it is not so easy for me to test it at the moment, but considering the source code in question did not change too much since 2018 I expect this bug is still there. I offered I could do a PR with simple fix, but with no response. 

I understand how autobots have to close these issues as part of project clean up, but I'd appreciate open source projects to give more attention to bugs reported by users, especially when they offer help - it's a free labor for you guys.

**Comment by StarlightIbuki** [comment] 2023-10-13 08:16
@maraswrona Apologize and thanks to you.
I revisited the ticket and found this more like a design problem: It makes much sense for short-period limits to be used as a protection, and month/year limits as quota management. How do we define rete-limiting for a long period?
I remember similar questions were asked and we updated the doc to tell what a user should expect.
This is a hard-to-answer question and to be honest we did not think it thoroughly at the very beginning.

**Comment by maraswrona** [comment] 2023-10-13 12:07
Thanks for the answer. I see your point with API protection vs quota management issue. For the latter the plugin should probably offer more sophisticated options, like usage reporting or maybe it should be different plugin entirely. Still, in my opinion simply extending the TTL for month and year counters to cover longest possible periods should cover my case and at the same time should not break anything else. Do you see any risks or downside?

**Comment by StarlightIbuki** [comment] 2023-10-19 06:23
@maraswrona We planned a review and improvement of the RL plugin in the future release.
As for the short-term solution(using the longest month and year) you mentioned, if it's OK for you, we'd like to know the motivation for it so we may have a better understanding.

**Comment by maraswrona** [comment] 2023-10-19 06:44
So I noticed that the plugin creates new counters at the beginning of each "counting period" - minute counter starts at 00s, hour counter at 00m:00s, daily counter at midnight and so forth. The montly counter is created at the beginning of the month but it only lasts for 30 days regardless of the length of the current month. For months that are 31 days long it will expire 1 day before the end, and new counter will be created in its place immediately (which will have again 30 days ttl and it's configured limit assigned). This is the place where I have a problem since this means customers can be shortly entitled to higher quota than they should be. However, on the 1st of next month this "rogue" counter will be overwritten with fresh one so everything comes back to normal.

That is at least what I observed in 2018 when I was debugging this. If this is the case, then this means counters living "too long" get overwritten by their fresh new versions at the beginning of new period, which means it should be ok to have a counter that occasionally has a lifespan larger than the current month / year. In contrary, having counters that occasionally expire sooner than they should leads to a situation I described. 

So IMHO there is no clear downside of having the monthly and yearly counters to expire after 31 and 366 days respectively, but there is a downside having them expire after 30 and 365 days.

**Comment by StarlightIbuki** [comment] 2023-10-19 07:05
@maraswrona Thanks for the thorough explanation.IMO removing the refreshing mechanism makes more sense

**Comment by chronolaw** [comment] 2024-01-18 01:26
@StarlightIbuki , do we have an internal ticket to track this issue?

**Comment by chronolaw** [comment] 2024-01-18 02:57
We have internally track this issue. thank you.

**Closed by chronolaw** 2024-01-18 02:57 UTC
Labels: plugins/rate-limiting
