### ISSUE TITLE
cat not set multi scopes when add oauth2 plugin on a service

### ISSUE THREAD

**Issue by xbazhen** [Kong/kong#6017] opened 2020-06-16 09:46 UTC
### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1. create a service 
2. create a route for this service 
3. add oauth2 plugin on this service
4. I want  "scopes": [“email”, "phone", "address"]，but only return  "scopes": ["address"]

use config.scopes[] is the same as config.scopes
"config.scopes[]=email"
"config.scopes[]=phone"
"config.scopes[]=address"

```
offical docs 
https://docs.konghq.com/hub/kong-inc/oauth2/
Enabling the plugin on a Service

$ curl -X POST http://kong:8001/services/{service}/plugins \
    --data "name=oauth2"  \
    --data "config.scopes=email" \
    --data "config.scopes=phone" \
    --data "config.scopes=address" \
    --data "config.mandatory_scope=true" \
    --data "config.enable_authorization_code=true"


{
    "created_at": 1592300403,
    "config": {
        "refresh_token_ttl": 1209600,
        "enable_client_credentials": false,
        "mandatory_scope": true,
        "provision_key": "LBOuaaUVSbwdsD3COjcMO6Uy3y8KoX9x",
        "accept_http_if_already_terminated": false,
        "hide_credentials": false,
        "enable_implicit_grant": false,
        "global_credentials": true,
        "enable_authorization_code": true,
        "enable_password_grant": false,
        "scopes": [
            "address"
        ],
        "anonymous": null,
        "token_expiration": 7200,
        "auth_header_name": "authorization"
    },
    "id": "46333a6f-75d7-4548-89fa-a5789d25d21c",
    "service": {
        "id": "009c1dcd-52c1-4d43-916d-96b052198db3"
    },
    "enabled": true,
    "protocols": [
        "grpc",
        "grpcs",
        "http",
        "https"
    ],
    "name": "oauth2",
    "consumer": null,
    "route": null,
    "tags": null
}
```

### Additional Details & Logs

- Kong version (2.0.4)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system (docker kong 2.0.4)

**Comment by bungle** [comment] 2020-09-16 23:24
I could not reproduce with latest version. So I think it is fixed. Thus closing this. Please reopen if you still see this.

**Closed by bungle** 2020-09-16 23:24 UTC
