### ISSUE TITLE
Kong manager is broken after upgrade to 3.4.3.4

### ISSUE THREAD

**Issue by RoSk0** [Kong/kong#12598] opened 2024-02-21 21:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong Enterprise 3.4.3.4

### Current Behavior

After upgrading from Kong 3.1.1.3 running on Ubuntu Focal to 3.4.3.4 running on Jammy Manager UI is broken. 
Attempt to access Manager results in a Manager UI being rendered and then immediately disappear.

Deployment runs in a traditional mode using custom Helm chart. Database updates ran successfully.

Admin API is available on https://uat2-api.cc.hostname.com/admin .

Kong Manager is available on https://uat2-api.cc.hostname.com/manager .

TLS is offloaded on the ingress controller, so Kong servers only HTTP traffic.

Both `/manager` and `/admin` are IP restricted and protected by the `basic-auth` on ingress. 

Firefox console shows two JavaScript errors:

```
TypeError: u.value is undefined
    p https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:503
    run https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    get value https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    V_t https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:503
    u https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:503
    run https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    get value https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    F https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:503
    run https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    get value https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    setup https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:503
    u2 https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    Ue https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    run https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    update https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    Al https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    WH https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    promise callback*KH https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    o2 https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    effect https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    EH https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    qE https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    Xb https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    effect https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    EH https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    qE https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    Xb https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    effect https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    EH https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    qE https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    Tl https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    TH https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    set value https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    TH https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    setWorkspaces https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:482
    k https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:18
    p https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:544
    Y7t https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:544
    promise callback*DIt</Y7t/< https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:544
    Y7t https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:544
    DIt https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:545
    async* https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:9
index.86740e45.3_4_3_3.js:12:77607
    FPe https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    _d https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    u2 https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    Ue https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    run https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    update https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    Al https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    WH https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    (Async: promise callback)
    KH https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    o2 https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    effect https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    EH https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    qE https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    Xb https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    effect https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    EH https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    qE https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    Xb https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    effect https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    EH https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    qE https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    Tl https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    TH https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    set value https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    TH https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:12
    setWorkspaces https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:482
    k https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:18
    p https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:544
    Y7t https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:544
    (Async: promise callback)
    Y7t https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:544
    Y7t https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:544
    DIt https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:545
    <anonymous> https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:9
```

and 

```
TypeError: f is undefined
    p https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:544
    Y7t https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:544
    promise callback*DIt</Y7t/< https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:544
    Y7t https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:544
    DIt https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:545
    async* https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:9
index.86740e45.3_4_3_3.js:544:153616
    Y7t https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:544
    (Async: promise callback)
    Y7t https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:544
    Y7t https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:544
    DIt https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:545
    <anonymous> https://uat2-api.cc.hostname.com/manager/assets/index.86740e45.3_4_3_3.js:9
```

Chromium console shows different errors:
```
index.86740e45.3_4_3_3.js:12 TypeError: Cannot read properties of undefined (reading 'filter')
    at Pm.fn (index.86740e45.3_4_3_3.js:503:66727)
    at Pm.run (index.86740e45.3_4_3_3.js:12:64983)
    at get value (index.86740e45.3_4_3_3.js:12:74178)
    at V_t (index.86740e45.3_4_3_3.js:503:66980)
    at Pm.fn (index.86740e45.3_4_3_3.js:503:67754)
    at Pm.run (index.86740e45.3_4_3_3.js:12:64983)
    at get value (index.86740e45.3_4_3_3.js:12:74178)
    at Pm.fn (index.86740e45.3_4_3_3.js:503:68221)
    at Pm.run (index.86740e45.3_4_3_3.js:12:64983)
    at get value (index.86740e45.3_4_3_3.js:12:74178)
FPe @ index.86740e45.3_4_3_3.js:12
_d @ index.86740e45.3_4_3_3.js:12
u2 @ index.86740e45.3_4_3_3.js:12
Ue @ index.86740e45.3_4_3_3.js:12
run @ index.86740e45.3_4_3_3.js:12
W.z.update @ index.86740e45.3_4_3_3.js:12
Al @ index.86740e45.3_4_3_3.js:12
WH @ index.86740e45.3_4_3_3.js:12
Promise.then (async)
KH @ index.86740e45.3_4_3_3.js:12
o2 @ index.86740e45.3_4_3_3.js:12
(anonymous) @ index.86740e45.3_4_3_3.js:12
EH @ index.86740e45.3_4_3_3.js:12
qE @ index.86740e45.3_4_3_3.js:12
Xb @ index.86740e45.3_4_3_3.js:12
(anonymous) @ index.86740e45.3_4_3_3.js:12
EH @ index.86740e45.3_4_3_3.js:12
qE @ index.86740e45.3_4_3_3.js:12
Xb @ index.86740e45.3_4_3_3.js:12
(anonymous) @ index.86740e45.3_4_3_3.js:12
EH @ index.86740e45.3_4_3_3.js:12
qE @ index.86740e45.3_4_3_3.js:12
Xb @ index.86740e45.3_4_3_3.js:12
(anonymous) @ index.86740e45.3_4_3_3.js:12
EH @ index.86740e45.3_4_3_3.js:12
qE @ index.86740e45.3_4_3_3.js:12
Tl @ index.86740e45.3_4_3_3.js:12
(anonymous) @ index.86740e45.3_4_3_3.js:12
set value @ index.86740e45.3_4_3_3.js:12
(anonymous) @ index.86740e45.3_4_3_3.js:12
setWorkspaces @ index.86740e45.3_4_3_3.js:482
(anonymous) @ index.86740e45.3_4_3_3.js:18
p @ index.86740e45.3_4_3_3.js:544
(anonymous) @ index.86740e45.3_4_3_3.js:544
Promise.then (async)
(anonymous) @ index.86740e45.3_4_3_3.js:544
Promise.then (async)
Y7t @ index.86740e45.3_4_3_3.js:544
(anonymous) @ index.86740e45.3_4_3_3.js:545
Promise.then (async)
(anonymous) @ index.86740e45.3_4_3_3.js:9
index.86740e45.3_4_3_3.js:544 TypeError: Cannot read properties of undefined (reading '0')
    at p (index.86740e45.3_4_3_3.js:544:152020)
    at index.86740e45.3_4_3_3.js:544:1535
```

HAR archive for the request is attached. 
[uat2-api.cc.hostname.com_Archive [24-02-22 09-58-52].har.json](https://github.com/Kong/kong/files/14365525/uat2-api.cc.hostname.com_Archive.24-02-22.09-58-52.har.json)

`GET`  request to the https://uat2-api.cc.hostname.com/admin is attached as well. 
[admin.json](https://github.com/Kong/kong/files/14365528/admin.json)

Our testing suggests that API proxying is working fine. There are no errors in the logs as well.

Any help and pointers to misconfiguration are greatly appreciated.

### Expected Behavior

Kong manager is served or better error message is provided.

**Comment by RoSk0** [comment] 2024-02-23 02:22
It's not exactly a bug, but rather a combination of local misconfiguration and poor Admin API behaviour.

As stated in the description, both Admin API and Manager are available on the same domain, but under different paths. Misconfiguration of Admin API ingress led to `/admin` not being stripped from the requests, so when Manager was requesting a list of available workspaces from `/admin/workspaces?size=1000` Admin API was receiving the full `/admin/workspaces?size=1000` rather than `/workspaces?size=1000`. Ideally, in my opinion, Admin API would respond with 400,  or at least 404 as `/admin/workspaces` endpoint is undefined. Unfortunately for me Admin API was returning default response with 200 and full Kong configuration instead.

**Comment by raoxiaoyan** [comment] 2024-02-27 03:06
@RoSk0 Thank you for reporting this. Can you provide your `kong.conf`, please?

**Comment by RoSk0** [comment] 2024-03-13 09:06
@raoxiaoyan sorry for the late reply. 

We are using the default config with the only addition around headers. Here is the excerpt from our Dockerfile:
```
&& cp /etc/kong/kong.conf.default /etc/kong/kong.conf \
&& echo "headers = off" >> /etc/kong/kong.conf
```

**Comment by chronolaw** [comment] 2024-04-02 01:52
@raoxiaoyan , do we have any update for this issue?

**Comment by raoxiaoyan** [comment] 2024-04-02 02:13
Sorry. I can't repro it very well.  From @RoSk0 said. It's not a bug. https://github.com/Kong/kong/issues/12598#issuecomment-1960647986
We could close it.

**Closed** 2024-04-02 02:13 UTC
Labels: kong-manager
