### ISSUE TITLE
Dev container required fixing for initial setup

### ISSUE THREAD

**Issue by ItsKaleb** [Kong/kong#11422] opened 2023-08-18 06:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.5

### Current Behavior

When I clone the master branch and attempt to start a dev container in VS Code, Kong fails to build with errors related to missing expat.h and curl.

Once resolved, further errors are encountered when attempting to run make test where a GitHub token is required to clone admin gui repo.

### Expected Behavior

Expected behaviour is that the dev container should be able to build successfully on a fresh clone and tests should be able to run.

### Steps To Reproduce

From a fresh environment:
* With VS Code installed
* With the Dev Containers extension
* Backed by a fresh Docker Desktop installation
* With WSL2 installed

Attempt to start the Dev Container through VS Code

### Anything else?

This is my first dive into dev containers, so I am not confident in my work around. If it does assist though, I was able to resolve the problem by making the following changes to /.devcontainer/Dockerfile

```
--- FROM kong/kong:3.0.0-ubuntu
+++ FROM kong/kong:3.4.0-ubuntu

USER root

RUN apt-get update

RUN apt-get install -y \
        build-essential \
        unzip \
        git \
        m4 \
        libyaml-dev

+++ RUN apt-get install -y \
+++         libexpat1-dev \
+++         curl
+++
+++ ENV GH_TOKEN "a github token with readonly permission for public repos"
```

**Comment by ItsKaleb** [comment] 2023-08-19 02:33
I've also found that, while I'm able to get the tests running now, they are incredibly slow. Plus there's no output, so I can't tell what they're doing or why they are taking so long. Running make test-plugins didn't finish after running for 3 hours.

**Comment by hanshuebner** [comment] 2023-08-22 13:05
The devcontainer configuration has not been maintained in a while and is likely no longer working.  The supported way to build Kong for testing bundled plugins is to follow the [build instructions](https://github.com/Kong/kong/blob/master/build/README.md).  From within the virtual environment built by bazel, it is possible to run the tests using the `bin/busted` script that is included with the source code.

**Comment by ItsKaleb** [comment] 2023-08-23 04:03
Hmm, ok. 
Would've been nice to have a slightly more turn-key option, but will give it a go on a Virtual Box VM.
Thanks for the input, @hanshuebner.

... Technically speaking, shouldn't it be possible to set up a dev container using something like a base Ubuntu image, and have it run the steps from those build instructions as part of the Dockerfile? I might also poke around with that and see if I can get the container working again too. Might be a nice to have?

**Comment by hanshuebner** [comment] 2023-08-23 04:11
Having a turn-key developer image would be nice, and updating the dev container Dockerfile to use an Ubuntu base image and then run a build would make sense.  If you get stuck at anything, let us know.  I'll also gladly test and review a PR with updates.

**Comment by ItsKaleb** [comment] 2023-09-04 01:29
Just as an update, I've so far got the dev container configured with the specified dev dependencies, and it's able to run `make dev` to build Kong. I can also run `make test`, but some of the tests fail - this is almost certainly due to the fact that I've not quite got the built version of Kong running in the container yet. 

The existing tools for running a locally built Kong assume that you are on a VM or local machine, and attempt to start the required containers - I still need to translate this into starting the Kong instance inside the container and leveraging the supporting containers (like postgres DB) that are started as part of the .devcontainer/docker-compose.yml file.

**Comment by ItsKaleb** [comment] 2023-09-04 08:10
I've spent another couple of hours on this today. 
While I am getting Kong to start up in the dev container, any calls made to it are just hanging at the moment.
I'm kinda skeptical that it's to do with the Postgres container, as a `nc` to that container also hangs. Unfortunately, I've not found any logs to indicate what's going on though. Mainly, a local curl to 0.0.0.0:8001/status just hangs.

What is slightly more promising is the output from the Postgres container - I can see evidence that the PG initialisation is working and the kong and kong-testing DBs are being set up. So hopefully once I get over this alleged connectivity issue things will fall into place.

**Comment by StarlightIbuki** [comment] 2023-10-11 09:10
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 09:10 UTC
Labels: chore
