### ISSUE TITLE
How can Kong retry target in upstream

### ISSUE THREAD

**Issue by guyueyimu** [Kong/kong#5650] opened 2020-03-09 07:32 UTC
### Summary

In the test, if the service fails to be called, we find that Kong's service can be retried. But if the target in upstream is not available, how to make Kong retry the next target like nginx.

### Steps To Reproduce

1.Set up routes, services, and upstream
2.Two targets in upstream (eg: 10.1.62.50:6080 and 10.1.62.50:6180)
3.Make a target (eg: 10.1.62.50:6180) unavailable
4.Request Kong with a certain amount of traffic, but some will fail, while nginx will not

### Additional Details & Logs

- Kong version 2.0.1
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
kongtest@eb7024:/home/kongtest/smekong/work/kong_ingress/logs>grep "info/21912" *
access.log:10.1.62.50 - - [04/Mar/2020:21:31:55 +0800] "POST /test/http/v1.0/echo/info/21912 HTTP/1.1" 502 77 "-" "callhttp_sbi/0201A0ABADA6853151E040C0"
error.log:2020/03/04 21:31:55 [error] 23770#0: *146252 connect() failed (111: Connection refused) while connecting to upstream, client: 10.1.62.50, server: kong, request: "POST /test/http/v1.0/echo/info/21912 HTTP/1.1", upstream: "http://10.1.62.50:6180/test/http/v1.0/echo/info/21912", host: "kong.ebupt"
error.log:2020/03/04 21:31:55 [error] 23770#0: *146252 connect() failed (111: Connection refused) while connecting to upstream, client: 10.1.62.50, server: kong, request: "POST /test/http/v1.0/echo/info/21912 HTTP/1.1", upstream: "http://10.1.62.50:6180/test/http/v1.0/echo/info/21912", host: "kong.ebupt"
error.log:2020/03/04 21:31:55 [error] 23770#0: *146252 connect() failed (111: Connection refused) while connecting to upstream, client: 10.1.62.50, server: kong, request: "POST /test/http/v1.0/echo/info/21912 HTTP/1.1", upstream: "http://10.1.62.50:6180/test/http/v1.0/echo/info/21912", host: "kong.ebupt"
error.log:2020/03/04 21:31:55 [error] 23770#0: *146252 connect() failed (111: Connection refused) while connecting to upstream, client: 10.1.62.50, server: kong, request: "POST /test/http/v1.0/echo/info/21912 HTTP/1.1", upstream: "http://10.1.62.50:6180/test/http/v1.0/echo/info/21912", host: "kong.ebupt"
error.log:2020/03/04 21:31:55 [error] 23770#0: *146252 connect() failed (111: Connection refused) while connecting to upstream, client: 10.1.62.50, server: kong, request: "POST /test/http/v1.0/echo/info/21912 HTTP/1.1", upstream: "http://10.1.62.50:6180/test/http/v1.0/echo/info/21912", host: "kong.ebupt"
error.log:2020/03/04 21:31:55 [error] 23770#0: *146252 connect() failed (111: Connection refused) while connecting to upstream, client: 10.1.62.50, server: kong, request: "POST /test/http/v1.0/echo/info/21912 HTTP/1.1", upstream: "http://10.1.62.50:6180/test/http/v1.0/echo/info/21912", host: "kong.ebupt"
kongtest@eb7024:/home/kongtest/smekong/work/kong_ingress/logs>grep "info/21916" *
access.log:10.1.62.50 - - [04/Mar/2020:21:31:55 +0800] "POST /test/http/v1.0/echo/info/21916 HTTP/1.1" 502 77 "-" "callhttp_sbi/0201E0ABADA6853151E040C4"
error.log:2020/03/04 21:31:55 [error] 23770#0: *146252 connect() failed (111: Connection refused) while connecting to upstream, client: 10.1.62.50, server: kong, request: "POST /test/http/v1.0/echo/info/21916 HTTP/1.1", upstream: "http://10.1.62.50:6180/test/http/v1.0/echo/info/21916", host: "kong.ebupt"
error.log:2020/03/04 21:31:55 [error] 23770#0: *146252 connect() failed (111: Connection refused) while connecting to upstream, client: 10.1.62.50, server: kong, request: "POST /test/http/v1.0/echo/info/21916 HTTP/1.1", upstream: "http://10.1.62.50:6180/test/http/v1.0/echo/info/21916", host: "kong.ebupt"
error.log:2020/03/04 21:31:55 [error] 23770#0: *146252 connect() failed (111: Connection refused) while connecting to upstream, client: 10.1.62.50, server: kong, request: "POST /test/http/v1.0/echo/info/21916 HTTP/1.1", upstream: "http://10.1.62.50:6180/test/http/v1.0/echo/info/21916", host: "kong.ebupt"
error.log:2020/03/04 21:31:55 [error] 23770#0: *146252 connect() failed (111: Connection refused) while connecting to upstream, client: 10.1.62.50, server: kong, request: "POST /test/http/v1.0/echo/info/21916 HTTP/1.1", upstream: "http://10.1.62.50:6180/test/http/v1.0/echo/info/21916", host: "kong.ebupt"
error.log:2020/03/04 21:31:55 [error] 23770#0: *146252 connect() failed (111: Connection refused) while connecting to upstream, client: 10.1.62.50, server: kong, request: "POST /test/http/v1.0/echo/info/21916 HTTP/1.1", upstream: "http://10.1.62.50:6180/test/http/v1.0/echo/info/21916", host: "kong.ebupt"
error.log:2020/03/04 21:31:55 [error] 23770#0: *146252 connect() failed (111: Connection refused) while connecting to upstream, client: 10.1.62.50, server: kong, request: "POST /test/http/v1.0/echo/info/21916 HTTP/1.1", upstream: "http://10.1.62.50:6180/test/http/v1.0/echo/info/21916", host: "kong.ebupt"
- Operating system CentOS Linux release 7.6.1810

**Comment by StarlightIbuki** [comment] 2023-10-11 06:14
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:14 UTC
Labels: core/balancer
