### ISSUE TITLE
how to remove nested json element using request-transformer

### ISSUE THREAD

**Issue by RahulRdec** [Kong/kong#7876] opened 2021-09-22 16:50 UTC
### Discussed in https://github.com/Kong/kong/discussions/7863

<div type='discussions-op-text'>

<sup>Originally posted by **RahulRdec** September 21, 2021</sup>
I am able to remove the top level element("kind") but can't remove nested. I want to remove namespace from the below request. I am trying 'spec.namespace' in remove body but isn’t working. any help will be appreciated. Thanks.

"kind":"update"
"spec": {"namespace": "teamname",}</div>

**Comment by alpes-developpement** [comment] 2022-09-19 11:58
No news about this issue ? I have the same problem, it's not possible to change a nested value in a json body.

**Comment by StarlightIbuki** [comment] 2023-10-11 06:36
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:36 UTC
Labels: plugins/request-transformer

**Comment by StarlightIbuki** [comment] 2023-10-11 08:09
@RahulRdec @alpes-developpement You could try using https://docs.konghq.com/hub/kong-inc/pre-function/configuration/ or write a custom plugin.
Hope this solves your problem. Please feel free to reopen the issue if you have further concerns.
