### ISSUE TITLE
Kong healthchecks disabled but removing services

### ISSUE THREAD

**Issue by slimm609** [Kong/kong#4385] opened 2019-03-13 11:31 UTC
Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

kong version 1.0.3
Kong healthchecks disabled but still removing services.

2019/03/13 11:18:40 [debug] 208#0: *671170 [lua] healthcheck.lua:989: log(): [healthcheck] (email-v1-blue) event: target 'email-v1-blue.service.consul:8000' removed
2019/03/13 11:18:40 [debug] 208#0: *671170 [lua] events.lua:192: do_event_json(): worker-events: handling event; source=lua-resty-healthcheck [email-v1-blue], event=remove, pid=208, data=table: 0x43a09460
2019/03/13 11:18:40 [debug] 208#0: *671170 [lua] healthcheck.lua:989: log(): [healthcheck] (email-v1-blue) event: target status 'ac1e0c1d.addr.dc1.consul:32799' from 'false' to 'true'
2019/03/13 11:18:40 [debug] 208#0: *671170 [lua] healthcheck.lua:989: log(): [healthcheck] (email-v1-blue) event: target added ac1e0c1d.addr.dc1.consul:32799
2019/03/13 11:18:40 [debug] 208#0: *671170 [lua] events.lua:192: do_event_json(): worker-events: handling event; source=lua-resty-healthcheck [email-v1-blue], event=healthy, pid=208, data=table: 0x43a08220
2019/03/13 11:18:40 [debug] 208#0: *671170 [lua] healthcheck.lua:989: log(): [healthcheck] (email-v1-blue) event: target status 'ac1e0c1d.addr.dc1.consul:32799' from 'false' to 'true'
2019/03/13 11:18:40 [debug] 208#0: *671170 [lua] healthcheck.lua:989: log(): [healthcheck] (email-v1-blue) event: target added ac1e0c1d.addr.dc1.consul:32799
2019/03/13 11:18:40 [debug] 208#0: *671170 [lua] healthcheck.lua:989: log(): [healthcheck] (email-v1-blue) event: target 'email-v1-blue.service.consul:8000' removed

We see this for every service that is doing a srv lookup from consul and we see it every second.

Its causing errors because the service isn't available.    Consul shows the service active the entire time and working without issues.

```
{
  "created_at": 1552421116,
  "hash_on": "none",
  "id": "cff44964-d124-4281-a382-0f8a4d3d2139",
  "name": "email-v1-blue",
  "hash_fallback_header": null,
  "hash_on_cookie": null,
  "healthchecks": {
    "active": {
      "unhealthy": {
        "http_statuses": [
          429,
          404,
          500,
          501,
          502,
          503,
          504,
          505
        ],
        "tcp_failures": 0,
        "timeouts": 0,
        "http_failures": 0,
        "interval": 0
      },
      "type": "http",
      "http_path": "/",
      "timeout": 1,
      "healthy": {
        "successes": 0,
        "interval": 0,
        "http_statuses": [
          200,
          302
        ]
      },
      "https_sni": null,
      "https_verify_certificate": true,
      "concurrency": 10
    },
    "passive": {
      "unhealthy": {
        "http_failures": 0,
        "http_statuses": [
          429,
          500,
          503
        ],
        "tcp_failures": 0,
        "timeouts": 0
      },
      "healthy": {
        "http_statuses": [
          200,
          201,
          202,
          203,
          204,
          205,
          206,
          207,
          208,
          226,
          300,
          301,
          302,
          303,
          304,
          305,
          306,
          307,
          308
        ],
        "successes": 0
      },
      "type": "http"
    }
  },
  "hash_on_cookie_path": "/",
  "hash_fallback": "none",
  "hash_on_header": null,
  "slots": 10000
}
```

### Additional Details & Logs

- Kong version (`$ kong version`) 
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by hishamhm** [comment] 2019-03-15 20:56
What output do you get when you access `/upstreams/email-v1-blue/health` via the Admin API?

**Comment by slimm609** [comment] 2019-03-15 21:15
```{"next":null,"data":[{"created_at":1552678664.799,"upstream":{"id":"ada4c754-a331-44b2-bef3-ed06dfe0c89e"},"id":"2df29428-5471-4bbf-8477-0d6ea09b5845","health":"HEALTHCHECKS_OFF","target":"email-v1-blue.service.consul:8000","weight":100}],"node_id":"b20d8d6c-fd1c-439e-ba07-ec9113c09439"}```

**Comment by slimm609** [comment] 2019-03-22 15:05
https://github.com/Kong/kong/blob/a90fcddf2215df61b69ffb6a03297e05090baec0/kong/runloop/balancer.lua#L394

Shouldn't this logic have an if around it to not even try to create a healthchecker if the health checks are disabled.

**Comment by slimm609** [comment] 2019-05-20 13:46
seeing this issue more with the latest version (1.1.2).   

Healthchecks are completely turned off but upstreams are getting removed as unhealthy.

**Comment by StarlightIbuki** [comment] 2023-10-11 06:20
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:20 UTC
Labels: task/needs-investigation, core/balancer
