### ISSUE TITLE
Kong Proxy SHM issues with kong events processor

### ISSUE THREAD

**Issue by mlatimer-figure** [Kong/kong#6793] opened 2021-02-01 17:17 UTC
### Summary

We recently upgraded our ingress-controller from 0.9.1 to 1.1.1, and our kong-proxy from 2.2.4 to 2.3.1  and started to see the following errors in our proxy logs since:

2021/02/01 16:59:56 [warn] 22#0: *12415095 [lua] events.lua:155: post_event(): worker-events: could not write to shm after 6 tries (no memory), it is either fragmented or cannot allocate more memory, consider increasing 'opts.shm_retries' or increasing the shm size, client: 127.0.0.1, server: kong_admin, request: "PUT /upstreams/071e7eb8-f1c2-49d8-948f-02a746bdc614 HTTP/1.1", host: "127.0.0.1:8444"
2021/02/01 16:59:56 [error] 22#0: *12415095 [lua] events.lua:273: post(): worker-events: failed posting event "upstreams" by "balancer"; no memory, client: 127.0.0.1, server: kong_admin, request: "PUT /upstreams/071e7eb8-f1c2-49d8-948f-02a746bdc614 HTTP/1.1", host: "127.0.0.1:8444"
2021/02/01 17:00:07 [warn] 22#0: *12416220 [lua] events.lua:155: post_event(): worker-events: could not write to shm after 6 tries (no memory), it is either fragmented or cannot allocate more memory, consider increasing 'opts.shm_retries' or increasing the shm size, client: 127.0.0.1, server: kong_admin, request: "PUT /upstreams/01f8580b-a04f-4cb8-b4a0-6c71d40bcbef HTTP/1.1", host: "127.0.0.1:8444"
2021/02/01 17:00:07 [error] 22#0: *12416220 [lua] events.lua:273: post(): worker-events: failed posting event "upstreams" by "balancer"; no memory, client: 127.0.0.1, server: kong_admin, request: "PUT /upstreams/01f8580b-a04f-4cb8-b4a0-6c71d40bcbef HTTP/1.1", host: "127.0.0.1:8444"

Kong Version: 2.3.1
Ingress Controller: 1.1.1
PostgreSQL: 9.6
Kubernetes: 1.15.12 GKE

We have the following configurations in place but are still seeing the issue:

increasing memory available to the pods
setting KONG_NGINX_WORKER_PROCESSES to 2 (2 CPU x Pods)
bumping KONG_MEM_CACHE_SIZE to 512m (definitely appears to be overkill)

The main thing we see is "kong_process_events appears to fill up quickly and I am not sure how to purge it or ensure there is enough memory. 

      "kong_process_events": {
        "allocated_slabs": "5.00 MiB",
        "capacity": "5.00 MiB"
      },

I have tried to increase this via NGINX directives but the pod just crashes when moving it to 10m

Here is the information from the /status endpoint:

{
  "database": {
    "reachable": true
  },
  "memory": {
    "workers_lua_vms": [
      {
        "http_allocated_gc": "36.73 MiB",
        "pid": 22
      }
    ],
    "lua_shared_dicts": {
      "kong_locks": {
        "allocated_slabs": "0.06 MiB",
        "capacity": "8.00 MiB"
      },
      "kong": {
        "allocated_slabs": "0.04 MiB",
        "capacity": "5.00 MiB"
      },
      "kong_process_events": {
        "allocated_slabs": "5.00 MiB",
        "capacity": "5.00 MiB"
      },
      "kong_db_cache_miss": {
        "allocated_slabs": "0.08 MiB",
        "capacity": "12.00 MiB"
      },
      "kong_healthchecks": {
        "allocated_slabs": "0.34 MiB",
        "capacity": "5.00 MiB"
      },
      "kong_cluster_events": {
        "allocated_slabs": "0.11 MiB",
        "capacity": "5.00 MiB"
      },
      "kong_core_db_cache_miss": {
        "allocated_slabs": "0.08 MiB",
        "capacity": "12.00 MiB"
      },
      "kong_core_db_cache": {
        "allocated_slabs": "4.93 MiB",
        "capacity": "512.00 MiB"
      },
      "prometheus_metrics": {
        "allocated_slabs": "0.04 MiB",
        "capacity": "5.00 MiB"
      },
      "kong_db_cache": {
        "allocated_slabs": "2.99 MiB",
        "capacity": "512.00 MiB"
      },
      "kong_rate_limiting_counters": {
        "allocated_slabs": "0.08 MiB",
        "capacity": "12.00 MiB"
      }
    }
  },
  "server": {
    "connections_writing": 1,
    "total_requests": 1219469,
    "connections_handled": 195468,
    "connections_accepted": 195468,
    "connections_reading": 0,
    "connections_active": 1,
    "connections_waiting": 0
  }
}

### Additional Details & Logs

This is constantly logging this error and we are not sure on how to fix it. Is it possible this is a memory leak?

**Comment by w313062006** [comment] 2021-03-04 03:00
you can edit /usr/local/share/lua/5.1/kong/templates/nginx_kong.lua to change kong_process_events value, I set the value 512m

**Comment by StarlightIbuki** [comment] 2023-10-11 06:20
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:20 UTC
Labels: task/bug
