### ISSUE TITLE
Rate Limiting plugin memory leak issue

### ISSUE THREAD

**Issue by wjxcai** [Kong/kong#3124] opened 2017-12-26 04:07 UTC
### Summary

After set config.second property in ratelimit plugin. The second cache (e.g. dict = kong_cache, key = ratelimit:561f23d4-23d2-4283-9f4c-7c077b5c77d3:118.116.111.5:1514260849000:second, value = 1) will take all cahce memory and never expired. When new API add in or be called. No memory for new API and plugins. Then no memory error show up.

### Steps To Reproduce

1. vim kong.conf
mem_cache_size = 100k
2. kong start --vv
3. create 6 APIs
4. Add ratelimit plugin set second 
$ curl -X POST http://kong:8001/apis/{api}/plugins \
    --data "name=rate-limiting" \
    --data "config.second=100" \
    --data "config.hour=10000"
5. keep calling the first 5 APIs.
6. After few minutes with no error.
7. call 6th API. you will see the error in error.log 
[error] 19343#0: *2427 [lua] responses.lua:107: send_HTTP_INTERNAL_SERVER_ERROR(): failed to get from node cache: could not write to lua_shared_dict: no memory, client: 118.116.111.5, server: kong, request: "GET /V1/ben_test_1221?auth_key=097C993DF185099B2B7633F4C1778023&t=1514259888796 HTTP/1.1", host: "ec2-13-56-255-95.us-west-1.compute.amazonaws.com:8000"

### Additional Details & Logs

- Kong version (0.11.0)
- Kong debug-level startup logs
[startup.log](https://github.com/Kong/kong/files/1586503/startup.log)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
[error.log](https://github.com/Kong/kong/files/1586509/error.log)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System
ubuntu 16.04 LTS

**Comment by wjxcai** [comment] 2017-12-26 05:42
More observation.
The code of [https://github.com/Kong/kong/blob/master/kong/plugins/rate-limiting/policies/init.lua](url)
line 33  `local newval, err = shm:incr(cache_key, value, 0)`
The function ngx.shared.DICT.incr does not have expiration setting. it will overrides the (least recently used) unexpired items in the store when running out of storage in the shared memory zone. Please refer to [https://github.com/openresty/lua-nginx-module#ngxshareddictincr](url)

I suggest change above code to the following code that use ngx.shared.DICT.set to set respective expire time
`local expireSecond = EXPIRATIONS[period]
          local existVal, err = shm:get(cache_key)
          if not existVal then
            local success, errNew = shm:set(cache_key, value, expireSecond)
            if not success then
              ngx_log(ngx.ERR, "[rate-limiting] could not increment counter ", "for period '", period, "': ", errNew)
              return nil, errNew
            end
          end

          if existVal then
            local newVal = existVal + value;
            local success, errUpdate = shm:set(cache_key, newVal, expireSecond)
            if not success then
              ngx_log(ngx.ERR, "[rate-limiting] could not increment counter ", "for period '", period, "': ", errUpdate)
              return nil, errUpdate
            end
          end`

**Comment by p0pr0ck5** [comment] 2017-12-27 18:24
Well, this is somewhat embarrassing. It seems I made a somewhat short-sighted decision in `fc9a96b76`, removing the expiry field from these elements.

Good news, though! We can use the hot-off-the-press `:expire` call (https://github.com/openresty/lua-nginx-module#ngxshareddictexpire) once we upgrade to OR 1.13.x.

**Comment by davidsiracusa** [comment] 2018-01-07 15:32
The rate limiting plugins, call to shm:incr, call ngx_http_lua_shdict.c|ngx_http_lua_shdict_incr which performs an atomic increment across all worker processes.  The underlying C code performs lock/unlock as needed.  Performing a get/set outside of the C logic, will lead to concurrency issues.  I have submitted an issue to openresty: https://github.com/openresty/openresty/issues/328

**Comment by davidsiracusa** [comment] 2018-01-07 18:12
For clarity: with regard to the logic above, performing the arithmetic increment will not work, as there are multiple worker processes and threads involved.  The increment must be performed in ngx_http_lua_shdict_incr, where locking ensures an atomic increment. A get/set will fall short.

. . .
if existVal then
**local newVal = existVal + value**
**local success, errUpdate = shm:set(cache_key, newVal, expireSecond)**
if not success then
ngx_log(ngx.ERR, "[rate-limiting] could not increment counter ", "for period '", period, "': ", errUpdate)
return nil, errUpdate
end
end

**Comment by wjxcai** [comment] 2018-01-08 02:50
@davidsiracusa Yes, your are correct. shm:set will not work for multiple worker processes. 
So use :expire call (https://github.com/openresty/lua-nginx-module#ngxshareddictexpire) is what we can do for now. Hope openresty can add expire parameter/setting to shm:incr ASAP.

**Comment by davidsiracusa** [comment] 2018-01-08 14:51
@agentzh’s is now open to adding a ttl argument to incr. He has asked me to contribute to openresty. Doing so is more efficient than calling expire multiple times from Kong.

**Comment by p0pr0ck5** [comment] 2018-01-08 18:52
Prior art related to this subject: https://github.com/openresty/lua-nginx-module/pull/942

**Comment by davidsiracusa** [comment] 2018-01-11 11:27
openresty/openresty#328 has been closed.
An initial time to live argument has been added to ngx_http_lua_ffi_shdict_incr in file:  ngx_http_lua_shdict.c.

**Comment by jeremyjpj0916** [comment] 2018-02-15 07:37
Been a bit over a month and thought would be good for a checkup, is this fix in the pipes to be released into the 12.x series or the 13.x series coming up?

**Comment by thibaultcha** [comment] 2018-02-15 09:15
There is a lot of confusion and a few assumptions being made here. There is no memory leak in the rate-limiting plug-in’’a business logic code. The exptime argument helps reducing the footprint, but by no means resolves a fictitious memory leak. It is not planned to be added to 0.12 or 0.13, since it is not even released in OpenResty. 

The initial error encountered here seems to be related to the host’s memory being filled because it simply isn’t large enough. We have encountered many such cases already in the issues the past few months. A reminder that kong will use roughly ~400Mbs of memory per worker (maybe more) with the default settings.

**Comment by davidsiracusa** [comment] 2018-02-15 11:19
Currently, request/response rate-limiting leverages kong_cache, of which entries accumulate over time, never to expire, eventually leading to a "no memory" error.  These never to be freed entries accelerate if per second rate limiting is used because the key uses a fully qualified date/time.  The issue is self-evident in the openresty code and has been acknowledged.  I've read that setting exptime may be made separately, shortly after incr, I feel this can affect performance, a waste of a roundtrip involving locking/unlocking the zone.  I suggested that the atomic increment include an exptime, as it's best set at creation.  This change has been made.

**Comment by davidsiracusa** [comment] 2018-02-15 18:43
Just so we're on the same page, we're using Kong 0.11.x.
_of which entries never expire_

**Comment by davidsiracusa** [comment] 2018-02-15 18:45
Just so we're on the same page, Kong 0.11.x:
_of which entries accumulate over time, never to expire_

**Comment by davidsiracusa** [comment] 2018-02-15 18:51
Just so we're on the same page, we're using Kong 0.11.xx:

In openresty file: ngx_http_lua_shdict.c, procedure: ngx_http_lua_ffi_shdict_incr expiry or time-to-live is hardcoded to 0, or forever so the LRU mechanism doesn't apply.  The updated openresty with init_ttl is welcome, and will address this leak.

**Comment by p0pr0ck5** [comment] 2018-02-15 18:59
@davidsiracusa have a look at https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_shdict.c#L249, which is called from almost all dictionary func handlers, including the FFI `incr` wrapper (https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_shdict.c#L2624). It is not accurate to say the LRU mechanism doesn't apply, because in cases where there is memory pressure in the zone the oldest entries will be forcefully evicted (see https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_shdict.c#L2773-L2784). None of this behavior has changed in between the Openresty releases used for Kong 0.11.x and 0.12.x.

**Comment by thibaultcha** [comment] 2018-02-15 18:59
@davidsiracusa I am sorry to have to say it, but this conversation is seriously starting to bother me. 

https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_shdict.c#L2768-L2784

https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_shdict.c#L266

**Comment by davidsiracusa** [comment] 2018-02-15 19:08
init_ttl was recently added, and is not present in openresty for Kong 0.11.xx.  
The procedure looks like this:
int ngx_http_lua_ffi_shdict_incr(ngx_shm_zone_t *zone, u_char *key,
    size_t key_len, double *value, char **err, int has_init, double init,
    int *forcible)...

**Comment by thibaultcha** [comment] 2018-02-15 20:03
How is this even related? The init_ttl flag has **nothing** to do with the LRU eviction mechanism.

**Comment by davidsiracusa** [comment] 2018-02-15 21:23
Sorry, as mentioned before these incr key/value pairs cannot be reclaimed by the LRU, they persist forever. Only candidates which do specify a ttl fall into the LRU expiry candidate category. Eventually incr uses  enough memory that memory is fully exhausted.  There a window as the ceiling closes in that some LRU eviction of compliant entries may free up holes, at this point "no memory errors" are sporadic, as incr closes in, a fatal lack of memory occurs.  This is easily reproduced.

**Comment by thibaultcha** [comment] 2018-02-15 23:08
> as mentioned before these incr key/value pairs cannot be reclaimed by the LRU, they persist forever. Only candidates which do specify a ttl fall into the LRU expiry candidate category.

For the last time, that is simply **wrong**.

```
error_log logs/error.log notice;

events {}

http {
    lua_shared_dict counters 12k;

    init_by_lua_block {
        require "resty.core"
    }

    server {
        listen 9000;

        location / {
            content_by_lua_block {
                local key = "key_" .. ngx.now() * 1000

                local newcount, err, forcible = ngx.shared.counters:incr(key, 1, 0)
                if err then
                    ngx.log(ngx.ERR, "failed to incr(): ", err)
                    return ngx.exit(500)
                end

                ngx.print(key, ": ", newcount)
                if forcible then
                    ngx.print(" (forcibly removed a value from the shm)")
                    ngx.log(ngx.NOTICE, "forcibly removed a value")
                end

                ngx.say()
            }
        }
    }
}
```

Yes, `no memory` error can happen but they do not happen because of a memory leak. Re-read my numerous answers to you in the Kong and OpenResty repositories, and the related thread I linked.

I am locking this topic.

**Closed by thibaultcha** 2018-02-15 23:08 UTC
