### ISSUE TITLE
Kong returns response of a request to another request

### ISSUE THREAD

**Issue by luong-komorebi** [Kong/kong#6213] opened 2020-08-12 07:00 UTC
### Summary

We run Kong 2.1.0 on our k8s production cluster and notices there are cases that a response by a request of a client is returned to another request. This leads to extremely dangerous errors, such as client A request resource B, client C request resource D, but the bug causes client A to receive resource D instead.

This does happen consistently in cases where a pod is unhealthy or restarting or terminating (maybe because of rolling upgrade of a deployment)

This does not happen with kong 2.0.x

### Steps To Reproduce
I set up this repo to set up an example 
https://github.com/luong-komorebi/reproduce-kong-bug

```
Kong Bug on 2.1.x

This bug is tested on Kong version 2.1.0 and 2.1.1 where Kong returns a response that does not belong to a request. This is caused when we have unhealthy pods in the system or all pods are in a rolling upgrade.
Steps to reproduce

This is a minimal ruby example that replicates our production environment. First, make sure you have Ruby installed on your system.

    Install deps with bundle install
    Install k8s with your solution, either minikube or docker for desktop
    Build the docker image
    Deploy Kong with helm or any installation method to the cluster
    Deploy the deployment, the service and the ingress to the cluster

In this example you can find:

    app.rb -> where the web server lives, simple echo server written in ruby. In this server, I also have an endpoint to simulate unhealthy pod.
    request.rb -> the script we will be using to spam requests to the server. Please make sure you change the ip address of the server and the port, according to your k8s set up. Here I used minikube so that url can be achieved via:

minikube service -n example kong-kong-proxy --url

    Other files for deployment to k8s like dockerfile and manifests

Reproduce the issue by:

    First make sure that kubectl get pods returning all the pods at running state
    Second make sure that you can make GET request to the server
    Spam request with bundle exec ruby request.rb

The result should be consistent: you will see the script stop and output a response that doesnt belong to a request
```

### Additional Details & Logs

- Kong version (`$ kong version`) : 2.1.0 and 2.1.1 both tested, deployed with helm chart and no other customization
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by nguyenductoan** [comment] 2020-08-12 07:15
This is duplicate of #6212

**Comment by gszr** [comment] 2020-08-12 17:36
Let's close this one and keep the discussion in #6212. Thanks for reporting, @luong-komorebi!

**Closed by gszr** 2020-08-12 17:36 UTC

**Comment by luong-komorebi** [comment] 2020-08-12 17:37
No problem @gszr . 6212 Issue opener and I are colleagues. We just had different ways to debug and did not come to the same issue
