### ISSUE TITLE
proxy-cache plugin always caches per consumer

### ISSUE THREAD

**Issue by wouthoekstra** [Kong/kong#5887] opened 2020-05-12 14:02 UTC
### Summary

[The documentation for the proxy cache plugin](https://docs.konghq.com/hub/kong-inc/proxy-cache/) suggests that responses can be cached by either consumer or api*. In practice it is not a choice; caching is always based on consumer, if available.

_*_ As an aside, this suggests an update to 'service' might be in order in the docs? :)

#### Current behavior
Authenticated requests are cached per consumer, even if plugin is installed on service or route.

#### Expected behavior:
I would have expected to cache the entire service / route notwithstanding the consumer if I installed the cache on a service or consumer.
Arguably this would make it hard to cache authenticated routes per consumer, but this could probably be solved by adding a boolean setting as e.g. `vary_consumers`.

### Steps To Reproduce

1. Install proxy-cache on either a route or service
2. Make a request authenticated as some consumer
3. Make a request authenticated as a different consumer
4. Check response headers, which indicate a cache miss and different x-cache-keys

**Comment by dlouzan** [comment] 2022-03-15 12:19
We can confirm the same behaviour; 2 years after I'm still unsure if this is an actual issue with the plugin, or incorrect documentation.

**Comment by StarlightIbuki** [comment] 2023-10-11 06:35
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:35 UTC
Labels: plugins/proxy-cache
