### ISSUE TITLE
Response ratelimiting plugin persist only tracked period

### ISSUE THREAD

**Issue by Simarn** [Kong/kong#6413] opened 2020-10-01 13:06 UTC
### Summary

Your plugin response-ratelimiting persist in database each calls value for all following periods : second, minute, hour, day, month, year.
I use a cassandra database and these data increase database size very fast.

I developed a solution that only persist tracked periods, it take all limits and track only periods which have a limit. 
This feature is very interesting to limit database size. I can't push my code in a new feature branch because i don't have rigths.

**Comment by Simarn** [comment] 2020-10-01 15:05
@bungle Thanks for your response, i follow your recommendation. Now you could find my PR.

**Comment by StarlightIbuki** [comment] 2023-10-11 06:15
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:15 UTC
Labels: task/code quality, plugins/response-ratelimiting
