### ISSUE TITLE
Luarocks packaging borked for 2.8.1?

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#9282] opened 2022-08-22 07:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.1

### Current Behavior

Please review: https://github.com/luarocks/luarocks/issues/1431 , it contains the details of the issue I see. 

### Expected Behavior

Luarocks install process works like it always have before in our pipelines. 

### Steps To Reproduce

```markdown
1. luarocks install kong 2.8.1
```

**Comment by bungle** [comment] 2022-08-22 13:32
I can reproduce it:
```
~ ❯  luarocks install kong 2.8.1
Installing https://luarocks.org/kong-2.8.1-0.src.rock

Error: Couldn't extract archive /private/var/folders/6p/w721tj_s2hv_1wjcdrqdw2rw0000gn/T/luarocks_kong-2.8.1-0-8986542/kong.git: unrecognized filename extension
```

**Comment by bungle** [comment] 2022-08-22 13:33
@hanshuebner do you have any idea?

**Comment by bungle** [comment] 2022-08-22 13:37
`2.8.0` works a bit better (still didn't work on my machine, but better), it has:
```
url = "git://github.com/Kong/kong",
```

The `2.8.1` has:
```
url = "https://github.com/Kong/kong.git"
```

**Comment by bungle** [comment] 2022-08-22 14:15
It looks like changing the url to:
```
url = "https://github.com/Kong/kong"
```

Fixes the issue, at least with:
```
luarocks make kong-2.8.1-0.rockspec OPENSSL_DIR=/opt/homebrew/opt/openssl@1.1
```

I still got weird:
```
Error: Build error: Failed installing kong/plugins/proxy-cache/handler.lua in /Users/bungle/.luaver/luarocks/3.9.1_5.1/lib/luarocks/rocks-5.1/kong/2.8.1-0/lua/kong/plugins/proxy-cache/handler.lua: kong/plugins/proxy-cache/handler.lua: No such file or directory
```

**Comment by jeremyjpj0916** [comment] 2022-08-22 14:26
Just for cross reference for internal purposes I did tie a Kong case ticket to this in the Ent. Support portal as well:
Case #00029768

Surprised the CICD integrity did not pick up on a luarocks make style failure. Maybe various valid package manager install tests as part of Kongs QA signoff would be good for cases like this. 

Sounds like you drove down into close to where the problem may live though. Last series luarocks made out fine for me was 2.7.1 as part of our pipelines.

**Comment by bungle** [comment] 2022-08-22 14:43
@jeremyjpj0916 yes, we need to check out what went wrong. I think the url can basically be anything as long as `.rock` is correct, but now it seems like .rock is not correct.

**Comment by bungle** [comment] 2022-08-23 11:28
@jeremyjpj0916 this should be fixed now. Please reopen if you see any further issues with it.

**Closed by bungle** 2022-08-23 11:28 UTC
Labels: question, distribution, chore, bug

**Comment by jeremyjpj0916** [comment] 2022-08-23 14:01
@bungle I do see the revis in luarocks UI now "[2.8.1-0](https://luarocks.org/modules/kong/kong/2.8.1-0)2 hours ago(revision: 2)263 downloads" , going to give it a go now!

**Comment by jeremyjpj0916** [comment] 2022-08-23 16:14
Worked fine now. Thx!
