### ISSUE TITLE
why kong1.4.x, kong1.5.x consume so much memory about 3.5G?

### ISSUE THREAD

**Issue by chenhuandong8010** [Kong/kong#5617] opened 2020-02-27 07:35 UTC
### Summary

I have test all version kong, when docker start kong, the kong memery as bellow:

 kong1.1.x, kong1.2.x, kong1.3.x : about 200-350M  
 kong1.4.x, kong1.5.x: about 3.5G
 kong2.0.x: about 350M 

    Why is there such a big difference?

   as before, i use kong1.3.x dbless and kong ingress controller 0.4.x, and found some uptream mistake, sometimes upstream lose, and After a minute, it works normally.

   so i update to kong1.4.x dbless and kong ingress controller 0.6.x, the upstream lose error fixed, but consume so much memory 4G, and after a month 12G ....  i confused.

  and now  i want to update to kong2.0.x,

------------------------------error log for kong1.4.x--------------------------------------------

cb594f6a-1f17-52bb-b4cf-0efe1b562879, context: ngx.timer
2020/02/21 07:36:17 [error] 34#0: *36372427 [lua] balancer.lua:605: on_target_event(): target create: upstream not found for db22f712-a259-5d82-acdd-6b1b7b211921, context: ngx.timer
2020/02/21 07:36:17 [error] 34#0: *36372427 [lua] balancer.lua:605: on_target_event(): target create: upstream not found for 26951ae0-35be-5276-a065-70086fbe4bf7, context: ngx.timer
2020/02/21 07:36:17 [error] 34#0: *36372427 [lua] balancer.lua:605: on_target_event(): target create: upstream not found for ca32ebf3-16ad-561c-9400-4002431b8777, context: ngx.timer
2020/02/21 07:36:17 [error] 34#0: *36372427 [lua] balancer.lua:605: on_target_event(): target create: upstream not found for c5c3bfb9-0505-5f17-8c8b-297d37e16c54, context: ngx.timer

**Comment by bungle** [comment] 2020-02-27 10:51
I am pretty sure this is duplicate of:
https://github.com/Kong/kong/issues/5324

**Closed** 2020-03-10 20:57 UTC
Labels: pending author feedback
