### ISSUE TITLE
How does Kong detect connection timeout?

### ISSUE THREAD

**Issue by Sereneee** [Kong/kong#7132] opened 2021-05-07 07:44 UTC
Currently, whenever an upstream service is down, kong will throw 
"{"message":"failure to get a peer from the ring-balancer"}"

My goal is to create a custom plugin that detects the connection time out and return a customized message to the client, the blocker I am facing right now is writing lua codes in my custom plugin to detect the timeout.
I have look through the kong plugin development kit document but haven't found anything that works.
I have tried kong.response.get_source(), but that didn't seem to detect the timeout either.

If anyone has any idea on how to detect connection timeout in lua codes or an article/document regarding this, feel free to share, thanks in advance!

**Comment by StarlightIbuki** [comment] 2023-10-11 06:20
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:20 UTC
Labels: core/balancer
