### ISSUE TITLE
New X-Forwarded-Prefix headers should contain route path only

### ISSUE THREAD

**Issue by rainest** [Kong/kong#6190] opened 2020-08-05 19:28 UTC
### Summary

See #5620 and specifically https://github.com/Kong/kong/pull/5620/files#diff-8cb7654e2e5f4b45e64e3cd2afdcfcd9R239-R271 for current behavior.

Based on the report in https://github.com/Kong/kubernetes-ingress-controller/issues/784 and a brief reading of that code, Kong will either send an existing `X-Forwarded-Prefix` header from a trusted sender or will generate a new `X-Forwarded-Prefix` header containing the entire path.

Though unclear, I believe the headers that Kong generates itself should contain the route path only, i.e. run https://docs.konghq.com/2.1.x/pdk/kong.router/#kongrouterget_route, extract the path, and set `X-Forwarded-Prefix` to that.

### Steps To Reproduce

1. Create a route+service using an echo service (httpbin or similar).
2. Send a request through the route, and inspect the `X-Forwarded-Prefix` header received upstream

### Additional Details & Logs

From the original report, CE 2.0.4 running on EKS 1.17. Exact route config used is available in https://github.com/Kong/kubernetes-ingress-controller/issues/784 but I believe this should affect any route equally; exact config shouldn't matter.

The correct behavior here is unclear. Based on the header name alone, I agree with the controller report: this should send the Kong route path prefix only, or the portion of the request matching it in the case of regex paths. However, this header is non-standard, and I cannot find anything that appears to be an authoritative source on its behavior. There are several open questions:

- If we receive an `X-Forwarded-Prefix` header from a trusted downstream, should we combine it with our route prefix in any way? As-is we use the downstream value exclusively.
- For regex paths, should we forward the matched string, or the original regex?

**Comment by rainest** [comment] 2020-08-05 19:31
@jerfer do you know of an authoritative source for this header's behavior, or absent that, any source that describes this header's behavior? We should probably be able to learn more about it by reviewing the source of other proxies, but it'd be useful to know if there is something close to an authoritative source.

**Comment by jerfer** [comment] 2020-08-05 20:15
@rainest Here you go, I found one of each.

- Source: line 224 in https://github.com/spring-cloud/spring-cloud-gateway/commit/bc1e549dc8f7aa92d90a1e3bb85670bb7229aee8
- Docs: https://docs.traefik.io/v2.0/middlewares/stripprefix/

Does that work for you?

**Comment by bungle** [comment] 2020-08-06 07:06
This is duplicate of #6132

**Comment by bungle** [comment] 2020-08-07 11:49
@rainest / @jerfer,

There is now a PR #6201 to fix this. Can you please try it out and report any issues / give feedback, thank you!

**Comment by gszr** [comment] 2020-08-12 17:41
Closing this issue, let's please keep the discussion in #6201. Thanks for reporting, @rainest!

**Closed by gszr** 2020-08-12 17:41 UTC
