### ISSUE TITLE
Kong is ignoring "#" character at the end of upstream uri

### ISSUE THREAD

**Issue by rkchilaka** [Kong/kong#4247] opened 2019-01-28 06:31 UTC
kong is ignoring the # character at the end of the upstream URI

**Comment by bungle** [comment] 2019-01-28 09:13
hash part ofthe url is not meant for servers to processed. You can urlencode the hash though.

**Comment by rkchilaka** [comment] 2019-01-28 09:52
Do you mean to encode the entire Upstream URI? and if stripuri is false and the matching part of the uri is not encoded, on appending the matching non-encoded URI, the resulting Uri will be part encoded and part not encoded. will this work ?

**Comment by p0pr0ck5** [comment] 2019-01-30 20:02
I'm not quite sure what you're trying to accomplish, but as @bungle mentioned, the octothorpe (`#`) is used by browsers as client behavior; browsers will not send the `#` character or any characters following it to the server. If you wanted to send the `#` character in the request URI, your HTTP client would need to encode it (e.g., send the literal characters `%23` in the request), and then your upstream service can decode this back `#`.

Since this is not a bug, but part of the HTTP spec and normal behavior for proper HTTP clients, I'm closing this bug. Please feel free to continue the discussion at https://discuss.konghq.com if there are further questions (or, if you feel this is a bug in Kong, please leave a note here and we can investigate re-opening this issue). Thanks!

**Closed by p0pr0ck5** 2019-01-30 20:02 UTC
