### ISSUE TITLE
kong with oauth2 token invalid every time 

### ISSUE THREAD

**Issue by anupam4881** [Kong/kong#3726] opened 2018-08-23 12:21 UTC
### Additional Details & Logs

- Kong version: kong-community-edition-0.14.0-1.noarch  
- Operating system centos 7.4

Hi Team,

We enabled oauth2 ( client credential flow) for one service  named hrms_billing with separate  consumer( hrms)  

After that we are able to get Token from endpoint, But when we summit request with provided token it always says invalid , I checked multiple times so decided to highlighted so that you can check whether its a bug or other issue. 

Will really appreciate if you help to understand kong for oauth2 implementation.

Step-11:  generate token like this for testing purpose  with high  very expire value  
[root@psld-ggn-233 ~]#   curl -X POST http://192.168.0.234:8001/oauth2_tokens --data "credential_id=0c43d1da-08dc-4126-a3d3-44f2036c4844"      --data "expires_in=360000000"

Step-10: check token generated and get this value 
[root@psld-ggn-233 ~]#  curl -X GET  http://192.168.0.234:8001/oauth2_tokens?credential_id=0c43d1da-08dc-4126-a3d3-44f2036c4844
{"total":1,"data":[{"created_at":1535020491000,"access_token":"c0lWMnk8ncEVqpBvW7fNq390Vxu1gGHX","expires_in":360000000,"id":"d7ce0088-3627-44fa-8c06-0b2f13d6311f","credential_id":"0c43d1da-08dc-4126-a3d3-44f2036c4844","token_type":"bearer"}]}
 
Step-9: send token with api to get response 
[root@psld-ggn-233 ~]# curl -X POST -H 'Authorization: Bearer c0lWMnk8ncEVqpBvW7fNq390Vxu1gGHX' -i 'http://g1.peoplestrong.com/api_v1/public/index.php/login/wines/1'
HTTP/1.1 401 Unauthorized
Date: Thu, 23 Aug 2018 11:07:33 GMT
Content-Type: application/json; charset=utf-8
Connection: close
Server: kong/0.14.0 
WWW-Authenticate: Bearer realm="service" error="invalid_token" error_description="The access token is invalid or has expired"

Rest details r below. 

[root@psld-ggn-233 ~]#  curl -X GET  http://192.168.0.234:8001/consumers/hrms/plugins
{"total":1,"data":[{"created_at":1535021437000,"config":{"path":"\/tmp\/abcd","reopen":false},"id":"039cc5d5-704f-4a40-9244-70f95e3748c5","enabled":true,"name":"file-log","service_id":"268c2499-47a7-4a5e-bfef-b72b44343514","consumer_id":"8ba4743c-aea7-4d39-bfb5-25ed8ba3cc91"}]}

[root@psld-ggn-233 ~]#  curl -X GET  http://192.168.0.234:8001/services/hrms_billing/routes
{"next":null,"data":[{"created_at":1534791379,"strip_path":true,"hosts":[],"preserve_host":false,"regex_priority":0,"updated_at":1534988394,"paths":["\/A"],"service":{"id":"268c2499-47a7-4a5e-bfef-b72b44343514"},"methods":[],"protocols":["http","https"],"id":"4a8b5a07-7f04-42f9-a37b-30b51e156041"},{"created_at":1534795000,"strip_path":true,"hosts":[],"preserve_host":true,"regex_priority":0,"updated_at":1534843166,"paths":["\/api_v1\/public\/index.php\/login\/wines"],"service":{"id":"268c2499-47a7-4a5e-bfef-b72b44343514"},"methods":[],"protocols":["http","https"],"id":"b6edbfa5-d3b9-4d45-b734-fc16cc9d461b"}]}

[root@psld-ggn-233 ~]# curl -X GET  http://192.168.0.234:8001/services/hrms_billing/plugins
{"total":4,"data":[{"created_at":1534844114000,"config":{"key_in_body":false,"key_names":["apikey"],"anonymous":"","hide_credentials":false,"run_on_preflight":true},"id":"860c9523-af70-48a3-93c5-b59720fd2344","name":"key-auth","service_id":"268c2499-47a7-4a5e-bfef-b72b44343514","enabled":false},{"created_at":1534853513000,"config":{"key_claim_name":"iss","secret_is_base64":false,"cookie_names":{},"anonymous":"","maximum_expiration":0,"run_on_preflight":true,"uri_param_names":["jwt"]},"id":"015e511a-81ba-4514-90bc-302979439d62","name":"jwt","service_id":"268c2499-47a7-4a5e-bfef-b72b44343514","enabled":false},{"created_at":1535013580000,"config":{"refresh_token_ttl":1209600,"enable_client_credentials":true,"mandatory_scope":false,"accept_http_if_already_terminated":false,"provision_key":"function","enable_implicit_grant":false,"global_credentials":false,"hide_credentials":false,"enable_password_grant":false,"anonymous":"","enable_authorization_code":false,"token_expiration":7200,"auth_header_name":"authorization"},"id":"188e0c45-59f6-4b97-ab33-4eb3af3ddab9","name":"oauth2","service_id":"268c2499-47a7-4a5e-bfef-b72b44343514","enabled":true},{"created_at":1535021437000,"config":{"path":"\/tmp\/abcd","reopen":false},"id":"039cc5d5-704f-4a40-9244-70f95e3748c5","enabled":true,"name":"file-log","service_id":"268c2499-47a7-4a5e-bfef-b72b44343514","consumer_id":"8ba4743c-aea7-4d39-bfb5-25ed8ba3cc91"}]}
[root@psld-ggn-233 ~]#         

Regards
Anupam Narayan

**Comment by bungle** [comment] 2018-08-29 11:06
The problem is that you have not created the token to a particular `service`or `api`(the step 11) and you have not defined `config.global_credentials` (see the plugins output). You can `PATCH` the OAuth2 plugin configuration with `config.global_credentials=true` to get this to work (or add `service_id` to token).

I will close this now. Please reopen if that still didn't fix your problem.

**Closed by bungle** 2018-08-29 11:06 UTC
