### ISSUE TITLE
‘005_120_to_130' migration failed

### ISSUE THREAD

**Issue by dangtrinhnt-mmt** [Kong/kong#5686] opened 2020-03-16 06:58 UTC
### Summary

Got this error running a migration from 0.14.1 to 1.5.0

Error: [PostgreSQL error] cluster_mutex callback threw an error: /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:158: [PostgreSQL error] failed to run migration '005_120_to_130' up: ERROR: there is no unique constraint matching given keys for referenced table "certificates".

After getting that error, I tried to manually create the new constraints and the migration again, the same error occurs. I think it may be a bug so I report it here.

Many thanks.

### Steps To Reproduce

1. Run this to do the db migration:

docker run --rm --network=kong-net \
-e "KONG_DATABASE=postgres" \
-e "KONG_PG_HOST=<pg host>" \
-e "KONG_PG_USER=<pg user>" \
-e "KONG_PG_DB=<pg db>" \
-e "KONG_PG_PASSWORD=<pg pass>" \
-e "KONG_CASSANDRA_CONTACT_POINTS=<pg host>" \
kong:1.5.1 kong migrations up

### Additional Details & Logs

- Kong version: 0.14.1 -> 1.5.1

**Comment by bungle** [comment] 2020-03-16 08:58
@dangtrinhnt-mmt, thanks fot the report, can you give output of:
```
\d certificates
```

in `psql`?

**Comment by dangtrinhnt-mmt** [comment] 2020-03-16 09:21
Thank you @bungle for helping me. I was successfully migrated following these steps:

1. Migrate to 1.2.3 fist:
kong migrations up

2. Manually apply the migration (running SQL queries) of https://github.com/Kong/kong/blob/1.3.0/kong/db/migrations/core/005_120_to_130.lua

All the queries are fine.

3. Reset migration
kong migrations reset -y

4. Bootstrap migration
kong migrations bootstrap

It's saying everything was fine, my old data is still there. I'm not sure why this work??

Here is the output of `\d certificates`:

```
                                  Table "public.certificates"
   Column   |           Type           |                      Modifiers
------------+--------------------------+-----------------------------------------------------
 id         | uuid                     | not null
 cert       | text                     |
 key        | text                     |
 created_at | timestamp with time zone | default timezone('utc'::text, CURRENT_TIMESTAMP(0))
Indexes:
    "ssl_certificates_pkey" PRIMARY KEY, btree (id)
Referenced by:
    TABLE "services" CONSTRAINT "services_client_certificate_id_fkey" FOREIGN KEY (client_certificate_id) REFERENCES certificates(id)
    TABLE "snis" CONSTRAINT "snis_certificate_id_fkey" FOREIGN KEY (certificate_id) REFERENCES certificates(id)
```

**Comment by hishamhm** [comment] 2020-03-16 14:47
> It's saying everything was fine, my old data is still there. I'm not sure why this work??

This is indeed really strange and sounds like a configuration issue somewhere — are you sure steps 3 and 4 ran with the same Kong configuration as steps 1 and 2?

We could not reproduce your original issue from our end when migrating from 0.14.1 to 1.5.0... without more info to diagnose this it will be really hard to do anything about it, so I guess we should close this one for now and reopen if anything else comes up? Feel free to reopen if you have any further information.

**Closed by hishamhm** 2020-03-16 14:47 UTC
Labels: pending author feedback, task/needs-investigation

**Comment by dangtrinhnt-mmt** [comment] 2020-03-16 22:53
Hi,
Thanks. You're right, I accidentally used the wrong env (KONG_PG_DB instead of KONG_PG_DATABASE) that made kong use the default database name (kong, there is one empty db named kong on my machine). I ran the migration again and it went well.
Thank you everyone for helping and sorry for this confusion.
