### ISSUE TITLE
*110 upstream timed out (110: Operation timed out) while reading response header from upstream

### ISSUE THREAD

**Issue by NilsFrkal** [Kong/kong#6871] opened 2021-02-26 04:33 UTC
Summary
Kong Version 2.3.2 - (same issue in previous version)

I have the problem that http(s) calls timeout in a repeatable pattern. The first login call is okay. Then after logout and immediate login for the 2nd time the login call times out with "*110 upstream timed out (110: Operation timed out) while reading response header from upstream". (please see details below)

I did play around with setting dns_valid_ttl and dns_stale_ttl to 0 without any affect.

I have second nginx server running on a different port and when I point the router to this port directly (bypassing Kong) everything works as expected and without problems.

The end point (nodejs) is also okay as in debugger mode you can see the callback being executed for the login request. So it appears that Kong stops listening to the callback.

If someone could help me that would be great.

Thanks, Nils

Steps To Reproduce
Additional Details
kong.mydomain.com.au | 203.166.242.79 - - [26/Feb/2021:00:40:47 +0000] "OPTIONS /api/users/loginMobile HTTP/2.0" 200 0 "https://mydomain.com.au/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4429.0 Safari/537.36"
kong.mydomain.com.au | 203.166.242.79 - - [26/Feb/2021:00:40:47 +0000] "POST /api/users/loginMobile HTTP/2.0" 200 34334 "https://mydomain.com.au/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4429.0 Safari/537.36"
kong.mydomain.com.au | 203.166.242.79 - - [26/Feb/2021:00:40:51 +0000] "OPTIONS /api/users/logout HTTP/2.0" 200 0 "https://mydomain.com.au/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4429.0 Safari/537.36"
kong.mydomain.com.au | 203.166.242.79 - - [26/Feb/2021:00:40:51 +0000] "GET /api/users/logout HTTP/2.0" 200 15 "https://mydomain.com.au/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4429.0 Safari/537.36"
kong.mydomain.com.au | 203.166.242.79 - - [26/Feb/2021:00:40:54 +0000] "OPTIONS /api/users/loginMobile HTTP/2.0" 200 0 "https://mydomain.com.au/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4429.0 Safari/537.36"
kong.mydomain.com.au | 2021/02/26 00:41:54 [error] 23#0: *202 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 203.166.242.79, server: kong, request: "POST /api/users/loginMobile HTTP/2.0", upstream: "http://172.19.0.20:8040/api/users/loginMobile", host: "api.mydomain.com.au:8443", referrer: "https://mydomain.com.au/"

**Comment by thibaultcha** [comment] 2021-02-26 05:36
Hi there!

I wasn't sure what you meant by "Kong is not listening to the callback"; did the second login request reach the upstream node.js or did it not? 

What would be ideal to investigate this would be if with the same configuration, would were to provide us with a packet capture (.pcap) spanning over the same requests as provided above. Something like [tcpdump](https://github.com/tldr-pages/tldr/blob/master/pages/common/tcpdump.md) can do the job.

An idea is to disable upstream connection pools (latency will increase) with `upstream_keepalive_pool_size = 0` (details in config file) and see how Kong behaves then.

**Comment by NilsFrkal** [comment] 2021-02-26 19:57
Thank you very much. Attached the tcpdumps from both network adapters during failed requests. Public traffic (from where the request originates from) is coming of ens38.

Setting upstream_keepalive_pool_size = 0 does solve the problem! 

And to answer your question, yes the second login call does reach the upstream nodejs server and completes successfully. 

Please let me know if I can assist further to investigate this.

Best, Nils

[tcpdump.zip](https://github.com/Kong/kong/files/6052146/tcpdump.zip)

**Comment by thibaultcha** [comment] 2021-03-01 17:16
At this time, the sheer number of HTTP/2 fixes in more recent Nginx core versions (1.17.x and 1.19.x) are highly suspicious to me especially the recv_timeout and lingering_close fixes for h2 given the error logs and packet captures you provided. Kong 2.4 will ship with the latest Nginx 1.19.x, although I am not sure when. @bungle?

**Comment by vladimir259** [comment] 2021-03-16 11:25
@NilsFrkal how long your requests in question normally take to complete?

**Comment by NilsFrkal** [comment] 2021-03-23 19:52
> @NilsFrkal how long your requests in question normally take to complete?
> 
> I had an issue with long running requests ( ~80s) and also "played around" with dns_* settings and observed very similar errors.

The request is typically very quick <100ms

**Comment by vladimir259** [comment] 2021-03-25 07:22
ow, ok, then its something different.

**Comment by StarlightIbuki** [comment] 2023-10-11 06:20
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:20 UTC
Labels: task/needs-investigation, core/proxy
