### ISSUE TITLE
Provision Key not getting generated when OAuth2.0 plugin is added

### ISSUE THREAD

**Issue by anshulbhargava** [Kong/kong#1828] opened 2016-11-17 06:54 UTC
I added oauth2.0 plugin to one of our APIs via the dashboard first, and the provision key field remained empty. Then I created another API via kong REST admin and tried adding oauth plugin. The response returned did not have any provision key.

How can this be resolved ?

<img width="564" alt="screen shot 2016-11-15 at 6 38 17 pm" src="https://cloud.githubusercontent.com/assets/22934192/20379176/ba7d3664-acc0-11e6-81b3-fff35e06092c.png">

**Comment by thefosk** [comment] 2016-11-17 07:04
* What operating system and Kong version are you using?
* Do you confirm that using plain `curl` works?

**Comment by anshulturvo** [comment] 2016-11-17 09:01
I am using the version 0.9, on MacOSX. 

The screenshot attached above shows the output of 'curl', which does not have a provision key.

**Comment by tpb-dev** [comment] 2017-02-22 08:15
I can concur with OP. I see the same problem. I am on Ubuntu 16.04, kong version 0.9.9. Here is my output via curl:

root@******:~# curl -X POST http://localhost:8001/apis/********/plugins \
>     --data "name=oauth2" \
>     --data "config.enable_authorization_code=true" \
>     --data "config.scopes=email,phone,address" \
>     --data "config.mandatory_scope=true"
{"api_id":"04362e39-00e0-41c2-a8d3-d2e2ef185354","id":"f31b4913-1e05-4d5e-bce3-104a647f6d12","created_at":1487751025000,"enabled":true,"name":"oauth2","config":{"mandatory_scope":true,"token_expiration":7200,"enable_implicit_grant":false,"scopes":["email","phone","address"],"enable_password_grant":false,"accept_http_if_already_terminated":false,"hide_credentials":false,"enable_client_credentials":false,"enable_authorization_code":true}}

**Comment by thefosk** [comment] 2017-02-23 01:53
Do you see any error in `/usr/local/kong/error.log` ?

**Comment by tpb-dev** [comment] 2017-02-23 04:02
Only one recurring error message while I ran that command again. I'm not sure if it's relevant to the issue as it shows up constantly without adding the oauth2 plugin:

2017/02/23 03:55:12 [notice] 8062#0: signal 17 (SIGCHLD) received
2017/02/23 03:55:42 [notice] 8062#0: signal 17 (SIGCHLD) received
2017/02/23 03:56:12 [notice] 8062#0: signal 17 (SIGCHLD) received
2017/02/23 03:56:42 [notice] 8062#0: signal 17 (SIGCHLD) received
2017/02/23 03:57:12 [notice] 8062#0: signal 17 (SIGCHLD) received
2017/02/23 03:57:42 [notice] 8062#0: signal 17 (SIGCHLD) received
2017/02/23 03:58:12 [notice] 8062#0: signal 17 (SIGCHLD) received
2017/02/23 03:58:42 [notice] 8062#0: signal 17 (SIGCHLD) received
2017/02/23 03:59:12 [notice] 8062#0: signal 17 (SIGCHLD) received
2017/02/23 03:59:29 [notice] 8062#0: signal 17 (SIGCHLD) received
2017/02/23 03:59:42 [notice] 8062#0: signal 17 (SIGCHLD) received
2017/02/23 04:00:13 [notice] 8062#0: signal 17 (SIGCHLD) received
2017/02/23 04:00:43 [notice] 8062#0: signal 17 (SIGCHLD) received
2017/02/23 04:00:46 [notice] 8062#0: signal 17 (SIGCHLD) received
2017/02/23 04:01:13 [notice] 8062#0: signal 17 (SIGCHLD) received

**Comment by TheDolo** [comment] 2017-05-10 22:51
Having the same problems!

**Comment by bungle** [comment] 2019-08-15 12:58
Couldn't reproduce this anymore, so closing this. Please reopen if you still see the issue with the latest Kong.

**Closed by bungle** 2019-08-15 12:58 UTC
Labels: oauth2
