### ISSUE TITLE
postgres connection error: sslv3 alert handshake failure 

### ISSUE THREAD

**Issue by melkayam92** [Kong/kong#4787] opened 2019-07-09 09:29 UTC
Running kong from docker, trying to connect to Postgres thru SSL with those settings:
      KONG_PG_SSL: 'on'
      KONG_PG_SSL_VERIFY: 'on'
      KONG_LUA_SSL_TRUSTED_CERTIFICATE: /path/to/ca/
      KONG_LUA_SSL_VERIFY_DEPTH: 10

gettings the following error:
Error: [PostgreSQL error] failed to retrieve server_version_num: sslv3 alert handshake failure

I read that it's maybe related to the TLS version?

### Additional Details & Logs
- Kong version 1.21

**Comment by kikito** [comment] 2019-07-31 16:42
Hi @melkayam92,

Does it work correctly if you try to connect to PostgreSQL *without* an SSL certificate?

**Comment by melkayam92** [comment] 2019-08-04 10:21
Yeah, it does works correctly without.

The issue only occurs when connecting with SSL certificate.

**Comment by jpuris** [comment] 2019-11-27 15:33
Able to reproduce with `kong version 1.1.2` and postgresql 9.6
_kong.conf_
```
pg_ssl = on
pg_ssl_verify = off
```
_postgresql.conf_
```
ssl = on
ssl_ciphers = 'TLSv1.2:!aNULL'
ssl_prefer_server_ciphers = on
```
I suspect this is due to postgresql not allowing anything other than TLSv1.2 and the error mentions SSLv3.
SSLv3 is really old and is considered insecure.

**Does kong support specifying the TLS protocol to use?**

**Comment by p0pr0ck5** [comment] 2020-01-13 18:39
There are two issues here; I will attempt to address both.

@melkayam92 `KONG_LUA_SSL_TRUSTED_CERTIFICATE` needs to reference a specific CA file, not the path to where CA certificates are located.

@jpuris no this is not the case, the error you are seeing here is a general OpenSSL response. Without seeing the actual error it is impossible to know.

Given the age of this issue and lack of action, I will close this now.please let us know if you have any other questions. Thanks!

**Closed by p0pr0ck5** 2020-01-13 18:39 UTC

**Comment by jennuineness** [comment] 2020-07-28 08:14
Hi there! I am getting the same issue as the OP. I am trying to connect Kong running on Docker with my PostgreSQL database cloud server.

The following environment variables are set when running the Docker container:
```
KONG_ADMIN_LISTEN="0.0.0.0:8001"
KONG_ADMIN_LISTEN_SSL="0.0.0.0:8444"
KONG_DATABASE="postgres"
KONG_PG_HOST="host.to.database.cloud"
KONG_PG_PORT="1337"
KONG_PG_USER="kong"
KONG_PG_PASSWORD="kong_password"
KONG_PG_DATABASE="kong"
KONG_PG_SSL="on"
KONG_PG_SSL_VERIFY="on"
KONG_LUA_SSL_TRUSTED_CERTIFICATE="/etc/ssl/certs/cert.pem"
```

### Additional Details & Logs
- Operating system: Docker with image kong:2.1-ubuntu

Here are my output logs when I run `docker logs`:
```
nginx: [warn] load balancing method redefined in /usr/local/kong/nginx-kong.conf:57
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:447: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: sslv3 alert handshake failure
stack traceback:
 [C]: in function 'assert'
 /usr/local/share/lua/5.1/kong/init.lua:447: in function 'init'
 init_by_lua:3: in main chunk
```

Any guidance is much appreciated! Thank you :)

**Comment by vgrimaldihub** [comment] 2021-12-15 15:09
Hi @jennuineness,
did you get any info to solve you issue?

I got a similar issue with cassandra. Maybe I missed some config in kong.conf (i'm using kong 2.4.0 and cassandra 3.11.11).
Thanks for any help.
