### ISSUE TITLE
[QUESTION] Is there way to disallow connection reusing (or generally inject custom nginx directives)  for the specific upstream ?

### ISSUE THREAD

**Issue by Voronenko** [Kong/kong#6053] opened 2020-06-24 12:33 UTC
Good day.

Is there possibility to  prohibit using keep-alive connection with some specific upstream service?

Issue can be demonstrated and reproduced on a raw nginx with this gist:  https://gist.github.com/Voronenko/ec3826b72b20c18410b26d4f5c0e2ccc

so - when kong first time connects to the external service to query for  method1, it is somehow binded to some backend service responsible for handling method1, which serves it with success for any number of calls.

In case if I request method2 from the same api, it fails, because connection is reused, gets to the host responsible for serving method1, and thus failing to serve method2.

I can replace ordering, and call first method2, get binded initially to another service, which does not care about method1.   

Decision most likely even can be done basing on a query string, i.e. I can't easily match by get request prefix in path.

In nginx I can "fix it" in a dirty way  by forcing  keepalive_requests 1  (from default 100) for the specific upstream.

 Is there approach to do the same with kong (perhaps via configuration or using some plugin)? - Either prohibit connection reusing, or at least inject specific nginx configuration into upstream definition for that service.

Unfortunately, at a moment I have no control over external service with such behavior.

Thank you for the attention

**Comment by bungle** [comment] 2020-06-24 19:21
This might be basis for that: https://github.com/Kong/kong/pull/5771

**Comment by Voronenko** [comment] 2020-06-24 19:28
Any suggested workaround until this moment ?Getting keepalive_requests=1 on a global level via kong.conf provides too big penalty for unaffected services?

**Comment by bungle** [comment] 2020-06-24 21:12
@Voronenko all the logic seems to be here:
https://github.com/Kong/kong/blob/next/kong/init.lua#L861-L890

Not that hard to modify to suit your needs (even before we add it to our configuration entities).

**Comment by StarlightIbuki** [comment] 2023-10-11 06:19
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:19 UTC
Labels: task/needs-investigation, core/proxy
