### ISSUE TITLE
TCP active.healthy check is disabled

### ISSUE THREAD

**Issue by lastboy1228** [Kong/kong#8872] opened 2022-05-27 13:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.1

### Current Behavior

The http module can not use TCP active.healthy check, because it was disable by the code:
```
-- Create a healthchecker object.
-- @param upstream An upstream entity table.
function healthcheckers_M.create_healthchecker(balancer, upstream)
  -- Do not run active healthchecks in `stream` module
  local checks = upstream.healthchecks
  if (ngx.config.subsystem == "stream" and checks.active.type ~= "tcp")
    or (ngx.config.subsystem == "http" and checks.active.type == "tcp")
  then
    checks = pl_tablex.deepcopy(checks)
    checks.active.healthy.interval = 0
    checks.active.unhealthy.interval = 0
  end
```

### Expected Behavior

Is it a bug?

**Comment by StarlightIbuki** [comment] 2023-10-11 06:35
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Closed by StarlightIbuki** 2023-10-11 06:35 UTC
Labels: core/balancer
